version: "3.9"

services:

  irs-redis:
    image: redis:7
    networks:
      - hmpps
    container_name: irs-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  irs-wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps
    container_name: irs-wiremock
    restart: always
    ports:
      - "9091:8080"

networks:
  hmpps:
