# Runs the services needed for integation testing
# or the subset of services needed by the application if it is connected to `dev` HMPPS APIs

services:

  redis:
    image: redis:7
    container_name: irs-redis
    networks:
      - hmpps
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  wiremock:
    image: wiremock/wiremock:3x
    container_name: irs-wiremock
    networks:
      - hmpps
    restart: always
    ports:
      - "9091:8080"

networks:
  hmpps:
