// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:24.277Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const ASSAULT_4: IncidentTypeConfiguration = {
  incidentType: 'ASSAULT_4',
  active: false,
  startingQuestionId: '61246',
  questions: {
    '61246': {
      id: '61246',
      active: false,
      question: 'What was the main management outcome of this incident?',
      label: 'What was the main management outcome of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '212856',
          response: 'No further action',
          active: false,
          label: 'No further action',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61247',
        },
        {
          id: '212857',
          response: 'IEP regression',
          active: false,
          label: 'IEP regression',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61247',
        },
        {
          id: '212858',
          response: 'Placed on report/adjudication referral',
          active: false,
          label: 'Placed on report/adjudication referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61247',
        },
        {
          id: '212859',
          response: 'Police referral',
          active: false,
          label: 'Police referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61247',
        },
      ],
    },
    '61247': {
      id: '61247',
      active: false,
      question: 'Is any member of staff facing disciplinary charges?',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          id: '212860',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61248',
        },
        {
          id: '212861',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61248',
        },
      ],
    },
    '61248': {
      id: '61248',
      active: false,
      question: 'Is there any media interest in this incident?',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '212862',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61249',
        },
        {
          id: '212863',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61249',
        },
      ],
    },
    '61249': {
      id: '61249',
      active: false,
      question: 'Has the prison service press office been informed?',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          id: '212864',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61250',
        },
        {
          id: '212865',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61250',
        },
      ],
    },
    '61250': {
      id: '61250',
      active: false,
      question: 'Is the location of the incident known?',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          id: '212866',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212867',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61251',
        },
      ],
    },
    '61251': {
      id: '61251',
      active: false,
      question: 'What was the location of the incident?',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '212868',
          response: 'Administration',
          active: false,
          label: 'Administration',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212869',
          response: 'Association area',
          active: false,
          label: 'Association area',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212870',
          response: 'Cell',
          active: false,
          label: 'Cell',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212871',
          response: 'Chapel',
          active: false,
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212872',
          response: 'Crown Court',
          active: false,
          label: 'Crown court',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212873',
          response: 'Dining room',
          active: false,
          label: 'Dining room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212874',
          response: 'Dormitory',
          active: false,
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212875',
          response: 'Education',
          active: false,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212876',
          response: 'Elsewhere',
          active: false,
          label: 'Elsewhere',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212877',
          response: 'Exercise yard',
          active: false,
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212878',
          response: 'External roof',
          active: false,
          label: 'External roof',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212879',
          response: 'Funeral',
          active: false,
          label: 'Funeral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212880',
          response: 'Gate',
          active: false,
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212881',
          response: 'Gym',
          active: false,
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212882',
          response: 'Health care centre',
          active: false,
          label: 'Health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212883',
          response: 'Hospital outside (patient)',
          active: false,
          label: 'Hospital outside (patient)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212884',
          response: 'Hospital outside (visiting)',
          active: false,
          label: 'Hospital outside (visiting)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212885',
          response: 'Induction/First night centre',
          active: false,
          label: 'Induction/first night centre',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212886',
          response: 'Kitchen',
          active: false,
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212887',
          response: 'Magistrates court',
          active: false,
          label: 'Magistrates court',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212888',
          response: 'Mail room',
          active: false,
          label: 'Mail room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212889',
          response: 'Office',
          active: false,
          label: 'Office',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212890',
          response: 'Outside working party',
          active: false,
          label: 'Outside working party',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212891',
          response: 'Reception',
          active: false,
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212892',
          response: 'Recess',
          active: false,
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212893',
          response: 'Segregation unit',
          active: false,
          label: 'Segregation unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212894',
          response: 'Showers/changing room',
          active: false,
          label: 'Showers/changing room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212895',
          response: 'Special unit',
          active: false,
          label: 'Special unit',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212896',
          response: 'Sports field',
          active: false,
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212897',
          response: 'Vehicle',
          active: false,
          label: 'Vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212898',
          response: 'Visits',
          active: false,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212899',
          response: 'Vulnerable prisoners unit (VPU)',
          active: false,
          label: 'Vulnerable prisoners unit (VPU)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212900',
          response: 'Weddings',
          active: false,
          label: 'Weddings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212901',
          response: 'Wing',
          active: false,
          label: 'Wing',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212902',
          response: 'Within perimeter',
          active: false,
          label: 'Within perimeter',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212903',
          response: 'Works department',
          active: false,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61252',
        },
        {
          id: '212904',
          response: 'Workshop',
          active: false,
          label: 'Workshop',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61252',
        },
      ],
    },
    '61252': {
      id: '61252',
      active: false,
      question: 'Was this a sexual assault?',
      label: 'Was this a sexual assault?',
      multipleAnswers: false,
      answers: [
        {
          id: '212905',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61253',
        },
        {
          id: '212906',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61253',
        },
      ],
    },
    '61253': {
      id: '61253',
      active: false,
      question: 'Did the assault occur during a fight?',
      label: 'Did the assault occur during a fight?',
      multipleAnswers: false,
      answers: [
        {
          id: '212907',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61254',
        },
        {
          id: '212908',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61254',
        },
      ],
    },
    '61254': {
      id: '61254',
      active: false,
      question: 'What type of assault was it?',
      label: 'What type of assault was it?',
      multipleAnswers: false,
      answers: [
        {
          id: '212909',
          response: 'Prisoner on prisoner',
          active: false,
          label: 'Prisoner on prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61255',
        },
        {
          id: '212910',
          response: 'Prisoner on staff',
          active: false,
          label: 'Prisoner on staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61256',
        },
        {
          id: '212911',
          response: 'Prisoner on other',
          active: false,
          label: 'Prisoner on other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61255',
        },
        {
          id: '212912',
          response: 'Other',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61255',
        },
      ],
    },
    '61255': {
      id: '61255',
      active: false,
      question: 'Were any staff assaulted?',
      label: 'Were any staff assaulted?',
      multipleAnswers: false,
      answers: [
        {
          id: '212913',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61257',
        },
        {
          id: '212914',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61256',
        },
      ],
    },
    '61256': {
      id: '61256',
      active: false,
      question: 'Describe the type of staff',
      label: 'Describe the type of staff',
      multipleAnswers: true,
      answers: [
        {
          id: '212915',
          response: 'Operational staff- Prison Officer',
          active: false,
          label: 'Operational staff- prison officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61257',
        },
        {
          id: '212916',
          response: 'Operational staff - Other',
          active: false,
          label: 'Operational staff - other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61257',
        },
        {
          id: '212917',
          response: 'Non-operational staff',
          active: false,
          label: 'Non-operational staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61257',
        },
        {
          id: '212918',
          response: 'Non-directly employed staff',
          active: false,
          label: 'Non-directly employed staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61257',
        },
      ],
    },
    '61257': {
      id: '61257',
      active: false,
      question: 'Was spitting used in this incident?',
      label: 'Was spitting used in this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '212919',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61261',
        },
        {
          id: '212920',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61258',
        },
      ],
    },
    '61258': {
      id: '61258',
      active: false,
      question: 'Is the assailant known to have an infectious disease that can be transmitted in saliva?',
      label: 'Is the assailant known to have an infectious disease that can be transmitted in saliva?',
      multipleAnswers: false,
      answers: [
        {
          id: '212921',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61259',
        },
        {
          id: '212922',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61259',
        },
      ],
    },
    '61259': {
      id: '61259',
      active: false,
      question: 'Did the saliva hit the body or clothing of the victim(s)?',
      label: 'Did the saliva hit the body or clothing of the victim(s)?',
      multipleAnswers: false,
      answers: [
        {
          id: '212923',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61261',
        },
        {
          id: '212924',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61260',
        },
      ],
    },
    '61260': {
      id: '61260',
      active: false,
      question: 'Where did it hit?',
      label: 'Where did it hit?',
      multipleAnswers: true,
      answers: [
        {
          id: '212925',
          response: 'Neck or above',
          active: false,
          label: 'Neck or above',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61261',
        },
        {
          id: '212926',
          response: 'Torso',
          active: false,
          label: 'Torso',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61261',
        },
        {
          id: '212927',
          response: 'Arms or hands',
          active: false,
          label: 'Arms or hands',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61261',
        },
        {
          id: '212928',
          response: 'Legs or feet',
          active: false,
          label: 'Legs or feet',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61261',
        },
      ],
    },
    '61261': {
      id: '61261',
      active: false,
      question: 'Were any weapons used?',
      label: 'Were any weapons used?',
      multipleAnswers: false,
      answers: [
        {
          id: '212929',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212930',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61262',
        },
      ],
    },
    '61262': {
      id: '61262',
      active: false,
      question: 'Describe the weapons used?',
      label: 'Describe the weapons used?',
      multipleAnswers: true,
      answers: [
        {
          id: '212931',
          response: 'Blunt instrument',
          active: false,
          label: 'Blunt instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212932',
          response: 'Knife/blade',
          active: false,
          label: 'Knife/blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212933',
          response: 'Other sharp instrument',
          active: false,
          label: 'Other sharp instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212934',
          response: 'Dangerous liquid',
          active: false,
          label: 'Dangerous liquid',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212935',
          response: 'Excreta/urine',
          active: false,
          label: 'Excreta/urine',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212936',
          response: 'Thrown equipment',
          active: false,
          label: 'Thrown equipment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212937',
          response: 'Thrown furniture',
          active: false,
          label: 'Thrown furniture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212938',
          response: 'Food',
          active: false,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212939',
          response: 'Ligature',
          active: false,
          label: 'Ligature',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212940',
          response: 'Chemical incapacitant',
          active: false,
          label: 'Chemical incapacitant',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212941',
          response: 'Firearm',
          active: false,
          label: 'Firearm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61263',
        },
        {
          id: '212942',
          response: 'Other',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61263',
        },
      ],
    },
    '61263': {
      id: '61263',
      active: false,
      question: 'Were any injuries received during this incident?',
      label: 'Were any injuries received during this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '212943',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61273',
        },
        {
          id: '212944',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61264',
        },
      ],
    },
    '61264': {
      id: '61264',
      active: false,
      question: 'Enter description of person(s) injured',
      label: 'Enter description of person(s) injured',
      multipleAnswers: true,
      answers: [
        {
          id: '212945',
          response: 'Prisoners',
          active: false,
          label: 'Prisoners',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61265',
        },
        {
          id: '212946',
          response: 'Operational staff- Prison Officer',
          active: false,
          label: 'Operational staff- prison officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61265',
        },
        {
          id: '212947',
          response: 'Operational staff - Other',
          active: false,
          label: 'Operational staff - other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61265',
        },
        {
          id: '212948',
          response: 'Non-operational staff',
          active: false,
          label: 'Non-operational staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61265',
        },
        {
          id: '212949',
          response: 'Non-directly employed staff',
          active: false,
          label: 'Non-directly employed staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61265',
        },
        {
          id: '212950',
          response: 'Police',
          active: false,
          label: 'Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61265',
        },
        {
          id: '212951',
          response: 'Visitor',
          active: false,
          label: 'Visitor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61265',
        },
        {
          id: '212952',
          response: 'Other',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61265',
        },
      ],
    },
    '61265': {
      id: '61265',
      active: false,
      question: 'Was a serious injury sustained?',
      label: 'Was a serious injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '212953',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212954',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61266',
        },
      ],
    },
    '61266': {
      id: '61266',
      active: false,
      question: 'Which serious injuries were sustained?',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '212955',
          response: 'Black eye',
          active: false,
          label: 'Black eye',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212956',
          response: 'Bites',
          active: false,
          label: 'Bites',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212957',
          response: 'Cuts requiring sutures',
          active: false,
          label: 'Cuts requiring sutures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212958',
          response: 'Extensive/multiple bruising',
          active: false,
          label: 'Extensive/multiple bruising',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212959',
          response: 'Fracture',
          active: false,
          label: 'Fracture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212960',
          response: 'Scald or burn',
          active: false,
          label: 'Scald or burn',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212961',
          response: 'Stabbing',
          active: false,
          label: 'Stabbing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212962',
          response: 'Broken teeth',
          active: false,
          label: 'Broken teeth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212963',
          response: 'Broken nose',
          active: false,
          label: 'Broken nose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212964',
          response: 'Crushing',
          active: false,
          label: 'Crushing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212965',
          response: 'Temporary/permanent blindness',
          active: false,
          label: 'Temporary/permanent blindness',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
        {
          id: '212966',
          response: 'Gun shot wound',
          active: false,
          label: 'Gun shot wound',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61267',
        },
      ],
    },
    '61267': {
      id: '61267',
      active: false,
      question: 'Was a minor injury sustained?',
      label: 'Was a minor injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '212967',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61269',
        },
        {
          id: '212968',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61268',
        },
      ],
    },
    '61268': {
      id: '61268',
      active: false,
      question: 'Which minor injuries were sustained?',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '212969',
          response: 'Grazes, scratches or abrasions',
          active: false,
          label: 'Grazes, scratches or abrasions',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61269',
        },
        {
          id: '212970',
          response: 'Minor bruises',
          active: false,
          label: 'Minor bruises',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61269',
        },
        {
          id: '212971',
          response: 'Superficial cuts',
          active: false,
          label: 'Superficial cuts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61269',
        },
        {
          id: '212972',
          response: 'Swellings',
          active: false,
          label: 'Swellings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61269',
        },
        {
          id: '212973',
          response: 'Other',
          active: false,
          label: 'Other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61269',
        },
      ],
    },
    '61269': {
      id: '61269',
      active: false,
      question: 'Did injuries result in attendance to outside hospital?',
      label: 'Did injuries result in attendance to outside hospital?',
      multipleAnswers: false,
      answers: [
        {
          id: '212974',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212975',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61270',
        },
      ],
    },
    '61270': {
      id: '61270',
      active: false,
      question: 'Type of hospital admission',
      label: 'Type of hospital admission',
      multipleAnswers: true,
      answers: [
        {
          id: '212976',
          response: 'A and E',
          active: false,
          label: 'A&E',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61271',
        },
        {
          id: '212977',
          response: 'Inpatient (overnight only)',
          active: false,
          label: 'Inpatient (overnight only)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61271',
        },
        {
          id: '212978',
          response: 'Inpatient (over 24hr)',
          active: false,
          label: 'Inpatient (over 24hr)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61271',
        },
        {
          id: '212979',
          response: 'Life support',
          active: false,
          label: 'Life support',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61271',
        },
      ],
    },
    '61271': {
      id: '61271',
      active: false,
      question: 'Who was admitted to outside hospital?',
      label: 'Who was admitted to outside hospital?',
      multipleAnswers: true,
      answers: [
        {
          id: '212980',
          response: 'Prisoners',
          active: false,
          label: 'Prisoners',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212981',
          response: 'Operational staff- Prison Officer',
          active: false,
          label: 'Operational staff- prison officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212982',
          response: 'Operational staff - Other',
          active: false,
          label: 'Operational staff - other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212983',
          response: 'Non-operational staff',
          active: false,
          label: 'Non-operational staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212984',
          response: 'Non-directly employed staff',
          active: false,
          label: 'Non-directly employed staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212985',
          response: 'Police',
          active: false,
          label: 'Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212986',
          response: 'Visitor',
          active: false,
          label: 'Visitor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61272',
        },
        {
          id: '212987',
          response: 'Other',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61272',
        },
      ],
    },
    '61272': {
      id: '61272',
      active: false,
      question: 'Was medical treatment for concussion or internal injuries required?',
      label: 'Was medical treatment for concussion or internal injuries required?',
      multipleAnswers: false,
      answers: [
        {
          id: '212988',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61273',
        },
        {
          id: '212989',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61273',
        },
      ],
    },
    '61273': {
      id: '61273',
      active: false,
      question: 'Are there any staff now off duty as a result of this incident?',
      label: 'Are there any staff now off duty as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '212990',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61274',
        },
        {
          id: '212991',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61274',
        },
      ],
    },
    '61274': {
      id: '61274',
      active: false,
      question: 'Are any staff on sick leave as a result of this incident?',
      label: 'Are any staff on sick leave as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '212992',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61275',
        },
        {
          id: '212993',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61275',
        },
      ],
    },
    '61275': {
      id: '61275',
      active: false,
      question: 'Did the assault occur in public view?',
      label: 'Did the assault occur in public view?',
      multipleAnswers: false,
      answers: [
        {
          id: '212994',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61276',
        },
        {
          id: '212995',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61276',
        },
      ],
    },
    '61276': {
      id: '61276',
      active: false,
      question: 'Is there any audio or visual footage of the assault?',
      label: 'Is there any audio or visual footage of the assault?',
      multipleAnswers: false,
      answers: [
        {
          id: '212996',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61278',
        },
        {
          id: '212997',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61277',
        },
      ],
    },
    '61277': {
      id: '61277',
      active: false,
      question: 'What is the source of the footage?',
      label: 'What is the source of the footage?',
      multipleAnswers: true,
      answers: [
        {
          id: '212998',
          response: 'Body Worn Video Camera',
          active: false,
          label: 'Body worn video camera',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61278',
        },
        {
          id: '212999',
          response: 'CCTV',
          active: false,
          label: 'CCTV',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61278',
        },
        {
          id: '213000',
          response: 'Pin Phones',
          active: false,
          label: 'Pin phones',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61278',
        },
        {
          id: '213001',
          response: 'Radio Net',
          active: false,
          label: 'Radio net',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61278',
        },
        {
          id: '213002',
          response: 'Other',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61278',
        },
      ],
    },
    '61278': {
      id: '61278',
      active: false,
      question: 'Was there an apparent reason for the assault?',
      label: 'Was there an apparent reason for the assault?',
      multipleAnswers: false,
      answers: [
        {
          id: '213005',
          response: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '213006',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSAILANT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'FIGHTER',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_ASSAILANT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'VICTIM',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default ASSAULT_4
