// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:23.616Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const ASSAULT_2: IncidentTypeConfiguration = {
  incidentType: 'ASSAULT_2',
  active: false,
  startingQuestionCode: '61179',
  questions: {
    '61179': {
      code: '61179',
      active: false,
      question: 'What was the main management outcome of this incident?',
      label: 'What was the main management outcome of this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '212684',
          response: 'No further action',
          active: false,
          label: 'No further action',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '61180',
        },
        {
          code: '212685',
          response: 'IEP regression',
          active: false,
          label: 'IEP regression',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '61180',
        },
        {
          code: '212686',
          response: 'Placed on report/adjudication referral',
          active: false,
          label: 'Placed on report/adjudication referral',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '61180',
        },
        {
          code: '212687',
          response: 'Police referral',
          active: false,
          label: 'Police referral',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '61180',
        },
      ],
    },
    '61180': {
      code: '61180',
      active: false,
      question: 'Is any member of staff facing disciplinary charges?',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: '213007',
          response: 'no',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61181': {
      code: '61181',
      active: false,
      question: 'Is there any media interest in this incident?',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '213011',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61182': {
      code: '61182',
      active: false,
      question: 'Has the prison service press office been informed?',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: '213012',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61183': {
      code: '61183',
      active: false,
      question: 'Is the location of the incident known?',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          code: '213008',
          response: 'n',
          active: true,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61184': {
      code: '61184',
      active: false,
      question: 'What was the location of the incident?',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '213009',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61185': {
      code: '61185',
      active: false,
      question: 'Was this a sexual assault?',
      label: 'Was this a sexual assault?',
      multipleAnswers: false,
      answers: [
        {
          code: '213010',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61186': {
      code: '61186',
      active: false,
      question: 'Did the assault occur during a fight?',
      label: 'Did the assault occur during a fight?',
      multipleAnswers: false,
      answers: [
        {
          code: '213013',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61187': {
      code: '61187',
      active: false,
      question: 'What type of assault was it?',
      label: 'What type of assault was it?',
      multipleAnswers: false,
      answers: [
        {
          code: '213014',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61188': {
      code: '61188',
      active: false,
      question: 'Were any staff assaulted?',
      label: 'Were any staff assaulted?',
      multipleAnswers: false,
      answers: [
        {
          code: '213015',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61189': {
      code: '61189',
      active: false,
      question: 'Describe the type of staff',
      label: 'Describe the type of staff',
      multipleAnswers: false,
      answers: [
        {
          code: '213016',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61190': {
      code: '61190',
      active: false,
      question: 'Was spitting used in this incident?',
      label: 'Was spitting used in this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '213017',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61191': {
      code: '61191',
      active: false,
      question: 'Is the assailant known to have an infectious disease that can be transmitted in saliva?',
      label: 'Is the assailant known to have an infectious disease that can be transmitted in saliva?',
      multipleAnswers: false,
      answers: [
        {
          code: '213018',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61192': {
      code: '61192',
      active: false,
      question: 'Did the saliva hit the body or clothing of the victim(s)?',
      label: 'Did the saliva hit the body or clothing of the victim(s)?',
      multipleAnswers: false,
      answers: [
        {
          code: '213019',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61193': {
      code: '61193',
      active: false,
      question: 'Where did it hit?',
      label: 'Where did it hit?',
      multipleAnswers: false,
      answers: [
        {
          code: '213020',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61194': {
      code: '61194',
      active: false,
      question: 'Were any weapons used?',
      label: 'Were any weapons used?',
      multipleAnswers: false,
      answers: [
        {
          code: '213021',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61195': {
      code: '61195',
      active: false,
      question: 'Describe the weapons used?',
      label: 'Describe the weapons used?',
      multipleAnswers: false,
      answers: [
        {
          code: '213022',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61196': {
      code: '61196',
      active: false,
      question: 'Were any injuries received during this incident?',
      label: 'Were any injuries received during this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '213023',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61197': {
      code: '61197',
      active: false,
      question: 'Enter description of person(s) injured',
      label: 'Enter description of person(s) injured',
      multipleAnswers: false,
      answers: [
        {
          code: '213024',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61198': {
      code: '61198',
      active: false,
      question: 'Was a serious injury sustained?',
      label: 'Was a serious injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          code: '213025',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61200': {
      code: '61200',
      active: false,
      question: 'Which serious injuries were sustained?',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: false,
      answers: [
        {
          code: '213026',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61201': {
      code: '61201',
      active: false,
      question: 'Was a minor injury sustained?',
      label: 'Was a minor injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          code: '213027',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61202': {
      code: '61202',
      active: false,
      question: 'Which minor injuries were sustained?',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: false,
      answers: [
        {
          code: '213028',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61203': {
      code: '61203',
      active: false,
      question: 'Did injuries result in attendance to outside hospital?',
      label: 'Did injuries result in attendance to outside hospital?',
      multipleAnswers: false,
      answers: [
        {
          code: '213029',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61204': {
      code: '61204',
      active: false,
      question: 'Type of hospital admission',
      label: 'Type of hospital admission',
      multipleAnswers: false,
      answers: [
        {
          code: '213030',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61205': {
      code: '61205',
      active: false,
      question: 'Who was admitted to outside hospital?',
      label: 'Who was admitted to outside hospital?',
      multipleAnswers: false,
      answers: [
        {
          code: '213031',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61206': {
      code: '61206',
      active: false,
      question: 'Was medical treatment for concussion or internal injuries required?',
      label: 'Was medical treatment for concussion or internal injuries required?',
      multipleAnswers: false,
      answers: [
        {
          code: '213032',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61207': {
      code: '61207',
      active: false,
      question: 'Are there any staff now off duty as a result of this incident?',
      label: 'Are there any staff now off duty as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '213033',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61208': {
      code: '61208',
      active: false,
      question: 'Are any staff on sick leave as a result of this incident?',
      label: 'Are any staff on sick leave as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '213034',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61209': {
      code: '61209',
      active: false,
      question: 'Did the assault occur in public view?',
      label: 'Did the assault occur in public view?',
      multipleAnswers: false,
      answers: [
        {
          code: '213035',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61210': {
      code: '61210',
      active: false,
      question: 'Is there any audio or visual footage of the assault?',
      label: 'Is there any audio or visual footage of the assault?',
      multipleAnswers: false,
      answers: [
        {
          code: '213036',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61211': {
      code: '61211',
      active: false,
      question: 'What is the source of the footage?',
      label: 'What is the source of the footage?',
      multipleAnswers: false,
      answers: [
        {
          code: '213037',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
    '61212': {
      code: '61212',
      active: false,
      question: 'Was there an apparent reason for the assault?',
      label: 'Was there an apparent reason for the assault?',
      multipleAnswers: false,
      answers: [
        {
          code: '213038',
          response: 'n',
          active: false,
          label: 'N',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
  },
  prisonerRoles: [],
}

export default ASSAULT_2
