// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-20T16:52:11.771Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const ASSAULT: IncidentTypeConfiguration = {
  incidentType: 'ASSAULT',
  active: true,
  startingQuestionId: '61279',
  questions: {
    '61279': {
      id: '61279',
      active: true,
      code: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THE INCIDENT',
      label: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO FURTHER ACTION',
          active: true,
          label: 'NO FURTHER ACTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61280',
        },
        {
          code: 'IEP REGRESSION',
          active: true,
          label: 'IEP REGRESSION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61280',
        },
        {
          code: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          active: true,
          label: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61280',
        },
        {
          code: 'POLICE REFERRAL',
          active: true,
          label: 'POLICE REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61280',
        },
      ],
    },
    '61280': {
      id: '61280',
      active: true,
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61281',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61281',
        },
      ],
    },
    '61281': {
      id: '61281',
      active: true,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61282',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61282',
        },
      ],
    },
    '61282': {
      id: '61282',
      active: true,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61283',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61283',
        },
      ],
    },
    '61283': {
      id: '61283',
      active: true,
      code: 'IS THE LOCATION OF THE INCDENT KNOWN',
      label: 'IS THE LOCATION OF THE INCDENT KNOWN',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61284',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
      ],
    },
    '61284': {
      id: '61284',
      active: true,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          active: true,
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'ASSOCIATION AREA',
          active: true,
          label: 'ASSOCIATION AREA',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'CELL',
          active: true,
          label: 'CELL',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'CHAPEL',
          active: true,
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'DINING ROOM',
          active: true,
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'DORMITORY',
          active: true,
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'EDUCATION',
          active: true,
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'EXERCISE YARD',
          active: true,
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'GATE',
          active: true,
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'GYM',
          active: true,
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'HEALTH CARE CENTRE',
          active: true,
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'KITCHEN',
          active: true,
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'OFFICE',
          active: true,
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'RECEPTION',
          active: true,
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'RECESS',
          active: true,
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'SEGREGATION UNIT',
          active: true,
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'SPECIAL UNIT',
          active: true,
          label: 'SPECIAL UNIT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'SHOWERS/CHANGING ROOM',
          active: true,
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'VISITS',
          active: true,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'WING',
          active: true,
          label: 'WING',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'WORKS DEPARTMENT',
          active: true,
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'WORKSHOP',
          active: true,
          label: 'WORKSHOP',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'WITHIN PERIMETER',
          active: true,
          label: 'WITHIN PERIMETER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'ELSEWHERE',
          active: true,
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'FUNERAL',
          active: true,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: true,
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: true,
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          active: true,
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'SPORTS FIELD',
          active: true,
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'VEHICLE',
          active: true,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'WEDDINGS',
          active: true,
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'MAGISTRATES COURT',
          active: true,
          label: 'MAGISTRATES COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'CROWN COURT',
          active: true,
          label: 'CROWN COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'INDUCTION/FIRST NIGHT CENTRE',
          active: true,
          label: 'INDUCTION/FIRST NIGHT CENTRE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'MAIL ROOM',
          active: true,
          label: 'MAIL ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'VULNERABLE PRISONERS UNIT (VPU)',
          active: true,
          label: 'VULNERABLE PRISONERS UNIT (VPU)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
        {
          code: 'EXTERNAL ROOF',
          active: true,
          label: 'EXTERNAL ROOF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61285',
        },
      ],
    },
    '61285': {
      id: '61285',
      active: true,
      code: 'WAS THIS A SEXUAL ASSAULT',
      label: 'WAS THIS A SEXUAL ASSAULT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61286',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61286',
        },
      ],
    },
    '61286': {
      id: '61286',
      active: true,
      code: 'DID THE ASSAULT OCCUR DURING A FIGHT',
      label: 'DID THE ASSAULT OCCUR DURING A FIGHT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61287',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61287',
        },
      ],
    },
    '61287': {
      id: '61287',
      active: true,
      code: 'WHAT TYPE OF ASSAULT WAS IT',
      label: 'WHAT TYPE OF ASSAULT WAS IT',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISONER ON PRISONER',
          active: true,
          label: 'PRISONER ON PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61288',
        },
        {
          code: 'PRISONER ON STAFF',
          active: true,
          label: 'PRISONER ON STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61289',
        },
        {
          code: 'PRISONER ON OTHER',
          active: true,
          label: 'PRISONER ON OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61288',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61288',
        },
      ],
    },
    '61288': {
      id: '61288',
      active: true,
      code: 'WERE ANY STAFF ASSAULTED',
      label: 'WERE ANY STAFF ASSAULTED',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61290',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61289',
        },
      ],
    },
    '61289': {
      id: '61289',
      active: true,
      code: 'DESCRIBE THE TYPE OF STAFF',
      label: 'DESCRIBE THE TYPE OF STAFF',
      multipleAnswers: true,
      answers: [
        {
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'OPERATIONAL STAFF - PRISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61290',
        },
        {
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'OPERATIONAL STAFF - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61290',
        },
        {
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'NON-OPERATIONAL STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61290',
        },
        {
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'NON-DIRECTLY EMPLOYED STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61290',
        },
      ],
    },
    '61290': {
      id: '61290',
      active: true,
      code: 'WAS SPITTING USED IN THIS INCIDENT',
      label: 'WAS SPITTING USED IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61294',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61291',
        },
      ],
    },
    '61291': {
      id: '61291',
      active: true,
      code: 'IS THE ASSAILANT KNOWN TO HAVE AN INFECTIOUS DISEASE THAT CAN BE TRANSMITTED IN SALIVA',
      label: 'IS THE ASSAILANT KNOWN TO HAVE AN INFECTIOUS DISEASE THAT CAN BE TRANSMITTED IN SALIVA',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61292',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61292',
        },
      ],
    },
    '61292': {
      id: '61292',
      active: true,
      code: 'DID THE SALIVA HIT THE BODY OR CLOTHING OF THE VICTIM(S)',
      label: 'DID THE SALIVA HIT THE BODY OR CLOTHING OF THE VICTIM(S)',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61294',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61293',
        },
      ],
    },
    '61293': {
      id: '61293',
      active: true,
      code: 'WHERE DID IT HIT',
      label: 'WHERE DID IT HIT',
      multipleAnswers: true,
      answers: [
        {
          code: 'NECK OR ABOVE',
          active: true,
          label: 'NECK OR ABOVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61294',
        },
        {
          code: 'TORSO',
          active: true,
          label: 'TORSO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61294',
        },
        {
          code: 'ARMS OR HANDS',
          active: true,
          label: 'ARMS OR HANDS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61294',
        },
        {
          code: 'LEGS OR FEET',
          active: true,
          label: 'LEGS OR FEET',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61294',
        },
      ],
    },
    '61294': {
      id: '61294',
      active: true,
      code: 'WERE ANY WEAPONS USED',
      label: 'WERE ANY WEAPONS USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61295',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
      ],
    },
    '61295': {
      id: '61295',
      active: true,
      code: 'DESCRIBE THE WEAPONS USED',
      label: 'DESCRIBE THE WEAPONS USED',
      multipleAnswers: true,
      answers: [
        {
          code: 'FIREARM',
          active: true,
          label: 'FIREARM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'CHEMICAL INCAPACITANT',
          active: true,
          label: 'CHEMICAL INCAPACITANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'KNIFE/BLADE',
          active: true,
          label: 'KNIFE/BLADE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'OTHER SHARP INSTRUMENT',
          active: true,
          label: 'OTHER SHARP INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'BLUNT INSTRUMENT',
          active: true,
          label: 'BLUNT INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'LIGATURE',
          active: true,
          label: 'LIGATURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'DANGEROUS LIQUID',
          active: true,
          label: 'DANGEROUS LIQUID',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'EXCRETA/URINE',
          active: true,
          label: 'EXCRETA/URINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'FOOD',
          active: true,
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'THROWN FURNITURE',
          active: true,
          label: 'THROWN FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'THROWN EQUIPMENT',
          active: true,
          label: 'THROWN EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61296',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61296',
        },
      ],
    },
    '61296': {
      id: '61296',
      active: true,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61297',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61306',
        },
      ],
    },
    '61297': {
      id: '61297',
      active: true,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61298',
        },
        {
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'OPERATIONAL STAFF - PRISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61298',
        },
        {
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'OPERATIONAL STAFF - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61298',
        },
        {
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'NON-OPERATIONAL STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61298',
        },
        {
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'NON-DIRECTLY EMPLOYED STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61298',
        },
        {
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61298',
        },
        {
          code: 'VISITOR',
          active: true,
          label: 'VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61298',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61298',
        },
      ],
    },
    '61298': {
      id: '61298',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'WAS A SERIOUS INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61299',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
      ],
    },
    '61299': {
      id: '61299',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'FRACTURE',
          active: true,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'SCALD OR BURN',
          active: true,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'STABBING',
          active: true,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'CRUSHING',
          active: true,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'BLACK EYE',
          active: true,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'BROKEN NOSE',
          active: true,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'BROKEN TEETH',
          active: true,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'BITES',
          active: true,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
        {
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61300',
        },
      ],
    },
    '61300': {
      id: '61300',
      active: true,
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'WAS A MINOR INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61301',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61302',
        },
      ],
    },
    '61301': {
      id: '61301',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61302',
        },
        {
          code: 'MINOR BRUISES',
          active: true,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61302',
        },
        {
          code: 'SWELLINGS',
          active: true,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61302',
        },
        {
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61302',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61302',
        },
      ],
    },
    '61302': {
      id: '61302',
      active: true,
      code: 'DID INJURIES RESULT IN ATTENDANCE TO OUTSIDE HOSPITAL',
      label: 'DID INJURIES RESULT IN ATTENDANCE TO OUTSIDE HOSPITAL',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61303',
        },
      ],
    },
    '61303': {
      id: '61303',
      active: true,
      code: 'TYPE OF HOSPITAL ADMISSION',
      label: 'TYPE OF HOSPITAL ADMISSION',
      multipleAnswers: true,
      answers: [
        {
          code: 'A AND E',
          active: true,
          label: 'A AND E',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61304',
        },
        {
          code: 'INPATIENT (OVERNIGHT ONLY)',
          active: true,
          label: 'INPATIENT (OVERNIGHT ONLY)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61304',
        },
        {
          code: 'INPATIENT (OVER 24HR)',
          active: true,
          label: 'INPATIENT (OVER 24HR)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61304',
        },
        {
          code: 'LIFE SUPPORT',
          active: true,
          label: 'LIFE SUPPORT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61304',
        },
      ],
    },
    '61304': {
      id: '61304',
      active: false,
      code: 'WHO WAS ADMMITED TO OUTSIDE HOSPITAL',
      label: 'WHO WAS ADMMITED TO OUTSIDE HOSPITAL',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONERS',
          active: false,
          label: 'PRISONERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: false,
          label: 'OPERATIONAL STAFF - PRISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'OPERATIONAL STAFF - OTHER',
          active: false,
          label: 'OPERATIONAL STAFF - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '61305': {
      id: '61305',
      active: true,
      code: 'WAS MEDICAL TREATMENT FOR CONCUSSION OR INTERNAL INJURIES REQUIRED',
      label: 'WAS MEDICAL TREATMENT FOR CONCUSSION OR INTERNAL INJURIES REQUIRED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61306',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61306',
        },
      ],
    },
    '61306': {
      id: '61306',
      active: true,
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61307',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61307',
        },
      ],
    },
    '61307': {
      id: '61307',
      active: true,
      code: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      label: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61308',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61308',
        },
      ],
    },
    '61308': {
      id: '61308',
      active: true,
      code: 'DID THE ASSAULT OCCUR IN PUBLIC VIEW',
      label: 'DID THE ASSAULT OCCUR IN PUBLIC VIEW',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61309',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61309',
        },
      ],
    },
    '61309': {
      id: '61309',
      active: true,
      code: 'IS THERE ANY AUDIO OR VISUAL FOOTAGE OF THE ASSAULT',
      label: 'IS THERE ANY AUDIO OR VISUAL FOOTAGE OF THE ASSAULT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61311',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61310',
        },
      ],
    },
    '61310': {
      id: '61310',
      active: true,
      code: 'WHAT IS THE SOURCE OF THE FOOTAGE',
      label: 'WHAT IS THE SOURCE OF THE FOOTAGE',
      multipleAnswers: true,
      answers: [
        {
          code: 'BODY WORN VIDEO CAMERA',
          active: true,
          label: 'BODY WORN VIDEO CAMERA',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61311',
        },
        {
          code: 'CCTV',
          active: true,
          label: 'CCTV',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61311',
        },
        {
          code: 'PIN PHONES',
          active: true,
          label: 'PIN PHONES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61311',
        },
        {
          code: 'RADIO NET',
          active: true,
          label: 'RADIO NET',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61311',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61311',
        },
      ],
    },
    '61311': {
      id: '61311',
      active: true,
      code: 'WAS THERE AN APPARENT REASON FOR THE ASSAULT',
      label: 'WAS THERE AN APPARENT REASON FOR THE ASSAULT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '61313': {
      id: '61313',
      active: true,
      code: 'WHO WAS ADMITTED TO OUTSIDE HOSPITAL',
      label: 'WHO WAS ADMITTED TO OUTSIDE HOSPITAL',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'OPERATIONAL STAFF - PRISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'OPERATIONAL STAFF - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'NON-OPERATIONAL STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'NON-DIRECTLY EMPLOYED STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'VISITOR',
          active: true,
          label: 'VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '61305',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '61305',
        },
      ],
    },
  },
} as const

export default ASSAULT
