// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-10-15T17:17:13.209Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const ATTEMPTED_ESCAPE_FROM_ESCORT: IncidentTypeConfiguration = {
  incidentType: 'ATTEMPTED_ESCAPE_FROM_ESCORT',
  active: true,
  startingQuestionId: '44423',
  questions: {
    '44139': {
      id: '44139',
      active: true,
      code: 'FROM WHAT ESCORT TYPE DID THE ATTEMPTED ESCAPE OCCUR',
      label: 'FROM WHAT ESCORT TYPE DID THE ATTEMPTED ESCAPE OCCUR',
      multipleAnswers: false,
      answers: [
        {
          id: '178956',
          code: 'HOSPITAL OUTPATIENT',
          active: true,
          label: 'HOSPITAL OUTPATIENT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44168',
        },
        {
          id: '178955',
          code: 'HOSPITAL INPATIENT',
          active: true,
          label: 'HOSPITAL INPATIENT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44168',
        },
        {
          id: '178962',
          code: 'INTER PRISON TRANSFER',
          active: true,
          label: 'INTER PRISON TRANSFER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178963',
          code: 'MAGISTRATES COURT',
          active: true,
          label: 'MAGISTRATES COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178958',
          code: 'CROWN COURT',
          active: true,
          label: 'CROWN COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178957',
          code: 'COUNTY COURT',
          active: true,
          label: 'COUNTY COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178959',
          code: 'FUNERAL',
          active: true,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178965',
          code: 'WEDDING',
          active: true,
          label: 'WEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178960',
          code: 'HOME VISIT',
          active: true,
          label: 'HOME VISIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178961',
          code: 'HOSP VISIT (DYING RELATIVE)',
          active: true,
          label: 'HOSP VISIT (DYING RELATIVE)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '178964',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
      ],
    },
    '44148': {
      id: '44148',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE KNIFE OR BLADE',
      label: 'WHAT WAS THE SOURCE OF THE KNIFE OR BLADE',
      multipleAnswers: false,
      answers: [
        {
          id: '178995',
          code: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'SECRETED ON THE PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
        {
          id: '178993',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
        {
          id: '178992',
          code: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
        {
          id: '178994',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
      ],
    },
    '44157': {
      id: '44157',
      active: true,
      code: 'WERE ANY OTHER WEAPONS USED DURING THE ATTEMPTED ESCAPE',
      label: 'WERE ANY OTHER WEAPONS USED DURING THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '179017',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44638',
        },
        {
          id: '179018',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
      ],
    },
    '44168': {
      id: '44168',
      active: true,
      code: 'WAS THE ESCORT FOR CHILD BIRTH OR PRE/POST NATAL TREATMENT',
      label: 'WAS THE ESCORT FOR CHILD BIRTH OR PRE/POST NATAL TREATMENT',
      multipleAnswers: false,
      answers: [
        {
          id: '179057',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          id: '179056',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
      ],
    },
    '44180': {
      id: '44180',
      active: true,
      code: 'DESCRIBE THE DAMAGE',
      label: 'DESCRIBE THE DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          id: '179090',
          code: 'MINOR',
          active: true,
          label: 'MINOR',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44881',
        },
        {
          id: '179091',
          code: 'SERIOUS',
          active: true,
          label: 'SERIOUS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44881',
        },
        {
          id: '179089',
          code: 'EXTENSIVE',
          active: true,
          label: 'EXTENSIVE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44881',
        },
      ],
    },
    '44203': {
      id: '44203',
      active: true,
      code: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      multipleAnswers: false,
      answers: [
        {
          id: '179172',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44479',
        },
        {
          id: '179171',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44479',
        },
      ],
    },
    '44226': {
      id: '44226',
      active: true,
      code: 'HOW WAS THE RESTRAINT OVERCOME AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'HOW WAS THE RESTRAINT OVERCOME AT THE POINT OF THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '179230',
          code: 'PRISONER USED KEY',
          active: true,
          label: 'PRISONER USED KEY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44967',
        },
        {
          id: '179231',
          code: 'SLIPPED RESTRAINT',
          active: true,
          label: 'SLIPPED RESTRAINT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44819',
        },
        {
          id: '179235',
          code: 'PICKED LOCK',
          active: true,
          label: 'PICKED LOCK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '179236',
          code: 'STAFF UNLOCKED UNDER THREAT',
          active: true,
          label: 'STAFF UNLOCKED UNDER THREAT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '179232',
          code: 'IMPROPER APPLICATION',
          active: true,
          label: 'IMPROPER APPLICATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '179234',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '179233',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44240': {
      id: '44240',
      active: true,
      code: 'HOW WAS THE ESCAPE PREVENTED',
      label: 'HOW WAS THE ESCAPE PREVENTED',
      multipleAnswers: false,
      answers: [
        {
          id: '179291',
          code: 'PHYSICAL BARRIER',
          active: true,
          label: 'PHYSICAL BARRIER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          id: '179293',
          code: 'PRISON STAFF INTERVENTION',
          active: true,
          label: 'PRISON STAFF INTERVENTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          id: '179292',
          code: 'POLICE INTERVENTION',
          active: true,
          label: 'POLICE INTERVENTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          id: '179289',
          code: 'MEMBER OF PUBLIC',
          active: true,
          label: 'MEMBER OF PUBLIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          id: '179294',
          code: 'PRISONER ABANDONED ATTEMPT',
          active: true,
          label: 'PRISONER ABANDONED ATTEMPT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          id: '179295',
          code: 'PRISONER INJURED IN ATTEMPT',
          active: true,
          label: 'PRISONER INJURED IN ATTEMPT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          id: '179290',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44559',
        },
      ],
    },
    '44269': {
      id: '44269',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '179372',
          code: 'FRACTURE',
          active: true,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179374',
          code: 'SCALD OR BURN',
          active: true,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179375',
          code: 'STABBING',
          active: true,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179369',
          code: 'CRUSHING',
          active: true,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179371',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179366',
          code: 'BLACK EYE',
          active: true,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179367',
          code: 'BROKEN NOSE',
          active: true,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179368',
          code: 'BROKEN TEETH',
          active: true,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179370',
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179365',
          code: 'BITES',
          active: true,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179373',
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          id: '179376',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
      ],
    },
    '44280': {
      id: '44280',
      active: true,
      code: 'HAS THE KEY BEEN RECOVERED',
      label: 'HAS THE KEY BEEN RECOVERED',
      multipleAnswers: false,
      answers: [
        {
          id: '179396',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '179395',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44288': {
      id: '44288',
      active: true,
      code: 'WAS THE FIREARM',
      label: 'WAS THE FIREARM',
      multipleAnswers: false,
      answers: [
        {
          id: '179414',
          code: 'REAL',
          active: true,
          label: 'REAL',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44701',
        },
        {
          id: '179415',
          code: 'REPLICA',
          active: true,
          label: 'REPLICA',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44701',
        },
        {
          id: '179413',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44701',
        },
      ],
    },
    '44294': {
      id: '44294',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE SPRAY',
      label: 'WHAT WAS THE SOURCE OF THE SPRAY',
      multipleAnswers: false,
      answers: [
        {
          id: '179429',
          code: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'SECRETED ON THE PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
        {
          id: '179427',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
        {
          id: '179426',
          code: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
        {
          id: '179428',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
      ],
    },
    '44302': {
      id: '44302',
      active: true,
      code: 'WAS DOUBLE CUFFING EMPLOYED',
      label: 'WAS DOUBLE CUFFING EMPLOYED',
      multipleAnswers: false,
      answers: [
        {
          id: '179474',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45034',
        },
        {
          id: '179473',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45034',
        },
      ],
    },
    '44306': {
      id: '44306',
      active: true,
      code: 'WERE ANY INJURIES SUSTAINED BY PRISONERS',
      label: 'WERE ANY INJURIES SUSTAINED BY PRISONERS',
      multipleAnswers: false,
      answers: [
        {
          id: '179516',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45099',
        },
        {
          id: '179517',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
      ],
    },
    '44307': {
      id: '44307',
      active: true,
      code: 'WHAT TYPE OF VEHICLE WAS IT',
      label: 'WHAT TYPE OF VEHICLE WAS IT',
      multipleAnswers: false,
      answers: [
        {
          id: '179519',
          code: 'COACH',
          active: true,
          label: 'COACH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '179520',
          code: 'MINIBUS',
          active: true,
          label: 'MINIBUS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '179523',
          code: 'TAXI',
          active: true,
          label: 'TAXI',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '179518',
          code: 'CELLULAR VEHICLE',
          active: true,
          label: 'CELLULAR VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '179522',
          code: 'SECURE TRANSIT',
          active: true,
          label: 'SECURE TRANSIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '179521',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44886',
        },
      ],
    },
    '44308': {
      id: '44308',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE FIREARM',
      label: 'WHAT WAS THE SOURCE OF THE FIREARM',
      multipleAnswers: false,
      answers: [
        {
          id: '179527',
          code: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'SECRETED ON THE PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
        {
          id: '179525',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
        {
          id: '179524',
          code: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
        {
          id: '179526',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
      ],
    },
    '44312': {
      id: '44312',
      active: true,
      code: 'WAS A FIREARM USED DURING THE ATTEMPTED ESCAPE',
      label: 'WAS A FIREARM USED DURING THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '179534',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44288',
        },
        {
          id: '179535',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
      ],
    },
    '44421': {
      id: '44421',
      active: true,
      code: 'WERE MINOR INJURIES SUSTAINED BY STAFF',
      label: 'WERE MINOR INJURIES SUSTAINED BY STAFF',
      multipleAnswers: false,
      answers: [
        {
          id: '179899',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44626',
        },
        {
          id: '179900',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
      ],
    },
    '44423': {
      id: '44423',
      active: true,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '179903',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44900',
        },
        {
          id: '179904',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44924',
        },
      ],
    },
    '44429': {
      id: '44429',
      active: true,
      code: 'WAS THE PRISONER WHO ATTEMPTED TO ESCAPE ON THE ESCAPE LIST',
      label: 'WAS THE PRISONER WHO ATTEMPTED TO ESCAPE ON THE ESCAPE LIST',
      multipleAnswers: false,
      answers: [
        {
          id: '179917',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45011',
        },
        {
          id: '179916',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45011',
        },
      ],
    },
    '44437': {
      id: '44437',
      active: true,
      code: 'WAS THE RESTRAINT OVERCOME AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'WAS THE RESTRAINT OVERCOME AT THE POINT OF THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '179938',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44226',
        },
        {
          id: '179939',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44457': {
      id: '44457',
      active: true,
      code: 'WERE THE ROUNDS DISCHARGED',
      label: 'WERE THE ROUNDS DISCHARGED',
      multipleAnswers: false,
      answers: [
        {
          id: '180006',
          code: 'LIVE',
          active: true,
          label: 'LIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
        {
          id: '180005',
          code: 'BLANK',
          active: true,
          label: 'BLANK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
        {
          id: '180007',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
      ],
    },
    '44479': {
      id: '44479',
      active: true,
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      multipleAnswers: false,
      answers: [
        {
          id: '180137',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44960',
        },
        {
          id: '180136',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44960',
        },
      ],
    },
    '44481': {
      id: '44481',
      active: true,
      code: 'DID ANY PRISONER REQUIRE MEDICAL TREATMENT FOR INJURIES',
      label: 'DID ANY PRISONER REQUIRE MEDICAL TREATMENT FOR INJURIES',
      multipleAnswers: false,
      answers: [
        {
          id: '180151',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44535',
        },
        {
          id: '180152',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
      ],
    },
    '44491': {
      id: '44491',
      active: true,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          id: '180183',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45094',
        },
        {
          id: '180182',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45094',
        },
      ],
    },
    '44496': {
      id: '44496',
      active: true,
      code: 'WHERE DID THE ATTEMPTED ESCAPE TAKE PLACE',
      label: 'WHERE DID THE ATTEMPTED ESCAPE TAKE PLACE',
      multipleAnswers: false,
      answers: [
        {
          id: '180197',
          code: 'VEHICLE EN ROUTE TO VENUE',
          active: true,
          label: 'VEHICLE EN ROUTE TO VENUE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          id: '180196',
          code: 'VEHICLE EN ROUTE FROM VENUE',
          active: true,
          label: 'VEHICLE EN ROUTE FROM VENUE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          id: '180195',
          code: 'LEAVING VEHICLE (DEBUSSING)',
          active: true,
          label: 'LEAVING VEHICLE (DEBUSSING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          id: '180194',
          code: 'ENTERING VEHICLE (EMBUSSING)',
          active: true,
          label: 'ENTERING VEHICLE (EMBUSSING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          id: '180206',
          code: 'UNSCHEDULED STOP',
          active: true,
          label: 'UNSCHEDULED STOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180198',
          code: 'CELL AT COURT',
          active: true,
          label: 'CELL AT COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180199',
          code: 'COURT CELLS AREA',
          active: true,
          label: 'COURT CELLS AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180201',
          code: 'COURT VISITS AREA',
          active: true,
          label: 'COURT VISITS AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180200',
          code: 'COURT DOCK',
          active: true,
          label: 'COURT DOCK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180204',
          code: 'HOSPITAL WARD/ROOM',
          active: true,
          label: 'HOSPITAL WARD/ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180202',
          code: 'HOSPITAL TREATMENT ROOM',
          active: true,
          label: 'HOSPITAL TREATMENT ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180203',
          code: 'HOSPITAL WAITING AREA',
          active: true,
          label: 'HOSPITAL WAITING AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          id: '180205',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44886',
        },
      ],
    },
    '44529': {
      id: '44529',
      active: true,
      code: 'WHY WAS A RESTRAINT NOT APPLIED AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'WHY WAS A RESTRAINT NOT APPLIED AT THE POINT OF THE ATTEMPTED ESCAPE',
      multipleAnswers: true,
      answers: [
        {
          id: '180340',
          code: 'GOVERNORS INSTRUCTION',
          active: true,
          label: 'GOVERNORS INSTRUCTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180347',
          code: 'PREVENTED BY DISABILITY',
          active: true,
          label: 'PREVENTED BY DISABILITY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180348',
          code: 'PREVENTED BY INJURY',
          active: true,
          label: 'PREVENTED BY INJURY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180344',
          code: 'MEDICAL TREATMENT/REQUEST',
          active: true,
          label: 'MEDICAL TREATMENT/REQUEST',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180342',
          code: 'IN COURT ROOM',
          active: true,
          label: 'IN COURT ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180343',
          code: 'LOCATED IN SECURE AREA',
          active: true,
          label: 'LOCATED IN SECURE AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180341',
          code: 'IN CELL OF CELLULAR VEHICLE',
          active: true,
          label: 'IN CELL OF CELLULAR VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180349',
          code: 'TRANSFER TO MENTAL HOSPITAL',
          active: true,
          label: 'TRANSFER TO MENTAL HOSPITAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180338',
          code: 'DURING MARRIAGE CEREMONY',
          active: true,
          label: 'DURING MARRIAGE CEREMONY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180345',
          code: 'NONE AVAILABLE',
          active: true,
          label: 'NONE AVAILABLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180339',
          code: 'FAILURE TO USE',
          active: true,
          label: 'FAILURE TO USE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '180346',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44535': {
      id: '44535',
      active: true,
      code: 'WHERE WERE THE INJURED PRISONERS TREATED',
      label: 'WHERE WERE THE INJURED PRISONERS TREATED',
      multipleAnswers: false,
      answers: [
        {
          id: '180392',
          code: 'PRISON HEALTH CARE CENTRE',
          active: true,
          label: 'PRISON HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
        {
          id: '180391',
          code: 'OUTSIDE HOSPITAL',
          active: true,
          label: 'OUTSIDE HOSPITAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
      ],
    },
    '44542': {
      id: '44542',
      active: true,
      code: 'WHAT RESTRAINT WAS BEING USED AT THE POINT OF ATTEMPTED ESCAPE',
      label: 'WHAT RESTRAINT WAS BEING USED AT THE POINT OF ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '180413',
          code: 'HANDCUFFS',
          active: true,
          label: 'HANDCUFFS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44302',
        },
        {
          id: '180415',
          code: 'ESCORT CHAIN',
          active: true,
          label: 'ESCORT CHAIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          id: '180414',
          code: 'CLOSETING CHAIN',
          active: true,
          label: 'CLOSETING CHAIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          id: '180416',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44437',
        },
      ],
    },
    '44559': {
      id: '44559',
      active: true,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      multipleAnswers: false,
      answers: [
        {
          id: '180461',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44180',
        },
        {
          id: '180462',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44566': {
      id: '44566',
      active: true,
      code: 'WAS A KNIFE OR BLADE USED DURING THE ATTEMPTED ESCAPE',
      label: 'WAS A KNIFE OR BLADE USED DURING THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '180475',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44888',
        },
        {
          id: '180476',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
      ],
    },
    '44599': {
      id: '44599',
      active: true,
      code: 'WAS OUTSIDE ASSISTANCE INVOLVED IN THE ATTEMPTED ESCAPE',
      label: 'WAS OUTSIDE ASSISTANCE INVOLVED IN THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '180600',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44312',
        },
        {
          id: '180599',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44312',
        },
      ],
    },
    '44604': {
      id: '44604',
      active: true,
      code: 'WHO USED THE SPRAY',
      label: 'WHO USED THE SPRAY',
      multipleAnswers: false,
      answers: [
        {
          id: '180612',
          code: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'PRISONER WHO ATTEMPTED ESCAPE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44294',
        },
        {
          id: '180610',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44294',
        },
        {
          id: '180611',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44294',
        },
      ],
    },
    '44626': {
      id: '44626',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '180668',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          id: '180669',
          code: 'MINOR BRUISES',
          active: true,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          id: '180672',
          code: 'SWELLINGS',
          active: true,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          id: '180671',
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          id: '180670',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45041',
        },
      ],
    },
    '44627': {
      id: '44627',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE WEAPONS USED',
      label: 'WHAT WAS THE SOURCE OF THE WEAPONS USED',
      multipleAnswers: false,
      answers: [
        {
          id: '180676',
          code: 'SECRETED ON PRISONER',
          active: true,
          label: 'SECRETED ON PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
        {
          id: '180674',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
        {
          id: '180673',
          code: 'BROUGHT BY OUTSIDE ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
        {
          id: '180675',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
      ],
    },
    '44638': {
      id: '44638',
      active: true,
      code: 'WHAT OTHER WEAPONS WERE USED',
      label: 'WHAT OTHER WEAPONS WERE USED',
      multipleAnswers: true,
      answers: [
        {
          id: '180721',
          code: 'OTHER SHARP INSTRUMENT',
          active: true,
          label: 'OTHER SHARP INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180715',
          code: 'BLUNT INSTRUMENT',
          active: true,
          label: 'BLUNT INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180719',
          code: 'LIGATURE',
          active: true,
          label: 'LIGATURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180716',
          code: 'DANGEROUS LIQUID',
          active: true,
          label: 'DANGEROUS LIQUID',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180717',
          code: 'EXCRETA/URINE',
          active: true,
          label: 'EXCRETA/URINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180722',
          code: 'SPITTING',
          active: true,
          label: 'SPITTING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180718',
          code: 'FOOD',
          active: true,
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180724',
          code: 'THROWN FURNITURE',
          active: true,
          label: 'THROWN FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180723',
          code: 'THROWN EQUIPMENT',
          active: true,
          label: 'THROWN EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          id: '180720',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44739',
        },
      ],
    },
    '44647': {
      id: '44647',
      active: true,
      code: 'WERE ANY INJURIES SUSTAINED BY STAFF',
      label: 'WERE ANY INJURIES SUSTAINED BY STAFF',
      multipleAnswers: false,
      answers: [
        {
          id: '180741',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45115',
        },
        {
          id: '180742',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
      ],
    },
    '44701': {
      id: '44701',
      active: true,
      code: 'WAS THE FIREARM DISCHARGED',
      label: 'WAS THE FIREARM DISCHARGED',
      multipleAnswers: false,
      answers: [
        {
          id: '180955',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44457',
        },
        {
          id: '180956',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
      ],
    },
    '44708': {
      id: '44708',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '180973',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          id: '180974',
          code: 'MINOR BRUISES',
          active: true,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          id: '180977',
          code: 'SWELLINGS',
          active: true,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          id: '180976',
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          id: '180975',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44481',
        },
      ],
    },
    '44739': {
      id: '44739',
      active: true,
      code: 'WHO USED THE OTHER WEAPONS',
      label: 'WHO USED THE OTHER WEAPONS',
      multipleAnswers: false,
      answers: [
        {
          id: '181079',
          code: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'PRISONER WHO ATTEMPTED ESCAPE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44627',
        },
        {
          id: '181077',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44627',
        },
        {
          id: '181078',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44627',
        },
      ],
    },
    '44771': {
      id: '44771',
      active: true,
      code: 'NUMBER OF PRISONERS ON ESCORT',
      label: 'NUMBER OF PRISONERS ON ESCORT',
      multipleAnswers: true,
      answers: [
        {
          id: '181161',
          code: 'MALE',
          active: true,
          label: 'MALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45061',
        },
        {
          id: '181160',
          code: 'FEMALE',
          active: true,
          label: 'FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45061',
        },
      ],
    },
    '44782': {
      id: '44782',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED BY STAFF',
      label: 'WAS A SERIOUS INJURY SUSTAINED BY STAFF',
      multipleAnswers: false,
      answers: [
        {
          id: '181182',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44269',
        },
        {
          id: '181183',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
      ],
    },
    '44794': {
      id: '44794',
      active: true,
      code: 'PRIOR TO PRIVATE SECTOR INVOLVEMENT WOULD THE ESCORT HAVE BEEN',
      label: 'PRIOR TO PRIVATE SECTOR INVOLVEMENT WOULD THE ESCORT HAVE BEEN',
      multipleAnswers: false,
      answers: [
        {
          id: '181244',
          code: 'PRISON SERVICE',
          active: true,
          label: 'PRISON SERVICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44139',
        },
        {
          id: '181243',
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44139',
        },
      ],
    },
    '44819': {
      id: '44819',
      active: true,
      code: 'WERE INSERTS USED',
      label: 'WERE INSERTS USED',
      multipleAnswers: false,
      answers: [
        {
          id: '181301',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          id: '181300',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44836': {
      id: '44836',
      active: true,
      code: 'WAS A CHEMICAL INCAPACITANT SPRAY USED DURING THE ATTEMPTED ESCAPE',
      label: 'WAS A CHEMICAL INCAPACITANT SPRAY USED DURING THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '181337',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44915',
        },
        {
          id: '181338',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
      ],
    },
    '44881': {
      id: '44881',
      active: true,
      code: 'ESTIMATED COST OF DAMAGE',
      label: 'ESTIMATED COST OF DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          id: '181519',
          code: 'ENTER AMOUNT IN POUND STERLING',
          active: true,
          label: 'ENTER AMOUNT IN POUND STERLING',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44886': {
      id: '44886',
      active: true,
      code: 'NUMBER OF STAFF ON ESCORT',
      label: 'NUMBER OF STAFF ON ESCORT',
      multipleAnswers: true,
      answers: [
        {
          id: '181537',
          code: 'MALE (ENTER NUMBER)',
          active: true,
          label: 'MALE (ENTER NUMBER)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44771',
        },
        {
          id: '181536',
          code: 'FEMALE (ENTER NUMBER)',
          active: true,
          label: 'FEMALE (ENTER NUMBER)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44771',
        },
      ],
    },
    '44888': {
      id: '44888',
      active: true,
      code: 'WAS THE KNIFE OR BLADE USED PURPOSE MADE OR IMPROVISED',
      label: 'WAS THE KNIFE OR BLADE USED PURPOSE MADE OR IMPROVISED',
      multipleAnswers: false,
      answers: [
        {
          id: '181549',
          code: 'PURPOSE MADE',
          active: true,
          label: 'PURPOSE MADE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44955',
        },
        {
          id: '181547',
          code: 'IMPROVISED',
          active: true,
          label: 'IMPROVISED',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44955',
        },
        {
          id: '181548',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44955',
        },
      ],
    },
    '44900': {
      id: '44900',
      active: true,
      code: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          id: '181581',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44924',
        },
        {
          id: '181580',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44924',
        },
      ],
    },
    '44905': {
      id: '44905',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '181600',
          code: 'FRACTURE',
          active: true,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181602',
          code: 'SCALD OR BURN',
          active: true,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181603',
          code: 'STABBING',
          active: true,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181597',
          code: 'CRUSHING',
          active: true,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181599',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181594',
          code: 'BLACK EYE',
          active: true,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181595',
          code: 'BROKEN NOSE',
          active: true,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181596',
          code: 'BROKEN TEETH',
          active: true,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181598',
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181593',
          code: 'BITES',
          active: true,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181601',
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          id: '181604',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
      ],
    },
    '44915': {
      id: '44915',
      active: true,
      code: 'DESCRIBE THE TYPE OF SPRAY',
      label: 'DESCRIBE THE TYPE OF SPRAY',
      multipleAnswers: true,
      answers: [
        {
          id: '181632',
          code: 'C.N (CHLORACETOPHEONE)',
          active: true,
          label: 'C.N (CHLORACETOPHEONE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          id: '181633',
          code: 'C.S (ORTHO..NITRILE)',
          active: true,
          label: 'C.S (ORTHO..NITRILE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          id: '181635',
          code: 'O.C (MACE/PEPPER)',
          active: true,
          label: 'O.C (MACE/PEPPER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          id: '181636',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          id: '181634',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
      ],
    },
    '44924': {
      id: '44924',
      active: true,
      code: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          id: '181667',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44203',
        },
        {
          id: '181666',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44203',
        },
      ],
    },
    '44955': {
      id: '44955',
      active: true,
      code: 'WHO USED THE KNIFE OR BLADE',
      label: 'WHO USED THE KNIFE OR BLADE',
      multipleAnswers: false,
      answers: [
        {
          id: '181814',
          code: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'PRISONER WHO ATTEMPTED ESCAPE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44148',
        },
        {
          id: '181812',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44148',
        },
        {
          id: '181813',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44148',
        },
      ],
    },
    '44960': {
      id: '44960',
      active: true,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '181823',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44491',
        },
        {
          id: '181822',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44491',
        },
      ],
    },
    '44967': {
      id: '44967',
      active: true,
      code: 'WAS THE KEY USED',
      label: 'WAS THE KEY USED',
      multipleAnswers: false,
      answers: [
        {
          id: '181843',
          code: 'REAL',
          active: true,
          label: 'REAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44280',
        },
        {
          id: '181841',
          code: 'IMPROVISED',
          active: true,
          label: 'IMPROVISED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44280',
        },
        {
          id: '181842',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44280',
        },
      ],
    },
    '45011': {
      id: '45011',
      active: true,
      code: 'WAS THE PRISONER RESTRAINED AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'WAS THE PRISONER RESTRAINED AT THE POINT OF THE ATTEMPTED ESCAPE',
      multipleAnswers: false,
      answers: [
        {
          id: '181989',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44542',
        },
        {
          id: '181990',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44529',
        },
      ],
    },
    '45034': {
      id: '45034',
      active: true,
      code: 'TO WHOM WAS THE PRISONER HANDCUFFED',
      label: 'TO WHOM WAS THE PRISONER HANDCUFFED',
      multipleAnswers: false,
      answers: [
        {
          id: '182086',
          code: 'OFFICER',
          active: true,
          label: 'OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          id: '182085',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45141',
        },
      ],
    },
    '45041': {
      id: '45041',
      active: true,
      code: 'DID ANY STAFF REQUIRE MEDICAL TREATMENT FOR INJURY',
      label: 'DID ANY STAFF REQUIRE MEDICAL TREATMENT FOR INJURY',
      multipleAnswers: false,
      answers: [
        {
          id: '182144',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45060',
        },
        {
          id: '182145',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
      ],
    },
    '45044': {
      id: '45044',
      active: true,
      code: 'WAS A MINOR INJURY SUSTAINED BY A PRISONER',
      label: 'WAS A MINOR INJURY SUSTAINED BY A PRISONER',
      multipleAnswers: false,
      answers: [
        {
          id: '182160',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44708',
        },
        {
          id: '182161',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
      ],
    },
    '45060': {
      id: '45060',
      active: true,
      code: 'WHERE WERE THE INJURED STAFF TREATED',
      label: 'WHERE WERE THE INJURED STAFF TREATED',
      multipleAnswers: false,
      answers: [
        {
          id: '182223',
          code: 'PRISON HEALTH CARE CENTRE',
          active: true,
          label: 'PRISON HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
        {
          id: '182221',
          code: 'OUTSIDE HOSPITAL',
          active: true,
          label: 'OUTSIDE HOSPITAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
        {
          id: '182222',
          code: 'OWN GP',
          active: true,
          label: 'OWN GP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
      ],
    },
    '45061': {
      id: '45061',
      active: true,
      code: 'WHAT WERE THE CATEGORIES OF THE PRISONERS UNDER ESCORT',
      label: 'WHAT WERE THE CATEGORIES OF THE PRISONERS UNDER ESCORT',
      multipleAnswers: true,
      answers: [
        {
          id: '182226',
          code: 'CATEGORY A',
          active: true,
          label: 'CATEGORY A',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182227',
          code: 'CATEGORY B',
          active: true,
          label: 'CATEGORY B',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182228',
          code: 'CATEGORY C',
          active: true,
          label: 'CATEGORY C',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182229',
          code: 'CATEGORY D',
          active: true,
          label: 'CATEGORY D',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182225',
          code: 'CATEGORISED YO',
          active: true,
          label: 'CATEGORISED YO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182232',
          code: 'UNCATEGORISED YO',
          active: true,
          label: 'UNCATEGORISED YO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182224',
          code: 'CATEGORISED FEMALE',
          active: true,
          label: 'CATEGORISED FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182231',
          code: 'UNCATEGORISED FEMALE',
          active: true,
          label: 'UNCATEGORISED FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          id: '182230',
          code: 'UNCATEGORISED ADULT MALE',
          active: true,
          label: 'UNCATEGORISED ADULT MALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
      ],
    },
    '45094': {
      id: '45094',
      active: true,
      code: 'WHO WAS RESPONSIBLE FOR THE ESCORT',
      label: 'WHO WAS RESPONSIBLE FOR THE ESCORT',
      multipleAnswers: false,
      answers: [
        {
          id: '182324',
          code: 'PUBLIC SECTOR',
          active: true,
          label: 'PUBLIC SECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44139',
        },
        {
          id: '182323',
          code: 'PRIVATE SECTOR',
          active: true,
          label: 'PRIVATE SECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44794',
        },
      ],
    },
    '45099': {
      id: '45099',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED BY A PRISONER',
      label: 'WAS A SERIOUS INJURY SUSTAINED BY A PRISONER',
      multipleAnswers: false,
      answers: [
        {
          id: '182340',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44905',
        },
        {
          id: '182341',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
      ],
    },
    '45115': {
      id: '45115',
      active: true,
      code: 'NUMBER OF STAFF INJURED',
      label: 'NUMBER OF STAFF INJURED',
      multipleAnswers: true,
      answers: [
        {
          id: '182409',
          code: 'MALE (ENTER NUMBER)',
          active: true,
          label: 'MALE (ENTER NUMBER)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44782',
        },
        {
          id: '182408',
          code: 'FEMALE (ENTER NUMBER)',
          active: true,
          label: 'FEMALE (ENTER NUMBER)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44782',
        },
      ],
    },
    '45138': {
      id: '45138',
      active: true,
      code: 'WHO USED THE FIREARM',
      label: 'WHO USED THE FIREARM',
      multipleAnswers: false,
      answers: [
        {
          id: '182521',
          code: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'PRISONER WHO ATTEMPTED ESCAPE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44308',
        },
        {
          id: '182519',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44308',
        },
        {
          id: '182520',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44308',
        },
      ],
    },
    '45141': {
      id: '45141',
      active: true,
      code: 'WAS THE OTHER PRISONER',
      label: 'WAS THE OTHER PRISONER',
      multipleAnswers: false,
      answers: [
        {
          id: '182528',
          code: 'A CO-DEFENDANT',
          active: true,
          label: 'A CO-DEFENDANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          id: '182530',
          code: 'A RELATIVE',
          active: true,
          label: 'A RELATIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          id: '182529',
          code: 'A KNOWN ASSOCIATE',
          active: true,
          label: 'A KNOWN ASSOCIATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          id: '182531',
          code: 'AN E LIST PRISONER',
          active: true,
          label: 'AN E LIST PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          id: '182532',
          code: 'NONE OF THE ABOVE',
          active: true,
          label: 'NONE OF THE ABOVE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44437',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: true,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default ATTEMPTED_ESCAPE_FROM_ESCORT
