// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:26.284Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const ATTEMPTED_ESCAPE_FROM_ESCORT_1: IncidentTypeConfiguration = {
  incidentType: 'ATTEMPTED_ESCAPE_FROM_ESCORT_1',
  active: true,
  startingQuestionId: '44423',
  questions: {
    '44139': {
      code: '44139',
      active: true,
      question: 'FROM WHAT ESCORT TYPE DID THE ATTEMPTED ESCAPE OCCUR',
      label: 'From what escort type did the attempted escape occur?',
      multipleAnswers: false,
      answers: [
        {
          code: '178956',
          response: 'HOSPITAL OUTPATIENT',
          active: true,
          label: 'Hospital outpatient',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44168',
        },
        {
          code: '178955',
          response: 'HOSPITAL INPATIENT',
          active: true,
          label: 'Hospital inpatient',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44168',
        },
        {
          code: '178962',
          response: 'INTER PRISON TRANSFER',
          active: true,
          label: 'Inter prison transfer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178963',
          response: 'MAGISTRATES COURT',
          active: true,
          label: 'Magistrates court',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178958',
          response: 'CROWN COURT',
          active: true,
          label: 'Crown court',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178957',
          response: 'COUNTY COURT',
          active: true,
          label: 'County court',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178959',
          response: 'FUNERAL',
          active: true,
          label: 'Funeral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178965',
          response: 'WEDDING',
          active: true,
          label: 'Wedding',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178960',
          response: 'HOME VISIT',
          active: true,
          label: 'Home visit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178961',
          response: 'HOSP VISIT (DYING RELATIVE)',
          active: true,
          label: 'Hosp visit (dying relative)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '178964',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44496',
        },
      ],
    },
    '44148': {
      code: '44148',
      active: true,
      question: 'WHAT WAS THE SOURCE OF THE KNIFE OR BLADE',
      label: 'What was the source of the knife or blade?',
      multipleAnswers: false,
      answers: [
        {
          code: '178995',
          response: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'Secreted on the prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
        {
          code: '178993',
          response: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'Found in vehicle/area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
        {
          code: '178992',
          response: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'Brought by accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
        {
          code: '178994',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
      ],
    },
    '44157': {
      code: '44157',
      active: true,
      question: 'WERE ANY OTHER WEAPONS USED DURING THE ATTEMPTED ESCAPE',
      label: 'Were any other weapons used during the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '179017',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44638',
        },
        {
          code: '179018',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
      ],
    },
    '44168': {
      code: '44168',
      active: true,
      question: 'WAS THE ESCORT FOR CHILD BIRTH OR PRE/POST NATAL TREATMENT',
      label: 'Was the escort for child birth or pre/post natal treatment?',
      multipleAnswers: false,
      answers: [
        {
          code: '179057',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
        {
          code: '179056',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44496',
        },
      ],
    },
    '44180': {
      code: '44180',
      active: true,
      question: 'DESCRIBE THE DAMAGE',
      label: 'Describe the damage',
      multipleAnswers: false,
      answers: [
        {
          code: '179090',
          response: 'MINOR',
          active: true,
          label: 'Minor',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44881',
        },
        {
          code: '179091',
          response: 'SERIOUS',
          active: true,
          label: 'Serious',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44881',
        },
        {
          code: '179089',
          response: 'EXTENSIVE',
          active: true,
          label: 'Extensive',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44881',
        },
      ],
    },
    '44203': {
      code: '44203',
      active: true,
      question: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "Is the incident subject to a governor's adjudication?",
      multipleAnswers: false,
      answers: [
        {
          code: '179172',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44479',
        },
        {
          code: '179171',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44479',
        },
      ],
    },
    '44226': {
      code: '44226',
      active: true,
      question: 'HOW WAS THE RESTRAINT OVERCOME AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'How was the restraint overcome at the point of the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '179230',
          response: 'PRISONER USED KEY',
          active: true,
          label: 'Prisoner used key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44967',
        },
        {
          code: '179231',
          response: 'SLIPPED RESTRAINT',
          active: true,
          label: 'Slipped restraint',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44819',
        },
        {
          code: '179235',
          response: 'PICKED LOCK',
          active: true,
          label: 'Picked lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '179236',
          response: 'STAFF UNLOCKED UNDER THREAT',
          active: true,
          label: 'Staff unlocked under threat',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '179232',
          response: 'IMPROPER APPLICATION',
          active: true,
          label: 'Improper application',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '179234',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '179233',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44240': {
      code: '44240',
      active: true,
      question: 'HOW WAS THE ESCAPE PREVENTED',
      label: 'How was the escape prevented?',
      multipleAnswers: false,
      answers: [
        {
          code: '179291',
          response: 'PHYSICAL BARRIER',
          active: true,
          label: 'Physical barrier',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          code: '179293',
          response: 'PRISON STAFF INTERVENTION',
          active: true,
          label: 'Prison staff intervention',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          code: '179292',
          response: 'POLICE INTERVENTION',
          active: true,
          label: 'Police intervention',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          code: '179289',
          response: 'MEMBER OF PUBLIC',
          active: true,
          label: 'Member of public',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          code: '179294',
          response: 'PRISONER ABANDONED ATTEMPT',
          active: true,
          label: 'Prisoner abandoned attempt',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          code: '179295',
          response: 'PRISONER INJURED IN ATTEMPT',
          active: true,
          label: 'Prisoner injured in attempt',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44559',
        },
        {
          code: '179290',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44559',
        },
      ],
    },
    '44269': {
      code: '44269',
      active: true,
      question: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          code: '179372',
          response: 'FRACTURE',
          active: true,
          label: 'Fracture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179374',
          response: 'SCALD OR BURN',
          active: true,
          label: 'Scald or burn',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179375',
          response: 'STABBING',
          active: true,
          label: 'Stabbing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179369',
          response: 'CRUSHING',
          active: true,
          label: 'Crushing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179371',
          response: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'Extensive/multiple bruising',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179366',
          response: 'BLACK EYE',
          active: true,
          label: 'Black eye',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179367',
          response: 'BROKEN NOSE',
          active: true,
          label: 'Broken nose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179368',
          response: 'BROKEN TEETH',
          active: true,
          label: 'Broken teeth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179370',
          response: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'Cuts requiring sutures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179365',
          response: 'BITES',
          active: true,
          label: 'Bites',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179373',
          response: 'GUN SHOT WOUND',
          active: true,
          label: 'Gun shot wound',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
        {
          code: '179376',
          response: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'Temporary/permanent blindness',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
      ],
    },
    '44280': {
      code: '44280',
      active: true,
      question: 'HAS THE KEY BEEN RECOVERED',
      label: 'Has the key been recovered?',
      multipleAnswers: false,
      answers: [
        {
          code: '179396',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '179395',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44288': {
      code: '44288',
      active: true,
      question: 'WAS THE FIREARM',
      label: 'Was the firearm?',
      multipleAnswers: false,
      answers: [
        {
          code: '179414',
          response: 'REAL',
          active: true,
          label: 'Real',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44701',
        },
        {
          code: '179415',
          response: 'REPLICA',
          active: true,
          label: 'Replica',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44701',
        },
        {
          code: '179413',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44701',
        },
      ],
    },
    '44294': {
      code: '44294',
      active: true,
      question: 'WHAT WAS THE SOURCE OF THE SPRAY',
      label: 'What was the source of the spray?',
      multipleAnswers: false,
      answers: [
        {
          code: '179429',
          response: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'Secreted on the prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
        {
          code: '179427',
          response: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'Found in vehicle/area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
        {
          code: '179426',
          response: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'Brought by accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
        {
          code: '179428',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
      ],
    },
    '44302': {
      code: '44302',
      active: true,
      question: 'WAS DOUBLE CUFFING EMPLOYED',
      label: 'Was double cuffing employed?',
      multipleAnswers: false,
      answers: [
        {
          code: '179474',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45034',
        },
        {
          code: '179473',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45034',
        },
      ],
    },
    '44306': {
      code: '44306',
      active: true,
      question: 'WERE ANY INJURIES SUSTAINED BY PRISONERS',
      label: 'Were any injuries sustained by prisoners?',
      multipleAnswers: false,
      answers: [
        {
          code: '179516',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45099',
        },
        {
          code: '179517',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
      ],
    },
    '44307': {
      code: '44307',
      active: true,
      question: 'WHAT TYPE OF VEHICLE WAS IT',
      label: 'What type of vehicle was it?',
      multipleAnswers: false,
      answers: [
        {
          code: '179519',
          response: 'COACH',
          active: true,
          label: 'Coach',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '179520',
          response: 'MINIBUS',
          active: true,
          label: 'Minibus',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '179523',
          response: 'TAXI',
          active: true,
          label: 'Taxi',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '179518',
          response: 'CELLULAR VEHICLE',
          active: true,
          label: 'Cellular vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '179522',
          response: 'SECURE TRANSIT',
          active: true,
          label: 'Secure transit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '179521',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44886',
        },
      ],
    },
    '44308': {
      code: '44308',
      active: true,
      question: 'WHAT WAS THE SOURCE OF THE FIREARM',
      label: 'What was the source of the firearm?',
      multipleAnswers: false,
      answers: [
        {
          code: '179527',
          response: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'Secreted on the prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
        {
          code: '179525',
          response: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'Found in vehicle/area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
        {
          code: '179524',
          response: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'Brought by accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
        {
          code: '179526',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
      ],
    },
    '44312': {
      code: '44312',
      active: true,
      question: 'WAS A FIREARM USED DURING THE ATTEMPTED ESCAPE',
      label: 'Was a firearm used during the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '179534',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44288',
        },
        {
          code: '179535',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44836',
        },
      ],
    },
    '44421': {
      code: '44421',
      active: true,
      question: 'WERE MINOR INJURIES SUSTAINED BY STAFF',
      label: 'Were minor injuries sustained by staff?',
      multipleAnswers: false,
      answers: [
        {
          code: '179899',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44626',
        },
        {
          code: '179900',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
      ],
    },
    '44423': {
      code: '44423',
      active: true,
      question: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '179903',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44900',
        },
        {
          code: '179904',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44924',
        },
      ],
    },
    '44429': {
      code: '44429',
      active: true,
      question: 'WAS THE PRISONER WHO ATTEMPTED TO ESCAPE ON THE ESCAPE LIST',
      label: 'Was the prisoner who attempted to escape on the escape list?',
      multipleAnswers: false,
      answers: [
        {
          code: '179917',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45011',
        },
        {
          code: '179916',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45011',
        },
      ],
    },
    '44437': {
      code: '44437',
      active: true,
      question: 'WAS THE RESTRAINT OVERCOME AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'Was the restraint overcome at the point of the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '179938',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44226',
        },
        {
          code: '179939',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44457': {
      code: '44457',
      active: true,
      question: 'WERE THE ROUNDS DISCHARGED',
      label: 'Were the rounds discharged?',
      multipleAnswers: false,
      answers: [
        {
          code: '180006',
          response: 'LIVE',
          active: true,
          label: 'Live',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
        {
          code: '180005',
          response: 'BLANK',
          active: true,
          label: 'Blank',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
        {
          code: '180007',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
      ],
    },
    '44479': {
      code: '44479',
      active: true,
      question: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: '180137',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44960',
        },
        {
          code: '180136',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44960',
        },
      ],
    },
    '44481': {
      code: '44481',
      active: true,
      question: 'DID ANY PRISONER REQUIRE MEDICAL TREATMENT FOR INJURIES',
      label: 'Did any prisoner require medical treatment for injuries?',
      multipleAnswers: false,
      answers: [
        {
          code: '180151',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44535',
        },
        {
          code: '180152',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
      ],
    },
    '44491': {
      code: '44491',
      active: true,
      question: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: '180183',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45094',
        },
        {
          code: '180182',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45094',
        },
      ],
    },
    '44496': {
      code: '44496',
      active: true,
      question: 'WHERE DID THE ATTEMPTED ESCAPE TAKE PLACE',
      label: 'Where did the attempted escape take place?',
      multipleAnswers: false,
      answers: [
        {
          code: '180197',
          response: 'VEHICLE EN ROUTE TO VENUE',
          active: true,
          label: 'Vehicle en route to venue',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          code: '180196',
          response: 'VEHICLE EN ROUTE FROM VENUE',
          active: true,
          label: 'Vehicle en route from venue',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          code: '180195',
          response: 'LEAVING VEHICLE (DEBUSSING)',
          active: true,
          label: 'Leaving vehicle (debussing)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          code: '180194',
          response: 'ENTERING VEHICLE (EMBUSSING)',
          active: true,
          label: 'Entering vehicle (embussing)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44307',
        },
        {
          code: '180206',
          response: 'UNSCHEDULED STOP',
          active: true,
          label: 'Unscheduled stop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180198',
          response: 'CELL AT COURT',
          active: true,
          label: 'Cell at court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180199',
          response: 'COURT CELLS AREA',
          active: true,
          label: 'Court cells area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180201',
          response: 'COURT VISITS AREA',
          active: true,
          label: 'Court visits area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180200',
          response: 'COURT DOCK',
          active: true,
          label: 'Court dock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180204',
          response: 'HOSPITAL WARD/ROOM',
          active: true,
          label: 'Hospital ward/room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180202',
          response: 'HOSPITAL TREATMENT ROOM',
          active: true,
          label: 'Hospital treatment room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180203',
          response: 'HOSPITAL WAITING AREA',
          active: true,
          label: 'Hospital waiting area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44886',
        },
        {
          code: '180205',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44886',
        },
      ],
    },
    '44529': {
      code: '44529',
      active: true,
      question: 'WHY WAS A RESTRAINT NOT APPLIED AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'Why was a restraint not applied at the point of the attempted escape?',
      multipleAnswers: true,
      answers: [
        {
          code: '180340',
          response: 'GOVERNORS INSTRUCTION',
          active: true,
          label: 'Governors instruction',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180347',
          response: 'PREVENTED BY DISABILITY',
          active: true,
          label: 'Prevented by disability',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180348',
          response: 'PREVENTED BY INJURY',
          active: true,
          label: 'Prevented by injury',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180344',
          response: 'MEDICAL TREATMENT/REQUEST',
          active: true,
          label: 'Medical treatment/request',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180342',
          response: 'IN COURT ROOM',
          active: true,
          label: 'In court room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180343',
          response: 'LOCATED IN SECURE AREA',
          active: true,
          label: 'Located in secure area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180341',
          response: 'IN CELL OF CELLULAR VEHICLE',
          active: true,
          label: 'In cell of cellular vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180349',
          response: 'TRANSFER TO MENTAL HOSPITAL',
          active: true,
          label: 'Transfer to mental hospital',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180338',
          response: 'DURING MARRIAGE CEREMONY',
          active: true,
          label: 'During marriage ceremony',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180345',
          response: 'NONE AVAILABLE',
          active: true,
          label: 'None available',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180339',
          response: 'FAILURE TO USE',
          active: true,
          label: 'Failure to use',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '180346',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44535': {
      code: '44535',
      active: true,
      question: 'WHERE WERE THE INJURED PRISONERS TREATED',
      label: 'Where were the injured prisoners treated?',
      multipleAnswers: false,
      answers: [
        {
          code: '180392',
          response: 'PRISON HEALTH CARE CENTRE',
          active: true,
          label: 'Prison health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
        {
          code: '180391',
          response: 'OUTSIDE HOSPITAL',
          active: true,
          label: 'Outside hospital',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44240',
        },
      ],
    },
    '44542': {
      code: '44542',
      active: true,
      question: 'WHAT RESTRAINT WAS BEING USED AT THE POINT OF ATTEMPTED ESCAPE',
      label: 'What restraint was being used at the point of attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '180413',
          response: 'HANDCUFFS',
          active: true,
          label: 'Handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44302',
        },
        {
          code: '180415',
          response: 'ESCORT CHAIN',
          active: true,
          label: 'Escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          code: '180414',
          response: 'CLOSETING CHAIN',
          active: true,
          label: 'Closeting chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          code: '180416',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44437',
        },
      ],
    },
    '44559': {
      code: '44559',
      active: true,
      question: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'Was damage caused to prison property?',
      multipleAnswers: false,
      answers: [
        {
          code: '180461',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44180',
        },
        {
          code: '180462',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44566': {
      code: '44566',
      active: true,
      question: 'WAS A KNIFE OR BLADE USED DURING THE ATTEMPTED ESCAPE',
      label: 'Was a knife or blade used during the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '180475',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44888',
        },
        {
          code: '180476',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44157',
        },
      ],
    },
    '44599': {
      code: '44599',
      active: true,
      question: 'WAS OUTSIDE ASSISTANCE INVOLVED IN THE ATTEMPTED ESCAPE',
      label: 'Was outside assistance involved in the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '180600',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44312',
        },
        {
          code: '180599',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44312',
        },
      ],
    },
    '44604': {
      code: '44604',
      active: true,
      question: 'WHO USED THE SPRAY',
      label: 'Who used the spray?',
      multipleAnswers: false,
      answers: [
        {
          code: '180612',
          response: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'Prisoner who attempted escape',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44294',
        },
        {
          code: '180610',
          response: 'OTHER PRISONER',
          active: true,
          label: 'Other prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44294',
        },
        {
          code: '180611',
          response: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'Outside accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44294',
        },
      ],
    },
    '44626': {
      code: '44626',
      active: true,
      question: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          code: '180668',
          response: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'Grazes, scratches or abrasions',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          code: '180669',
          response: 'MINOR BRUISES',
          active: true,
          label: 'Minor bruises',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          code: '180672',
          response: 'SWELLINGS',
          active: true,
          label: 'Swellings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          code: '180671',
          response: 'SUPERFICIAL CUTS',
          active: true,
          label: 'Superficial cuts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45041',
        },
        {
          code: '180670',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45041',
        },
      ],
    },
    '44627': {
      code: '44627',
      active: true,
      question: 'WHAT WAS THE SOURCE OF THE WEAPONS USED',
      label: 'What was the source of the weapons used?',
      multipleAnswers: false,
      answers: [
        {
          code: '180676',
          response: 'SECRETED ON PRISONER',
          active: true,
          label: 'Secreted on prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
        {
          code: '180674',
          response: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'Found in vehicle/area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
        {
          code: '180673',
          response: 'BROUGHT BY OUTSIDE ACCOMPLICE',
          active: true,
          label: 'Brought by outside accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
        {
          code: '180675',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44647',
        },
      ],
    },
    '44638': {
      code: '44638',
      active: true,
      question: 'WHAT OTHER WEAPONS WERE USED',
      label: 'What other weapons were used?',
      multipleAnswers: true,
      answers: [
        {
          code: '180721',
          response: 'OTHER SHARP INSTRUMENT',
          active: true,
          label: 'Other sharp instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180715',
          response: 'BLUNT INSTRUMENT',
          active: true,
          label: 'Blunt instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180719',
          response: 'LIGATURE',
          active: true,
          label: 'Ligature',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180716',
          response: 'DANGEROUS LIQUID',
          active: true,
          label: 'Dangerous liquid',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180717',
          response: 'EXCRETA/URINE',
          active: true,
          label: 'Excreta/urine',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180722',
          response: 'SPITTING',
          active: true,
          label: 'Spitting',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180718',
          response: 'FOOD',
          active: true,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180724',
          response: 'THROWN FURNITURE',
          active: true,
          label: 'Thrown furniture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180723',
          response: 'THROWN EQUIPMENT',
          active: true,
          label: 'Thrown equipment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44739',
        },
        {
          code: '180720',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44739',
        },
      ],
    },
    '44647': {
      code: '44647',
      active: true,
      question: 'WERE ANY INJURIES SUSTAINED BY STAFF',
      label: 'Were any injuries sustained by staff?',
      multipleAnswers: false,
      answers: [
        {
          code: '180741',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45115',
        },
        {
          code: '180742',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
      ],
    },
    '44701': {
      code: '44701',
      active: true,
      question: 'WAS THE FIREARM DISCHARGED',
      label: 'Was the firearm discharged?',
      multipleAnswers: false,
      answers: [
        {
          code: '180955',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44457',
        },
        {
          code: '180956',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45138',
        },
      ],
    },
    '44708': {
      code: '44708',
      active: true,
      question: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          code: '180973',
          response: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'Grazes, scratches or abrasions',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          code: '180974',
          response: 'MINOR BRUISES',
          active: true,
          label: 'Minor bruises',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          code: '180977',
          response: 'SWELLINGS',
          active: true,
          label: 'Swellings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          code: '180976',
          response: 'SUPERFICIAL CUTS',
          active: true,
          label: 'Superficial cuts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
        {
          code: '180975',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44481',
        },
      ],
    },
    '44739': {
      code: '44739',
      active: true,
      question: 'WHO USED THE OTHER WEAPONS',
      label: 'Who used the other weapons?',
      multipleAnswers: false,
      answers: [
        {
          code: '181079',
          response: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'Prisoner who attempted escape',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44627',
        },
        {
          code: '181077',
          response: 'OTHER PRISONER',
          active: true,
          label: 'Other prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44627',
        },
        {
          code: '181078',
          response: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'Outside accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44627',
        },
      ],
    },
    '44771': {
      code: '44771',
      active: true,
      question: 'NUMBER OF PRISONERS ON ESCORT',
      label: 'Number of prisoners on escort',
      multipleAnswers: true,
      answers: [
        {
          code: '181161',
          response: 'MALE',
          active: true,
          label: 'Male',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45061',
        },
        {
          code: '181160',
          response: 'FEMALE',
          active: true,
          label: 'Female',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45061',
        },
      ],
    },
    '44782': {
      code: '44782',
      active: true,
      question: 'WAS A SERIOUS INJURY SUSTAINED BY STAFF',
      label: 'Was a serious injury sustained by staff?',
      multipleAnswers: false,
      answers: [
        {
          code: '181182',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44269',
        },
        {
          code: '181183',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44421',
        },
      ],
    },
    '44794': {
      code: '44794',
      active: true,
      question: 'PRIOR TO PRIVATE SECTOR INVOLVEMENT WOULD THE ESCORT HAVE BEEN',
      label: 'Prior to private sector involvement would the escort have been',
      multipleAnswers: false,
      answers: [
        {
          code: '181244',
          response: 'PRISON SERVICE',
          active: true,
          label: 'Prison service',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44139',
        },
        {
          code: '181243',
          response: 'POLICE',
          active: true,
          label: 'Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44139',
        },
      ],
    },
    '44819': {
      code: '44819',
      active: true,
      question: 'WERE INSERTS USED',
      label: 'Were inserts used?',
      multipleAnswers: false,
      answers: [
        {
          code: '181301',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
        {
          code: '181300',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44599',
        },
      ],
    },
    '44836': {
      code: '44836',
      active: true,
      question: 'WAS A CHEMICAL INCAPACITANT SPRAY USED DURING THE ATTEMPTED ESCAPE',
      label: 'Was a chemical incapacitant spray used during the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '181337',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44915',
        },
        {
          code: '181338',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44566',
        },
      ],
    },
    '44881': {
      code: '44881',
      active: true,
      question: 'ESTIMATED COST OF DAMAGE',
      label: 'Estimated cost of damage',
      multipleAnswers: false,
      answers: [
        {
          code: '181519',
          response: 'ENTER AMOUNT IN POUND STERLING',
          active: true,
          label: 'Enter amount in pound sterling',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44886': {
      code: '44886',
      active: true,
      question: 'NUMBER OF STAFF ON ESCORT',
      label: 'Number of staff on escort',
      multipleAnswers: true,
      answers: [
        {
          code: '181537',
          response: 'MALE (ENTER NUMBER)',
          active: true,
          label: 'Male (enter number)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44771',
        },
        {
          code: '181536',
          response: 'FEMALE (ENTER NUMBER)',
          active: true,
          label: 'Female (enter number)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44771',
        },
      ],
    },
    '44888': {
      code: '44888',
      active: true,
      question: 'WAS THE KNIFE OR BLADE USED PURPOSE MADE OR IMPROVISED',
      label: 'Was the knife or blade used purpose made or improvised?',
      multipleAnswers: false,
      answers: [
        {
          code: '181549',
          response: 'PURPOSE MADE',
          active: true,
          label: 'Purpose made',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44955',
        },
        {
          code: '181547',
          response: 'IMPROVISED',
          active: true,
          label: 'Improvised',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44955',
        },
        {
          code: '181548',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44955',
        },
      ],
    },
    '44900': {
      code: '44900',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'Is the incident the subject of a police investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '181581',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44924',
        },
        {
          code: '181580',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44924',
        },
      ],
    },
    '44905': {
      code: '44905',
      active: true,
      question: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          code: '181600',
          response: 'FRACTURE',
          active: true,
          label: 'Fracture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181602',
          response: 'SCALD OR BURN',
          active: true,
          label: 'Scald or burn',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181603',
          response: 'STABBING',
          active: true,
          label: 'Stabbing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181597',
          response: 'CRUSHING',
          active: true,
          label: 'Crushing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181599',
          response: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'Extensive/multiple bruising',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181594',
          response: 'BLACK EYE',
          active: true,
          label: 'Black eye',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181595',
          response: 'BROKEN NOSE',
          active: true,
          label: 'Broken nose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181596',
          response: 'BROKEN TEETH',
          active: true,
          label: 'Broken teeth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181598',
          response: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'Cuts requiring sutures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181593',
          response: 'BITES',
          active: true,
          label: 'Bites',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181601',
          response: 'GUN SHOT WOUND',
          active: true,
          label: 'Gun shot wound',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
        {
          code: '181604',
          response: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'Temporary/permanent blindness',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
      ],
    },
    '44915': {
      code: '44915',
      active: true,
      question: 'DESCRIBE THE TYPE OF SPRAY',
      label: 'Describe the type of spray',
      multipleAnswers: true,
      answers: [
        {
          code: '181632',
          response: 'C.N (CHLORACETOPHEONE)',
          active: true,
          label: 'C.n (chloracetopheone)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          code: '181633',
          response: 'C.S (ORTHO..NITRILE)',
          active: true,
          label: 'C.s (ortho..nitrile)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          code: '181635',
          response: 'O.C (MACE/PEPPER)',
          active: true,
          label: 'O.c (mace/pepper)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          code: '181636',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44604',
        },
        {
          code: '181634',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44604',
        },
      ],
    },
    '44924': {
      code: '44924',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'Is the incident the subject of an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '181667',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44203',
        },
        {
          code: '181666',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44203',
        },
      ],
    },
    '44955': {
      code: '44955',
      active: true,
      question: 'WHO USED THE KNIFE OR BLADE',
      label: 'Who used the knife or blade?',
      multipleAnswers: false,
      answers: [
        {
          code: '181814',
          response: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'Prisoner who attempted escape',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44148',
        },
        {
          code: '181812',
          response: 'OTHER PRISONER',
          active: true,
          label: 'Other prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44148',
        },
        {
          code: '181813',
          response: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'Outside accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44148',
        },
      ],
    },
    '44960': {
      code: '44960',
      active: true,
      question: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '181823',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44491',
        },
        {
          code: '181822',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44491',
        },
      ],
    },
    '44967': {
      code: '44967',
      active: true,
      question: 'WAS THE KEY USED',
      label: 'Was the key used?',
      multipleAnswers: false,
      answers: [
        {
          code: '181843',
          response: 'REAL',
          active: true,
          label: 'Real',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44280',
        },
        {
          code: '181841',
          response: 'IMPROVISED',
          active: true,
          label: 'Improvised',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44280',
        },
        {
          code: '181842',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44280',
        },
      ],
    },
    '45011': {
      code: '45011',
      active: true,
      question: 'WAS THE PRISONER RESTRAINED AT THE POINT OF THE ATTEMPTED ESCAPE',
      label: 'Was the prisoner restrained at the point of the attempted escape?',
      multipleAnswers: false,
      answers: [
        {
          code: '181989',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44542',
        },
        {
          code: '181990',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44529',
        },
      ],
    },
    '45034': {
      code: '45034',
      active: true,
      question: 'TO WHOM WAS THE PRISONER HANDCUFFED',
      label: 'To whom was the prisoner handcuffed',
      multipleAnswers: false,
      answers: [
        {
          code: '182086',
          response: 'OFFICER',
          active: true,
          label: 'Officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          code: '182085',
          response: 'OTHER PRISONER',
          active: true,
          label: 'Other prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45141',
        },
      ],
    },
    '45041': {
      code: '45041',
      active: true,
      question: 'DID ANY STAFF REQUIRE MEDICAL TREATMENT FOR INJURY',
      label: 'Did any staff require medical treatment for injury?',
      multipleAnswers: false,
      answers: [
        {
          code: '182144',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45060',
        },
        {
          code: '182145',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
      ],
    },
    '45044': {
      code: '45044',
      active: true,
      question: 'WAS A MINOR INJURY SUSTAINED BY A PRISONER',
      label: 'Was a minor injury sustained by a prisoner?',
      multipleAnswers: false,
      answers: [
        {
          code: '182160',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44708',
        },
        {
          code: '182161',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44481',
        },
      ],
    },
    '45060': {
      code: '45060',
      active: true,
      question: 'WHERE WERE THE INJURED STAFF TREATED',
      label: 'Where were the injured staff treated?',
      multipleAnswers: false,
      answers: [
        {
          code: '182223',
          response: 'PRISON HEALTH CARE CENTRE',
          active: true,
          label: 'Prison health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
        {
          code: '182221',
          response: 'OUTSIDE HOSPITAL',
          active: true,
          label: 'Outside hospital',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
        {
          code: '182222',
          response: 'OWN GP',
          active: true,
          label: 'Own GP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44306',
        },
      ],
    },
    '45061': {
      code: '45061',
      active: true,
      question: 'WHAT WERE THE CATEGORIES OF THE PRISONERS UNDER ESCORT',
      label: 'What were the categories of the prisoners under escort?',
      multipleAnswers: true,
      answers: [
        {
          code: '182226',
          response: 'CATEGORY A',
          active: true,
          label: 'Category A',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182227',
          response: 'CATEGORY B',
          active: true,
          label: 'Category B',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182228',
          response: 'CATEGORY C',
          active: true,
          label: 'Category C',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182229',
          response: 'CATEGORY D',
          active: true,
          label: 'Category D',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182225',
          response: 'CATEGORISED YO',
          active: true,
          label: 'Categorised YO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182232',
          response: 'UNCATEGORISED YO',
          active: true,
          label: 'Uncategorised YO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182224',
          response: 'CATEGORISED FEMALE',
          active: true,
          label: 'Categorised female',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182231',
          response: 'UNCATEGORISED FEMALE',
          active: true,
          label: 'Uncategorised female',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
        {
          code: '182230',
          response: 'UNCATEGORISED ADULT MALE',
          active: true,
          label: 'Uncategorised adult male',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44429',
        },
      ],
    },
    '45094': {
      code: '45094',
      active: true,
      question: 'WHO WAS RESPONSIBLE FOR THE ESCORT',
      label: 'Who was responsible for the escort?',
      multipleAnswers: false,
      answers: [
        {
          code: '182324',
          response: 'PUBLIC SECTOR',
          active: true,
          label: 'Public sector',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44139',
        },
        {
          code: '182323',
          response: 'PRIVATE SECTOR',
          active: true,
          label: 'Private sector',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44794',
        },
      ],
    },
    '45099': {
      code: '45099',
      active: true,
      question: 'WAS A SERIOUS INJURY SUSTAINED BY A PRISONER',
      label: 'Was a serious injury sustained by a prisoner?',
      multipleAnswers: false,
      answers: [
        {
          code: '182340',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44905',
        },
        {
          code: '182341',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45044',
        },
      ],
    },
    '45115': {
      code: '45115',
      active: true,
      question: 'NUMBER OF STAFF INJURED',
      label: 'Number of staff injured',
      multipleAnswers: true,
      answers: [
        {
          code: '182409',
          response: 'MALE (ENTER NUMBER)',
          active: true,
          label: 'Male (enter number)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44782',
        },
        {
          code: '182408',
          response: 'FEMALE (ENTER NUMBER)',
          active: true,
          label: 'Female (enter number)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44782',
        },
      ],
    },
    '45138': {
      code: '45138',
      active: true,
      question: 'WHO USED THE FIREARM',
      label: 'Who used the firearm?',
      multipleAnswers: false,
      answers: [
        {
          code: '182521',
          response: 'PRISONER WHO ATTEMPTED ESCAPE',
          active: true,
          label: 'Prisoner who attempted escape',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44308',
        },
        {
          code: '182519',
          response: 'OTHER PRISONER',
          active: true,
          label: 'Other prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44308',
        },
        {
          code: '182520',
          response: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'Outside accomplice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44308',
        },
      ],
    },
    '45141': {
      code: '45141',
      active: true,
      question: 'WAS THE OTHER PRISONER',
      label: 'Was the other prisoner?',
      multipleAnswers: false,
      answers: [
        {
          code: '182528',
          response: 'A CO-DEFENDANT',
          active: true,
          label: 'A co-defendant',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          code: '182530',
          response: 'A RELATIVE',
          active: true,
          label: 'A relative',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          code: '182529',
          response: 'A KNOWN ASSOCIATE',
          active: true,
          label: 'A known associate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          code: '182531',
          response: 'AN E LIST PRISONER',
          active: true,
          label: 'An e list prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44437',
        },
        {
          code: '182532',
          response: 'NONE OF THE ABOVE',
          active: true,
          label: 'None of the above',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44437',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: true,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default ATTEMPTED_ESCAPE_FROM_ESCORT_1
