// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-20T16:52:15.825Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const BREACH_OF_SECURITY: IncidentTypeConfiguration = {
  incidentType: 'BREACH_OF_SECURITY',
  active: true,
  startingQuestionId: '44253',
  questions: {
    '44124': {
      id: '44124',
      active: true,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44136',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44249',
        },
      ],
    },
    '44136': {
      id: '44136',
      active: true,
      code: 'WHAT WAS DAMAGED',
      label: 'WHAT WAS DAMAGED',
      multipleAnswers: true,
      answers: [
        {
          code: 'FURNITURE',
          active: true,
          label: 'FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45016',
        },
        {
          code: 'FITTINGS',
          active: true,
          label: 'FITTINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45016',
        },
        {
          code: 'MACHINERY',
          active: true,
          label: 'MACHINERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45016',
        },
        {
          code: 'EQUIPMENT',
          active: true,
          label: 'EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45016',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45016',
        },
      ],
    },
    '44249': {
      id: '44249',
      active: true,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45137',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44906',
        },
      ],
    },
    '44253': {
      id: '44253',
      active: true,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44286',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44364',
        },
      ],
    },
    '44286': {
      id: '44286',
      active: true,
      code: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44364',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44364',
        },
      ],
    },
    '44301': {
      id: '44301',
      active: true,
      code: 'DESCRIBE THE ILLICIT ITEM FOUND',
      label: 'DESCRIBE THE ILLICIT ITEM FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'WEAPONS',
          active: true,
          label: 'WEAPONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'ALCOHOL',
          active: true,
          label: 'ALCOHOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'CIGARETTES',
          active: true,
          label: 'CIGARETTES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'TOBACCO',
          active: true,
          label: 'TOBACCO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'CASH',
          active: true,
          label: 'CASH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'ESCAPE EQUIPMENT',
          active: true,
          label: 'ESCAPE EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'TOOLS',
          active: true,
          label: 'TOOLS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44333': {
      id: '44333',
      active: true,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44124',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44124',
        },
      ],
    },
    '44364': {
      id: '44364',
      active: true,
      code: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44786',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44786',
        },
      ],
    },
    '44389': {
      id: '44389',
      active: true,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44883',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44883',
        },
      ],
    },
    '44500': {
      id: '44500',
      active: true,
      code: 'WAS THE DEMONSTRATION KNOWN ABOUT IN ADVANCE',
      label: 'WAS THE DEMONSTRATION KNOWN ABOUT IN ADVANCE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44606',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44658',
        },
      ],
    },
    '44514': {
      id: '44514',
      active: true,
      code: 'DID UNAUTHORISED PERSONS ENTER THE PRISON',
      label: 'DID UNAUTHORISED PERSONS ENTER THE PRISON',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44543',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44883',
        },
      ],
    },
    '44543': {
      id: '44543',
      active: true,
      code: 'WERE THESE PERSONS APPREHENDED',
      label: 'WERE THESE PERSONS APPREHENDED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44855',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44883',
        },
      ],
    },
    '44561': {
      id: '44561',
      active: true,
      code: 'WAS A KNOWN ORGANISATION INVOLVED',
      label: 'WAS A KNOWN ORGANISATION INVOLVED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44500',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44500',
        },
      ],
    },
    '44606': {
      id: '44606',
      active: true,
      code: 'HOW WAS IT KNOWN ABOUT',
      label: 'HOW WAS IT KNOWN ABOUT',
      multipleAnswers: false,
      answers: [
        {
          code: 'INFORMATION FROM PRISONERS',
          active: true,
          label: 'INFORMATION FROM PRISONERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44658',
        },
        {
          code: 'INFORMATION FROM POLICE',
          active: true,
          label: 'INFORMATION FROM POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44658',
        },
        {
          code: 'INFORMATION FROM HQ/AM',
          active: true,
          label: 'INFORMATION FROM HQ/AM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44658',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44658',
        },
      ],
    },
    '44616': {
      id: '44616',
      active: true,
      code: 'ESTIMATED COST OF DAMAGE',
      label: 'ESTIMATED COST OF DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          code: 'ENTER AMOUNT IN POUND STERLING',
          active: true,
          label: 'ENTER AMOUNT IN POUND STERLING',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44249',
        },
      ],
    },
    '44658': {
      id: '44658',
      active: true,
      code: 'WHAT WAS THE REASON FOR THE DEMONSTRATION',
      label: 'WHAT WAS THE REASON FOR THE DEMONSTRATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'PARTICULAR PRISONER',
          active: true,
          label: 'PARTICULAR PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44686',
        },
        {
          code: 'LOCAL ISSUE',
          active: true,
          label: 'LOCAL ISSUE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44686',
        },
        {
          code: 'GENERAL ISSUE',
          active: true,
          label: 'GENERAL ISSUE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44686',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44686',
        },
      ],
    },
    '44686': {
      id: '44686',
      active: true,
      code: 'DID THE POLICE ATTEND',
      label: 'DID THE POLICE ATTEND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44728',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44124',
        },
      ],
    },
    '44709': {
      id: '44709',
      active: true,
      code: 'WAS THE DEMONSTRATION ORGANISED OR SPONTANEOUS',
      label: 'WAS THE DEMONSTRATION ORGANISED OR SPONTANEOUS',
      multipleAnswers: false,
      answers: [
        {
          code: 'ORGANISED',
          active: true,
          label: 'ORGANISED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44561',
        },
        {
          code: 'SPONTANEOUS',
          active: true,
          label: 'SPONTANEOUS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44561',
        },
      ],
    },
    '44728': {
      id: '44728',
      active: true,
      code: 'WERE ANY ARRESTS MADE',
      label: 'WERE ANY ARRESTS MADE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44333',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44333',
        },
      ],
    },
    '44786': {
      id: '44786',
      active: true,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45095',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45095',
        },
      ],
    },
    '44855': {
      id: '44855',
      active: true,
      code: 'WERE THESE PERSONS ARRESTED BY THE POLICE',
      label: 'WERE THESE PERSONS ARRESTED BY THE POLICE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44389',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44883',
        },
      ],
    },
    '44864': {
      id: '44864',
      active: true,
      code: 'WAS THE SECURE PERIMETER BREACHED',
      label: 'WAS THE SECURE PERIMETER BREACHED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44918',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44514',
        },
      ],
    },
    '44883': {
      id: '44883',
      active: true,
      code: 'WAS THE INCIDENT A DEMONSTRATION',
      label: 'WAS THE INCIDENT A DEMONSTRATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44709',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44124',
        },
      ],
    },
    '44906': {
      id: '44906',
      active: true,
      code: 'WERE ANY ILLICIT ITEMS FOUND',
      label: 'WERE ANY ILLICIT ITEMS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44301',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44918': {
      id: '44918',
      active: true,
      code: 'DESCRIBE HOW THE SECURE PERIMETER WAS BREACHED',
      label: 'DESCRIBE HOW THE SECURE PERIMETER WAS BREACHED',
      multipleAnswers: false,
      answers: [
        {
          code: 'THROWN OVER',
          active: true,
          label: 'THROWN OVER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44514',
        },
        {
          code: 'CLIMBED OVER',
          active: true,
          label: 'CLIMBED OVER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44514',
        },
        {
          code: 'CUT THROUGH',
          active: true,
          label: 'CUT THROUGH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44514',
        },
        {
          code: 'VEHICLE RAMMED',
          active: true,
          label: 'VEHICLE RAMMED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44514',
        },
        {
          code: 'EXPLOSIVES',
          active: true,
          label: 'EXPLOSIVES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44514',
        },
        {
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44514',
        },
      ],
    },
    '44946': {
      id: '44946',
      active: true,
      code: 'WHAT WAS THE INCIDENT LOCATION',
      label: 'WHAT WAS THE INCIDENT LOCATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'INSIDE PRISON',
          active: true,
          label: 'INSIDE PRISON',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44864',
        },
        {
          code: 'OUTSIDE PRISON',
          active: true,
          label: 'OUTSIDE PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44864',
        },
      ],
    },
    '45016': {
      id: '45016',
      active: true,
      code: 'DESCRIBE THE DAMAGE',
      label: 'DESCRIBE THE DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          code: 'MINOR',
          active: true,
          label: 'MINOR',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44616',
        },
        {
          code: 'SERIOUS',
          active: true,
          label: 'SERIOUS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44616',
        },
        {
          code: 'EXTENSIVE',
          active: true,
          label: 'EXTENSIVE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44616',
        },
      ],
    },
    '45095': {
      id: '45095',
      active: true,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44946',
        },
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44946',
        },
      ],
    },
    '45137': {
      id: '45137',
      active: true,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      multipleAnswers: true,
      answers: [
        {
          code: 'STAFF',
          active: true,
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44906',
        },
        {
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44906',
        },
        {
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44906',
        },
        {
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44906',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44906',
        },
      ],
    },
  },
} as const

export default BREACH_OF_SECURITY
