// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:29.852Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const CONCERTED_INDISCIPLINE_1: IncidentTypeConfiguration = {
  incidentType: 'CONCERTED_INDISCIPLINE_1',
  active: false,
  startingQuestionId: '44750',
  questions: {
    '44122': {
      code: '44122',
      active: false,
      question: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      label: 'Was control and restraints employed?',
      multipleAnswers: false,
      answers: [
        {
          id: '178890',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44979',
        },
        {
          id: '178889',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44979',
        },
      ],
    },
    '44140': {
      code: '44140',
      active: false,
      question: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "Is the incident subject to a governor's adjudication?",
      multipleAnswers: false,
      answers: [
        {
          id: '178967',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44256',
        },
        {
          id: '178966',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44256',
        },
      ],
    },
    '44156': {
      code: '44156',
      active: false,
      question: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          id: '179016',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44267',
        },
        {
          id: '179015',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44267',
        },
      ],
    },
    '44161': {
      code: '44161',
      active: false,
      question: 'WERE WORKS SERVICES STAFF PRESENT',
      label: 'Were works services staff present?',
      multipleAnswers: false,
      answers: [
        {
          id: '179029',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45165',
        },
        {
          id: '179028',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45165',
        },
      ],
    },
    '44162': {
      code: '44162',
      active: false,
      question: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      label: 'Has the service supplier been notified of a replacement keyword?',
      multipleAnswers: false,
      answers: [
        {
          id: '179031',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44216',
        },
        {
          id: '179030',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44216',
        },
      ],
    },
    '44170': {
      code: '44170',
      active: false,
      question: 'HOW MANY PRISONERS WERE INVOLVED',
      label: 'How many prisoners were involved?',
      multipleAnswers: false,
      answers: [
        {
          id: '179060',
          response: 'NUMBER',
          active: false,
          label: 'Number',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44551',
        },
      ],
    },
    '44182': {
      code: '44182',
      active: false,
      question: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'Is the incident the subject of a police investigation?',
      multipleAnswers: false,
      answers: [
        {
          id: '179094',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44783',
        },
        {
          id: '179095',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44774',
        },
      ],
    },
    '44216': {
      code: '44216',
      active: false,
      question: 'INDICATE THE NATURE OF THE SHUT DOWN',
      label: 'Indicate the nature of the shut down',
      multipleAnswers: true,
      answers: [
        {
          id: '179206',
          response: 'TELEPHONY',
          active: false,
          label: 'Telephony',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44562',
        },
        {
          id: '179205',
          response: 'IT',
          active: false,
          label: 'IT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44562',
        },
      ],
    },
    '44238': {
      code: '44238',
      active: false,
      question: 'WERE EXTENDABLE BATONS USED',
      label: 'Were extendable batons used?',
      multipleAnswers: false,
      answers: [
        {
          id: '179284',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44338',
        },
        {
          id: '179283',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44338',
        },
      ],
    },
    '44250': {
      code: '44250',
      active: false,
      question: 'WAS THE KEYWORD REQUESTED?',
      label: 'Was the keyword requested?',
      multipleAnswers: false,
      answers: [
        {
          id: '179323',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44162',
        },
        {
          id: '179324',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44216',
        },
      ],
    },
    '44256': {
      code: '44256',
      active: false,
      question: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          id: '179336',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45065',
        },
        {
          id: '179335',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45065',
        },
      ],
    },
    '44267': {
      code: '44267',
      active: false,
      question: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'Were any injuries received during this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '179360',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45129',
        },
        {
          id: '179361',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44884',
        },
      ],
    },
    '44279': {
      code: '44279',
      active: false,
      question: 'QUOTE THE VANTIVE CASE NUMBER',
      label: 'Quote the Vantive case number',
      multipleAnswers: false,
      answers: [
        {
          id: '179394',
          response: 'NUMBER',
          active: false,
          label: 'Number',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44250',
        },
      ],
    },
    '44296': {
      code: '44296',
      active: false,
      question: 'WERE TRAINED NEGOTIATORS DEPLOYED',
      label: 'Were trained negotiators deployed?',
      multipleAnswers: false,
      answers: [
        {
          id: '179433',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44317',
        },
        {
          id: '179432',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44317',
        },
      ],
    },
    '44299': {
      code: '44299',
      active: false,
      question: 'WAS THE FIRE SERVICE PRESENT',
      label: 'Was the fire service present?',
      multipleAnswers: false,
      answers: [
        {
          id: '179450',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45174',
        },
        {
          id: '179449',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45174',
        },
      ],
    },
    '44304': {
      code: '44304',
      active: false,
      question: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '179481',
          response: 'ADMINISTRATION',
          active: false,
          label: 'Administration',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179482',
          response: 'ASSOCIATION AREA',
          active: false,
          label: 'Association area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179483',
          response: 'CELL',
          active: false,
          label: 'Cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179484',
          response: 'CHAPEL',
          active: false,
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179486',
          response: 'DINING ROOM',
          active: false,
          label: 'Dining room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179487',
          response: 'DORMITORY',
          active: false,
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179488',
          response: 'EDUCATION',
          active: false,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179490',
          response: 'EXERCISE YARD',
          active: false,
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179492',
          response: 'GATE',
          active: false,
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179493',
          response: 'GYM',
          active: false,
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179494',
          response: 'HEALTH CARE CENTRE',
          active: false,
          label: 'Health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179497',
          response: 'KITCHEN',
          active: false,
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179499',
          response: 'OFFICE',
          active: false,
          label: 'Office',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179501',
          response: 'RECEPTION',
          active: false,
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179502',
          response: 'RECESS',
          active: false,
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179503',
          response: 'SEGREGATION UNIT',
          active: false,
          label: 'Segregation unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179505',
          response: 'SPECIAL UNIT',
          active: false,
          label: 'Special unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179504',
          response: 'SHOWERS/CHANGING ROOM',
          active: false,
          label: 'Showers/changing room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179508',
          response: 'VISITS',
          active: false,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179510',
          response: 'WING',
          active: false,
          label: 'Wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179512',
          response: 'WORKS DEPARTMENT',
          active: false,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179513',
          response: 'WORKSHOP',
          active: false,
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179511',
          response: 'WITHIN PERIMETER',
          active: false,
          label: 'Within perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179489',
          response: 'ELSEWHERE',
          active: false,
          label: 'Elsewhere',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179491',
          response: 'FUNERAL',
          active: false,
          label: 'Funeral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179495',
          response: 'HOSPITAL OUTSIDE (PATIENT)',
          active: false,
          label: 'Hospital outside (patient)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179496',
          response: 'HOSPITAL OUTSIDE (VISITING)',
          active: false,
          label: 'Hospital outside (visiting)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179500',
          response: 'OUTSIDE WORKING PARTY',
          active: false,
          label: 'Outside working party',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179506',
          response: 'SPORTS FIELD',
          active: false,
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179507',
          response: 'VEHICLE',
          active: false,
          label: 'Vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179509',
          response: 'WEDDINGS',
          active: false,
          label: 'Weddings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179498',
          response: 'MAGISTRATES COURT',
          active: false,
          label: 'Magistrates court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
        {
          id: '179485',
          response: 'CROWN COURT',
          active: false,
          label: 'Crown court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
      ],
    },
    '44317': {
      code: '44317',
      active: false,
      question: 'WAS AN INCIDENT LIAISON OFFICER PRESENT',
      label: 'Was an incident liaison officer present?',
      multipleAnswers: false,
      answers: [
        {
          id: '179552',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45045',
        },
        {
          id: '179551',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45045',
        },
      ],
    },
    '44336': {
      code: '44336',
      active: false,
      question: 'WAS ANY EVACUATION NECESSARY',
      label: 'Was any evacuation necessary?',
      multipleAnswers: false,
      answers: [
        {
          id: '179630',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44483',
        },
        {
          id: '179629',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44483',
        },
      ],
    },
    '44338': {
      code: '44338',
      active: false,
      question: 'DURATION OF INCIDENT IN HOURS',
      label: 'Duration of incident in hours',
      multipleAnswers: false,
      answers: [
        {
          id: '179637',
          response: 'NUMBER OF HOURS',
          active: false,
          label: 'Number of hours',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45153',
        },
      ],
    },
    '44387': {
      code: '44387',
      active: false,
      question: 'DESCRIBE THE DAMAGE',
      label: 'Describe the damage',
      multipleAnswers: false,
      answers: [
        {
          id: '179809',
          response: 'MINOR',
          active: false,
          label: 'Minor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44661',
        },
        {
          id: '179810',
          response: 'SERIOUS',
          active: false,
          label: 'Serious',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44661',
        },
        {
          id: '179808',
          response: 'EXTENSIVE',
          active: false,
          label: 'Extensive',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44661',
        },
      ],
    },
    '44438': {
      code: '44438',
      active: false,
      question: 'WERE WEAPONS USED BY THE PERPETRATORS',
      label: 'Were weapons used by the perpetrators?',
      multipleAnswers: false,
      answers: [
        {
          id: '179940',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44654',
        },
        {
          id: '179941',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
      ],
    },
    '44483': {
      code: '44483',
      active: false,
      question: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      label: 'Was there an apparent reason for the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '180154',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44656',
        },
        {
          id: '180155',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44738',
        },
      ],
    },
    '44531': {
      code: '44531',
      active: false,
      question: 'WAS A MINOR INJURY SUSTAINED',
      label: 'Was a minor injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '180352',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44877',
        },
        {
          id: '180353',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44734',
        },
      ],
    },
    '44551': {
      code: '44551',
      active: false,
      question: 'HAVE THE RING LEADERS BEEN IDENTIFIED',
      label: 'Have the ring leaders been identified?',
      multipleAnswers: false,
      answers: [
        {
          id: '180435',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44623',
        },
        {
          id: '180434',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44623',
        },
      ],
    },
    '44562': {
      code: '44562',
      active: false,
      question: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      label: 'What time was the system shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '180466',
          response: 'ENTER TIME',
          active: false,
          label: 'Enter time',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44577',
        },
      ],
    },
    '44577': {
      code: '44577',
      active: false,
      question: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      label: 'Was this a full or partial shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '180509',
          response: 'FULL',
          active: false,
          label: 'Full',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44809',
        },
        {
          id: '180510',
          response: 'PARTIAL',
          active: false,
          label: 'Partial',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44809',
        },
      ],
    },
    '44623': {
      code: '44623',
      active: false,
      question: 'HAVE THE RING LEADERS BEEN ENTERED ON INMATE INVOLVEMENT',
      label: 'Have the ring leaders been entered on inmate involvement?',
      multipleAnswers: false,
      answers: [
        {
          id: '180663',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44917',
        },
        {
          id: '180662',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44917',
        },
      ],
    },
    '44654': {
      code: '44654',
      active: false,
      question: 'DESCRIBE WEAPONS USED',
      label: 'Describe weapons used',
      multipleAnswers: true,
      answers: [
        {
          id: '180765',
          response: 'FIREARM',
          active: false,
          label: 'Firearm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180762',
          response: 'CHEMICAL INCAPACITANT',
          active: false,
          label: 'Chemical incapacitant',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180767',
          response: 'KNIFE/BLADE',
          active: false,
          label: 'Knife/blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180770',
          response: 'OTHER SHARP INSTRUMENT',
          active: false,
          label: 'Other sharp instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180761',
          response: 'BLUNT INSTRUMENT',
          active: false,
          label: 'Blunt instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180768',
          response: 'LIGATURE',
          active: false,
          label: 'Ligature',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180763',
          response: 'DANGEROUS LIQUID',
          active: false,
          label: 'Dangerous liquid',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180764',
          response: 'EXCRETA/URINE',
          active: false,
          label: 'Excreta/urine',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180771',
          response: 'SPITTING',
          active: false,
          label: 'Spitting',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180766',
          response: 'FOOD',
          active: false,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180773',
          response: 'THROWN FURNITURE',
          active: false,
          label: 'Thrown furniture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180772',
          response: 'THROWN EQUIPMENT',
          active: false,
          label: 'Thrown equipment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44336',
        },
        {
          id: '180769',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44336',
        },
      ],
    },
    '44656': {
      code: '44656',
      active: false,
      question: 'DESCRIBE THE APPARENT REASON FOR THE INCIDENT',
      label: 'Describe the apparent reason for the incident',
      multipleAnswers: false,
      answers: [
        {
          id: '180776',
          response: 'FACILITIES',
          active: false,
          label: 'Facilities',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44738',
        },
        {
          id: '180777',
          response: 'FOOD',
          active: false,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44738',
        },
        {
          id: '180779',
          response: 'PAY',
          active: false,
          label: 'Pay',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44738',
        },
        {
          id: '180781',
          response: 'VISITS',
          active: false,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44738',
        },
        {
          id: '180780',
          response: 'TIME OUT OF CELL',
          active: false,
          label: 'Time out of cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44738',
        },
        {
          id: '180778',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44738',
        },
      ],
    },
    '44661': {
      code: '44661',
      active: false,
      question: 'ESTIMATED COST OF DAMAGE',
      label: 'Estimated cost of damage',
      multipleAnswers: false,
      answers: [
        {
          id: '180798',
          response: 'ENTER AMOUNT IN POUND STERLING',
          active: false,
          label: 'Enter amount in pound sterling',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44810',
        },
      ],
    },
    '44662': {
      code: '44662',
      active: false,
      question: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'Was the system re-activated locally or by the service supplier?',
      multipleAnswers: false,
      answers: [
        {
          id: '180799',
          response: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '180800',
          response: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44663': {
      code: '44663',
      active: false,
      question: 'WAS A CANDR ADVISOR PRESENT',
      label: 'Was a CANDR advisor present?',
      multipleAnswers: false,
      answers: [
        {
          id: '180802',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44684',
        },
        {
          id: '180801',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44684',
        },
      ],
    },
    '44679': {
      code: '44679',
      active: false,
      question: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      label: 'Are any staff on sick leave as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '180845',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44867',
        },
        {
          id: '180844',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44867',
        },
      ],
    },
    '44684': {
      code: '44684',
      active: false,
      question: 'WAS THE EMERGENCY RESPONSE VEHICLE PRESENT',
      label: 'Was the emergency response vehicle present?',
      multipleAnswers: false,
      answers: [
        {
          id: '180856',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44296',
        },
        {
          id: '180855',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44296',
        },
      ],
    },
    '44697': {
      code: '44697',
      active: false,
      question: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'Who was detained in outside hospital?',
      multipleAnswers: true,
      answers: [
        {
          id: '180918',
          response: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44884',
        },
        {
          id: '180917',
          response: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44884',
        },
        {
          id: '180914',
          response: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44884',
        },
        {
          id: '180916',
          response: 'POLICE',
          active: false,
          label: 'Police',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44884',
        },
        {
          id: '180915',
          response: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44884',
        },
      ],
    },
    '44724': {
      code: '44724',
      active: false,
      question: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '181028',
          response: 'FRACTURE',
          active: false,
          label: 'Fracture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181030',
          response: 'SCALD OR BURN',
          active: false,
          label: 'Scald or burn',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181031',
          response: 'STABBING',
          active: false,
          label: 'Stabbing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181025',
          response: 'CRUSHING',
          active: false,
          label: 'Crushing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181027',
          response: 'EXTENSIVE/MULTIPLE BRUISING',
          active: false,
          label: 'Extensive/multiple bruising',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181022',
          response: 'BLACK EYE',
          active: false,
          label: 'Black eye',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181023',
          response: 'BROKEN NOSE',
          active: false,
          label: 'Broken nose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181024',
          response: 'BROKEN TEETH',
          active: false,
          label: 'Broken teeth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181026',
          response: 'CUTS REQUIRING SUTURES',
          active: false,
          label: 'Cuts requiring sutures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181021',
          response: 'BITES',
          active: false,
          label: 'Bites',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181029',
          response: 'GUN SHOT WOUND',
          active: false,
          label: 'Gun shot wound',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
        {
          id: '181032',
          response: 'TEMPORARY/PERMANENT BLINDNESS',
          active: false,
          label: 'Temporary/permanent blindness',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
      ],
    },
    '44734': {
      code: '44734',
      active: false,
      question: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'Enter description of person(s) injured',
      multipleAnswers: true,
      answers: [
        {
          id: '181068',
          response: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44973',
        },
        {
          id: '181067',
          response: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44973',
        },
        {
          id: '181064',
          response: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44973',
        },
        {
          id: '181066',
          response: 'POLICE',
          active: false,
          label: 'Police',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44973',
        },
        {
          id: '181065',
          response: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44973',
        },
      ],
    },
    '44738': {
      code: '44738',
      active: false,
      question: 'DESCRIBE THE INCIDENT AS EITHER ACTIVE OR PASSIVE',
      label: 'Describe the incident as either active or passive',
      multipleAnswers: false,
      answers: [
        {
          id: '181075',
          response: 'ACTIVE',
          active: false,
          label: 'Active',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44760',
        },
        {
          id: '181076',
          response: 'PASSIVE',
          active: false,
          label: 'Passive',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44760',
        },
      ],
    },
    '44750': {
      code: '44750',
      active: false,
      question: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          id: '181105',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44304',
        },
        {
          id: '181106',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44910',
        },
      ],
    },
    '44758': {
      code: '44758',
      active: false,
      question: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'Was the telephone/it system shut down locally or by the service supplier?',
      multipleAnswers: false,
      answers: [
        {
          id: '181122',
          response: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44216',
        },
        {
          id: '181121',
          response: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44279',
        },
      ],
    },
    '44760': {
      code: '44760',
      active: false,
      question: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'Describe how the incident was resolved',
      multipleAnswers: false,
      answers: [
        {
          id: '181126',
          response: 'NEGOTIATION',
          active: false,
          label: 'Negotiation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44170',
        },
        {
          id: '181125',
          response: 'INTERVENTION',
          active: false,
          label: 'Intervention',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44170',
        },
        {
          id: '181127',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44170',
        },
      ],
    },
    '44764': {
      code: '44764',
      active: false,
      question: 'WAS THE SYSTEM COMPROMISED?',
      label: 'Was the system compromised?',
      multipleAnswers: false,
      answers: [
        {
          id: '181141',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45013',
        },
        {
          id: '181142',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44902',
        },
      ],
    },
    '44774': {
      code: '44774',
      active: false,
      question: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'Is the incident the subject of an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          id: '181167',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44140',
        },
        {
          id: '181166',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44140',
        },
      ],
    },
    '44783': {
      code: '44783',
      active: false,
      question: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'Has any prosecution taken place or is any pending?',
      multipleAnswers: false,
      answers: [
        {
          id: '181185',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44774',
        },
        {
          id: '181184',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44774',
        },
      ],
    },
    '44809': {
      code: '44809',
      active: false,
      question: 'WHO AUTHORISED THE SHUT DOWN?',
      label: 'Who authorised the shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '181279',
          response: 'GOVERNOR',
          active: false,
          label: 'Governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44764',
        },
        {
          id: '181277',
          response: 'DEPUTY GOVERNOR',
          active: false,
          label: 'Deputy governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44764',
        },
        {
          id: '181278',
          response: 'DUTY GOVERNOR',
          active: false,
          label: 'Duty governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44764',
        },
        {
          id: '181280',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44764',
        },
      ],
    },
    '44810': {
      code: '44810',
      active: false,
      question: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      label: 'Was the telephone/it system shut down during the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181281',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44758',
        },
        {
          id: '181282',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44867': {
      code: '44867',
      active: false,
      question: 'WAS A BARRICADE USED',
      label: 'Was a barricade used?',
      multipleAnswers: false,
      answers: [
        {
          id: '181453',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44663',
        },
        {
          id: '181452',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44663',
        },
      ],
    },
    '44877': {
      code: '44877',
      active: false,
      question: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '181507',
          response: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: false,
          label: 'Grazes, scratches or abrasions',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44734',
        },
        {
          id: '181508',
          response: 'MINOR BRUISES',
          active: false,
          label: 'Minor bruises',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44734',
        },
        {
          id: '181511',
          response: 'SWELLINGS',
          active: false,
          label: 'Swellings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44734',
        },
        {
          id: '181510',
          response: 'SUPERFICIAL CUTS',
          active: false,
          label: 'Superficial cuts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44734',
        },
        {
          id: '181509',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44734',
        },
      ],
    },
    '44884': {
      code: '44884',
      active: false,
      question: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'Are there any staff now off duty as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181533',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44679',
        },
        {
          id: '181532',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44679',
        },
      ],
    },
    '44902': {
      code: '44902',
      active: false,
      question: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      label: 'When was the system re-activated?',
      multipleAnswers: false,
      answers: [
        {
          id: '181584',
          response: 'ENTER COMMENT AND DATE',
          active: false,
          label: 'Enter comment and date',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '44662',
        },
      ],
    },
    '44910': {
      code: '44910',
      active: false,
      question: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181623',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44182',
        },
        {
          id: '181622',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44182',
        },
      ],
    },
    '44917': {
      code: '44917',
      active: false,
      question: 'WAS OPERATION TORNADO USED',
      label: 'Was operation Tornado used?',
      multipleAnswers: false,
      answers: [
        {
          id: '181640',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44122',
        },
        {
          id: '181639',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44122',
        },
      ],
    },
    '44973': {
      code: '44973',
      active: false,
      question: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'Did injuries result in detention in outside hospital as an in-patient?',
      multipleAnswers: false,
      answers: [
        {
          id: '181882',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44697',
        },
        {
          id: '181883',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44884',
        },
      ],
    },
    '44979': {
      code: '44979',
      active: false,
      question: 'WERE WATER HOSES USED',
      label: 'Were water hoses used?',
      multipleAnswers: false,
      answers: [
        {
          id: '181903',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44238',
        },
        {
          id: '181902',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44238',
        },
      ],
    },
    '45013': {
      code: '45013',
      active: false,
      question: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      label: 'Describe what was compromised and by whom',
      multipleAnswers: false,
      answers: [
        {
          id: '181993',
          response: 'DESCRIPTION',
          active: false,
          label: 'Description',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44902',
        },
      ],
    },
    '45045': {
      code: '45045',
      active: false,
      question: 'WERE HEALTH CARE CENTRE STAFF PRESENT',
      label: 'Were health care centre staff present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182163',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44161',
        },
        {
          id: '182162',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44161',
        },
      ],
    },
    '45065': {
      code: '45065',
      active: false,
      question: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '182246',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44156',
        },
        {
          id: '182245',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44156',
        },
      ],
    },
    '45117': {
      code: '45117',
      active: false,
      question: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'Was damage caused to prison property?',
      multipleAnswers: false,
      answers: [
        {
          id: '182419',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44387',
        },
        {
          id: '182420',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44810',
        },
      ],
    },
    '45129': {
      code: '45129',
      active: false,
      question: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'Was a serious injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '182465',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44724',
        },
        {
          id: '182466',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44531',
        },
      ],
    },
    '45153': {
      code: '45153',
      active: false,
      question: 'WAS THE INCIDENT IN PUBLIC VIEW',
      label: 'Was the incident in public view?',
      multipleAnswers: false,
      answers: [
        {
          id: '182570',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45117',
        },
        {
          id: '182569',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45117',
        },
      ],
    },
    '45158': {
      code: '45158',
      active: false,
      question: 'WAS THE AMBULANCE SERVICE PRESENT',
      label: 'Was the ambulance service present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182593',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44299',
        },
        {
          id: '182592',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44299',
        },
      ],
    },
    '45165': {
      code: '45165',
      active: false,
      question: 'WERE BOARD OF VISITORS MEMBERS PRESENT',
      label: 'Were board of visitors members present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182609',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45158',
        },
        {
          id: '182608',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45158',
        },
      ],
    },
    '45174': {
      code: '45174',
      active: false,
      question: 'WERE THE POLICE PRESENT',
      label: 'Were the police present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182642',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44438',
        },
        {
          id: '182641',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44438',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default CONCERTED_INDISCIPLINE_1
