// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-11-11T11:19:56.280Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const DAMAGE: IncidentTypeConfiguration = {
  incidentType: 'DAMAGE',
  active: false,
  startingQuestionId: '44784',
  questions: {
    '44167': {
      id: '44167',
      active: true,
      code: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      multipleAnswers: false,
      answers: [
        {
          id: '179054',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45002',
        },
        {
          id: '179055',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44655',
        },
      ],
    },
    '44190': {
      id: '44190',
      active: true,
      code: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          id: '179113',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44572',
        },
        {
          id: '179114',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44200',
        },
      ],
    },
    '44200': {
      id: '44200',
      active: true,
      code: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          id: '179166',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45050',
        },
        {
          id: '179165',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45050',
        },
      ],
    },
    '44230': {
      id: '44230',
      active: true,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      multipleAnswers: true,
      answers: [
        {
          id: '179247',
          code: 'STAFF',
          active: true,
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44167',
        },
        {
          id: '179246',
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44167',
        },
        {
          id: '179243',
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44167',
        },
        {
          id: '179245',
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44167',
        },
        {
          id: '179244',
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44167',
        },
      ],
    },
    '44295': {
      id: '44295',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'WAS A SERIOUS INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          id: '179430',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44785',
        },
        {
          id: '179431',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
      ],
    },
    '44324': {
      id: '44324',
      active: true,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '179570',
          code: 'ADMINISTRATION',
          active: true,
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179571',
          code: 'ASSOCIATION AREA',
          active: true,
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179572',
          code: 'CELL',
          active: true,
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179573',
          code: 'CHAPEL',
          active: true,
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179575',
          code: 'DINING ROOM',
          active: true,
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179576',
          code: 'DORMITORY',
          active: true,
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179577',
          code: 'EDUCATION',
          active: true,
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179579',
          code: 'EXERCISE YARD',
          active: true,
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179581',
          code: 'GATE',
          active: true,
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179582',
          code: 'GYM',
          active: true,
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179583',
          code: 'HEALTH CARE CENTRE',
          active: true,
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179586',
          code: 'KITCHEN',
          active: true,
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179588',
          code: 'OFFICE',
          active: true,
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179590',
          code: 'RECEPTION',
          active: true,
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179591',
          code: 'RECESS',
          active: true,
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179592',
          code: 'SEGREGATION UNIT',
          active: true,
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179594',
          code: 'SPECIAL UNIT',
          active: true,
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179593',
          code: 'SHOWERS/CHANGING ROOM',
          active: true,
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179597',
          code: 'VISITS',
          active: true,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179599',
          code: 'WING',
          active: true,
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179601',
          code: 'WORKS DEPARTMENT',
          active: true,
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179602',
          code: 'WORKSHOP',
          active: true,
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179600',
          code: 'WITHIN PERIMETER',
          active: true,
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179578',
          code: 'ELSEWHERE',
          active: true,
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179580',
          code: 'FUNERAL',
          active: true,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179584',
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: true,
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179585',
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: true,
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179589',
          code: 'OUTSIDE WORKING PARTY',
          active: true,
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179595',
          code: 'SPORTS FIELD',
          active: true,
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179596',
          code: 'VEHICLE',
          active: true,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179598',
          code: 'WEDDINGS',
          active: true,
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179587',
          code: 'MAGISTRATES COURT',
          active: true,
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
        {
          id: '179574',
          code: 'CROWN COURT',
          active: true,
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44343',
        },
      ],
    },
    '44343': {
      id: '44343',
      active: true,
      code: 'WHAT WAS DAMAGED',
      label: 'WHAT WAS DAMAGED',
      multipleAnswers: true,
      answers: [
        {
          id: '179657',
          code: 'FURNITURE',
          active: true,
          label: 'FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44466',
        },
        {
          id: '179656',
          code: 'FITTINGS',
          active: true,
          label: 'FITTINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44466',
        },
        {
          id: '179658',
          code: 'MACHINERY',
          active: true,
          label: 'MACHINERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44466',
        },
        {
          id: '179655',
          code: 'EQUIPMENT',
          active: true,
          label: 'EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44466',
        },
        {
          id: '179659',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44466',
        },
      ],
    },
    '44379': {
      id: '44379',
      active: true,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '179784',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44295',
        },
        {
          id: '179785',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44655',
        },
      ],
    },
    '44466': {
      id: '44466',
      active: true,
      code: 'DESCRIBE THE DAMAGE',
      label: 'DESCRIBE THE DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          id: '180083',
          code: 'MINOR',
          active: true,
          label: 'MINOR',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44763',
        },
        {
          id: '180084',
          code: 'SERIOUS',
          active: true,
          label: 'SERIOUS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44763',
        },
        {
          id: '180082',
          code: 'EXTENSIVE',
          active: true,
          label: 'EXTENSIVE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44763',
        },
      ],
    },
    '44512': {
      id: '44512',
      active: true,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '180259',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45082',
        },
        {
          id: '180258',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45082',
        },
      ],
    },
    '44572': {
      id: '44572',
      active: true,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      multipleAnswers: false,
      answers: [
        {
          id: '180492',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44200',
        },
        {
          id: '180491',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44200',
        },
      ],
    },
    '44576': {
      id: '44576',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '180504',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44230',
        },
        {
          id: '180505',
          code: 'MINOR BRUISES',
          active: true,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44230',
        },
        {
          id: '180508',
          code: 'SWELLINGS',
          active: true,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44230',
        },
        {
          id: '180507',
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44230',
        },
        {
          id: '180506',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44230',
        },
      ],
    },
    '44655': {
      id: '44655',
      active: true,
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '180775',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44735',
        },
        {
          id: '180774',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44735',
        },
      ],
    },
    '44735': {
      id: '44735',
      active: true,
      code: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      label: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '181070',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44324',
        },
        {
          id: '181069',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44324',
        },
      ],
    },
    '44763': {
      id: '44763',
      active: true,
      code: 'ESTIMATED COST OF DAMAGE',
      label: 'ESTIMATED COST OF DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          id: '181140',
          code: 'ENTER AMOUNT IN POUND STERLING',
          active: true,
          label: 'ENTER AMOUNT IN POUND STERLING',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44784': {
      id: '44784',
      active: true,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '181186',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44190',
        },
        {
          id: '181187',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44200',
        },
      ],
    },
    '44785': {
      id: '44785',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '181195',
          code: 'FRACTURE',
          active: true,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181197',
          code: 'SCALD OR BURN',
          active: true,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181198',
          code: 'STABBING',
          active: true,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181192',
          code: 'CRUSHING',
          active: true,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181194',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181189',
          code: 'BLACK EYE',
          active: true,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181190',
          code: 'BROKEN NOSE',
          active: true,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181191',
          code: 'BROKEN TEETH',
          active: true,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181193',
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181188',
          code: 'BITES',
          active: true,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181196',
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
        {
          id: '181199',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44971',
        },
      ],
    },
    '44971': {
      id: '44971',
      active: true,
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'WAS A MINOR INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          id: '181864',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44576',
        },
        {
          id: '181865',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44230',
        },
      ],
    },
    '45002': {
      id: '45002',
      active: true,
      code: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      multipleAnswers: true,
      answers: [
        {
          id: '181966',
          code: 'STAFF',
          active: true,
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44655',
        },
        {
          id: '181965',
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44655',
        },
        {
          id: '181962',
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44655',
        },
        {
          id: '181964',
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44655',
        },
        {
          id: '181963',
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44655',
        },
      ],
    },
    '45050': {
      id: '45050',
      active: true,
      code: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      multipleAnswers: false,
      answers: [
        {
          id: '182174',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44512',
        },
        {
          id: '182173',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44512',
        },
      ],
    },
    '45082': {
      id: '45082',
      active: true,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          id: '182287',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44379',
        },
        {
          id: '182286',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44379',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default DAMAGE
