// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:31.856Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const DEATH_PRISONER_1: IncidentTypeConfiguration = {
  incidentType: 'DEATH_PRISONER_1',
  active: true,
  startingQuestionCode: '44646',
  questions: {
    '44159': {
      code: '44159',
      active: true,
      question: 'WHAT WERE THE CIRCUMSTANCES OF THE DEATH',
      label: 'What were the circumstances of the death?',
      multipleAnswers: false,
      answers: [
        {
          code: '179023',
          response: 'APPARENT SELF INFLICTED',
          active: true,
          label: 'Apparent self inflicted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44383',
        },
        {
          code: '179024',
          response: 'APPARENT NATURAL CAUSES',
          active: true,
          label: 'Apparent natural causes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44384',
        },
        {
          code: '179025',
          response: 'ACCIDENTAL',
          active: true,
          label: 'Accidental',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45144',
        },
        {
          code: '179026',
          response: 'SUSPICIOUS CIRCUMSTANCES',
          active: true,
          label: 'Suspicious circumstances',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
      ],
    },
    '44292': {
      code: '44292',
      active: true,
      question: 'IS THE DEATH SUBJECT TO A HEALTH AND SAFETY INVESTIGATION',
      label: 'Is the death subject to a health and safety investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '179423',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44159',
        },
        {
          code: '179422',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44159',
        },
      ],
    },
    '44303': {
      code: '44303',
      active: true,
      question: 'WHAT VERDICT DID THE INQUEST REACH',
      label: 'What verdict did the inquest reach?',
      multipleAnswers: false,
      answers: [
        {
          code: '179477',
          response: 'NATURAL CAUSES',
          active: true,
          label: 'Natural causes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '179480',
          response: 'SUICIDE',
          active: true,
          label: 'Suicide',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '179475',
          response: 'ACCIDENTAL',
          active: true,
          label: 'Accidental',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '179476',
          response: 'MISADVENTURE',
          active: true,
          label: 'Misadventure',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '179478',
          response: 'OPEN VERDICT',
          active: true,
          label: 'Open verdict',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '179479',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: null,
        },
      ],
    },
    '44366': {
      code: '44366',
      active: true,
      question: 'WHERE WAS THE PRISONER LOCATED AT THE TIME OF DEATH',
      label: 'Where was the prisoner located at the time of death?',
      multipleAnswers: false,
      answers: [
        {
          code: '179724',
          response: 'SINGLE CELL: ORDINARY LOCATION',
          active: true,
          label: 'Single cell: ordinary location',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179725',
          response: 'SINGLE CELL: SEGREGATION UNIT',
          active: true,
          label: 'Single cell: segregation unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179723',
          response: 'SHARED CELL: ORDINARY LOCATION',
          active: true,
          label: 'Shared cell: ordinary location',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179727',
          response: 'SPECIAL CELL: SEGREGATION UNIT',
          active: true,
          label: 'Special cell: segregation unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179726',
          response: 'SINGLE CELL:HEALTH CARE CENTRE',
          active: true,
          label: 'Single cell:health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179729',
          response: 'WARD: HEALTH CARE CENTRE',
          active: true,
          label: 'Ward: health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179728',
          response: 'UNFURNISHED ROOM: H.C.C.',
          active: true,
          label: 'Unfurnished room: h.c.c.',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179722',
          response: 'PROTECTIVE ROOM: H.C.C.',
          active: true,
          label: 'Protective room: h.c.c.',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
        {
          code: '179721',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44680',
        },
      ],
    },
    '44383': {
      code: '44383',
      active: true,
      question: 'WHAT METHOD WAS USED',
      label: 'What method was used?',
      multipleAnswers: false,
      answers: [
        {
          code: '179796',
          response: 'HANGING',
          active: true,
          label: 'Hanging',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44929',
        },
        {
          code: '179797',
          response: 'CUTTING',
          active: true,
          label: 'Cutting',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
        {
          code: '179799',
          response: 'SUFFOCATION',
          active: true,
          label: 'Suffocation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
        {
          code: '179798',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
      ],
    },
    '44384': {
      code: '44384',
      active: true,
      question: 'WHAT WAS THE LIKELY CAUSE OF DEATH',
      label: 'What was the likely cause of death?',
      multipleAnswers: false,
      answers: [
        {
          code: '179802',
          response: 'MYOCARDIAL INFARCTION',
          active: true,
          label: 'Myocardial infarction',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '179800',
          response: 'LONG TERM ALCOHOL MISUSE',
          active: true,
          label: 'Long term alcohol misuse',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '179801',
          response: 'LONG TERM DRUG MISUSE',
          active: true,
          label: 'Long term drug misuse',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '179803',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
      ],
    },
    '44418': {
      code: '44418',
      active: true,
      question: 'WAS THE PRISONER RECEIVING MEDICATION AT THE TIME OF DEATH',
      label: 'Was the prisoner receiving medication at the time of death?',
      multipleAnswers: false,
      answers: [
        {
          code: '179894',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44691',
        },
        {
          code: '179893',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44691',
        },
      ],
    },
    '44420': {
      code: '44420',
      active: true,
      question: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '179898',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44743',
        },
        {
          code: '179897',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44743',
        },
      ],
    },
    '44468': {
      code: '44468',
      active: true,
      question: 'HAS THE NEXT OF KIN BEEN INFORMED',
      label: 'Has the next of kin been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: '180087',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '45063',
        },
        {
          code: '180086',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45063',
        },
      ],
    },
    '44537': {
      code: '44537',
      active: true,
      question: 'WHERE WAS THE PRISONER AT THE TIME OF DEATH',
      label: 'Where was the prisoner at the time of death?',
      multipleAnswers: false,
      answers: [
        {
          code: '180395',
          response: 'IN THE PRISON',
          active: true,
          label: 'In the prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44366',
        },
        {
          code: '180396',
          response: 'CUSTODY OF STAFF OUT OF PRISON',
          active: true,
          label: 'Custody of staff out of prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45166',
        },
        {
          code: '180397',
          response: 'ON TEMPORARY RELEASE',
          active: true,
          label: 'On temporary release',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44721',
        },
        {
          code: '180398',
          response: 'UNLAWFULLY AT LARGE',
          active: true,
          label: 'Unlawfully at large',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45043',
        },
      ],
    },
    '44640': {
      code: '44640',
      active: true,
      question: "HAS A CORONER'S INQUEST BEEN HELD",
      label: "Has a coroner's inquest been held?",
      multipleAnswers: false,
      answers: [
        {
          code: '180727',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionCode: '44303',
        },
        {
          code: '180728',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
      ],
    },
    '44646': {
      code: '44646',
      active: true,
      question: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '180739',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionCode: '45038',
        },
        {
          code: '180740',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45120',
        },
      ],
    },
    '44680': {
      code: '44680',
      active: true,
      question: 'WAS THE PRISONER ALONE AT THE TIME OF DEATH',
      label: 'Was the prisoner alone at the time of death?',
      multipleAnswers: false,
      answers: [
        {
          code: '180847',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44418',
        },
        {
          code: '180846',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44418',
        },
      ],
    },
    '44691': {
      code: '44691',
      active: true,
      question: 'WHO FOUND THE PRISONER',
      label: 'Who found the prisoner?',
      multipleAnswers: false,
      answers: [
        {
          code: '180883',
          response: 'PRISON STAFF',
          active: true,
          label: 'Prison staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45108',
        },
        {
          code: '180880',
          response: 'CELL MATE',
          active: true,
          label: 'Cell mate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45108',
        },
        {
          code: '180882',
          response: 'OTHER PRISONER',
          active: true,
          label: 'Other prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45108',
        },
        {
          code: '180881',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '45108',
        },
      ],
    },
    '44720': {
      code: '44720',
      active: true,
      question: 'WHO PRONOUNCED DEATH',
      label: 'Who pronounced death?',
      multipleAnswers: false,
      answers: [
        {
          code: '181004',
          response: 'PRISON MEDICAL OFFICER',
          active: true,
          label: 'Prison medical officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44962',
        },
        {
          code: '181002',
          response: 'HOSPITAL DOCTOR',
          active: true,
          label: 'Hospital doctor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44962',
        },
        {
          code: '181003',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44962',
        },
      ],
    },
    '44721': {
      code: '44721',
      active: true,
      question: 'WAS THE PRISONER ON T/R IN OUTSIDE HOSPITAL',
      label: 'Was the prisoner on t/r in outside hospital?',
      multipleAnswers: false,
      answers: [
        {
          code: '181005',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44720',
        },
        {
          code: '181006',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45043',
        },
      ],
    },
    '44743': {
      code: '44743',
      active: true,
      question: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: '181091',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionCode: '44537',
        },
        {
          code: '181090',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44537',
        },
      ],
    },
    '44770': {
      code: '44770',
      active: true,
      question: 'WHAT WAS THE LIGATURE ATTACHED TO',
      label: 'What was the ligature attached to?',
      multipleAnswers: false,
      answers: [
        {
          code: '181159',
          response: 'WINDOW BARS',
          active: true,
          label: 'Window bars',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
        {
          code: '181156',
          response: 'CELL DOOR',
          active: true,
          label: 'Cell door',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
        {
          code: '181157',
          response: 'LIGHT FITTINGS',
          active: true,
          label: 'Light fittings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
        {
          code: '181155',
          response: 'BED',
          active: true,
          label: 'Bed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
        {
          code: '181158',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '45023',
        },
      ],
    },
    '44862': {
      code: '44862',
      active: true,
      question: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: '181442',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44420',
        },
        {
          code: '181441',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44420',
        },
      ],
    },
    '44876': {
      code: '44876',
      active: true,
      question: 'WAS RESUSCITATION ATTEMPTED',
      label: 'Was resuscitation attempted?',
      multipleAnswers: false,
      answers: [
        {
          code: '181506',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44901',
        },
        {
          code: '181505',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44901',
        },
      ],
    },
    '44901': {
      code: '44901',
      active: true,
      question: 'WAS THE PRISONER TAKEN TO AN OUTSIDE HOSPITAL',
      label: 'Was the prisoner taken to an outside hospital?',
      multipleAnswers: false,
      answers: [
        {
          code: '181583',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44720',
        },
        {
          code: '181582',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44720',
        },
      ],
    },
    '44929': {
      code: '44929',
      active: true,
      question: 'WHAT WAS THE LIGATURE MADE FROM',
      label: 'What was the ligature made from?',
      multipleAnswers: false,
      answers: [
        {
          code: '181719',
          response: 'BEDDING',
          active: true,
          label: 'Bedding',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44770',
        },
        {
          code: '181722',
          response: 'SHOELACES',
          active: true,
          label: 'Shoelaces',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44770',
        },
        {
          code: '181720',
          response: 'CLOTHING',
          active: true,
          label: 'Clothing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44770',
        },
        {
          code: '181721',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44770',
        },
      ],
    },
    '44962': {
      code: '44962',
      active: true,
      question: 'WHAT TIME WAS DEATH PRONOUNCED',
      label: 'What time was death pronounced?',
      multipleAnswers: true,
      answers: [
        {
          code: '181829',
          response: 'DATE',
          active: true,
          label: 'Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionCode: '44292',
        },
        {
          code: '181830',
          response: 'TIME',
          active: true,
          label: 'Time',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44292',
        },
      ],
    },
    '45023': {
      code: '45023',
      active: true,
      question: 'WAS A F2052SH/ACCT OPEN AT THE TIME OF DEATH',
      label: 'Was a F2052SH/ACCT open at the time of death?',
      multipleAnswers: false,
      answers: [
        {
          code: '182033',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '182032',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
      ],
    },
    '45038': {
      code: '45038',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'Is the incident the subject of a police investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '182127',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45120',
        },
        {
          code: '182126',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '45120',
        },
      ],
    },
    '45043': {
      code: '45043',
      active: true,
      question: 'IS THE PLACE OF DEATH KNOWN',
      label: 'Is the place of death known?',
      multipleAnswers: false,
      answers: [
        {
          code: '182159',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44159',
        },
        {
          code: '182158',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44159',
        },
      ],
    },
    '45063': {
      code: '45063',
      active: true,
      question: 'HAS CORONER BEEN INFORMED',
      label: 'Has coroner been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: '182239',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44640',
        },
        {
          code: '182238',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44640',
        },
      ],
    },
    '45108': {
      code: '45108',
      active: true,
      question: 'AT WHAT TIME WAS THE PRISONER FOUND',
      label: 'At what time was the prisoner found',
      multipleAnswers: false,
      answers: [
        {
          code: '182373',
          response: 'DATE',
          active: true,
          label: 'Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionCode: '44876',
        },
        {
          code: '182374',
          response: 'TIME',
          active: true,
          label: 'Time',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44876',
        },
      ],
    },
    '45120': {
      code: '45120',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'Is the incident the subject of an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '182429',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44862',
        },
        {
          code: '182428',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44862',
        },
      ],
    },
    '45144': {
      code: '45144',
      active: true,
      question: 'WAS THE ACCIDENTAL DEATH CAUSED BY',
      label: 'Was the accidental death caused by?',
      multipleAnswers: false,
      answers: [
        {
          code: '182541',
          response: 'DRUG OVERDOSE',
          active: true,
          label: 'Drug overdose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '182542',
          response: 'FALL',
          active: true,
          label: 'Fall',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '182544',
          response: 'TRANSPORT ACCIDENT',
          active: true,
          label: 'Transport accident',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '182540',
          response: 'ACCIDENT INVOLVING MACHINERY',
          active: true,
          label: 'Accident involving machinery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
        {
          code: '182543',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44468',
        },
      ],
    },
    '45166': {
      code: '45166',
      active: true,
      question: 'WHERE DID THE DEATH TAKE PLACE',
      label: 'Where did the death take place?',
      multipleAnswers: false,
      answers: [
        {
          code: '182615',
          response: 'OUTSIDE HOSPITAL',
          active: true,
          label: 'Outside hospital',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44720',
        },
        {
          code: '182614',
          response: 'OUTSIDE WORKING PARTY',
          active: true,
          label: 'Outside working party',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44876',
        },
        {
          code: '182613',
          response: 'OUTSIDE P.E. ACTIVITY',
          active: true,
          label: 'Outside p.e. activity',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44876',
        },
        {
          code: '182610',
          response: 'AT COURT',
          active: true,
          label: 'At court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionCode: '44876',
        },
        {
          code: '182612',
          response: 'OTHER ESCORT',
          active: true,
          label: 'Other escort',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44876',
        },
        {
          code: '182611',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionCode: '44876',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'DECEASED',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
  requiresPrisoners: true,
}

export default DEATH_PRISONER_1
