// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-25T09:25:56.946Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const DISORDER: IncidentTypeConfiguration = {
  incidentType: 'DISORDER',
  active: true,
  startingQuestionId: '63179',
  questions: {
    '63179': {
      id: '63179',
      active: true,
      code: 'WHAT TYPE OF DISORDER INCIDENT WAS THIS?',
      label: 'WHAT TYPE OF DISORDER INCIDENT WAS THIS?',
      multipleAnswers: false,
      answers: [
        {
          code: 'BARRICADE/PREVENTION OF ACCESS',
          active: true,
          label: 'BARRICADE/PREVENTION OF ACCESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
        {
          code: 'CONCERTED INDISCIPLINE',
          active: true,
          label: 'CONCERTED INDISCIPLINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
        {
          code: 'HOSTAGE',
          active: true,
          label: 'HOSTAGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
        {
          code: 'INCIDENT AT HEIGHT',
          active: true,
          label: 'INCIDENT AT HEIGHT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
      ],
    },
    '63180': {
      id: '63180',
      active: true,
      code: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT',
      label: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO FURTHER ACTION',
          active: true,
          label: 'NO FURTHER ACTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
        {
          code: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          active: true,
          label: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
        {
          code: 'IEP REGRESSION',
          active: true,
          label: 'IEP REGRESSION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
        {
          code: 'POLICE REFERRAL',
          active: true,
          label: 'POLICE REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
      ],
    },
    '63181': {
      id: '63181',
      active: true,
      code: 'IS THE LOCATION OF THIS INCIDENT KNOWN',
      label: 'IS THE LOCATION OF THIS INCIDENT KNOWN',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63182',
        },
      ],
    },
    '63182': {
      id: '63182',
      active: true,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          active: true,
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'ASSOCIATION AREA',
          active: true,
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'CELL',
          active: true,
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'CHAPEL',
          active: true,
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'CROWN COURT',
          active: true,
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'DINING ROOM',
          active: true,
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'DORMITORY',
          active: true,
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'EDUCATION',
          active: true,
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'EXERCISE YARD',
          active: true,
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'EXTERNAL ROOF',
          active: true,
          label: 'EXTERNAL ROOF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'FUNERAL',
          active: true,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'GATE',
          active: true,
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'GYM',
          active: true,
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'HEALTH CARE CENTRE',
          active: true,
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: true,
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: true,
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'INDUCTION/1ST NIGHT CENTRE',
          active: true,
          label: 'INDUCTION/1ST NIGHT CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'KITCHEN',
          active: true,
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'MAGISTRATES COURT',
          active: true,
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'OFFICE',
          active: true,
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          active: true,
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'RECEPTION',
          active: true,
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'RECESS',
          active: true,
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'SEGREGATION UNIT',
          active: true,
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'SHOWERS/CHANGING ROOM',
          active: true,
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'SPECIAL UNIT',
          active: true,
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'SPORTS FIELD',
          active: true,
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'VEHICLE',
          active: true,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'VISITS',
          active: true,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'VULNERABLE PRISONERS UNIT',
          active: true,
          label: 'VULNERABLE PRISONERS UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'WEDDINGS',
          active: true,
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'WING',
          active: true,
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'WITHIN PERIMETER',
          active: true,
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'WORKS DEPARTMENT',
          active: true,
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'WORKSHOP',
          active: true,
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63183',
        },
      ],
    },
    '63183': {
      id: '63183',
      active: true,
      code: 'WAS THE INCIDENT IN PUBLIC VIEW',
      label: 'WAS THE INCIDENT IN PUBLIC VIEW',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63184',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63184',
        },
      ],
    },
    '63184': {
      id: '63184',
      active: true,
      code: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      label: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'DEMANDING EXTERNAL TRANSFER',
          active: true,
          label: 'DEMANDING EXTERNAL TRANSFER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'DEMANDING INTERNAL TRANSFER',
          active: true,
          label: 'DEMANDING INTERNAL TRANSFER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'FACILITIES',
          active: true,
          label: 'FACILITIES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'FOOD',
          active: true,
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'PAY',
          active: true,
          label: 'PAY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'REFUSING EXTERNAL TRANSFER',
          active: true,
          label: 'REFUSING EXTERNAL TRANSFER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'REFUSING INTERNAL TRANSFER',
          active: true,
          label: 'REFUSING INTERNAL TRANSFER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'TIME OUT OF CELL',
          active: true,
          label: 'TIME OUT OF CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'VISITS',
          active: true,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63185',
        },
      ],
    },
    '63185': {
      id: '63185',
      active: true,
      code: 'WHAT AGGRAVATING FACTORS WHERE PRESENT',
      label: 'WHAT AGGRAVATING FACTORS WHERE PRESENT',
      multipleAnswers: true,
      answers: [
        {
          code: 'ACCESS DIFFICULTIES',
          active: true,
          label: 'ACCESS DIFFICULTIES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          code: 'DAMAGE RESULTING IN LOSS OF FACILITIES OR UTILITIES',
          active: true,
          label: 'DAMAGE RESULTING IN LOSS OF FACILITIES OR UTILITIES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          code: 'DAMAGE RESULTING IN THE LOSS OF ACCOMMODATION',
          active: true,
          label: 'DAMAGE RESULTING IN THE LOSS OF ACCOMMODATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          code: 'MEDIA INTEREST',
          active: true,
          label: 'MEDIA INTEREST',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          code: 'ORRU ASSISTANCE REQUESTED',
          active: true,
          label: 'ORRU ASSISTANCE REQUESTED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          code: 'PERPETRATOR UNDER INFLUENCE OF DRUGS OR ALCOHOL',
          active: true,
          label: 'PERPETRATOR UNDER INFLUENCE OF DRUGS OR ALCOHOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          code: 'THREAT OR ACTUAL SELF HARM',
          active: true,
          label: 'THREAT OR ACTUAL SELF HARM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          code: 'VIOLENCE DIRECTED AGAINST STAFF',
          active: true,
          label: 'VIOLENCE DIRECTED AGAINST STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
      ],
    },
    '63186': {
      id: '63186',
      active: true,
      code: 'WHAT WAS THE DURATION OF THE INCIDENT',
      label: 'WHAT WAS THE DURATION OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: '< 1 minute',
          active: true,
          label: '< 1 minute',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '1 min to <5mins',
          active: true,
          label: '1 min to <5mins',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '10 mins to <15mins',
          active: true,
          label: '10 mins to <15mins',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '15 mins to <30mins',
          active: true,
          label: '15 mins to <30mins',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '30 mins to <1 hour',
          active: true,
          label: '30 mins to <1 hour',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '1 hour to <2 hours',
          active: true,
          label: '1 hour to <2 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '2 hours to <3 hours',
          active: true,
          label: '2 hours to <3 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '3 hours to <4 hours',
          active: true,
          label: '3 hours to <4 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '4 hours to <5 hours',
          active: true,
          label: '4 hours to <5 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: '5 hours plus',
          active: true,
          label: '5 hours plus',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          code: 'UNKNOWN - ENTER DETAILS',
          active: true,
          label: 'UNKNOWN - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63187',
        },
      ],
    },
    '63187': {
      id: '63187',
      active: true,
      code: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      multipleAnswers: false,
      answers: [
        {
          code: 'COMPLIED WITH ORDER OR INSTRUCTION',
          active: true,
          label: 'COMPLIED WITH ORDER OR INSTRUCTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          code: 'NEGOTIATION',
          active: true,
          label: 'NEGOTIATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          code: 'INTERVENTION (LOCAL STAFF)',
          active: true,
          label: 'INTERVENTION (LOCAL STAFF)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          code: 'INTERVENTION (ORRU STAFF)',
          active: true,
          label: 'INTERVENTION (ORRU STAFF)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          code: 'INTERVENTION (OPERATION TORNADO)',
          active: true,
          label: 'INTERVENTION (OPERATION TORNADO)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63188',
        },
      ],
    },
    '63188': {
      id: '63188',
      active: true,
      code: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      label: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63189',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63189',
        },
      ],
    },
    '63189': {
      id: '63189',
      active: true,
      code: 'WERE PRISON RESOURCES PRESENT',
      label: 'WERE PRISON RESOURCES PRESENT',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          code: 'C & R ADVISOR',
          active: true,
          label: 'C & R ADVISOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          code: 'INCIDENT LIAISON OFFICER',
          active: true,
          label: 'INCIDENT LIAISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          code: 'HEALTH CARE STAFF',
          active: true,
          label: 'HEALTH CARE STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          code: 'WORKS SERVICES STAFF',
          active: true,
          label: 'WORKS SERVICES STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63190',
        },
      ],
    },
    '63190': {
      id: '63190',
      active: true,
      code: 'WAS SPECIALIST EQUIPMENT / RESOURCES USED?',
      label: 'WAS SPECIALIST EQUIPMENT / RESOURCES USED?',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          code: 'DOOR JACK',
          active: true,
          label: 'DOOR JACK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          code: 'EXTENDABLE BATONS',
          active: true,
          label: 'EXTENDABLE BATONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          code: 'NEGOTIATION ADVISER (INCLUDING HOSTAGE)',
          active: true,
          label: 'NEGOTIATION ADVISER (INCLUDING HOSTAGE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          code: 'OPERATIONAL RESILIENCE AND RESPONSE UNIT (ORRU)',
          active: true,
          label: 'OPERATIONAL RESILIENCE AND RESPONSE UNIT (ORRU)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          code: 'TORNADO',
          active: true,
          label: 'TORNADO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          code: 'WATER HOSES',
          active: true,
          label: 'WATER HOSES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63191',
        },
      ],
    },
    '63191': {
      id: '63191',
      active: true,
      code: 'WERE EMERGENCY SERVICES PRESENT',
      label: 'WERE EMERGENCY SERVICES PRESENT',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          code: 'FIRE',
          active: true,
          label: 'FIRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          code: 'AMBULANCE',
          active: true,
          label: 'AMBULANCE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63192',
        },
      ],
    },
    '63192': {
      id: '63192',
      active: true,
      code: 'WAS ANY EVACUATION NECESSARY',
      label: 'WAS ANY EVACUATION NECESSARY',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63193',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63193',
        },
      ],
    },
    '63193': {
      id: '63193',
      active: true,
      code: 'DESCRIBE THE INCIDENT AS EITHER ACTIVE OR PASSIVE',
      label: 'DESCRIBE THE INCIDENT AS EITHER ACTIVE OR PASSIVE',
      multipleAnswers: false,
      answers: [
        {
          code: 'ACTIVE',
          active: true,
          label: 'ACTIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63194',
        },
        {
          code: 'PASSIVE',
          active: true,
          label: 'PASSIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63194',
        },
      ],
    },
    '63194': {
      id: '63194',
      active: true,
      code: 'HOW MANY PRISONERS WERE INVOLVED',
      label: 'HOW MANY PRISONERS WERE INVOLVED',
      multipleAnswers: false,
      answers: [
        {
          code: 'NUMBER - ENTER DETAILS',
          active: true,
          label: 'NUMBER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63195',
        },
      ],
    },
    '63195': {
      id: '63195',
      active: true,
      code: 'PERPETRATOR(S) TYPE',
      label: 'PERPETRATOR(S) TYPE',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONER - ENTER NUMBER OF',
          active: true,
          label: 'PRISONER - ENTER NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63196',
        },
        {
          code: 'VISITOR - ENTER NUMBER OF',
          active: true,
          label: 'VISITOR - ENTER NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63196',
        },
        {
          code: 'OTHER - ENTER NUMBER OF',
          active: true,
          label: 'OTHER - ENTER NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63196',
        },
      ],
    },
    '63196': {
      id: '63196',
      active: true,
      code: 'HAVE THE RINGLEADERS BEEN IDENTIFIED',
      label: 'HAVE THE RINGLEADERS BEEN IDENTIFIED',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63198',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63197',
        },
      ],
    },
    '63197': {
      id: '63197',
      active: true,
      code: 'HAVE THE RINGLEADERS BEEN ENTERED ON LINKED OFFENDER',
      label: 'HAVE THE RINGLEADERS BEEN ENTERED ON LINKED OFFENDER',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63198',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63198',
        },
      ],
    },
    '63198': {
      id: '63198',
      active: true,
      code: 'WERE WEAPONS USED BY THE PERPETRATOR',
      label: 'WERE WEAPONS USED BY THE PERPETRATOR',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63199',
        },
        {
          code: 'YES - PLEASE LOG FIND INCIDENT IF WEAPON RECOVERED',
          active: true,
          label: 'YES - PLEASE LOG FIND INCIDENT IF WEAPON RECOVERED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63199',
        },
      ],
    },
    '63199': {
      id: '63199',
      active: true,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63200',
        },
        {
          code: 'YES - PLEASE LOG DAMAGE INCIDENT',
          active: true,
          label: 'YES - PLEASE LOG DAMAGE INCIDENT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63200',
        },
      ],
    },
    '63200': {
      id: '63200',
      active: true,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63201',
        },
      ],
    },
    '63201': {
      id: '63201',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'WAS A SERIOUS INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63202',
        },
      ],
    },
    '63202': {
      id: '63202',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'BITES',
          active: true,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'BLACK EYE',
          active: true,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'BROKEN NOSE',
          active: true,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'BROKEN TEETH',
          active: true,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'CRUSHING',
          active: true,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'FRACTURE',
          active: true,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'SCALD OR BURN',
          active: true,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'STABBING',
          active: true,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
      ],
    },
    '63203': {
      id: '63203',
      active: true,
      code: 'ENTER DESCIPTION OF PERSON(S) INJURED (SERIOUS)',
      label: 'ENTER DESCIPTION OF PERSON(S) INJURED (SERIOUS)',
      multipleAnswers: true,
      answers: [
        {
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'CIVILIAN GRADES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'OPERATIONAL STAFF - PRISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'OPERATIONAL STAFF - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'NON-OPERATIONAL STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'NON-DIRECTLY EMPLOYED STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63204',
        },
      ],
    },
    '63204': {
      id: '63204',
      active: true,
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'WAS A MINOR INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63205',
        },
      ],
    },
    '63205': {
      id: '63205',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          code: 'MINOR BRUISES',
          active: true,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          code: 'SWELLINGS',
          active: true,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
      ],
    },
    '63206': {
      id: '63206',
      active: true,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED (MINOR)',
      label: 'ENTER DESCRIPTION OF PERSON(S) INJURED (MINOR)',
      multipleAnswers: true,
      answers: [
        {
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'CIVILIAN GRADES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'OPERATIONAL STAFF - PRISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'OPERATIONAL STAFF - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'NON-OPERATIONAL STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'NON-DIRECTLY EMPLOYED STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: false,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63207',
        },
      ],
    },
    '63207': {
      id: '63207',
      active: true,
      code: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS IN-PATIENT',
      label: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS IN-PATIENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63208',
        },
      ],
    },
    '63208': {
      id: '63208',
      active: true,
      code: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      multipleAnswers: true,
      answers: [
        {
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'CIVILIAN GRADES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'PRISONERS',
          active: true,
          label: 'PRISONERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'OPERATIONAL STAFF - PRISON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'OPERATIONAL STAFF - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'NON-OPERATIONAL STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'NON-DIRECTLY EMPLOYED STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'OTHER - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63209',
        },
      ],
    },
    '63209': {
      id: '63209',
      active: true,
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63210',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63210',
        },
      ],
    },
    '63210': {
      id: '63210',
      active: true,
      code: 'DID INCIDENT HAPPENT AT HEIGHT (FULLY OR PARTIALLY)',
      label: 'DID INCIDENT HAPPENT AT HEIGHT (FULLY OR PARTIALLY)',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63211',
        },
      ],
    },
    '63211': {
      id: '63211',
      active: true,
      code: 'DESCRIBE METHOD OF GAINING ACCESS TO AREA AT HEIGHT',
      label: 'DESCRIBE METHOD OF GAINING ACCESS TO AREA AT HEIGHT',
      multipleAnswers: true,
      answers: [
        {
          code: 'CONTRACTORS EQUIPMENT',
          active: true,
          label: 'CONTRACTORS EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'EXTERNAL ACCESS: FENCING',
          active: true,
          label: 'EXTERNAL ACCESS: FENCING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'EXTERNAL ACCESS: ROOF',
          active: true,
          label: 'EXTERNAL ACCESS: ROOF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'EXTERNAL ACCESS: TREE',
          active: true,
          label: 'EXTERNAL ACCESS: TREE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'INTERNAL ACCESS: LANDINGS/RAILINGS',
          active: true,
          label: 'INTERNAL ACCESS: LANDINGS/RAILINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'INTERNAL ACCESS: NETTING',
          active: true,
          label: 'INTERNAL ACCESS: NETTING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'INTERNAL ACCESS: WINDOW/GATE BARS',
          active: true,
          label: 'INTERNAL ACCESS: WINDOW/GATE BARS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'OTHER: INTERNAL - ENTER DETAILS',
          active: true,
          label: 'OTHER: INTERNAL - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          code: 'OTHER: EXTERNAL - ENTER DETAILS',
          active: true,
          label: 'OTHER: EXTERNAL - ENTER DETAILS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63212',
        },
      ],
    },
    '63212': {
      id: '63212',
      active: true,
      code: 'WHAT HEIGHT DID THE INCIDENT TAKE PLACE',
      label: 'WHAT HEIGHT DID THE INCIDENT TAKE PLACE',
      multipleAnswers: true,
      answers: [
        {
          code: 'BETWEEN 3 FEET AND <1ST FLOOR',
          active: true,
          label: 'BETWEEN 3 FEET AND <1ST FLOOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          code: '1ST FLOOR',
          active: true,
          label: '1ST FLOOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          code: '2ND FLOOR',
          active: true,
          label: '2ND FLOOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          code: '3RD FLOOR OR HIGHER',
          active: true,
          label: '3RD FLOOR OR HIGHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
      ],
    },
    '63213': {
      id: '63213',
      active: true,
      code: 'WAS A BARRICADE USED',
      label: 'WAS A BARRICADE USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63214',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63214',
        },
      ],
    },
    '63214': {
      id: '63214',
      active: true,
      code: 'DID INCIDENT INVOLVE HOSTAGE(S)',
      label: 'DID INCIDENT INVOLVE HOSTAGE(S)',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63215',
        },
      ],
    },
    '63215': {
      id: '63215',
      active: true,
      code: 'DESCRIBE STATUS OF HOSTAGES',
      label: 'DESCRIBE STATUS OF HOSTAGES',
      multipleAnswers: true,
      answers: [
        {
          code: 'CIVILIAN STAFF - STATE NUMBER OF',
          active: true,
          label: 'CIVILIAN STAFF - STATE NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          code: 'OFFICER - STATE NUMBER OF',
          active: true,
          label: 'OFFICER - STATE NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          code: 'PRISONER - STATE NUMBER OF',
          active: true,
          label: 'PRISONER - STATE NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          code: 'STAFF - STATE NUMBER OF',
          active: true,
          label: 'STAFF - STATE NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          code: 'OTHER - STATE NUMBER OF',
          active: true,
          label: 'OTHER - STATE NUMBER OF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
      ],
    },
    '63216': {
      id: '63216',
      active: true,
      code: 'WAS A HOSTAGE PART OF THE BARRICADE',
      label: 'WAS A HOSTAGE PART OF THE BARRICADE',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63217',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63217',
        },
      ],
    },
    '63217': {
      id: '63217',
      active: true,
      code: 'WAS PHYSICAL VIOLENCE USED TOWARDS HOSTAGE',
      label: 'WAS PHYSICAL VIOLENCE USED TOWARDS HOSTAGE',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63218',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63218',
        },
      ],
    },
    '63218': {
      id: '63218',
      active: true,
      code: 'WAS THE HOSTAGE PHYSICALLY RESTRAINED BY THE PERPETRATOR',
      label: 'WAS THE HOSTAGE PHYSICALLY RESTRAINED BY THE PERPETRATOR',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63219',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63219',
        },
      ],
    },
    '63219': {
      id: '63219',
      active: true,
      code: 'WAS THERE EVIDENCE OF THE STOCKHOLM SYNDROME',
      label: 'WAS THERE EVIDENCE OF THE STOCKHOLM SYNDROME',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63220',
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63220',
        },
      ],
    },
    '63220': {
      id: '63220',
      active: true,
      code: 'WAS THERE EVIDENCE OF COLLUSION',
      label: 'WAS THERE EVIDENCE OF COLLUSION',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSAILANT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'FIGHTER',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'HOSTAGE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_ASSAILANT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'VICTIM',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default DISORDER
