// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:34.590Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const DISORDER_2: IncidentTypeConfiguration = {
  incidentType: 'DISORDER_2',
  active: true,
  startingQuestionId: '63179',
  questions: {
    '63179': {
      id: '63179',
      active: true,
      code: 'WHAT TYPE OF DISORDER INCIDENT WAS THIS?',
      label: 'What type of disorder incident was this?',
      multipleAnswers: false,
      answers: [
        {
          id: '214684',
          code: 'BARRICADE/PREVENTION OF ACCESS',
          active: true,
          label: 'Barricade/prevention of access',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
        {
          id: '214685',
          code: 'CONCERTED INDISCIPLINE',
          active: true,
          label: 'Concerted indiscipline',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
        {
          id: '214686',
          code: 'HOSTAGE',
          active: true,
          label: 'Hostage',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
        {
          id: '214687',
          code: 'INCIDENT AT HEIGHT',
          active: true,
          label: 'Incident at height',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63180',
        },
      ],
    },
    '63180': {
      id: '63180',
      active: true,
      code: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT',
      label: 'What was the main management outcome of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '214688',
          code: 'NO FURTHER ACTION',
          active: true,
          label: 'No further action',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
        {
          id: '214689',
          code: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          active: true,
          label: 'Placed on report/adjudication referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
        {
          id: '214690',
          code: 'IEP REGRESSION',
          active: true,
          label: 'IEP regression',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
        {
          id: '214691',
          code: 'POLICE REFERRAL',
          active: true,
          label: 'Police referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63181',
        },
      ],
    },
    '63181': {
      id: '63181',
      active: true,
      code: 'IS THE LOCATION OF THIS INCIDENT KNOWN',
      label: 'Is the location of this incident known?',
      multipleAnswers: false,
      answers: [
        {
          id: '214692',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214693',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63182',
        },
      ],
    },
    '63182': {
      id: '63182',
      active: true,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '214694',
          code: 'ADMINISTRATION',
          active: true,
          label: 'Administration',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214695',
          code: 'ASSOCIATION AREA',
          active: true,
          label: 'Association area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214696',
          code: 'CELL',
          active: true,
          label: 'Cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214697',
          code: 'CHAPEL',
          active: true,
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214698',
          code: 'CROWN COURT',
          active: true,
          label: 'Crown court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214699',
          code: 'DINING ROOM',
          active: true,
          label: 'Dining room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214700',
          code: 'DORMITORY',
          active: true,
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214701',
          code: 'EDUCATION',
          active: true,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214702',
          code: 'EXERCISE YARD',
          active: true,
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214703',
          code: 'EXTERNAL ROOF',
          active: true,
          label: 'External roof',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214704',
          code: 'FUNERAL',
          active: true,
          label: 'Funeral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214705',
          code: 'GATE',
          active: true,
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214706',
          code: 'GYM',
          active: true,
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214707',
          code: 'HEALTH CARE CENTRE',
          active: true,
          label: 'Health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214708',
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: true,
          label: 'Hospital outside (patient)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214709',
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: true,
          label: 'Hospital outside (visiting)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214710',
          code: 'INDUCTION/1ST NIGHT CENTRE',
          active: true,
          label: 'Induction/1st night centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214711',
          code: 'KITCHEN',
          active: true,
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214712',
          code: 'MAGISTRATES COURT',
          active: true,
          label: 'Magistrates court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214713',
          code: 'OFFICE',
          active: true,
          label: 'Office',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214714',
          code: 'OUTSIDE WORKING PARTY',
          active: true,
          label: 'Outside working party',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214715',
          code: 'RECEPTION',
          active: true,
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214716',
          code: 'RECESS',
          active: true,
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214717',
          code: 'SEGREGATION UNIT',
          active: true,
          label: 'Segregation unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214718',
          code: 'SHOWERS/CHANGING ROOM',
          active: true,
          label: 'Showers/changing room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214719',
          code: 'SPECIAL UNIT',
          active: true,
          label: 'Special unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214720',
          code: 'SPORTS FIELD',
          active: true,
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214721',
          code: 'VEHICLE',
          active: true,
          label: 'Vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214722',
          code: 'VISITS',
          active: true,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214723',
          code: 'VULNERABLE PRISONERS UNIT',
          active: true,
          label: 'Vulnerable prisoners unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214724',
          code: 'WEDDINGS',
          active: true,
          label: 'Weddings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214725',
          code: 'WING',
          active: true,
          label: 'Wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214726',
          code: 'WITHIN PERIMETER',
          active: true,
          label: 'Within perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214727',
          code: 'WORKS DEPARTMENT',
          active: true,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214728',
          code: 'WORKSHOP',
          active: true,
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63183',
        },
        {
          id: '214729',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63183',
        },
      ],
    },
    '63183': {
      id: '63183',
      active: true,
      code: 'WAS THE INCIDENT IN PUBLIC VIEW',
      label: 'Was the incident in public view?',
      multipleAnswers: false,
      answers: [
        {
          id: '214730',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63184',
        },
        {
          id: '214731',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63184',
        },
      ],
    },
    '63184': {
      id: '63184',
      active: true,
      code: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      label: 'Was there an apparent reason for the incident?',
      multipleAnswers: true,
      answers: [
        {
          id: '214732',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214733',
          code: 'DEMANDING EXTERNAL TRANSFER',
          active: true,
          label: 'Demanding external transfer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214734',
          code: 'DEMANDING INTERNAL TRANSFER',
          active: true,
          label: 'Demanding internal transfer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214735',
          code: 'FACILITIES',
          active: true,
          label: 'Facilities',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214736',
          code: 'FOOD',
          active: true,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214737',
          code: 'PAY',
          active: true,
          label: 'Pay',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214738',
          code: 'REFUSING EXTERNAL TRANSFER',
          active: true,
          label: 'Refusing external transfer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214739',
          code: 'REFUSING INTERNAL TRANSFER',
          active: true,
          label: 'Refusing internal transfer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214740',
          code: 'TIME OUT OF CELL',
          active: true,
          label: 'Time out of cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214741',
          code: 'VISITS',
          active: true,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63185',
        },
        {
          id: '214742',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63185',
        },
      ],
    },
    '63185': {
      id: '63185',
      active: true,
      code: 'WHAT AGGRAVATING FACTORS WHERE PRESENT',
      label: 'What aggravating factors where present?',
      multipleAnswers: true,
      answers: [
        {
          id: '214743',
          code: 'ACCESS DIFFICULTIES',
          active: true,
          label: 'Access difficulties',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          id: '214744',
          code: 'DAMAGE RESULTING IN LOSS OF FACILITIES OR UTILITIES',
          active: true,
          label: 'Damage resulting in loss of facilities or utilities',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          id: '214745',
          code: 'DAMAGE RESULTING IN THE LOSS OF ACCOMMODATION',
          active: true,
          label: 'Damage resulting in the loss of accommodation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          id: '214746',
          code: 'MEDIA INTEREST',
          active: true,
          label: 'Media interest',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          id: '214747',
          code: 'ORRU ASSISTANCE REQUESTED',
          active: true,
          label: 'ORRU assistance requested',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          id: '214748',
          code: 'PERPETRATOR UNDER INFLUENCE OF DRUGS OR ALCOHOL',
          active: true,
          label: 'Perpetrator under influence of drugs or alcohol',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          id: '214749',
          code: 'THREAT OR ACTUAL SELF HARM',
          active: true,
          label: 'Threat or actual self harm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
        {
          id: '214750',
          code: 'VIOLENCE DIRECTED AGAINST STAFF',
          active: true,
          label: 'Violence directed against staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63186',
        },
      ],
    },
    '63186': {
      id: '63186',
      active: true,
      code: 'WHAT WAS THE DURATION OF THE INCIDENT',
      label: 'What was the duration of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '214751',
          code: '< 1 minute',
          active: true,
          label: '< 1 minute',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214752',
          code: '1 min to <5mins',
          active: true,
          label: '1 min to <5mins',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214753',
          code: '10 mins to <15mins',
          active: true,
          label: '10 mins to <15mins',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214754',
          code: '15 mins to <30mins',
          active: true,
          label: '15 mins to <30mins',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214755',
          code: '30 mins to <1 hour',
          active: true,
          label: '30 mins to <1 hour',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214756',
          code: '1 hour to <2 hours',
          active: true,
          label: '1 hour to <2 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214757',
          code: '2 hours to <3 hours',
          active: true,
          label: '2 hours to <3 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214758',
          code: '3 hours to <4 hours',
          active: true,
          label: '3 hours to <4 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214759',
          code: '4 hours to <5 hours',
          active: true,
          label: '4 hours to <5 hours',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214760',
          code: '5 hours plus',
          active: true,
          label: '5 hours plus',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63187',
        },
        {
          id: '214761',
          code: 'UNKNOWN - ENTER DETAILS',
          active: true,
          label: 'Unknown - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63187',
        },
      ],
    },
    '63187': {
      id: '63187',
      active: true,
      code: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'Describe how the incident was resolved',
      multipleAnswers: false,
      answers: [
        {
          id: '214762',
          code: 'COMPLIED WITH ORDER OR INSTRUCTION',
          active: true,
          label: 'Complied with order or instruction',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          id: '214763',
          code: 'NEGOTIATION',
          active: true,
          label: 'Negotiation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          id: '214764',
          code: 'INTERVENTION (LOCAL STAFF)',
          active: true,
          label: 'Intervention (local staff)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          id: '214765',
          code: 'INTERVENTION (ORRU STAFF)',
          active: true,
          label: 'Intervention (ORRU staff)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          id: '214766',
          code: 'INTERVENTION (OPERATION TORNADO)',
          active: true,
          label: 'Intervention (operation Tornado)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63188',
        },
        {
          id: '214767',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63188',
        },
      ],
    },
    '63188': {
      id: '63188',
      active: true,
      code: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      label: 'Was control and restraints employed?',
      multipleAnswers: false,
      answers: [
        {
          id: '214768',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63189',
        },
        {
          id: '214769',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63189',
        },
      ],
    },
    '63189': {
      id: '63189',
      active: true,
      code: 'WERE PRISON RESOURCES PRESENT',
      label: 'Were prison resources present?',
      multipleAnswers: true,
      answers: [
        {
          id: '214770',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          id: '214771',
          code: 'C & R ADVISOR',
          active: true,
          label: 'C & r advisor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          id: '214772',
          code: 'INCIDENT LIAISON OFFICER',
          active: true,
          label: 'Incident liaison officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          id: '214773',
          code: 'HEALTH CARE STAFF',
          active: true,
          label: 'Health care staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          id: '214774',
          code: 'WORKS SERVICES STAFF',
          active: true,
          label: 'Works services staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63190',
        },
        {
          id: '214775',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63190',
        },
      ],
    },
    '63190': {
      id: '63190',
      active: true,
      code: 'WAS SPECIALIST EQUIPMENT / RESOURCES USED?',
      label: 'Was specialist equipment / resources used?',
      multipleAnswers: true,
      answers: [
        {
          id: '214776',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          id: '214777',
          code: 'DOOR JACK',
          active: true,
          label: 'Door jack',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          id: '214778',
          code: 'EXTENDABLE BATONS',
          active: true,
          label: 'Extendable batons',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          id: '214779',
          code: 'NEGOTIATION ADVISER (INCLUDING HOSTAGE)',
          active: true,
          label: 'Negotiation adviser (including hostage)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          id: '214780',
          code: 'OPERATIONAL RESILIENCE AND RESPONSE UNIT (ORRU)',
          active: true,
          label: 'Operational resilience and response unit (ORRU)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          id: '214781',
          code: 'TORNADO',
          active: true,
          label: 'Tornado',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          id: '214782',
          code: 'WATER HOSES',
          active: true,
          label: 'Water hoses',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63191',
        },
        {
          id: '214783',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63191',
        },
      ],
    },
    '63191': {
      id: '63191',
      active: true,
      code: 'WERE EMERGENCY SERVICES PRESENT',
      label: 'Were emergency services present?',
      multipleAnswers: true,
      answers: [
        {
          id: '214784',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          id: '214785',
          code: 'POLICE',
          active: true,
          label: 'Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          id: '214786',
          code: 'FIRE',
          active: true,
          label: 'Fire',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          id: '214787',
          code: 'AMBULANCE',
          active: true,
          label: 'Ambulance',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63192',
        },
        {
          id: '214788',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63192',
        },
      ],
    },
    '63192': {
      id: '63192',
      active: true,
      code: 'WAS ANY EVACUATION NECESSARY',
      label: 'Was any evacuation necessary?',
      multipleAnswers: false,
      answers: [
        {
          id: '214789',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63193',
        },
        {
          id: '214790',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63193',
        },
      ],
    },
    '63193': {
      id: '63193',
      active: true,
      code: 'DESCRIBE THE INCIDENT AS EITHER ACTIVE OR PASSIVE',
      label: 'Describe the incident as either active or passive',
      multipleAnswers: false,
      answers: [
        {
          id: '214791',
          code: 'ACTIVE',
          active: true,
          label: 'Active',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63194',
        },
        {
          id: '214792',
          code: 'PASSIVE',
          active: true,
          label: 'Passive',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63194',
        },
      ],
    },
    '63194': {
      id: '63194',
      active: true,
      code: 'HOW MANY PRISONERS WERE INVOLVED',
      label: 'How many prisoners were involved?',
      multipleAnswers: false,
      answers: [
        {
          id: '214793',
          code: 'NUMBER - ENTER DETAILS',
          active: true,
          label: 'Number - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63195',
        },
      ],
    },
    '63195': {
      id: '63195',
      active: true,
      code: 'PERPETRATOR(S) TYPE',
      label: 'Perpetrator(s) type',
      multipleAnswers: true,
      answers: [
        {
          id: '214794',
          code: 'PRISONER - ENTER NUMBER OF',
          active: true,
          label: 'Prisoner - enter number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63196',
        },
        {
          id: '214795',
          code: 'VISITOR - ENTER NUMBER OF',
          active: true,
          label: 'Visitor - enter number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63196',
        },
        {
          id: '214796',
          code: 'OTHER - ENTER NUMBER OF',
          active: true,
          label: 'Other - enter number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63196',
        },
      ],
    },
    '63196': {
      id: '63196',
      active: true,
      code: 'HAVE THE RINGLEADERS BEEN IDENTIFIED',
      label: 'Have the ringleaders been identified?',
      multipleAnswers: false,
      answers: [
        {
          id: '214797',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63198',
        },
        {
          id: '214798',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63197',
        },
      ],
    },
    '63197': {
      id: '63197',
      active: true,
      code: 'HAVE THE RINGLEADERS BEEN ENTERED ON LINKED OFFENDER',
      label: 'Have the ringleaders been entered on linked offender?',
      multipleAnswers: false,
      answers: [
        {
          id: '214799',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63198',
        },
        {
          id: '214800',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63198',
        },
      ],
    },
    '63198': {
      id: '63198',
      active: true,
      code: 'WERE WEAPONS USED BY THE PERPETRATOR',
      label: 'Were weapons used by the perpetrator?',
      multipleAnswers: false,
      answers: [
        {
          id: '214801',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63199',
        },
        {
          id: '214802',
          code: 'YES - PLEASE LOG FIND INCIDENT IF WEAPON RECOVERED',
          active: true,
          label: 'Yes - please log find incident if weapon recovered',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63199',
        },
      ],
    },
    '63199': {
      id: '63199',
      active: true,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'Was damage caused to prison property?',
      multipleAnswers: false,
      answers: [
        {
          id: '214803',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63200',
        },
        {
          id: '214804',
          code: 'YES - PLEASE LOG DAMAGE INCIDENT',
          active: true,
          label: 'Yes - please log damage incident',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63200',
        },
      ],
    },
    '63200': {
      id: '63200',
      active: true,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'Were any injuries received during this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '214805',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214806',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63201',
        },
      ],
    },
    '63201': {
      id: '63201',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'Was a serious injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '214807',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214808',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63202',
        },
      ],
    },
    '63202': {
      id: '63202',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '214809',
          code: 'BITES',
          active: true,
          label: 'Bites',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214810',
          code: 'BLACK EYE',
          active: true,
          label: 'Black eye',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214811',
          code: 'BROKEN NOSE',
          active: true,
          label: 'Broken nose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214812',
          code: 'BROKEN TEETH',
          active: true,
          label: 'Broken teeth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214813',
          code: 'CRUSHING',
          active: true,
          label: 'Crushing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214814',
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'Cuts requiring sutures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214815',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'Extensive/multiple bruising',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214816',
          code: 'FRACTURE',
          active: true,
          label: 'Fracture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214817',
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'Gun shot wound',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214818',
          code: 'SCALD OR BURN',
          active: true,
          label: 'Scald or burn',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214819',
          code: 'STABBING',
          active: true,
          label: 'Stabbing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
        {
          id: '214820',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'Temporary/permanent blindness',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63203',
        },
      ],
    },
    '63203': {
      id: '63203',
      active: true,
      code: 'ENTER DESCIPTION OF PERSON(S) INJURED (SERIOUS)',
      label: 'Enter desciption of person(s) injured (serious)',
      multipleAnswers: true,
      answers: [
        {
          id: '214821',
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'Civilian grades',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214822',
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'External civilians',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214823',
          code: 'POLICE',
          active: true,
          label: 'Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214824',
          code: 'PRISONERS',
          active: true,
          label: 'Prisoners',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214825',
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'Operational staff - prison officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214826',
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'Operational staff - other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214827',
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'Non-operational staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214828',
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'Non-directly employed staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63204',
        },
        {
          id: '214829',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63204',
        },
      ],
    },
    '63204': {
      id: '63204',
      active: true,
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'Was a minor injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '214830',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214831',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63205',
        },
      ],
    },
    '63205': {
      id: '63205',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '214832',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'Grazes, scratches or abrasions',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          id: '214833',
          code: 'MINOR BRUISES',
          active: true,
          label: 'Minor bruises',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          id: '214834',
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'Superficial cuts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          id: '214835',
          code: 'SWELLINGS',
          active: true,
          label: 'Swellings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
        {
          id: '214836',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63206',
        },
      ],
    },
    '63206': {
      id: '63206',
      active: true,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED (MINOR)',
      label: 'Enter description of person(s) injured (minor)',
      multipleAnswers: true,
      answers: [
        {
          id: '214837',
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'Civilian grades',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214838',
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'External civilians',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214839',
          code: 'POLICE',
          active: true,
          label: 'Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214840',
          code: 'PRISONERS',
          active: true,
          label: 'Prisoners',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214841',
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'Operational staff - prison officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214842',
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'Operational staff - other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214843',
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'Non-operational staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214844',
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'Non-directly employed staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214845',
          code: 'OTHER - ENTER DETAILS',
          active: false,
          label: 'Other - enter details',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63207',
        },
        {
          id: '214846',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63207',
        },
      ],
    },
    '63207': {
      id: '63207',
      active: true,
      code: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS IN-PATIENT',
      label: 'Did injuries result in detention in outside hospital as in-patient?',
      multipleAnswers: false,
      answers: [
        {
          id: '214847',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214848',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63208',
        },
      ],
    },
    '63208': {
      id: '63208',
      active: true,
      code: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'Who was detained in outside hospital?',
      multipleAnswers: true,
      answers: [
        {
          id: '214849',
          code: 'CIVILIAN GRADES',
          active: true,
          label: 'Civilian grades',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214850',
          code: 'EXTERNAL CIVILIANS',
          active: true,
          label: 'External civilians',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214851',
          code: 'POLICE',
          active: true,
          label: 'Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214852',
          code: 'PRISONERS',
          active: true,
          label: 'Prisoners',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214853',
          code: 'OPERATIONAL STAFF - PRISON OFFICER',
          active: true,
          label: 'Operational staff - prison officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214854',
          code: 'OPERATIONAL STAFF - OTHER',
          active: true,
          label: 'Operational staff - other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214855',
          code: 'NON-OPERATIONAL STAFF',
          active: true,
          label: 'Non-operational staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214856',
          code: 'NON-DIRECTLY EMPLOYED STAFF',
          active: true,
          label: 'Non-directly employed staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63209',
        },
        {
          id: '214857',
          code: 'OTHER - ENTER DETAILS',
          active: true,
          label: 'Other - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63209',
        },
      ],
    },
    '63209': {
      id: '63209',
      active: true,
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'Are there any staff now off duty as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '214858',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63210',
        },
        {
          id: '214859',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63210',
        },
      ],
    },
    '63210': {
      id: '63210',
      active: true,
      code: 'DID INCIDENT HAPPENT AT HEIGHT (FULLY OR PARTIALLY)',
      label: 'Did incident happent at height (fully or partially)?',
      multipleAnswers: false,
      answers: [
        {
          id: '214860',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          id: '214861',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63211',
        },
      ],
    },
    '63211': {
      id: '63211',
      active: true,
      code: 'DESCRIBE METHOD OF GAINING ACCESS TO AREA AT HEIGHT',
      label: 'Describe method of gaining access to area at height',
      multipleAnswers: true,
      answers: [
        {
          id: '214862',
          code: 'CONTRACTORS EQUIPMENT',
          active: true,
          label: 'Contractors equipment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214863',
          code: 'EXTERNAL ACCESS: FENCING',
          active: true,
          label: 'External access: fencing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214864',
          code: 'EXTERNAL ACCESS: ROOF',
          active: true,
          label: 'External access: roof',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214865',
          code: 'EXTERNAL ACCESS: TREE',
          active: true,
          label: 'External access: tree',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214866',
          code: 'INTERNAL ACCESS: LANDINGS/RAILINGS',
          active: true,
          label: 'Internal access: landings/railings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214867',
          code: 'INTERNAL ACCESS: NETTING',
          active: true,
          label: 'Internal access: netting',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214868',
          code: 'INTERNAL ACCESS: WINDOW/GATE BARS',
          active: true,
          label: 'Internal access: window/gate bars',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214869',
          code: 'OTHER: INTERNAL - ENTER DETAILS',
          active: true,
          label: 'Other: internal - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63212',
        },
        {
          id: '214870',
          code: 'OTHER: EXTERNAL - ENTER DETAILS',
          active: true,
          label: 'Other: external - enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63212',
        },
      ],
    },
    '63212': {
      id: '63212',
      active: true,
      code: 'WHAT HEIGHT DID THE INCIDENT TAKE PLACE',
      label: 'What height did the incident take place?',
      multipleAnswers: true,
      answers: [
        {
          id: '214871',
          code: 'BETWEEN 3 FEET AND <1ST FLOOR',
          active: true,
          label: 'Between 3 feet and <1st floor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          id: '214872',
          code: '1ST FLOOR',
          active: true,
          label: '1st floor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          id: '214873',
          code: '2ND FLOOR',
          active: true,
          label: '2nd floor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
        {
          id: '214874',
          code: '3RD FLOOR OR HIGHER',
          active: true,
          label: '3rd floor or higher',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63213',
        },
      ],
    },
    '63213': {
      id: '63213',
      active: true,
      code: 'WAS A BARRICADE USED',
      label: 'Was a barricade used?',
      multipleAnswers: false,
      answers: [
        {
          id: '214875',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63214',
        },
        {
          id: '214876',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63214',
        },
      ],
    },
    '63214': {
      id: '63214',
      active: true,
      code: 'DID INCIDENT INVOLVE HOSTAGE(S)',
      label: 'Did incident involve hostage(s)?',
      multipleAnswers: false,
      answers: [
        {
          id: '214877',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '214878',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63215',
        },
      ],
    },
    '63215': {
      id: '63215',
      active: true,
      code: 'DESCRIBE STATUS OF HOSTAGES',
      label: 'Describe status of hostages',
      multipleAnswers: true,
      answers: [
        {
          id: '214879',
          code: 'CIVILIAN STAFF - STATE NUMBER OF',
          active: true,
          label: 'Civilian staff - state number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          id: '214880',
          code: 'OFFICER - STATE NUMBER OF',
          active: true,
          label: 'Officer - state number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          id: '214881',
          code: 'PRISONER - STATE NUMBER OF',
          active: true,
          label: 'Prisoner - state number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          id: '214882',
          code: 'STAFF - STATE NUMBER OF',
          active: true,
          label: 'Staff - state number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
        {
          id: '214883',
          code: 'OTHER - STATE NUMBER OF',
          active: true,
          label: 'Other - state number of',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '63216',
        },
      ],
    },
    '63216': {
      id: '63216',
      active: true,
      code: 'WAS A HOSTAGE PART OF THE BARRICADE',
      label: 'Was a hostage part of the barricade?',
      multipleAnswers: false,
      answers: [
        {
          id: '214884',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63217',
        },
        {
          id: '214885',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63217',
        },
      ],
    },
    '63217': {
      id: '63217',
      active: true,
      code: 'WAS PHYSICAL VIOLENCE USED TOWARDS HOSTAGE',
      label: 'Was physical violence used towards hostage?',
      multipleAnswers: false,
      answers: [
        {
          id: '214886',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63218',
        },
        {
          id: '214887',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63218',
        },
      ],
    },
    '63218': {
      id: '63218',
      active: true,
      code: 'WAS THE HOSTAGE PHYSICALLY RESTRAINED BY THE PERPETRATOR',
      label: 'Was the hostage physically restrained by the perpetrator?',
      multipleAnswers: false,
      answers: [
        {
          id: '214888',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63219',
        },
        {
          id: '214889',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63219',
        },
      ],
    },
    '63219': {
      id: '63219',
      active: true,
      code: 'WAS THERE EVIDENCE OF THE STOCKHOLM SYNDROME',
      label: 'Was there evidence of the Stockholm syndrome?',
      multipleAnswers: false,
      answers: [
        {
          id: '214890',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63220',
        },
        {
          id: '214891',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '63220',
        },
      ],
    },
    '63220': {
      id: '63220',
      active: true,
      code: 'WAS THERE EVIDENCE OF COLLUSION',
      label: 'Was there evidence of collusion?',
      multipleAnswers: false,
      answers: [
        {
          id: '214892',
          code: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '214893',
          code: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSAILANT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'FIGHTER',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'HOSTAGE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_ASSAILANT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'VICTIM',
      onlyOneAllowed: false,
      active: true,
    },
  ],
  requiresPrisoners: true,
}

export default DISORDER_2
