// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-12-02T17:35:23.425Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const ESCAPE_FROM_ESCORT: IncidentTypeConfiguration = {
  incidentType: 'ESCAPE_FROM_ESCORT',
  active: true,
  startingQuestionId: '44975',
  questions: {
    '44134': {
      id: '44134',
      active: true,
      code: 'WERE ANY INJURIES SUSTAINED BY PRISONERS',
      label: 'Were any injuries sustained by prisoners?',
      multipleAnswers: false,
      answers: [
        {
          id: '178932',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45118',
        },
        {
          id: '178933',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44908',
        },
      ],
    },
    '44143': {
      id: '44143',
      active: true,
      code: 'WHAT WERE THE CATEGORIES OF THE PRISONERS UNDER ESCORT',
      label: 'What were the categories of the prisoners under escort?',
      multipleAnswers: true,
      answers: [
        {
          id: '178974',
          code: 'CATEGORY A',
          active: true,
          label: 'CATEGORY A',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178975',
          code: 'CATEGORY B',
          active: true,
          label: 'CATEGORY B',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178976',
          code: 'CATEGORY C',
          active: true,
          label: 'CATEGORY C',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178973',
          code: 'CATEGORISED YO',
          active: true,
          label: 'CATEGORISED YO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178977',
          code: 'CATEGORY D',
          active: true,
          label: 'CATEGORY D',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178980',
          code: 'UNCATEGORISED YO',
          active: true,
          label: 'UNCATEGORISED YO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178972',
          code: 'CATEGORISED FEMALE',
          active: true,
          label: 'CATEGORISED FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178979',
          code: 'UNCATEGORISED FEMALE',
          active: true,
          label: 'UNCATEGORISED FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
        {
          id: '178978',
          code: 'UNCATEGORISED ADULT MALE',
          active: true,
          label: 'UNCATEGORISED ADULT MALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45156',
        },
      ],
    },
    '44164': {
      id: '44164',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '179039',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44571',
        },
        {
          id: '179040',
          code: 'MINOR BRUISES',
          active: true,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44571',
        },
        {
          id: '179043',
          code: 'SWELLINGS',
          active: true,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44571',
        },
        {
          id: '179042',
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44571',
        },
        {
          id: '179041',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44571',
        },
      ],
    },
    '44188': {
      id: '44188',
      active: true,
      code: 'WHAT TYPE OF VEHICLE WAS IT',
      label: 'What type of vehicle was it?',
      multipleAnswers: false,
      answers: [
        {
          id: '179106',
          code: 'COACH',
          active: true,
          label: 'COACH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '179107',
          code: 'MINIBUS',
          active: true,
          label: 'MINIBUS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '179110',
          code: 'TAXI',
          active: true,
          label: 'TAXI',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '179105',
          code: 'CELLULAR VEHICLE',
          active: true,
          label: 'CELLULAR VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '179109',
          code: 'SECURE TRANSIT',
          active: true,
          label: 'SECURE TRANSIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '179108',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44448',
        },
      ],
    },
    '44211': {
      id: '44211',
      active: true,
      code: 'WAS THE RESTRAINT OVERCOME AT THE POINT OF ESCAPE',
      label: 'Was the restraint overcome at the point of escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '179195',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44859',
        },
        {
          id: '179196',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
      ],
    },
    '44215': {
      id: '44215',
      active: true,
      code: 'WERE THE ROUNDS DISCHARGED',
      label: 'Were the rounds discharged?',
      multipleAnswers: false,
      answers: [
        {
          id: '179203',
          code: 'LIVE',
          active: true,
          label: 'LIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44994',
        },
        {
          id: '179202',
          code: 'BLANK',
          active: true,
          label: 'BLANK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44994',
        },
        {
          id: '179204',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44994',
        },
      ],
    },
    '44246': {
      id: '44246',
      active: true,
      code: 'WAS THE FIREARM',
      label: 'Was the firearm?',
      multipleAnswers: false,
      answers: [
        {
          id: '179314',
          code: 'REAL',
          active: true,
          label: 'REAL',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44998',
        },
        {
          id: '179315',
          code: 'REPLICA',
          active: true,
          label: 'REPLICA',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44998',
        },
        {
          id: '179313',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44998',
        },
      ],
    },
    '44281': {
      id: '44281',
      active: true,
      code: 'WAS THE OTHER PRISONER',
      label: 'Was the other prisoner?',
      multipleAnswers: false,
      answers: [
        {
          id: '179397',
          code: 'A CO-DEFENDANT',
          active: true,
          label: 'A CO-DEFENDANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44211',
        },
        {
          id: '179399',
          code: 'A RELATIVE',
          active: true,
          label: 'A RELATIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44211',
        },
        {
          id: '179398',
          code: 'A KNOWN ASSOCIATE',
          active: true,
          label: 'A KNOWN ASSOCIATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44211',
        },
        {
          id: '179400',
          code: 'AN E LIST PRISONER',
          active: true,
          label: 'AN E LIST PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44211',
        },
        {
          id: '179401',
          code: 'NONE OF THE ABOVE',
          active: true,
          label: 'NONE OF THE ABOVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44211',
        },
      ],
    },
    '44298': {
      id: '44298',
      active: true,
      code: 'HAS THE PRISONER BEEN CHARGED WITH A FURTHER OFFENCE',
      label: 'Has the prisoner been charged with a further offence?',
      multipleAnswers: false,
      answers: [
        {
          id: '179447',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44970',
        },
        {
          id: '179448',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44696',
        },
      ],
    },
    '44360': {
      id: '44360',
      active: true,
      code: 'THE INCIDENT IS SUBJECT TO',
      label: 'The incident is subject to',
      multipleAnswers: true,
      answers: [
        {
          id: '179709',
          code: 'INVESTIGATION BY POLICE',
          active: true,
          label: 'INVESTIGATION BY POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45066',
        },
        {
          id: '179710',
          code: 'INVESTIGATION INTERNALLY',
          active: true,
          label: 'INVESTIGATION INTERNALLY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45066',
        },
        {
          id: '179708',
          code: "GOVERNOR'S ADJUDICATION",
          active: true,
          label: "GOVERNOR'S ADJUDICATION",
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45066',
        },
        {
          id: '179711',
          code: 'NO INVESTIGATION',
          active: true,
          label: 'NO INVESTIGATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45066',
        },
      ],
    },
    '44409': {
      id: '44409',
      active: true,
      code: 'WAS THE ESCORT FOR CHILD BIRTH OR PRE/POST NATAL TREATMENT',
      label: 'Was the escort for child birth or pre/post natal treatment?',
      multipleAnswers: false,
      answers: [
        {
          id: '179878',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '179877',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45112',
        },
      ],
    },
    '44419': {
      id: '44419',
      active: true,
      code: 'WAS THE PRISONER RESTRAINED AT THE POINT OF ESCAPE',
      label: 'Was the prisoner restrained at the point of escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '179895',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44966',
        },
        {
          id: '179896',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44727',
        },
      ],
    },
    '44426': {
      id: '44426',
      active: true,
      code: 'ESTIMATED COST OF DAMAGE',
      label: 'Estimated cost of damage',
      multipleAnswers: false,
      answers: [
        {
          id: '179911',
          code: 'ENTER AMOUNT IN POUND STERLING',
          active: true,
          label: 'ENTER AMOUNT IN POUND STERLING',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44443': {
      id: '44443',
      active: true,
      code: 'WAS OUTSIDE ASSISTANCE INVOLVED IN THE ESCAPE',
      label: 'Was outside assistance involved in the escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '179959',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45136',
        },
        {
          id: '179958',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45136',
        },
      ],
    },
    '44448': {
      id: '44448',
      active: true,
      code: 'NUMBER OF STAFF ON ESCORT',
      label: 'Number of staff on escort',
      multipleAnswers: true,
      answers: [
        {
          id: '179980',
          code: 'MALE',
          active: true,
          label: 'MALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44757',
        },
        {
          id: '179979',
          code: 'FEMALE',
          active: true,
          label: 'FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44757',
        },
      ],
    },
    '44490': {
      id: '44490',
      active: true,
      code: 'FROM WHAT ESCORT TYPE DID THE ESCAPE OCCUR',
      label: 'From what escort type did the escape occur?',
      multipleAnswers: false,
      answers: [
        {
          id: '180172',
          code: 'HOSPITAL OUTPATIENT',
          active: true,
          label: 'HOSPITAL OUTPATIENT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44409',
        },
        {
          id: '180171',
          code: 'HOSPITAL INPATIENT',
          active: true,
          label: 'HOSPITAL INPATIENT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44409',
        },
        {
          id: '180178',
          code: 'INTER PRISON TRANSFER',
          active: true,
          label: 'INTER PRISON TRANSFER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180179',
          code: 'MAGISTRATES COURT',
          active: true,
          label: 'MAGISTRATES COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180174',
          code: 'CROWN COURT',
          active: true,
          label: 'CROWN COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180173',
          code: 'COUNTY COURT',
          active: true,
          label: 'COUNTY COURT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180175',
          code: 'FUNERAL',
          active: true,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180181',
          code: 'WEDDING',
          active: true,
          label: 'WEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180176',
          code: 'HOME VISIT',
          active: true,
          label: 'HOME VISIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180177',
          code: 'HOSP VISIT (DYING RELATIVE)',
          active: true,
          label: 'HOSP VISIT (DYING RELATIVE)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45112',
        },
        {
          id: '180180',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45112',
        },
      ],
    },
    '44507': {
      id: '44507',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE WEAPONS USED',
      label: 'What was the source of the weapons used?',
      multipleAnswers: false,
      answers: [
        {
          id: '180246',
          code: 'SECRETED ON PRISONER',
          active: true,
          label: 'SECRETED ON PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45151',
        },
        {
          id: '180244',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45151',
        },
        {
          id: '180243',
          code: 'BROUGHT BY OUTSIDE ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45151',
        },
        {
          id: '180245',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45151',
        },
      ],
    },
    '44519': {
      id: '44519',
      active: true,
      code: 'WAS A MINOR INJURY SUSTAINED BY A PRISONER',
      label: 'Was a minor injury sustained by a prisoner?',
      multipleAnswers: false,
      answers: [
        {
          id: '180275',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44164',
        },
        {
          id: '180276',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44571',
        },
      ],
    },
    '44521': {
      id: '44521',
      active: true,
      code: 'WAS A CHEMICAL INCAPACITANT SPRAY USED DURING THE ESCAPE',
      label: 'Was a chemical incapacitant spray used during the escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '180280',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44904',
        },
        {
          id: '180281',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44729',
        },
      ],
    },
    '44538': {
      id: '44538',
      active: true,
      code: 'WHERE WERE THE INJURED STAFF TREATED',
      label: 'Where were the injured staff treated?',
      multipleAnswers: false,
      answers: [
        {
          id: '180401',
          code: 'PRISON HEALTH CARE CENTRE',
          active: true,
          label: 'PRISON HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44134',
        },
        {
          id: '180399',
          code: 'OUTSIDE HOSPITAL',
          active: true,
          label: 'OUTSIDE HOSPITAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44134',
        },
        {
          id: '180400',
          code: 'OWN GP',
          active: true,
          label: 'OWN GP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44134',
        },
      ],
    },
    '44539': {
      id: '44539',
      active: true,
      code: 'WERE MINOR INJURIES SUSTAINED BY STAFF',
      label: 'Were minor injuries sustained by staff?',
      multipleAnswers: false,
      answers: [
        {
          id: '180402',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45154',
        },
        {
          id: '180403',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45024',
        },
      ],
    },
    '44571': {
      id: '44571',
      active: true,
      code: 'DID ANY PRISONER REQUIRE MEDICAL TREATMENT FOR INJURIES',
      label: 'Did any prisoner require medical treatment for injuries?',
      multipleAnswers: false,
      answers: [
        {
          id: '180489',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44706',
        },
        {
          id: '180490',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44908',
        },
      ],
    },
    '44581': {
      id: '44581',
      active: true,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'Was damage caused to prison property?',
      multipleAnswers: false,
      answers: [
        {
          id: '180522',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44650',
        },
        {
          id: '180523',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44605': {
      id: '44605',
      active: true,
      code: 'WHO USED THE OTHER WEAPONS',
      label: 'Who used the other weapons?',
      multipleAnswers: true,
      answers: [
        {
          id: '180615',
          code: 'PRISONER WHO ESCAPED',
          active: true,
          label: 'PRISONER WHO ESCAPED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44507',
        },
        {
          id: '180613',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44507',
        },
        {
          id: '180614',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44507',
        },
      ],
    },
    '44644': {
      id: '44644',
      active: true,
      code: 'HAS THE KEY BEEN RECOVERED',
      label: 'Has the key been recovered?',
      multipleAnswers: false,
      answers: [
        {
          id: '180736',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '180735',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
      ],
    },
    '44650': {
      id: '44650',
      active: true,
      code: 'DESCRIBE THE DAMAGE',
      label: 'Describe the damage',
      multipleAnswers: false,
      answers: [
        {
          id: '180749',
          code: 'MINOR',
          active: true,
          label: 'MINOR',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44426',
        },
        {
          id: '180750',
          code: 'SERIOUS',
          active: true,
          label: 'SERIOUS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44426',
        },
        {
          id: '180748',
          code: 'EXTENSIVE',
          active: true,
          label: 'EXTENSIVE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44426',
        },
      ],
    },
    '44673': {
      id: '44673',
      active: true,
      code: 'WERE INSERTS USED',
      label: 'Were inserts used?',
      multipleAnswers: false,
      answers: [
        {
          id: '180832',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '180831',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
      ],
    },
    '44675': {
      id: '44675',
      active: true,
      code: 'WAS THE KEY USED',
      label: 'Was the key used?',
      multipleAnswers: false,
      answers: [
        {
          id: '180837',
          code: 'REAL',
          active: true,
          label: 'REAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44644',
        },
        {
          id: '180835',
          code: 'IMPROVISED',
          active: true,
          label: 'IMPROVISED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44644',
        },
        {
          id: '180836',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44644',
        },
      ],
    },
    '44696': {
      id: '44696',
      active: true,
      code: 'WAS THIS A KPI ESCAPE',
      label: 'Was this a KPI escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '180913',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44581',
        },
        {
          id: '180912',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44581',
        },
      ],
    },
    '44706': {
      id: '44706',
      active: true,
      code: 'WHERE WERE THE INJURED PRISONERS TREATED',
      label: 'Where were the injured prisoners treated?',
      multipleAnswers: false,
      answers: [
        {
          id: '180970',
          code: 'PRISON HEALTH CARE CENTRE',
          active: true,
          label: 'PRISON HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44908',
        },
        {
          id: '180969',
          code: 'OUTSIDE HOSPITAL',
          active: true,
          label: 'OUTSIDE HOSPITAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44908',
        },
      ],
    },
    '44715': {
      id: '44715',
      active: true,
      code: 'WHO USED THE SPRAY',
      label: 'Who used the spray?',
      multipleAnswers: true,
      answers: [
        {
          id: '180990',
          code: 'PRISONER WHO ESCAPED',
          active: true,
          label: 'PRISONER WHO ESCAPED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44838',
        },
        {
          id: '180988',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44838',
        },
        {
          id: '180989',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44838',
        },
      ],
    },
    '44727': {
      id: '44727',
      active: true,
      code: 'WHY WAS A RESTRAINT NOT APPLIED AT THE POINT OF ESCAPE',
      label: 'Why was a restraint not applied at the point of escape?',
      multipleAnswers: true,
      answers: [
        {
          id: '181039',
          code: 'GOVERNORS INSTRUCTION',
          active: true,
          label: 'GOVERNORS INSTRUCTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181046',
          code: 'PREVENTED BY DISABILITY',
          active: true,
          label: 'PREVENTED BY DISABILITY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181047',
          code: 'PREVENTED BY INJURY',
          active: true,
          label: 'PREVENTED BY INJURY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181043',
          code: 'MEDICAL TREATMENT/REQUEST',
          active: true,
          label: 'MEDICAL TREATMENT/REQUEST',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181041',
          code: 'IN COURT ROOM',
          active: true,
          label: 'IN COURT ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181042',
          code: 'LOCATED IN SECURE AREA',
          active: true,
          label: 'LOCATED IN SECURE AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181040',
          code: 'IN CELL OF CELLULAR VEHICLE',
          active: true,
          label: 'IN CELL OF CELLULAR VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181048',
          code: 'TRANSFER TO MENTAL HOSPITAL',
          active: true,
          label: 'TRANSFER TO MENTAL HOSPITAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181037',
          code: 'DURING MARRIAGE CEREMONY',
          active: true,
          label: 'DURING MARRIAGE CEREMONY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181044',
          code: 'NONE AVAILABLE',
          active: true,
          label: 'NONE AVAILABLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181038',
          code: 'FAILURE TO USE',
          active: true,
          label: 'FAILURE TO USE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181045',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44443',
        },
      ],
    },
    '44729': {
      id: '44729',
      active: true,
      code: 'WAS A KNIFE OR BLADE USED DURING THE ESCAPE',
      label: 'Was a knife or blade used during the escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '181051',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45068',
        },
        {
          id: '181052',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44845',
        },
      ],
    },
    '44754': {
      id: '44754',
      active: true,
      code: 'WHO USED THE KNIFE OR BLADE',
      label: 'Who used the knife or blade?',
      multipleAnswers: true,
      answers: [
        {
          id: '181114',
          code: 'PRISONER WHO ESCAPED',
          active: true,
          label: 'PRISONER WHO ESCAPED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45080',
        },
        {
          id: '181112',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45080',
        },
        {
          id: '181113',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45080',
        },
      ],
    },
    '44757': {
      id: '44757',
      active: true,
      code: 'NUMBER OF PRISONERS ON ESCORT',
      label: 'Number of prisoners on escort',
      multipleAnswers: true,
      answers: [
        {
          id: '181120',
          code: 'MALE',
          active: true,
          label: 'MALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44143',
        },
        {
          id: '181119',
          code: 'FEMALE',
          active: true,
          label: 'FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44143',
        },
      ],
    },
    '44828': {
      id: '44828',
      active: true,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181322',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45089',
        },
        {
          id: '181321',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45089',
        },
      ],
    },
    '44838': {
      id: '44838',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE SPRAY',
      label: 'What was the source of the spray?',
      multipleAnswers: false,
      answers: [
        {
          id: '181345',
          code: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'SECRETED ON THE PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44729',
        },
        {
          id: '181343',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44729',
        },
        {
          id: '181342',
          code: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44729',
        },
        {
          id: '181344',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44729',
        },
      ],
    },
    '44845': {
      id: '44845',
      active: true,
      code: 'WERE ANY OTHER WEAPONS USED DURING THE ESCAPE',
      label: 'Were any other weapons used during the escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '181372',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44882',
        },
        {
          id: '181373',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45151',
        },
      ],
    },
    '44850': {
      id: '44850',
      active: true,
      code: 'PRIOR TO PRIVATE SECTOR INVOLVEMENT WOULD THE ESCORT HAVE BEEN',
      label: 'Prior to private sector involvement would the escort have been',
      multipleAnswers: false,
      answers: [
        {
          id: '181382',
          code: 'PRISON SERVICE',
          active: true,
          label: 'PRISON SERVICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44490',
        },
        {
          id: '181381',
          code: 'POLICE',
          active: true,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44490',
        },
      ],
    },
    '44859': {
      id: '44859',
      active: true,
      code: 'HOW WAS THE RESTRAINT OVERCOME AT THE POINT OF ESCAPE',
      label: 'How was the restraint overcome at the point of escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '181430',
          code: 'PRISONER USED KEY',
          active: true,
          label: 'PRISONER USED KEY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44675',
        },
        {
          id: '181431',
          code: 'SLIPPED RESTRAINT',
          active: true,
          label: 'SLIPPED RESTRAINT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44673',
        },
        {
          id: '181435',
          code: 'PICKED LOCK',
          active: true,
          label: 'PICKED LOCK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181436',
          code: 'STAFF UNLOCKED UNDER THREAT',
          active: true,
          label: 'STAFF UNLOCKED UNDER THREAT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181432',
          code: 'IMPROPER APPLICATION',
          active: true,
          label: 'IMPROPER APPLICATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181434',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44443',
        },
        {
          id: '181433',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44443',
        },
      ],
    },
    '44882': {
      id: '44882',
      active: true,
      code: 'WHAT OTHER WEAPONS WERE USED',
      label: 'What other weapons were used?',
      multipleAnswers: true,
      answers: [
        {
          id: '181526',
          code: 'OTHER SHARP INSTRUMENT',
          active: true,
          label: 'OTHER SHARP INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181520',
          code: 'BLUNT INSTRUMENT',
          active: true,
          label: 'BLUNT INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181524',
          code: 'LIGATURE',
          active: true,
          label: 'LIGATURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181521',
          code: 'DANGEROUS LIQUID',
          active: true,
          label: 'DANGEROUS LIQUID',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181522',
          code: 'EXCRETA/URINE',
          active: true,
          label: 'EXCRETA/URINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181527',
          code: 'SPITTING',
          active: true,
          label: 'SPITTING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181523',
          code: 'FOOD',
          active: true,
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181529',
          code: 'THROWN FURNITURE',
          active: true,
          label: 'THROWN FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181528',
          code: 'THROWN EQUIPMENT',
          active: true,
          label: 'THROWN EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44605',
        },
        {
          id: '181525',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44605',
        },
      ],
    },
    '44904': {
      id: '44904',
      active: true,
      code: 'DESCRIBE THE TYPE OF SPRAY',
      label: 'Describe the type of spray',
      multipleAnswers: true,
      answers: [
        {
          id: '181588',
          code: 'C.N (CHLORACETOPHEONE)',
          active: true,
          label: 'C.N (CHLORACETOPHEONE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44715',
        },
        {
          id: '181589',
          code: 'C.S (ORTHO..NITRILE)',
          active: true,
          label: 'C.S (ORTHO..NITRILE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44715',
        },
        {
          id: '181591',
          code: 'O.C (MACE/PEPPER)',
          active: true,
          label: 'O.C (MACE/PEPPER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44715',
        },
        {
          id: '181592',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44715',
        },
        {
          id: '181590',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44715',
        },
      ],
    },
    '44908': {
      id: '44908',
      active: true,
      code: 'HAS PRISONER BEEN RECAPTURED',
      label: 'Has prisoner been recaptured?',
      multipleAnswers: false,
      answers: [
        {
          id: '181611',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45025',
        },
        {
          id: '181612',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44696',
        },
      ],
    },
    '44930': {
      id: '44930',
      active: true,
      code: 'TO WHOM WAS THE PRISONER HANDCUFFED',
      label: 'To whom was the prisoner handcuffed',
      multipleAnswers: false,
      answers: [
        {
          id: '181724',
          code: 'OFFICER',
          active: true,
          label: 'OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44859',
        },
        {
          id: '181723',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44281',
        },
      ],
    },
    '44966': {
      id: '44966',
      active: true,
      code: 'WHAT RESTRAINT WAS BEING USED AT THE POINT OF ESCAPE',
      label: 'What restraint was being used at the point of escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '181837',
          code: 'HANDCUFFS',
          active: true,
          label: 'HANDCUFFS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45149',
        },
        {
          id: '181839',
          code: 'ESCORT CHAIN',
          active: true,
          label: 'ESCORT CHAIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44211',
        },
        {
          id: '181838',
          code: 'CLOSETING CHAIN',
          active: true,
          label: 'CLOSETING CHAIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44211',
        },
        {
          id: '181840',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44211',
        },
      ],
    },
    '44970': {
      id: '44970',
      active: true,
      code: 'WITH WHAT OFFENCE HAS THE PRISONER BEEN CHARGED',
      label: 'With what offence has the prisoner been charged?',
      multipleAnswers: true,
      answers: [
        {
          id: '181856',
          code: 'MURDER/ATTEMPTED MURDER',
          active: true,
          label: 'MURDER/ATTEMPTED MURDER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181855',
          code: 'MANSLAUGHTER',
          active: true,
          label: 'MANSLAUGHTER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181852',
          code: 'ASSAULT',
          active: true,
          label: 'ASSAULT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181860',
          code: 'RAPE/ATTEMPTED RAPE',
          active: true,
          label: 'RAPE/ATTEMPTED RAPE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181858',
          code: 'OTHER SEXUAL OFFENCE',
          active: true,
          label: 'OTHER SEXUAL OFFENCE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181862',
          code: 'THEFT',
          active: true,
          label: 'THEFT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181861',
          code: 'ROBBERY',
          active: true,
          label: 'ROBBERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181854',
          code: 'FIREARM OFFENCE',
          active: true,
          label: 'FIREARM OFFENCE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181853',
          code: 'DRUG OFFENCE',
          active: true,
          label: 'DRUG OFFENCE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181863',
          code: 'VEHICLE CRIME',
          active: true,
          label: 'VEHICLE CRIME',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181859',
          code: 'PUBLIC ORDER OFFENCE',
          active: true,
          label: 'PUBLIC ORDER OFFENCE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45145',
        },
        {
          id: '181857',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45145',
        },
      ],
    },
    '44975': {
      id: '44975',
      active: true,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181891',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44360',
        },
        {
          id: '181890',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44360',
        },
      ],
    },
    '44994': {
      id: '44994',
      active: true,
      code: 'WHO USED THE FIREARM',
      label: 'Who used the firearm?',
      multipleAnswers: true,
      answers: [
        {
          id: '181944',
          code: 'PRISONER WHO ESCAPED',
          active: true,
          label: 'PRISONER WHO ESCAPED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45104',
        },
        {
          id: '181942',
          code: 'OTHER PRISONER',
          active: true,
          label: 'OTHER PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45104',
        },
        {
          id: '181943',
          code: 'OUTSIDE ACCOMPLICE',
          active: true,
          label: 'OUTSIDE ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45104',
        },
      ],
    },
    '44998': {
      id: '44998',
      active: true,
      code: 'WAS THE FIREARM DISCHARGED',
      label: 'Was the firearm discharged?',
      multipleAnswers: false,
      answers: [
        {
          id: '181953',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44215',
        },
        {
          id: '181954',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44994',
        },
      ],
    },
    '45024': {
      id: '45024',
      active: true,
      code: 'DID ANY STAFF REQUIRE MEDICAL TREATMENT FOR INJURY',
      label: 'Did any staff require medical treatment for injury?',
      multipleAnswers: false,
      answers: [
        {
          id: '182034',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44538',
        },
        {
          id: '182035',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44134',
        },
      ],
    },
    '45025': {
      id: '45025',
      active: true,
      code: 'HOW WAS THE PRISONER RECAPTURED',
      label: 'How was the prisoner recaptured?',
      multipleAnswers: false,
      answers: [
        {
          id: '182037',
          code: 'POLICE ARREST',
          active: true,
          label: 'POLICE ARREST',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44298',
        },
        {
          id: '182038',
          code: 'PRISON STAFF ARREST',
          active: true,
          label: 'PRISON STAFF ARREST',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44298',
        },
        {
          id: '182039',
          code: 'SURRENDER',
          active: true,
          label: 'SURRENDER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44298',
        },
        {
          id: '182036',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44298',
        },
      ],
    },
    '45030': {
      id: '45030',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '182057',
          code: 'FRACTURE',
          active: true,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182059',
          code: 'SCALD OR BURN',
          active: true,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182060',
          code: 'STABBING',
          active: true,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182054',
          code: 'CRUSHING',
          active: true,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182056',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182051',
          code: 'BLACK EYE',
          active: true,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182052',
          code: 'BROKEN NOSE',
          active: true,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182053',
          code: 'BROKEN TEETH',
          active: true,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182055',
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182050',
          code: 'BITES',
          active: true,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182058',
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
        {
          id: '182061',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
      ],
    },
    '45035': {
      id: '45035',
      active: true,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '182094',
          code: 'FRACTURE',
          active: true,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182096',
          code: 'SCALD OR BURN',
          active: true,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182097',
          code: 'STABBING',
          active: true,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182091',
          code: 'CRUSHING',
          active: true,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182093',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: true,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182088',
          code: 'BLACK EYE',
          active: true,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182089',
          code: 'BROKEN NOSE',
          active: true,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182090',
          code: 'BROKEN TEETH',
          active: true,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182092',
          code: 'CUTS REQUIRING SUTURES',
          active: true,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182087',
          code: 'BITES',
          active: true,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182095',
          code: 'GUN SHOT WOUND',
          active: true,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
        {
          id: '182098',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: true,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
      ],
    },
    '45066': {
      id: '45066',
      active: true,
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          id: '182248',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44828',
        },
        {
          id: '182247',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44828',
        },
      ],
    },
    '45068': {
      id: '45068',
      active: true,
      code: 'WAS THE KNIFE OR BLADE USED PURPOSE MADE OR IMPROVISED',
      label: 'Was the knife or blade used purpose made or improvised?',
      multipleAnswers: false,
      answers: [
        {
          id: '182253',
          code: 'PURPOSE MADE',
          active: true,
          label: 'PURPOSE MADE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44754',
        },
        {
          id: '182251',
          code: 'IMPROVISED',
          active: true,
          label: 'IMPROVISED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44754',
        },
        {
          id: '182252',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44754',
        },
      ],
    },
    '45070': {
      id: '45070',
      active: true,
      code: 'NUMBER OF STAFF INJURED',
      label: 'Number of staff injured',
      multipleAnswers: false,
      answers: [
        {
          id: '182257',
          code: 'MALE',
          active: true,
          label: 'MALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45157',
        },
        {
          id: '182256',
          code: 'FEMALE',
          active: true,
          label: 'FEMALE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45157',
        },
      ],
    },
    '45080': {
      id: '45080',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE KNIFE OR BLADE',
      label: 'What was the source of the knife or blade?',
      multipleAnswers: false,
      answers: [
        {
          id: '182283',
          code: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'SECRETED ON THE PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44845',
        },
        {
          id: '182281',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44845',
        },
        {
          id: '182280',
          code: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44845',
        },
        {
          id: '182282',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44845',
        },
      ],
    },
    '45089': {
      id: '45089',
      active: true,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          id: '182302',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45110',
        },
        {
          id: '182301',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45110',
        },
      ],
    },
    '45104': {
      id: '45104',
      active: true,
      code: 'WHAT WAS THE SOURCE OF THE FIREARM',
      label: 'What was the source of the firearm?',
      multipleAnswers: false,
      answers: [
        {
          id: '182365',
          code: 'SECRETED ON THE PRISONER',
          active: true,
          label: 'SECRETED ON THE PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44521',
        },
        {
          id: '182363',
          code: 'FOUND IN VEHICLE/AREA',
          active: true,
          label: 'FOUND IN VEHICLE/AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44521',
        },
        {
          id: '182362',
          code: 'BROUGHT BY ACCOMPLICE',
          active: true,
          label: 'BROUGHT BY ACCOMPLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44521',
        },
        {
          id: '182364',
          code: 'NOT KNOWN',
          active: true,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44521',
        },
      ],
    },
    '45110': {
      id: '45110',
      active: true,
      code: 'WHO WAS RESPONSIBLE FOR THE ESCORT',
      label: 'Who was responsible for the escort?',
      multipleAnswers: false,
      answers: [
        {
          id: '182377',
          code: 'PUBLIC SECTOR',
          active: true,
          label: 'PUBLIC SECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44490',
        },
        {
          id: '182376',
          code: 'PRIVATE SECTOR',
          active: true,
          label: 'PRIVATE SECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44850',
        },
      ],
    },
    '45112': {
      id: '45112',
      active: true,
      code: 'WHERE DID THE ESCAPE TAKE PLACE',
      label: 'Where did the escape take place?',
      multipleAnswers: false,
      answers: [
        {
          id: '182389',
          code: 'VEHICLE EN ROUTE TO VENUE',
          active: true,
          label: 'VEHICLE EN ROUTE TO VENUE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44188',
        },
        {
          id: '182388',
          code: 'VEHICLE EN ROUTE FROM VENUE',
          active: true,
          label: 'VEHICLE EN ROUTE FROM VENUE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44188',
        },
        {
          id: '182387',
          code: 'LEAVING VEHICLE (DEBUSSING)',
          active: true,
          label: 'LEAVING VEHICLE (DEBUSSING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44188',
        },
        {
          id: '182386',
          code: 'ENTERING VEHICLE (EMBUSSING)',
          active: true,
          label: 'ENTERING VEHICLE (EMBUSSING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44188',
        },
        {
          id: '182398',
          code: 'UNSCHEDULED STOP',
          active: true,
          label: 'UNSCHEDULED STOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182390',
          code: 'CELL AT COURT',
          active: true,
          label: 'CELL AT COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182391',
          code: 'COURT CELLS AREA',
          active: true,
          label: 'COURT CELLS AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182393',
          code: 'COURT VISITS AREA',
          active: true,
          label: 'COURT VISITS AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182392',
          code: 'COURT DOCK',
          active: true,
          label: 'COURT DOCK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182396',
          code: 'HOSPITAL WARD/ROOM',
          active: true,
          label: 'HOSPITAL WARD/ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182394',
          code: 'HOSPITAL TREATMENT ROOM',
          active: true,
          label: 'HOSPITAL TREATMENT ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182395',
          code: 'HOSPITAL WAITING AREA',
          active: true,
          label: 'HOSPITAL WAITING AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44448',
        },
        {
          id: '182397',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44448',
        },
      ],
    },
    '45118': {
      id: '45118',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED BY A PRISONER',
      label: 'Was a serious injury sustained by a prisoner?',
      multipleAnswers: false,
      answers: [
        {
          id: '182421',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45035',
        },
        {
          id: '182422',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44519',
        },
      ],
    },
    '45136': {
      id: '45136',
      active: true,
      code: 'WAS A FIREARM USED DURING THE ESCAPE',
      label: 'Was a firearm used during the escape?',
      multipleAnswers: false,
      answers: [
        {
          id: '182512',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44246',
        },
        {
          id: '182513',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44521',
        },
      ],
    },
    '45145': {
      id: '45145',
      active: true,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'Has any prosecution taken place or is any pending?',
      multipleAnswers: false,
      answers: [
        {
          id: '182546',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44696',
        },
        {
          id: '182545',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44696',
        },
      ],
    },
    '45149': {
      id: '45149',
      active: true,
      code: 'WAS DOUBLE CUFFING EMPLOYED',
      label: 'Was double cuffing employed?',
      multipleAnswers: false,
      answers: [
        {
          id: '182556',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44930',
        },
        {
          id: '182555',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44930',
        },
      ],
    },
    '45151': {
      id: '45151',
      active: true,
      code: 'WERE ANY INJURIES SUSTAINED BY STAFF',
      label: 'Were any injuries sustained by staff?',
      multipleAnswers: false,
      answers: [
        {
          id: '182559',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45070',
        },
        {
          id: '182560',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44134',
        },
      ],
    },
    '45154': {
      id: '45154',
      active: true,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '182571',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: true,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45024',
        },
        {
          id: '182572',
          code: 'MINOR BRUISES',
          active: true,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45024',
        },
        {
          id: '182575',
          code: 'SWELLINGS',
          active: true,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45024',
        },
        {
          id: '182574',
          code: 'SUPERFICIAL CUTS',
          active: true,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45024',
        },
        {
          id: '182573',
          code: 'OTHER',
          active: true,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45024',
        },
      ],
    },
    '45156': {
      id: '45156',
      active: true,
      code: 'WAS THE PRISONER WHO ESCAPED ON THE ESCAPE LIST',
      label: 'Was the prisoner who escaped on the escape list?',
      multipleAnswers: false,
      answers: [
        {
          id: '182589',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44419',
        },
        {
          id: '182588',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44419',
        },
      ],
    },
    '45157': {
      id: '45157',
      active: true,
      code: 'WAS A SERIOUS INJURY SUSTAINED BY STAFF',
      label: 'Was a serious injury sustained by staff?',
      multipleAnswers: false,
      answers: [
        {
          id: '182590',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45030',
        },
        {
          id: '182591',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44539',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ESCAPE',
      onlyOneAllowed: true,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default ESCAPE_FROM_ESCORT
