// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:43.275Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const FIND_5: IncidentTypeConfiguration = {
  incidentType: 'FIND_5',
  active: false,
  startingQuestionCode: '57284',
  questions: {
    '57284': {
      code: '57284',
      active: false,
      question: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT?',
      label: 'What was the main management outcome of this incident?',
      multipleAnswers: true,
      answers: [
        {
          code: '209109',
          response: 'NO FURTHER ACTION',
          active: true,
          label: 'No further action',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57285',
        },
        {
          code: '209110',
          response: 'IEP REGRESSION',
          active: true,
          label: 'IEP regression',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57285',
        },
        {
          code: '209111',
          response: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          active: true,
          label: 'Placed on report/adjudication referral',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57285',
        },
        {
          code: '209112',
          response: 'POLICE REFERRAL',
          active: true,
          label: 'Police referral',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57285',
        },
        {
          code: '209113',
          response: 'CPS REFRRAL',
          active: false,
          label: 'CPS referral',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57285',
        },
        {
          code: '209114',
          response: 'PROSECUTION REFERRAL',
          active: true,
          label: 'Prosecution referral',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57285',
        },
      ],
    },
    '57285': {
      code: '57285',
      active: true,
      question: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES?',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: '209115',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57286',
        },
        {
          code: '209116',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57286',
        },
      ],
    },
    '57286': {
      code: '57286',
      active: true,
      question: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          code: '209117',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57287',
        },
        {
          code: '209118',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
      ],
    },
    '57287': {
      code: '57287',
      active: true,
      question: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '209119',
          response: 'ADMINISTRATION',
          active: true,
          label: 'Administration',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209120',
          response: 'ASSOCIATION AREA',
          active: true,
          label: 'Association area',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209121',
          response: 'CELL',
          active: true,
          label: 'Cell',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209122',
          response: 'CHAPEL',
          active: true,
          label: 'Chapel',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209123',
          response: 'CROWN COURT',
          active: true,
          label: 'Crown court',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209124',
          response: 'DINING ROOM',
          active: true,
          label: 'Dining room',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209125',
          response: 'DORMITORY',
          active: true,
          label: 'Dormitory',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209126',
          response: 'EDUCATION',
          active: true,
          label: 'Education',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209127',
          response: 'ELSEWHERE',
          active: true,
          label: 'Elsewhere',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209128',
          response: 'EXERCISE YARD',
          active: true,
          label: 'Exercise yard',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209129',
          response: 'FUNERAL',
          active: true,
          label: 'Funeral',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209130',
          response: 'GATE',
          active: true,
          label: 'Gate',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209131',
          response: 'GYM',
          active: true,
          label: 'Gym',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209132',
          response: 'HEALTH CARE CENTRE',
          active: true,
          label: 'Health care centre',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209133',
          response: 'HOSPITAL OUTSIDE (PATIENT)',
          active: true,
          label: 'Hospital outside (patient)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209134',
          response: 'HOSPITAL OUTSIDE (VISITING)',
          active: true,
          label: 'Hospital outside (visiting)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209135',
          response: 'KITCHEN',
          active: true,
          label: 'Kitchen',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209136',
          response: 'MAGISTRATES COURT',
          active: true,
          label: 'Magistrates court',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209137',
          response: 'OFFICE',
          active: true,
          label: 'Office',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209138',
          response: 'OUTSIDE WORKING PARTY',
          active: true,
          label: 'Outside working party',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209139',
          response: 'RECEPTION',
          active: true,
          label: 'Reception',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209140',
          response: 'RECESS',
          active: true,
          label: 'Recess',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209141',
          response: 'SEGREGATION UNIT',
          active: true,
          label: 'Segregation unit',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209142',
          response: 'SHOWERS/CHANGING ROOM',
          active: true,
          label: 'Showers/changing room',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209143',
          response: 'SPECIAL UNIT',
          active: true,
          label: 'Special unit',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209144',
          response: 'SPORTS FIELD',
          active: true,
          label: 'Sports field',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209145',
          response: 'VEHICLE',
          active: true,
          label: 'Vehicle',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209146',
          response: 'VISITS',
          active: true,
          label: 'Visits',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209147',
          response: 'WEDDINGS',
          active: true,
          label: 'Weddings',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209148',
          response: 'WING',
          active: true,
          label: 'Wing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209149',
          response: 'WITHIN PERIMETER',
          active: true,
          label: 'Within perimeter',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209150',
          response: 'WORKS DEPARTMENT',
          active: true,
          label: 'Works department',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209151',
          response: 'WORKSHOP',
          active: true,
          label: 'Workshop',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209152',
          response: 'INDUCTION/1ST NIGHT CENTRE',
          active: true,
          label: 'Induction/1st night centre',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209153',
          response: 'MAIL ROOM',
          active: true,
          label: 'Mail room',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209154',
          response: 'EXTERNAL ROOF',
          active: true,
          label: 'External roof',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
        {
          code: '209155',
          response: 'VULNERABLE PRISONERS UNIT (VPU)',
          active: true,
          label: 'Vulnerable prisoners unit (VPU)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57288',
        },
      ],
    },
    '57288': {
      code: '57288',
      active: true,
      question: 'WAS A DRUG FOUND?',
      label: 'Was a drug found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209156',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57289',
        },
        {
          code: '209157',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57294',
        },
      ],
    },
    '57289': {
      code: '57289',
      active: true,
      question: 'DESCRIBE THE DRUG FOUND',
      label: 'Describe the drug found',
      multipleAnswers: true,
      answers: [
        {
          code: '209158',
          response: 'AMPHETAMINES',
          active: true,
          label: 'Amphetamines',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209159',
          response: 'BARBITURATES',
          active: true,
          label: 'Barbiturates',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209160',
          response: 'BENZODIAZEPINES',
          active: true,
          label: 'Benzodiazepines',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209161',
          response: 'BUPRENORPHINE/SUBUTEX',
          active: true,
          label: 'Buprenorphine/subutex',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209162',
          response: 'CANNABIS',
          active: true,
          label: 'Cannabis',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209163',
          response: 'CANNABIS PLANT',
          active: true,
          label: 'Cannabis plant',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209164',
          response: 'COCAINE',
          active: true,
          label: 'Cocaine',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209165',
          response: 'CRACK',
          active: true,
          label: 'Crack',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209166',
          response: 'HEROIN',
          active: true,
          label: 'Heroin',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209167',
          response: 'LSD',
          active: true,
          label: 'LSD',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209168',
          response: 'METHADONE',
          active: true,
          label: 'Methadone',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209169',
          response: 'PREGABALIN',
          active: true,
          label: 'Pregabalin',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209170',
          response: 'TRANQUILISERS',
          active: true,
          label: 'Tranquilisers',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209171',
          response: 'TRAMADOL',
          active: true,
          label: 'Tramadol',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209172',
          response: 'GABAPENTIN',
          active: true,
          label: 'Gabapentin',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209173',
          response: 'NPS: SPICE',
          active: true,
          label: 'NPS: spice',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209174',
          response: 'NPS: BLACK MAMBA',
          active: true,
          label: 'NPS: black mamba',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209175',
          response: 'NPS: OTHER',
          active: true,
          label: 'NPS: other',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209176',
          response: 'STEROIDS',
          active: true,
          label: 'Steroids',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209177',
          response: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'Other (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
        {
          code: '209178',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57290',
        },
      ],
    },
    '57290': {
      code: '57290',
      active: true,
      question: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND?',
      label: 'What was the estimated weight of all drugs/substances found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209179',
          response: '<1g',
          active: true,
          label: '<1g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209180',
          response: '2g to 5g',
          active: true,
          label: '2g to 5g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209181',
          response: '6g to 10g',
          active: true,
          label: '6g to 10g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209182',
          response: '11g to 20g',
          active: true,
          label: '11g to 20g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209183',
          response: '21g to 30g',
          active: true,
          label: '21g to 30g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209184',
          response: '31g to 40g',
          active: true,
          label: '31g to 40g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209185',
          response: '41g to 50g',
          active: true,
          label: '41g to 50g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209186',
          response: '51g to 100g',
          active: true,
          label: '51g to 100g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209187',
          response: '101g to 200g',
          active: true,
          label: '101g to 200g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209188',
          response: '201g to 300g',
          active: true,
          label: '201g to 300g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209189',
          response: '301g to 400g',
          active: true,
          label: '301g to 400g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209190',
          response: '401g to 500g',
          active: true,
          label: '401g to 500g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209191',
          response: '501g to 1,000g',
          active: true,
          label: '501g to 1,000g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209192',
          response: 'More than 1kg',
          active: true,
          label: 'More than 1kg',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
        {
          code: '209193',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57291',
        },
      ],
    },
    '57291': {
      code: '57291',
      active: true,
      question: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      label: 'Was the substance found analysed?',
      multipleAnswers: false,
      answers: [
        {
          code: '209194',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57292',
        },
        {
          code: '209195',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57293',
        },
      ],
    },
    '57292': {
      code: '57292',
      active: true,
      question: 'HOW WAS THE SUBSTANCE ANALYSED?',
      label: 'How was the substance analysed?',
      multipleAnswers: false,
      answers: [
        {
          code: '209196',
          response: 'FORENSIC LABORATORY',
          active: true,
          label: 'Forensic laboratory',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57293',
        },
        {
          code: '209197',
          response: 'LOCAL WITH BDH KIT OR SIMILAR',
          active: true,
          label: 'Local with BDH kit or similar',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57293',
        },
      ],
    },
    '57293': {
      code: '57293',
      active: true,
      question: 'TO WHICH POLICE STATION WERE SEIZED DRUGS SENT FOR DESTRUCTION?',
      label: 'To which police station were seized drugs sent for destruction?',
      multipleAnswers: false,
      answers: [
        {
          code: '209198',
          response: 'NAME',
          active: true,
          label: 'Name',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57294',
        },
      ],
    },
    '57294': {
      code: '57294',
      active: true,
      question: 'WAS DRUG EQUIPMENT FOUND?',
      label: 'Was drug equipment found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209199',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57295',
        },
        {
          code: '209200',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
      ],
    },
    '57295': {
      code: '57295',
      active: true,
      question: 'DESCRIBE DRUG EQUIPMENT FOUND',
      label: 'Describe drug equipment found',
      multipleAnswers: true,
      answers: [
        {
          code: '209201',
          response: 'AUTHENTIC NEEDLE',
          active: true,
          label: 'Authentic needle',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
        {
          code: '209202',
          response: 'AUTHENTIC SYRINGE',
          active: true,
          label: 'Authentic syringe',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
        {
          code: '209203',
          response: 'IMPROVISED NEEDLE',
          active: true,
          label: 'Improvised needle',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
        {
          code: '209204',
          response: 'IMPROVISED SYRINGE',
          active: true,
          label: 'Improvised syringe',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
        {
          code: '209205',
          response: 'PIPE(S)',
          active: true,
          label: 'Pipe(s)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
        {
          code: '209206',
          response: 'ROACH',
          active: true,
          label: 'Roach',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
        {
          code: '209207',
          response: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'Other (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57296',
        },
      ],
    },
    '57296': {
      code: '57296',
      active: true,
      question: 'WAS A MOBILE PHONE RELATED ITEM FOUND?',
      label: 'Was a mobile phone related item found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209208',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57297',
        },
        {
          code: '209209',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57307',
        },
      ],
    },
    '57297': {
      code: '57297',
      active: true,
      question: 'WAS A MOBILE PHONE FOUND?',
      label: 'Was a mobile phone found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209210',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57298',
        },
        {
          code: '209211',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
      ],
    },
    '57298': {
      code: '57298',
      active: true,
      question: 'ENTER NUMBER OF MOBILES FOUND',
      label: 'Enter number of mobiles found',
      multipleAnswers: false,
      answers: [
        {
          code: '209212',
          response: '1',
          active: true,
          label: '1',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209213',
          response: '2',
          active: true,
          label: '2',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209214',
          response: '3',
          active: true,
          label: '3',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209215',
          response: '4',
          active: true,
          label: '4',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209216',
          response: '5',
          active: true,
          label: '5',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209217',
          response: '6',
          active: true,
          label: '6',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209218',
          response: '7',
          active: true,
          label: '7',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209219',
          response: '8',
          active: true,
          label: '8',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209220',
          response: '9',
          active: true,
          label: '9',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209221',
          response: '10',
          active: true,
          label: '10',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209222',
          response: '11',
          active: true,
          label: '11',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209223',
          response: '12',
          active: true,
          label: '12',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209224',
          response: '13',
          active: true,
          label: '13',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209225',
          response: '14',
          active: true,
          label: '14',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209226',
          response: '15',
          active: true,
          label: '15',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209227',
          response: '16',
          active: true,
          label: '16',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209228',
          response: '17',
          active: true,
          label: '17',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209229',
          response: '18',
          active: true,
          label: '18',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209230',
          response: '19',
          active: true,
          label: '19',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209231',
          response: '20',
          active: true,
          label: '20',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209232',
          response: 'MORE THAN 20',
          active: true,
          label: 'More than 20',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
        {
          code: '209233',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57299',
        },
      ],
    },
    '57299': {
      code: '57299',
      active: true,
      question: 'WAS A SIM CARD FOUND?',
      label: 'Was a SIM card found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209234',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57300',
        },
        {
          code: '209235',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
      ],
    },
    '57300': {
      code: '57300',
      active: true,
      question: 'ENTER NUMBER OF SIM CARDS FOUND',
      label: 'Enter number of SIM cards found',
      multipleAnswers: false,
      answers: [
        {
          code: '209236',
          response: '1',
          active: true,
          label: '1',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209237',
          response: '2',
          active: true,
          label: '2',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209238',
          response: '3',
          active: true,
          label: '3',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209239',
          response: '4',
          active: true,
          label: '4',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209240',
          response: '5',
          active: true,
          label: '5',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209241',
          response: '6',
          active: true,
          label: '6',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209242',
          response: '7',
          active: true,
          label: '7',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209243',
          response: '8',
          active: true,
          label: '8',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209244',
          response: '9',
          active: true,
          label: '9',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209245',
          response: '10',
          active: true,
          label: '10',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209246',
          response: '11',
          active: true,
          label: '11',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209247',
          response: '12',
          active: true,
          label: '12',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209248',
          response: '13',
          active: true,
          label: '13',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209249',
          response: '14',
          active: true,
          label: '14',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209250',
          response: '15',
          active: true,
          label: '15',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209251',
          response: '16',
          active: true,
          label: '16',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209252',
          response: '17',
          active: true,
          label: '17',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209253',
          response: '18',
          active: true,
          label: '18',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209254',
          response: '19',
          active: true,
          label: '19',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209255',
          response: '20',
          active: true,
          label: '20',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209256',
          response: 'MORE THAN 20',
          active: true,
          label: 'More than 20',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
        {
          code: '209257',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57301',
        },
      ],
    },
    '57301': {
      code: '57301',
      active: true,
      question: ' WAS A MEMORY CARD FOUND?',
      label: 'Was a memory card found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209258',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57302',
        },
        {
          code: '209259',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
      ],
    },
    '57302': {
      code: '57302',
      active: true,
      question: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      label: 'Enter number of memory cards found',
      multipleAnswers: false,
      answers: [
        {
          code: '209260',
          response: '1',
          active: true,
          label: '1',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209261',
          response: '2',
          active: true,
          label: '2',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209262',
          response: '3',
          active: true,
          label: '3',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209263',
          response: '4',
          active: true,
          label: '4',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209264',
          response: '5',
          active: true,
          label: '5',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209265',
          response: '6',
          active: true,
          label: '6',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209266',
          response: '7',
          active: true,
          label: '7',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209267',
          response: '8',
          active: true,
          label: '8',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209268',
          response: '9',
          active: true,
          label: '9',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209269',
          response: '10',
          active: true,
          label: '10',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209270',
          response: '11',
          active: true,
          label: '11',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209271',
          response: '12',
          active: true,
          label: '12',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209272',
          response: '13',
          active: true,
          label: '13',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209273',
          response: '14',
          active: true,
          label: '14',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209274',
          response: '15',
          active: true,
          label: '15',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209275',
          response: '16',
          active: true,
          label: '16',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209276',
          response: '17',
          active: true,
          label: '17',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209277',
          response: '18',
          active: true,
          label: '18',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209278',
          response: '19',
          active: true,
          label: '19',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209279',
          response: '20',
          active: true,
          label: '20',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209280',
          response: 'MORE THAN 20',
          active: true,
          label: 'More than 20',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
        {
          code: '209281',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57303',
        },
      ],
    },
    '57303': {
      code: '57303',
      active: true,
      question: 'WAS A CHARGER FOUND?',
      label: 'Was a charger found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209282',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57304',
        },
        {
          code: '209283',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57304',
        },
      ],
    },
    '57304': {
      code: '57304',
      active: true,
      question: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      label: 'Was any other mobile phone/communication related item found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209284',
          response: 'YES (PLEASE SPECIFY)',
          active: true,
          label: 'Yes (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57305',
        },
        {
          code: '209285',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57305',
        },
      ],
    },
    '57305': {
      code: '57305',
      active: true,
      question: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO NDTSG?',
      label: 'Has phone/SIM/memory card been sent to NDTSG?',
      multipleAnswers: true,
      answers: [
        {
          code: '209286',
          response: 'YES (PLEASE ENTER DATE)',
          active: true,
          label: 'Yes (please enter date)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: true,
          nextQuestionCode: '57306',
        },
        {
          code: '209287',
          response: 'EVIDENCE BAG (PLEASE ENTER BAG NUMBER)',
          active: true,
          label: 'Evidence bag (please enter bag number)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57306',
        },
        {
          code: '209288',
          response: 'NO (PLEASE STATE WHY)',
          active: true,
          label: 'No (please state why)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57306',
        },
      ],
    },
    '57306': {
      code: '57306',
      active: true,
      question: 'HAS PHONE/SIM/EQUIPMENT BEEN RETAINED BY POLICE?',
      label: 'Has phone/SIM/equipment been retained by police?',
      multipleAnswers: false,
      answers: [
        {
          code: '209289',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57307',
        },
        {
          code: '209290',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57307',
        },
      ],
    },
    '57307': {
      code: '57307',
      active: true,
      question: 'WAS A WEAPON FOUND?',
      label: 'Was a weapon found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209291',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57308',
        },
        {
          code: '209292',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57309',
        },
      ],
    },
    '57308': {
      code: '57308',
      active: true,
      question: 'DESCRIBE THE WEAPON',
      label: 'Describe the weapon',
      multipleAnswers: true,
      answers: [
        {
          code: '209293',
          response: 'BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC.)',
          active: true,
          label: 'Blunt instrument (cosh, item in sock etc.)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57309',
        },
        {
          code: '209294',
          response: 'KNIFE/BLADED ARTICLE',
          active: true,
          label: 'Knife/bladed article',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57309',
        },
        {
          code: '209295',
          response: 'FIREARM (FAKE GUNS, AMMUNITION, CHEMIICAL INCAPACITANT ETC.)',
          active: true,
          label: 'Firearm (fake guns, ammunition, chemical incapacitant etc.)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57309',
        },
        {
          code: '209296',
          response: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'Other (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57309',
        },
      ],
    },
    '57309': {
      code: '57309',
      active: true,
      question: 'WAS ANY ALCOHOL/HOOCH FOUND?',
      label: 'Was any alcohol/hooch found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209297',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57310',
        },
        {
          code: '209298',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
      ],
    },
    '57310': {
      code: '57310',
      active: true,
      question: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND?',
      label: 'What quantity of alcohol/hooch was found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209299',
          response: '< 1 litre',
          active: true,
          label: '< 1 litre',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209300',
          response: '1 to 2 litres',
          active: true,
          label: '1 to 2 litres',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209301',
          response: '2 to 3 litres',
          active: true,
          label: '2 to 3 litres',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209302',
          response: '3 to 4 litres',
          active: true,
          label: '3 to 4 litres',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209303',
          response: ' 4 to 5 litres',
          active: true,
          label: '4 to 5 litres',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209304',
          response: '6 to 10 litres',
          active: true,
          label: '6 to 10 litres',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209305',
          response: '11 to 20 litres',
          active: true,
          label: '11 to 20 litres',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209306',
          response: 'More than 20 litres',
          active: true,
          label: 'More than 20 litres',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
        {
          code: '209307',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57311',
        },
      ],
    },
    '57311': {
      code: '57311',
      active: true,
      question: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      label: 'Was any distilling equipment found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209308',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57312',
        },
        {
          code: '209309',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57312',
        },
      ],
    },
    '57312': {
      code: '57312',
      active: true,
      question: 'WAS ANY TOBACCO FOUND?',
      label: 'Was any tobacco found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209310',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57313',
        },
        {
          code: '209311',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57315',
        },
      ],
    },
    '57313': {
      code: '57313',
      active: true,
      question: 'DESCRIBE THE TOBACCO FOUND',
      label: 'Describe the tobacco found',
      multipleAnswers: true,
      answers: [
        {
          code: '209312',
          response: 'LOOSE TOBACCO',
          active: true,
          label: 'Loose tobacco',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57314',
        },
        {
          code: '209313',
          response: 'CIGARETTES/CIGARS',
          active: true,
          label: 'Cigarettes/cigars',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57314',
        },
        {
          code: '209314',
          response: 'OTHER (INC PACKAGING AND ROACHES)',
          active: true,
          label: 'Other (inc packaging and roaches)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57314',
        },
      ],
    },
    '57314': {
      code: '57314',
      active: true,
      question: 'APPROX WEIGHT OF TOBACCO?',
      label: 'Approx weight of tobacco?',
      multipleAnswers: false,
      answers: [
        {
          code: '209315',
          response: '<1g',
          active: true,
          label: '<1g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57315',
        },
        {
          code: '209316',
          response: '2g to 5g',
          active: true,
          label: '2g to 5g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57315',
        },
        {
          code: '209317',
          response: '6g to 10g',
          active: true,
          label: '6g to 10g',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57315',
        },
        {
          code: '209318',
          response: '10g+',
          active: true,
          label: '10g+',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57315',
        },
      ],
    },
    '57315': {
      code: '57315',
      active: true,
      question: 'WERE ANY OTHER REPORTABLE ITEMS FOUND?',
      label: 'Were any other reportable items found?',
      multipleAnswers: false,
      answers: [
        {
          code: '209319',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57316',
        },
        {
          code: '209320',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57317',
        },
      ],
    },
    '57316': {
      code: '57316',
      active: true,
      question: 'DESCRIBE THE ITEM',
      label: 'Describe the item',
      multipleAnswers: false,
      answers: [
        {
          code: '209321',
          response: 'PLEASE SPECIFY',
          active: true,
          label: 'Please specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57317',
        },
      ],
    },
    '57317': {
      code: '57317',
      active: true,
      question: 'DESCRIBE HOW THE ITEM WAS FOUND?',
      label: 'Describe how the item was found?',
      multipleAnswers: true,
      answers: [
        {
          code: '209322',
          response: 'BOSS CHAIR',
          active: true,
          label: 'Boss chair',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209323',
          response: 'CELL SEARCH',
          active: true,
          label: 'Cell search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209324',
          response: 'CRIME SCENE',
          active: true,
          label: 'Crime scene',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209325',
          response: 'DOG SEARCH',
          active: true,
          label: 'Dog search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209326',
          response: 'DRONE RECOVERY',
          active: true,
          label: 'Drone recovery',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209327',
          response: 'HIGH SENSITIVITY WAND',
          active: true,
          label: 'High sensitivity wand',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209328',
          response: 'INFORMATION RECEIVED',
          active: true,
          label: 'Information received',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209329',
          response: 'INTELLIGENCE LED SEARCH',
          active: true,
          label: 'Intelligence led search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209330',
          response: 'ITEM OBSERVED',
          active: true,
          label: 'Item observed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209331',
          response: 'MOBILE PHONE SIGNAL DETECTOR',
          active: true,
          label: 'Mobile phone signal detector',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209332',
          response: 'MOBILE PHONE ROD',
          active: true,
          label: 'Mobile phone rod',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209333',
          response: 'OTHER SEARCH (INMATE)',
          active: true,
          label: 'Other search (inmate)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209334',
          response: 'OTHER SEARCH (PREMISES)',
          active: true,
          label: 'Other search (premises)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209335',
          response: 'OTHER SEARCH (VISITOR)',
          active: true,
          label: 'Other search (visitor)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209336',
          response: 'PRE-OCCUPATION SEARCH',
          active: true,
          label: 'Pre-occupation search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209337',
          response: 'UNUSUAL BEHAVIOUR',
          active: true,
          label: 'Unusual behaviour',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
        {
          code: '209338',
          response: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'Other (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57318',
        },
      ],
    },
    '57318': {
      code: '57318',
      active: true,
      question: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      label: 'Describe the method of entry into the establishment',
      multipleAnswers: true,
      answers: [
        {
          code: '209339',
          response: 'PRISONER',
          active: true,
          label: 'Prisoner',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209340',
          response: 'STAFF',
          active: true,
          label: 'Staff',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209341',
          response: 'VISITOR (FRIEND)',
          active: true,
          label: 'Visitor (friend)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209342',
          response: 'VISITOR (OFFICIAL)',
          active: true,
          label: 'Visitor (official)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209343',
          response: 'VISITOR (RELATIVE)',
          active: true,
          label: 'Visitor (relative)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209344',
          response: 'CONTRACTOR',
          active: true,
          label: 'Contractor',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209345',
          response: 'POST (RULE 39)',
          active: true,
          label: 'Post (rule 39)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209346',
          response: 'POST (OTHER)',
          active: true,
          label: 'Post (other)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209347',
          response: 'THROWN IN',
          active: true,
          label: 'Thrown in',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209348',
          response: 'DRONE/UAV',
          active: true,
          label: 'Drone/UAV',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209349',
          response: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'Other (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
        {
          code: '209350',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57319',
        },
      ],
    },
    '57319': {
      code: '57319',
      active: true,
      question: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      label: 'If found in possession, whose was it found in?',
      multipleAnswers: false,
      answers: [
        {
          code: '209351',
          response: 'PRISONER',
          active: true,
          label: 'Prisoner',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
        {
          code: '209352',
          response: 'STAFF',
          active: true,
          label: 'Staff',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
        {
          code: '209353',
          response: 'VISITOR (FRIEND)',
          active: true,
          label: 'Visitor (friend)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
        {
          code: '209354',
          response: 'VISITOR (OFFICIAL)',
          active: true,
          label: 'Visitor (official)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
        {
          code: '209355',
          response: 'VISITOR (RELATIVE)',
          active: true,
          label: 'Visitor (relative)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
        {
          code: '209356',
          response: 'CONTRACTOR',
          active: true,
          label: 'Contractor',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
        {
          code: '209357',
          response: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'Other (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
        {
          code: '209358',
          response: 'NOT APPLICABLE',
          active: true,
          label: 'Not applicable',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57320',
        },
      ],
    },
    '57320': {
      code: '57320',
      active: true,
      question: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      label: 'What was the method of concealment?',
      multipleAnswers: false,
      answers: [
        {
          code: '209359',
          response: 'NOT CONCEALED',
          active: true,
          label: 'Not concealed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209360',
          response: 'BED/BEDDING',
          active: true,
          label: 'Bed/bedding',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209361',
          response: 'BOOK/PAPERS',
          active: true,
          label: 'Book/papers',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209362',
          response: 'CELL/BUILDING FABRIC',
          active: true,
          label: 'Cell/building fabric',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209363',
          response: 'FOOD/CONTAINER',
          active: true,
          label: 'Food/container',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209364',
          response: 'IN CLOTHING',
          active: true,
          label: 'In clothing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209365',
          response: 'IN HAND',
          active: true,
          label: 'In hand',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209366',
          response: 'IN MOUTH',
          active: true,
          label: 'In mouth',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209367',
          response: 'INTERNALLY/PLUGGED',
          active: true,
          label: 'Internally/plugged',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209368',
          response: 'LETTER/PARCEL',
          active: true,
          label: 'Letter/parcel',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209369',
          response: 'LIGHT FITTINGS',
          active: true,
          label: 'Light fittings',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209370',
          response: 'PIPEWORK',
          active: true,
          label: 'Pipework',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209371',
          response: 'RULE 39/LEGAL PAPERS',
          active: true,
          label: 'Rule 39/legal papers',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209372',
          response: 'TV/RADIO/DVD/CONSOLES ETC.',
          active: true,
          label: 'TV/radio/DVD/consoles etc.',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
        {
          code: '209373',
          response: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'Other (please specify)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57321',
        },
      ],
    },
    '57321': {
      code: '57321',
      active: true,
      question: 'IS THE ITEM HEAVILY CONTAMINATED? (E.G. BLOOD, FAECES)',
      label: 'Is the item heavily contaminated? (e.g. blood, faeces)?',
      multipleAnswers: false,
      answers: [
        {
          code: '209374',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57322',
        },
        {
          code: '209375',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57322',
        },
      ],
    },
    '57322': {
      code: '57322',
      active: true,
      question: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE?',
      label: 'Was a visitor suspected of involvement and arrested by the police?',
      multipleAnswers: false,
      answers: [
        {
          code: '209376',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57323',
        },
        {
          code: '209377',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57325',
        },
      ],
    },
    '57323': {
      code: '57323',
      active: true,
      question: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      label: 'Describe circumstances of visitors arrest',
      multipleAnswers: false,
      answers: [
        {
          code: '209378',
          response: 'AFTER ENTERING PRISON',
          active: true,
          label: 'After entering prison',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57324',
        },
        {
          code: '209379',
          response: 'BEFORE ENTERING PRISON',
          active: true,
          label: 'Before entering prison',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57324',
        },
      ],
    },
    '57324': {
      code: '57324',
      active: true,
      question: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN TO?',
      label: 'To which police station was the visitor taken to?',
      multipleAnswers: false,
      answers: [
        {
          code: '209380',
          response: 'PLEASE SPECIFY',
          active: true,
          label: 'Please specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '57325',
        },
      ],
    },
    '57325': {
      code: '57325',
      active: true,
      question: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      label: 'Were the items obtained on temporary release?',
      multipleAnswers: false,
      answers: [
        {
          code: '209381',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57326',
        },
        {
          code: '209382',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57327',
        },
        {
          code: '209383',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57327',
        },
      ],
    },
    '57326': {
      code: '57326',
      active: true,
      question: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      label: 'Describe the type of temporary release',
      multipleAnswers: false,
      answers: [
        {
          code: '209384',
          response: 'COMMUNITY VISIT',
          active: true,
          label: 'Community visit',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57327',
        },
        {
          code: '209385',
          response: 'COMPASSIONATE',
          active: true,
          label: 'Compassionate',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57327',
        },
        {
          code: '209386',
          response: 'FACILITY',
          active: true,
          label: 'Facility',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57327',
        },
        {
          code: '209387',
          response: 'RESETTLEMENT',
          active: true,
          label: 'Resettlement',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57327',
        },
        {
          code: '209388',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '57327',
        },
      ],
    },
    '57327': {
      code: '57327',
      active: true,
      question: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND? (DRUGS, MOBILE PHONES ETC.)',
      label: 'What was the total estimated value of the find? (drugs, mobile phones etc.)?',
      multipleAnswers: false,
      answers: [
        {
          code: '209389',
          response: '£0',
          active: true,
          label: '£0',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209390',
          response: '£1 to £100',
          active: true,
          label: '£1 to £100',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209391',
          response: '£101 to £200',
          active: true,
          label: '£101 to £200',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209392',
          response: '£201 to £300',
          active: true,
          label: '£201 to £300',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209393',
          response: '£301 to £400',
          active: true,
          label: '£301 to £400',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209394',
          response: '£401 to £500',
          active: true,
          label: '£401 to £500',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209395',
          response: '£501 to £1,000',
          active: true,
          label: '£501 to £1,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209396',
          response: '£1,001 to £5,000',
          active: true,
          label: '£1,001 to £5,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209397',
          response: '£5,001 to £10,000',
          active: true,
          label: '£5,001 to £10,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209398',
          response: '£10,001 to £20,000',
          active: true,
          label: '£10,001 to £20,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209399',
          response: '£20,001 to £30,000',
          active: true,
          label: '£20,001 to £30,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209400',
          response: '£30,001 to £40,000',
          active: true,
          label: '£30,001 to £40,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209401',
          response: '£40,001 to £50,000',
          active: true,
          label: '£40,001 to £50,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209402',
          response: 'More than £50,000',
          active: true,
          label: 'More than £50,000',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '209403',
          response: 'UNKNOWN',
          active: true,
          label: 'Unknown',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IN_POSSESSION',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'INTENDED_RECIPIENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default FIND_5
