// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:49.292Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const HOSTAGE_1: IncidentTypeConfiguration = {
  incidentType: 'HOSTAGE_1',
  active: false,
  startingQuestionId: '44318',
  questions: {
    '44137': {
      code: '44137',
      active: false,
      question: 'WAS A HOSTAGE NEGOTIATION ADVISER PRESENT',
      label: 'Was a hostage negotiation adviser present?',
      multipleAnswers: false,
      answers: [
        {
          id: '178952',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44365',
        },
        {
          id: '178951',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44365',
        },
      ],
    },
    '44210': {
      code: '44210',
      active: false,
      question: 'WERE IMB MEMBERS PRESENT',
      label: 'Were IMB members present?',
      multipleAnswers: false,
      answers: [
        {
          id: '179194',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44452',
        },
        {
          id: '179193',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44452',
        },
      ],
    },
    '44213': {
      code: '44213',
      active: false,
      question: 'ESTIMATED COST OF DAMAGE',
      label: 'Estimated cost of damage',
      multipleAnswers: false,
      answers: [
        {
          id: '179199',
          response: 'ENTER AMOUNT IN POUND STERLING',
          active: false,
          label: 'Enter amount in pound sterling',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44293',
        },
      ],
    },
    '44218': {
      code: '44218',
      active: false,
      question: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'Did injuries result in detention in outside hospital as an in-patient?',
      multipleAnswers: false,
      answers: [
        {
          id: '179209',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44235',
        },
        {
          id: '179210',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44347',
        },
      ],
    },
    '44234': {
      code: '44234',
      active: false,
      question: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'Has any prosecution taken place or is any pending?',
      multipleAnswers: false,
      answers: [
        {
          id: '179270',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45093',
        },
        {
          id: '179269',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45093',
        },
      ],
    },
    '44235': {
      code: '44235',
      active: false,
      question: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'Who was detained in outside hospital?',
      multipleAnswers: true,
      answers: [
        {
          id: '179275',
          response: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          id: '179274',
          response: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          id: '179271',
          response: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          id: '179273',
          response: 'POLICE',
          active: false,
          label: 'Police',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          id: '179272',
          response: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
      ],
    },
    '44239': {
      code: '44239',
      active: false,
      question: 'WHO AUTHORISED THE SHUT DOWN?',
      label: 'Who authorised the shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '179287',
          response: 'GOVERNOR',
          active: false,
          label: 'Governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45076',
        },
        {
          id: '179285',
          response: 'DEPUTY GOVERNOR',
          active: false,
          label: 'Deputy governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45076',
        },
        {
          id: '179286',
          response: 'DUTY GOVERNOR',
          active: false,
          label: 'Duty governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45076',
        },
        {
          id: '179288',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45076',
        },
      ],
    },
    '44257': {
      code: '44257',
      active: false,
      question: 'WERE WATER HOSES USED',
      label: 'Were water hoses used?',
      multipleAnswers: false,
      answers: [
        {
          id: '179338',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44891',
        },
        {
          id: '179337',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44891',
        },
      ],
    },
    '44265': {
      code: '44265',
      active: false,
      question: 'WERE THE POLICE PRESENT',
      label: 'Were the police present?',
      multipleAnswers: false,
      answers: [
        {
          id: '179357',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44963',
        },
        {
          id: '179356',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44963',
        },
      ],
    },
    '44275': {
      code: '44275',
      active: false,
      question: 'INDICATE THE NATURE OF THE SHUT DOWN',
      label: 'Indicate the nature of the shut down',
      multipleAnswers: true,
      answers: [
        {
          id: '179388',
          response: 'TELEPHONY',
          active: false,
          label: 'Telephony',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44788',
        },
        {
          id: '179387',
          response: 'IT',
          active: false,
          label: 'IT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44788',
        },
      ],
    },
    '44293': {
      code: '44293',
      active: false,
      question: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      label: 'Was the telephone/it system shut down during the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '179424',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44805',
        },
        {
          id: '179425',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44311': {
      code: '44311',
      active: false,
      question: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'Was damage caused to prison property?',
      multipleAnswers: false,
      answers: [
        {
          id: '179532',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44600',
        },
        {
          id: '179533',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44293',
        },
      ],
    },
    '44318': {
      code: '44318',
      active: false,
      question: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          id: '179553',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44463',
        },
        {
          id: '179554',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
      ],
    },
    '44322': {
      code: '44322',
      active: false,
      question: 'WAS THERE EVIDENCE OF COLLUSION',
      label: 'Was there evidence of collusion?',
      multipleAnswers: false,
      answers: [
        {
          id: '179568',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44137',
        },
        {
          id: '179567',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44137',
        },
      ],
    },
    '44335': {
      code: '44335',
      active: false,
      question: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'Were any injuries received during this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '179627',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45101',
        },
        {
          id: '179628',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44347',
        },
      ],
    },
    '44347': {
      code: '44347',
      active: false,
      question: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT',
      label: 'Are there any staff now off duty as a result?',
      multipleAnswers: false,
      answers: [
        {
          id: '179669',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44937',
        },
        {
          id: '179668',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44937',
        },
      ],
    },
    '44356': {
      code: '44356',
      active: false,
      question: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      label: 'Has the service supplier been notified of a replacement keyword?',
      multipleAnswers: false,
      answers: [
        {
          id: '179701',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
        {
          id: '179700',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
      ],
    },
    '44365': {
      code: '44365',
      active: false,
      question: 'WAS A CANDR ADVISOR PRESENT',
      label: 'Was a CANDR advisor present?',
      multipleAnswers: false,
      answers: [
        {
          id: '179720',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44959',
        },
        {
          id: '179719',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44959',
        },
      ],
    },
    '44403': {
      code: '44403',
      active: false,
      question: 'QUOTE THE VANTIVE CASE NUMBER',
      label: 'Quote the Vantive case number',
      multipleAnswers: false,
      answers: [
        {
          id: '179850',
          response: 'NUMBER',
          active: false,
          label: 'Number',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44831',
        },
      ],
    },
    '44411': {
      code: '44411',
      active: false,
      question: 'DID A TACTICAL FIREARMS ADVISER ATTEND',
      label: 'Did a tactical firearms adviser attend?',
      multipleAnswers: false,
      answers: [
        {
          id: '179881',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44939',
        },
        {
          id: '179880',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44939',
        },
      ],
    },
    '44431': {
      code: '44431',
      active: false,
      question: 'WAS PHYSICAL VIOLENCE USED TOWARDS HOSTAGE',
      label: 'Was physical violence used towards hostage?',
      multipleAnswers: false,
      answers: [
        {
          id: '179920',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44777',
        },
        {
          id: '179919',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44777',
        },
      ],
    },
    '44452': {
      code: '44452',
      active: false,
      question: 'WERE WEAPONS USED BY THE PERPETRATOR',
      label: 'Were weapons used by the perpetrator?',
      multipleAnswers: false,
      answers: [
        {
          id: '179989',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44474',
        },
        {
          id: '179990',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
      ],
    },
    '44463': {
      code: '44463',
      active: false,
      question: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '180034',
          response: 'ADMINISTRATION',
          active: false,
          label: 'Administration',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180035',
          response: 'ASSOCIATION AREA',
          active: false,
          label: 'Association area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180036',
          response: 'CELL',
          active: false,
          label: 'Cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180037',
          response: 'CHAPEL',
          active: false,
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180039',
          response: 'DINING ROOM',
          active: false,
          label: 'Dining room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180040',
          response: 'DORMITORY',
          active: false,
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180041',
          response: 'EDUCATION',
          active: false,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180043',
          response: 'EXERCISE YARD',
          active: false,
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180045',
          response: 'GATE',
          active: false,
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180046',
          response: 'GYM',
          active: false,
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180047',
          response: 'HEALTH CARE CENTRE',
          active: false,
          label: 'Health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180050',
          response: 'KITCHEN',
          active: false,
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180052',
          response: 'OFFICE',
          active: false,
          label: 'Office',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180054',
          response: 'RECEPTION',
          active: false,
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180055',
          response: 'RECESS',
          active: false,
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180056',
          response: 'SEGREGATION UNIT',
          active: false,
          label: 'Segregation unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180058',
          response: 'SPECIAL UNIT',
          active: false,
          label: 'Special unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180057',
          response: 'SHOWERS/CHANGING ROOM',
          active: false,
          label: 'Showers/changing room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180061',
          response: 'VISITS',
          active: false,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180063',
          response: 'WING',
          active: false,
          label: 'Wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180065',
          response: 'WORKS DEPARTMENT',
          active: false,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180066',
          response: 'WORKSHOP',
          active: false,
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180064',
          response: 'WITHIN PERIMETER',
          active: false,
          label: 'Within perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180042',
          response: 'ELSEWHERE',
          active: false,
          label: 'Elsewhere',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180044',
          response: 'FUNERAL',
          active: false,
          label: 'Funeral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180048',
          response: 'HOSPITAL OUTSIDE (PATIENT)',
          active: false,
          label: 'Hospital outside (patient)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180049',
          response: 'HOSPITAL OUTSIDE (VISITING)',
          active: false,
          label: 'Hospital outside (visiting)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180053',
          response: 'OUTSIDE WORKING PARTY',
          active: false,
          label: 'Outside working party',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180059',
          response: 'SPORTS FIELD',
          active: false,
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180060',
          response: 'VEHICLE',
          active: false,
          label: 'Vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180062',
          response: 'WEDDINGS',
          active: false,
          label: 'Weddings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180051',
          response: 'MAGISTRATES COURT',
          active: false,
          label: 'Magistrates court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          id: '180038',
          response: 'CROWN COURT',
          active: true,
          label: 'Crown court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
      ],
    },
    '44474': {
      code: '44474',
      active: false,
      question: 'DESCRIBE WEAPONS USED',
      label: 'Describe weapons used',
      multipleAnswers: true,
      answers: [
        {
          id: '180117',
          response: 'FIREARM',
          active: false,
          label: 'Firearm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180114',
          response: 'CHEMICAL INCAPACITANT',
          active: false,
          label: 'Chemical incapacitant',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180119',
          response: 'KNIFE/BLADE',
          active: false,
          label: 'Knife/blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180122',
          response: 'OTHER SHARP INSTRUMENT',
          active: false,
          label: 'Other sharp instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180113',
          response: 'BLUNT INSTRUMENT',
          active: false,
          label: 'Blunt instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180120',
          response: 'LIGATURE',
          active: false,
          label: 'Ligature',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180115',
          response: 'DANGEROUS LIQUID',
          active: false,
          label: 'Dangerous liquid',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180116',
          response: 'EXCRETA/URINE',
          active: false,
          label: 'Excreta/urine',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180123',
          response: 'SPITTING',
          active: false,
          label: 'Spitting',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180118',
          response: 'FOOD',
          active: false,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180125',
          response: 'THROWN FURNITURE',
          active: false,
          label: 'Thrown furniture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180124',
          response: 'THROWN EQUIPMENT',
          active: false,
          label: 'Thrown equipment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          id: '180121',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45162',
        },
      ],
    },
    '44488': {
      code: '44488',
      active: false,
      question: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'Was the system re-activated locally or by the service supplier?',
      multipleAnswers: false,
      answers: [
        {
          id: '180167',
          response: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '180168',
          response: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44497': {
      code: '44497',
      active: false,
      question: 'WAS A BARRICADE USED',
      label: 'Was a barricade used?',
      multipleAnswers: false,
      answers: [
        {
          id: '180207',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44614',
        },
        {
          id: '180208',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44431',
        },
      ],
    },
    '44555': {
      code: '44555',
      active: false,
      question: 'WAS THE AMBULANCE SERVICE PRESENT',
      label: 'Was the ambulance service present?',
      multipleAnswers: false,
      answers: [
        {
          id: '180454',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45078',
        },
        {
          id: '180453',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45078',
        },
      ],
    },
    '44564': {
      code: '44564',
      active: false,
      question: 'ENTER NUMBER OF PERPETRATORS',
      label: 'Enter number of perpetrators',
      multipleAnswers: false,
      answers: [
        {
          id: '180472',
          response: 'NUMBER',
          active: false,
          label: 'Number',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45004',
        },
      ],
    },
    '44569': {
      code: '44569',
      active: false,
      question: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          id: '180486',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44335',
        },
        {
          id: '180485',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44335',
        },
      ],
    },
    '44585': {
      code: '44585',
      active: false,
      question: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'Describe how the incident was resolved',
      multipleAnswers: false,
      answers: [
        {
          id: '180536',
          response: 'INTERVENTION',
          active: false,
          label: 'Intervention',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44814',
        },
        {
          id: '180537',
          response: 'NEGOTIATION',
          active: false,
          label: 'Negotiation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44891',
        },
        {
          id: '180538',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44891',
        },
      ],
    },
    '44600': {
      code: '44600',
      active: false,
      question: 'DESCRIBE THE DAMAGE',
      label: 'Describe the damage',
      multipleAnswers: false,
      answers: [
        {
          id: '180602',
          response: 'MINOR',
          active: false,
          label: 'Minor',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44213',
        },
        {
          id: '180603',
          response: 'SERIOUS',
          active: false,
          label: 'Serious',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44213',
        },
        {
          id: '180601',
          response: 'EXTENSIVE',
          active: false,
          label: 'Extensive',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44213',
        },
      ],
    },
    '44608': {
      code: '44608',
      active: false,
      question: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '180622',
          response: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: false,
          label: 'Grazes, scratches or abrasions',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          id: '180623',
          response: 'MINOR BRUISES',
          active: false,
          label: 'Minor bruises',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          id: '180626',
          response: 'SWELLINGS',
          active: false,
          label: 'Swellings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          id: '180625',
          response: 'SUPERFICIAL CUTS',
          active: false,
          label: 'Superficial cuts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          id: '180624',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45059',
        },
      ],
    },
    '44611': {
      code: '44611',
      active: false,
      question: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      label: 'Describe what was compromised and by whom',
      multipleAnswers: false,
      answers: [
        {
          id: '180631',
          response: 'DESCRIPTION',
          active: false,
          label: 'Description',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44817',
        },
      ],
    },
    '44613': {
      code: '44613',
      active: false,
      question: 'WAS A MINOR INJURY SUSTAINED',
      label: 'Was a minor injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '180637',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44608',
        },
        {
          id: '180638',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
      ],
    },
    '44614': {
      code: '44614',
      active: false,
      question: 'WAS A HOSTAGE PART OF THE BARRICADE',
      label: 'Was a hostage part of the barricade?',
      multipleAnswers: false,
      answers: [
        {
          id: '180640',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44431',
        },
        {
          id: '180639',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44431',
        },
      ],
    },
    '44690': {
      code: '44690',
      active: false,
      question: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '180879',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45135',
        },
        {
          id: '180878',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45135',
        },
      ],
    },
    '44693': {
      code: '44693',
      active: false,
      question: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '180893',
          response: 'FRACTURE',
          active: false,
          label: 'Fracture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180895',
          response: 'SCALD OR BURN',
          active: false,
          label: 'Scald or burn',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180896',
          response: 'STABBING',
          active: false,
          label: 'Stabbing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180890',
          response: 'CRUSHING',
          active: false,
          label: 'Crushing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180892',
          response: 'EXTENSIVE/MULTIPLE BRUISING',
          active: false,
          label: 'Extensive/multiple bruising',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180887',
          response: 'BLACK EYE',
          active: false,
          label: 'Black eye',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180888',
          response: 'BROKEN NOSE',
          active: false,
          label: 'Broken nose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180889',
          response: 'BROKEN TEETH',
          active: false,
          label: 'Broken teeth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180891',
          response: 'CUTS REQUIRING SUTURES',
          active: false,
          label: 'Cuts requiring sutures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180886',
          response: 'BITES',
          active: false,
          label: 'Bites',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180894',
          response: 'GUN SHOT WOUND',
          active: false,
          label: 'Gun shot wound',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          id: '180897',
          response: 'TEMPORARY/PERMANENT BLINDNESS',
          active: false,
          label: 'Temporary/permanent blindness',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
      ],
    },
    '44711': {
      code: '44711',
      active: false,
      question: 'WERE HEALTH CARE CENTRE STAFF PRESENT',
      label: 'Were health care centre staff present?',
      multipleAnswers: false,
      answers: [
        {
          id: '180983',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44555',
        },
        {
          id: '180982',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44555',
        },
      ],
    },
    '44777': {
      code: '44777',
      active: false,
      question: 'WAS THE HOSTAGE PHYSICALLY RESTRAINED BY THE PERPETRATOR',
      label: 'Was the hostage physically restrained by the perpetrator?',
      multipleAnswers: false,
      answers: [
        {
          id: '181173',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44585',
        },
        {
          id: '181172',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44585',
        },
      ],
    },
    '44788': {
      code: '44788',
      active: false,
      question: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      label: 'What time was the system shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '181205',
          response: 'ENTER TIME',
          active: false,
          label: 'Enter time',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45012',
        },
      ],
    },
    '44805': {
      code: '44805',
      active: false,
      question: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'Was the telephone/it system shut down locally or by the service supplier?',
      multipleAnswers: false,
      answers: [
        {
          id: '181269',
          response: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
        {
          id: '181268',
          response: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44403',
        },
      ],
    },
    '44814': {
      code: '44814',
      active: false,
      question: 'WAS A DOOR JACK USED',
      label: 'Was a door jack used?',
      multipleAnswers: false,
      answers: [
        {
          id: '181293',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44257',
        },
        {
          id: '181292',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44257',
        },
      ],
    },
    '44817': {
      code: '44817',
      active: false,
      question: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      label: 'When was the system re-activated?',
      multipleAnswers: false,
      answers: [
        {
          id: '181298',
          response: 'ENTER COMMENT AND DATE',
          active: false,
          label: 'Enter comment and date',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '44488',
        },
      ],
    },
    '44823': {
      code: '44823',
      active: false,
      question: 'DESCRIBE STATUS OF PERPETRATORS',
      label: 'Describe status of perpetrators',
      multipleAnswers: true,
      answers: [
        {
          id: '181309',
          response: 'PRISONER',
          active: false,
          label: 'Prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44497',
        },
        {
          id: '181310',
          response: 'VISITOR',
          active: false,
          label: 'Visitor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44497',
        },
        {
          id: '181308',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44497',
        },
      ],
    },
    '44831': {
      code: '44831',
      active: false,
      question: 'WAS THE KEYWORD REQUESTED?',
      label: 'Was the keyword requested?',
      multipleAnswers: false,
      answers: [
        {
          id: '181327',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44356',
        },
        {
          id: '181328',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
      ],
    },
    '44891': {
      code: '44891',
      active: false,
      question: 'WAS THERE EVIDENCE OF THE STOCKHOLM SYNDROME',
      label: 'Was there evidence of the Stockholm syndrome?',
      multipleAnswers: false,
      answers: [
        {
          id: '181557',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44322',
        },
        {
          id: '181556',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44322',
        },
      ],
    },
    '44937': {
      code: '44937',
      active: false,
      question: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF INCIDENT',
      label: 'Are any staff on sick leave as a result of incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181748',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44564',
        },
        {
          id: '181747',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44564',
        },
      ],
    },
    '44939': {
      code: '44939',
      active: false,
      question: 'WERE FIREARMS OFFICERS DEPLOYED',
      label: 'Were firearms officers deployed?',
      multipleAnswers: false,
      answers: [
        {
          id: '181752',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44210',
        },
        {
          id: '181751',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44210',
        },
      ],
    },
    '44959': {
      code: '44959',
      active: false,
      question: 'WAS THE EMERGENCY RESPONSE VEHICLE PRESENT',
      label: 'Was the emergency response vehicle present?',
      multipleAnswers: false,
      answers: [
        {
          id: '181821',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45079',
        },
        {
          id: '181820',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45079',
        },
      ],
    },
    '44963': {
      code: '44963',
      active: false,
      question: 'WAS A TECHNICAL SUPPORT UNIT PRESENT',
      label: 'Was a technical support unit present?',
      multipleAnswers: false,
      answers: [
        {
          id: '181832',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44411',
        },
        {
          id: '181831',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44411',
        },
      ],
    },
    '45004': {
      code: '45004',
      active: false,
      question: 'ENTER NUMBER OF HOSTAGES',
      label: 'Enter number of hostages',
      multipleAnswers: false,
      answers: [
        {
          id: '181969',
          response: 'NUMBER',
          active: false,
          label: 'Number',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45143',
        },
      ],
    },
    '45012': {
      code: '45012',
      active: false,
      question: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      label: 'Was this a full or partial shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '181991',
          response: 'FULL',
          active: false,
          label: 'Full',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44239',
        },
        {
          id: '181992',
          response: 'PARTIAL',
          active: false,
          label: 'Partial',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44239',
        },
      ],
    },
    '45059': {
      code: '45059',
      active: false,
      question: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'Enter description of person(s) injured',
      multipleAnswers: true,
      answers: [
        {
          id: '182220',
          response: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          id: '182219',
          response: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          id: '182216',
          response: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          id: '182218',
          response: 'POLICE',
          active: false,
          label: 'Police',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          id: '182217',
          response: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
      ],
    },
    '45076': {
      code: '45076',
      active: false,
      question: 'WAS THE SYSTEM COMPROMISED?',
      label: 'Was the system compromised?',
      multipleAnswers: false,
      answers: [
        {
          id: '182272',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44611',
        },
        {
          id: '182273',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44817',
        },
      ],
    },
    '45078': {
      code: '45078',
      active: false,
      question: 'WAS THE FIRE SERVICE PRESENT',
      label: 'Was the fire service present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182277',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45148',
        },
        {
          id: '182276',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45148',
        },
      ],
    },
    '45079': {
      code: '45079',
      active: false,
      question: 'WAS AN INCIDENT LIAISON OFFICER PRESENT',
      label: 'Was an incident liaison officer present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182279',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45087',
        },
        {
          id: '182278',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45087',
        },
      ],
    },
    '45087': {
      code: '45087',
      active: false,
      question: 'WAS A MEDICAL OFFICER PRESENT',
      label: 'Was a medical officer present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182298',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44711',
        },
        {
          id: '182297',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44711',
        },
      ],
    },
    '45093': {
      code: '45093',
      active: false,
      question: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '182322',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44569',
        },
        {
          id: '182321',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44569',
        },
      ],
    },
    '45101': {
      code: '45101',
      active: false,
      question: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'Was a serious injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '182344',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44693',
        },
        {
          id: '182345',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
      ],
    },
    '45135': {
      code: '45135',
      active: false,
      question: 'THE INCIDENT IS SUBJECT TO',
      label: 'The incident is subject to',
      multipleAnswers: true,
      answers: [
        {
          id: '182509',
          response: 'INVESTIGATION BY POLICE',
          active: false,
          label: 'Investigation by police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
        {
          id: '182510',
          response: 'INVESTIGATION INTERNALLY',
          active: false,
          label: 'Investigation internally',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
        {
          id: '182508',
          response: "GOVERNOR'S ADJUDICATION",
          active: false,
          label: "Governor's adjudication",
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
        {
          id: '182511',
          response: 'NO INVESTIGATION',
          active: false,
          label: 'No investigation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
      ],
    },
    '45143': {
      code: '45143',
      active: false,
      question: 'DESCRIBE STATUS OF HOSTAGES',
      label: 'Describe status of hostages',
      multipleAnswers: true,
      answers: [
        {
          id: '182538',
          response: 'PRISONER',
          active: false,
          label: 'Prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          id: '182539',
          response: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          id: '182536',
          response: 'OFFICER',
          active: false,
          label: 'Officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          id: '182535',
          response: 'CIVILIAN STAFF',
          active: false,
          label: 'Civilian staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          id: '182537',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44823',
        },
      ],
    },
    '45148': {
      code: '45148',
      active: false,
      question: 'WERE WORKS SERVICES STAFF PRESENT',
      label: 'Were works services staff present?',
      multipleAnswers: false,
      answers: [
        {
          id: '182554',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44265',
        },
        {
          id: '182553',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44265',
        },
      ],
    },
    '45162': {
      code: '45162',
      active: false,
      question: 'DURATION OF INCIDENT IN HOURS',
      label: 'Duration of incident in hours',
      multipleAnswers: false,
      answers: [
        {
          id: '182603',
          response: 'HOURS',
          active: false,
          label: 'Hours',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44311',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'HOSTAGE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default HOSTAGE_1
