// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:50.691Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const INCIDENT_AT_HEIGHT_1: IncidentTypeConfiguration = {
  incidentType: 'INCIDENT_AT_HEIGHT_1',
  active: false,
  startingQuestionCode: '44417',
  questions: {
    '44145': {
      code: '44145',
      active: false,
      question: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      label: 'Was this a full or partial shut down?',
      multipleAnswers: false,
      answers: [
        {
          code: '178986',
          response: 'FULL',
          active: false,
          label: 'Full',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44806',
        },
        {
          code: '178987',
          response: 'PARTIAL',
          active: false,
          label: 'Partial',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44806',
        },
      ],
    },
    '44150': {
      code: '44150',
      active: false,
      question: 'ESTIMATED COST OF DAMAGE',
      label: 'Estimated cost of damage',
      multipleAnswers: false,
      answers: [
        {
          code: '178998',
          response: 'ENTER AMOUNT IN POUND STERLING',
          active: false,
          label: 'Enter amount in pound sterling',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '45127',
        },
      ],
    },
    '44151': {
      code: '44151',
      active: false,
      question: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'Were any injuries received during this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '178999',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44518',
        },
        {
          code: '179000',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44842',
        },
      ],
    },
    '44175': {
      code: '44175',
      active: false,
      question: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'Who was detained in outside hospital?',
      multipleAnswers: true,
      answers: [
        {
          code: '179082',
          response: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44842',
        },
        {
          code: '179081',
          response: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44842',
        },
        {
          code: '179078',
          response: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44842',
        },
        {
          code: '179080',
          response: 'POLICE',
          active: false,
          label: 'Police',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44842',
        },
        {
          code: '179079',
          response: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44842',
        },
      ],
    },
    '44177': {
      code: '44177',
      active: false,
      question: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      label: 'When was the system re-activated?',
      multipleAnswers: false,
      answers: [
        {
          code: '179084',
          response: 'ENTER COMMENT AND DATE',
          active: false,
          label: 'Enter comment and date',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: true,
          nextQuestionCode: '44328',
        },
      ],
    },
    '44183': {
      code: '44183',
      active: false,
      question: 'DURATION OF INCIDENT IN HOURS',
      label: 'Duration of incident in hours',
      multipleAnswers: false,
      answers: [
        {
          code: '179096',
          response: 'NUMBER OF HOURS',
          active: false,
          label: 'Number of hours',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44639',
        },
      ],
    },
    '44196': {
      code: '44196',
      active: false,
      question: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      label: 'Was there an apparent reason for the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '179157',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44337',
        },
        {
          code: '179158',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45128',
        },
      ],
    },
    '44273': {
      code: '44273',
      active: false,
      question: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      label: 'Are any staff on sick leave as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '179384',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44487',
        },
        {
          code: '179383',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44487',
        },
      ],
    },
    '44289': {
      code: '44289',
      active: false,
      question: 'WAS THE KEYWORD REQUESTED?',
      label: 'Was the keyword requested?',
      multipleAnswers: false,
      answers: [
        {
          code: '179416',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44767',
        },
        {
          code: '179417',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45163',
        },
      ],
    },
    '44328': {
      code: '44328',
      active: false,
      question: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'Was the system re-activated locally or by the service supplier?',
      multipleAnswers: false,
      answers: [
        {
          code: '179610',
          response: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '179611',
          response: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
      ],
    },
    '44334': {
      code: '44334',
      active: false,
      question: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'Was damage caused to prison property?',
      multipleAnswers: false,
      answers: [
        {
          code: '179625',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45098',
        },
        {
          code: '179626',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45127',
        },
      ],
    },
    '44337': {
      code: '44337',
      active: false,
      question: 'DESCRIBE THE APPARENT REASON FOR THE INCIDENT',
      label: 'Describe the apparent reason for the incident',
      multipleAnswers: false,
      answers: [
        {
          code: '179631',
          response: 'FACILITIES',
          active: false,
          label: 'Facilities',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45128',
        },
        {
          code: '179632',
          response: 'FOOD',
          active: false,
          label: 'Food',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45128',
        },
        {
          code: '179634',
          response: 'PAY',
          active: false,
          label: 'Pay',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45128',
        },
        {
          code: '179636',
          response: 'VISITS',
          active: false,
          label: 'Visits',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45128',
        },
        {
          code: '179635',
          response: 'TIME OUT OF CELL',
          active: false,
          label: 'Time out of cell',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45128',
        },
        {
          code: '179633',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '45128',
        },
      ],
    },
    '44359': {
      code: '44359',
      active: false,
      question: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '179707',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44375',
        },
        {
          code: '179706',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44375',
        },
      ],
    },
    '44374': {
      code: '44374',
      active: false,
      question: 'WAS THE AMBULANCE SERVICE PRESENT',
      label: 'Was the ambulance service present?',
      multipleAnswers: false,
      answers: [
        {
          code: '179765',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44536',
        },
        {
          code: '179764',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44536',
        },
      ],
    },
    '44375': {
      code: '44375',
      active: false,
      question: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: '179767',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: true,
          nextQuestionCode: '44151',
        },
        {
          code: '179766',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44151',
        },
      ],
    },
    '44394': {
      code: '44394',
      active: false,
      question: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          code: '179828',
          response: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: false,
          label: 'Grazes, scratches or abrasions',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44462',
        },
        {
          code: '179829',
          response: 'MINOR BRUISES',
          active: false,
          label: 'Minor bruises',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44462',
        },
        {
          code: '179832',
          response: 'SWELLINGS',
          active: false,
          label: 'Swellings',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44462',
        },
        {
          code: '179831',
          response: 'SUPERFICIAL CUTS',
          active: false,
          label: 'Superficial cuts',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44462',
        },
        {
          code: '179830',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44462',
        },
      ],
    },
    '44417': {
      code: '44417',
      active: false,
      question: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          code: '179891',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44927',
        },
        {
          code: '179892',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
      ],
    },
    '44422': {
      code: '44422',
      active: false,
      question: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'Is the incident the subject of a police investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '179901',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44853',
        },
        {
          code: '179902',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44804',
        },
      ],
    },
    '44462': {
      code: '44462',
      active: false,
      question: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'Enter description of person(s) injured',
      multipleAnswers: true,
      answers: [
        {
          code: '180033',
          response: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44533',
        },
        {
          code: '180032',
          response: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44533',
        },
        {
          code: '180029',
          response: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44533',
        },
        {
          code: '180031',
          response: 'POLICE',
          active: false,
          label: 'Police',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44533',
        },
        {
          code: '180030',
          response: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44533',
        },
      ],
    },
    '44465': {
      code: '44465',
      active: false,
      question: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: '180081',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44359',
        },
        {
          code: '180080',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44359',
        },
      ],
    },
    '44469': {
      code: '44469',
      active: false,
      question: 'WERE WORKS SERVICES STAFF PRESENT',
      label: 'Were works services staff present?',
      multipleAnswers: false,
      answers: [
        {
          code: '180089',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44625',
        },
        {
          code: '180088',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44625',
        },
      ],
    },
    '44475': {
      code: '44475',
      active: false,
      question: 'WERE EXTENDABLE BATONS USED',
      label: 'Were extendable batons used?',
      multipleAnswers: false,
      answers: [
        {
          code: '180127',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44183',
        },
        {
          code: '180126',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44183',
        },
      ],
    },
    '44487': {
      code: '44487',
      active: false,
      question: 'DESCRIBE METHOD OF GAINING ACCESS TO AREA AT HEIGHT',
      label: 'Describe method of gaining access to area at height',
      multipleAnswers: false,
      answers: [
        {
          code: '180163',
          response: 'EXTERNAL ACCESS',
          active: false,
          label: 'External access',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44986',
        },
        {
          code: '180164',
          response: 'INTERNAL ACCESS',
          active: false,
          label: 'Internal access',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44986',
        },
        {
          code: '180166',
          response: 'WORKS EQUIPMENT',
          active: false,
          label: 'Works equipment',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44986',
        },
        {
          code: '180162',
          response: 'CONTRACTORS EQUIPMENT',
          active: false,
          label: 'Contractors equipment',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44986',
        },
        {
          code: '180165',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44986',
        },
      ],
    },
    '44518': {
      code: '44518',
      active: false,
      question: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'Was a serious injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          code: '180273',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45155',
        },
        {
          code: '180274',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
      ],
    },
    '44533': {
      code: '44533',
      active: false,
      question: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'Did injuries result in detention in outside hospital as an in-patient?',
      multipleAnswers: false,
      answers: [
        {
          code: '180387',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44175',
        },
        {
          code: '180388',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44842',
        },
      ],
    },
    '44536': {
      code: '44536',
      active: false,
      question: 'WAS THE FIRE SERVICE PRESENT',
      label: 'Was the fire service present?',
      multipleAnswers: false,
      answers: [
        {
          code: '180394',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44797',
        },
        {
          code: '180393',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44797',
        },
      ],
    },
    '44553': {
      code: '44553',
      active: false,
      question: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "Is the incident subject to a governor's adjudication?",
      multipleAnswers: false,
      answers: [
        {
          code: '180439',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44465',
        },
        {
          code: '180438',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44465',
        },
      ],
    },
    '44580': {
      code: '44580',
      active: false,
      question: 'WERE HEALTH CARE CENTRE STAFF PRESENT',
      label: 'Were health care centre staff present?',
      multipleAnswers: false,
      answers: [
        {
          code: '180521',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44469',
        },
        {
          code: '180520',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44469',
        },
      ],
    },
    '44596': {
      code: '44596',
      active: false,
      question: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '180594',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: true,
          nextQuestionCode: '44422',
        },
        {
          code: '180593',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44422',
        },
      ],
    },
    '44610': {
      code: '44610',
      active: false,
      question: 'WERE WATER HOSES USED',
      label: 'Were water hoses used?',
      multipleAnswers: false,
      answers: [
        {
          code: '180630',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44475',
        },
        {
          code: '180629',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44475',
        },
      ],
    },
    '44625': {
      code: '44625',
      active: false,
      question: 'WERE IMB MEMBERS PRESENT',
      label: 'Were IMB members present?',
      multipleAnswers: false,
      answers: [
        {
          code: '180667',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44374',
        },
        {
          code: '180666',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44374',
        },
      ],
    },
    '44630': {
      code: '44630',
      active: false,
      question: 'HAVE THE RING LEADERS BEEN ENTERED ON INMATE INVOLVEMENT',
      label: 'Have the ring leaders been entered on inmate involvement?',
      multipleAnswers: false,
      answers: [
        {
          code: '180694',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44756',
        },
        {
          code: '180693',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44756',
        },
      ],
    },
    '44639': {
      code: '44639',
      active: false,
      question: 'WAS THE INCIDENT IN PUBLIC VIEW',
      label: 'Was the incident in public view?',
      multipleAnswers: false,
      answers: [
        {
          code: '180726',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44334',
        },
        {
          code: '180725',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44334',
        },
      ],
    },
    '44660': {
      code: '44660',
      active: false,
      question: 'HOW MANY PRISONERS WERE INVOLVED',
      label: 'How many prisoners were involved?',
      multipleAnswers: false,
      answers: [
        {
          code: '180797',
          response: 'ENTER NUMBER',
          active: false,
          label: 'Enter number',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44889',
        },
      ],
    },
    '44687': {
      code: '44687',
      active: false,
      question: 'DESCRIBE WEAPONS USED',
      label: 'Describe weapons used',
      multipleAnswers: true,
      answers: [
        {
          code: '180865',
          response: 'FIREARM',
          active: false,
          label: 'Firearm',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180862',
          response: 'CHEMICAL INCAPACITANT',
          active: false,
          label: 'Chemical incapacitant',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180867',
          response: 'KNIFE/BLADE',
          active: false,
          label: 'Knife/blade',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180870',
          response: 'OTHER SHARP INSTRUMENT',
          active: false,
          label: 'Other sharp instrument',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180861',
          response: 'BLUNT INSTRUMENT',
          active: false,
          label: 'Blunt instrument',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180868',
          response: 'LIGATURE',
          active: false,
          label: 'Ligature',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180863',
          response: 'DANGEROUS LIQUID',
          active: false,
          label: 'Dangerous liquid',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180864',
          response: 'EXCRETA/URINE',
          active: false,
          label: 'Excreta/urine',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180871',
          response: 'SPITTING',
          active: false,
          label: 'Spitting',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180866',
          response: 'FOOD',
          active: false,
          label: 'Food',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180873',
          response: 'THROWN FURNITURE',
          active: false,
          label: 'Thrown furniture',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180872',
          response: 'THROWN EQUIPMENT',
          active: false,
          label: 'Thrown equipment',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
        {
          code: '180869',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
      ],
    },
    '44710': {
      code: '44710',
      active: false,
      question: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      label: 'Was control and restraints employed?',
      multipleAnswers: false,
      answers: [
        {
          code: '180981',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44610',
        },
        {
          code: '180980',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44610',
        },
      ],
    },
    '44714': {
      code: '44714',
      active: false,
      question: 'QUOTE THE VANTIVE CASE NUMBER',
      label: 'Quote the Vantive case number',
      multipleAnswers: false,
      answers: [
        {
          code: '180987',
          response: 'NUMBER',
          active: false,
          label: 'Number',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44289',
        },
      ],
    },
    '44725': {
      code: '44725',
      active: false,
      question: 'WAS ANY EVACUATION NECESSARY',
      label: 'Was any evacuation necessary?',
      multipleAnswers: false,
      answers: [
        {
          code: '181034',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44196',
        },
        {
          code: '181033',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44196',
        },
      ],
    },
    '44756': {
      code: '44756',
      active: false,
      question: 'WAS OPERATION TORNADO USED',
      label: 'Was operation Tornado used?',
      multipleAnswers: false,
      answers: [
        {
          code: '181118',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44710',
        },
        {
          code: '181117',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44710',
        },
      ],
    },
    '44767': {
      code: '44767',
      active: false,
      question: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      label: 'Has the service supplier been notified of a replacement keyword?',
      multipleAnswers: false,
      answers: [
        {
          code: '181148',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45163',
        },
        {
          code: '181147',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45163',
        },
      ],
    },
    '44780': {
      code: '44780',
      active: false,
      question: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'Describe how the incident was resolved',
      multipleAnswers: false,
      answers: [
        {
          code: '181178',
          response: 'NEGOTIATION',
          active: false,
          label: 'Negotiation',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44660',
        },
        {
          code: '181177',
          response: 'INTERVENTION',
          active: false,
          label: 'Intervention',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44660',
        },
        {
          code: '181179',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44660',
        },
      ],
    },
    '44797': {
      code: '44797',
      active: false,
      question: 'WERE THE POLICE PRESENT',
      label: 'Were the police present?',
      multipleAnswers: false,
      answers: [
        {
          code: '181252',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44873',
        },
        {
          code: '181251',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44873',
        },
      ],
    },
    '44804': {
      code: '44804',
      active: false,
      question: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'Is the incident the subject of an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '181267',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44553',
        },
        {
          code: '181266',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44553',
        },
      ],
    },
    '44806': {
      code: '44806',
      active: false,
      question: 'WHO AUTHORISED THE SHUT DOWN?',
      label: 'Who authorised the shut down?',
      multipleAnswers: false,
      answers: [
        {
          code: '181272',
          response: 'GOVERNOR',
          active: false,
          label: 'Governor',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44825',
        },
        {
          code: '181270',
          response: 'DEPUTY GOVERNOR',
          active: false,
          label: 'Deputy governor',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44825',
        },
        {
          code: '181271',
          response: 'DUTY GOVERNOR',
          active: false,
          label: 'Duty governor',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44825',
        },
        {
          code: '181273',
          response: 'OTHER',
          active: false,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44825',
        },
      ],
    },
    '44815': {
      code: '44815',
      active: false,
      question: 'WERE TRAINED NEGOTIATORS DEPLOYED',
      label: 'Were trained negotiators deployed?',
      multipleAnswers: false,
      answers: [
        {
          code: '181295',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44951',
        },
        {
          code: '181294',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44951',
        },
      ],
    },
    '44825': {
      code: '44825',
      active: false,
      question: 'WAS THE SYSTEM COMPROMISED?',
      label: 'Was the system compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '181313',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44847',
        },
        {
          code: '181314',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44177',
        },
      ],
    },
    '44842': {
      code: '44842',
      active: false,
      question: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'Are there any staff now off duty as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '181359',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44273',
        },
        {
          code: '181358',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44273',
        },
      ],
    },
    '44847': {
      code: '44847',
      active: false,
      question: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      label: 'Describe what was compromised and by whom',
      multipleAnswers: false,
      answers: [
        {
          code: '181375',
          response: 'DESCRIPTION',
          active: false,
          label: 'Description',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44177',
        },
      ],
    },
    '44853': {
      code: '44853',
      active: false,
      question: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'Has any prosecution taken place or is any pending?',
      multipleAnswers: false,
      answers: [
        {
          code: '181399',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44804',
        },
        {
          code: '181398',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44804',
        },
      ],
    },
    '44873': {
      code: '44873',
      active: false,
      question: 'WERE WEAPONS USED BY THE PERPETRATOR',
      label: 'Were weapons used by the perpetrator?',
      multipleAnswers: false,
      answers: [
        {
          code: '181492',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44687',
        },
        {
          code: '181493',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44725',
        },
      ],
    },
    '44889': {
      code: '44889',
      active: false,
      question: 'HAVE THE RING LEADERS BEEN IDENTIFIED',
      label: 'Have the ring leaders been identified?',
      multipleAnswers: false,
      answers: [
        {
          code: '181551',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44630',
        },
        {
          code: '181550',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44630',
        },
      ],
    },
    '44892': {
      code: '44892',
      active: false,
      question: 'WAS THE EMERGENCY RESPONSE VEHICLE PRESENT',
      label: 'Was the emergency response vehicle present?',
      multipleAnswers: false,
      answers: [
        {
          code: '181559',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44815',
        },
        {
          code: '181558',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44815',
        },
      ],
    },
    '44927': {
      code: '44927',
      active: false,
      question: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '181684',
          response: 'ADMINISTRATION',
          active: false,
          label: 'Administration',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181685',
          response: 'ASSOCIATION AREA',
          active: false,
          label: 'Association area',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181686',
          response: 'CELL',
          active: false,
          label: 'Cell',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181687',
          response: 'CHAPEL',
          active: false,
          label: 'Chapel',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181689',
          response: 'DINING ROOM',
          active: false,
          label: 'Dining room',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181690',
          response: 'DORMITORY',
          active: false,
          label: 'Dormitory',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181691',
          response: 'EDUCATION',
          active: false,
          label: 'Education',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181693',
          response: 'EXERCISE YARD',
          active: false,
          label: 'Exercise yard',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181695',
          response: 'GATE',
          active: false,
          label: 'Gate',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181696',
          response: 'GYM',
          active: false,
          label: 'Gym',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181697',
          response: 'HEALTH CARE CENTRE',
          active: false,
          label: 'Health care centre',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181700',
          response: 'KITCHEN',
          active: false,
          label: 'Kitchen',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181702',
          response: 'OFFICE',
          active: false,
          label: 'Office',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181704',
          response: 'RECEPTION',
          active: false,
          label: 'Reception',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181705',
          response: 'RECESS',
          active: false,
          label: 'Recess',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181706',
          response: 'SEGREGATION UNIT',
          active: false,
          label: 'Segregation unit',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181708',
          response: 'SPECIAL UNIT',
          active: false,
          label: 'Special unit',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181707',
          response: 'SHOWERS/CHANGING ROOM',
          active: false,
          label: 'Showers/changing room',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181711',
          response: 'VISITS',
          active: false,
          label: 'Visits',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181713',
          response: 'WING',
          active: false,
          label: 'Wing',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181715',
          response: 'WORKS DEPARTMENT',
          active: false,
          label: 'Works department',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181716',
          response: 'WORKSHOP',
          active: false,
          label: 'Workshop',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181714',
          response: 'WITHIN PERIMETER',
          active: false,
          label: 'Within perimeter',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181692',
          response: 'ELSEWHERE',
          active: false,
          label: 'Elsewhere',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181694',
          response: 'FUNERAL',
          active: false,
          label: 'Funeral',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181698',
          response: 'HOSPITAL OUTSIDE (PATIENT)',
          active: false,
          label: 'Hospital outside (patient)',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181699',
          response: 'HOSPITAL OUTSIDE (VISITING)',
          active: false,
          label: 'Hospital outside (visiting)',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181703',
          response: 'OUTSIDE WORKING PARTY',
          active: false,
          label: 'Outside working party',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181709',
          response: 'SPORTS FIELD',
          active: false,
          label: 'Sports field',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181710',
          response: 'VEHICLE',
          active: false,
          label: 'Vehicle',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181712',
          response: 'WEDDINGS',
          active: false,
          label: 'Weddings',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181701',
          response: 'MAGISTRATES COURT',
          active: false,
          label: 'Magistrates court',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
        {
          code: '181688',
          response: 'CROWN COURT',
          active: false,
          label: 'Crown court',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44596',
        },
      ],
    },
    '44951': {
      code: '44951',
      active: false,
      question: 'WAS AN INCIDENT LIAISON OFFICER PRESENT',
      label: 'Was an incident liaison officer present?',
      multipleAnswers: false,
      answers: [
        {
          code: '181799',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44580',
        },
        {
          code: '181798',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44580',
        },
      ],
    },
    '44985': {
      code: '44985',
      active: false,
      question: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'Was the telephone/it system shut down locally or by the service supplier?',
      multipleAnswers: false,
      answers: [
        {
          code: '181921',
          response: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45163',
        },
        {
          code: '181920',
          response: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44714',
        },
      ],
    },
    '44986': {
      code: '44986',
      active: false,
      question: 'WAS A CANDR ADVISOR PRESENT',
      label: 'Was a CANDR advisor present?',
      multipleAnswers: false,
      answers: [
        {
          code: '181923',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44892',
        },
        {
          code: '181922',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44892',
        },
      ],
    },
    '45028': {
      code: '45028',
      active: false,
      question: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      label: 'What time was the system shut down?',
      multipleAnswers: false,
      answers: [
        {
          code: '182044',
          response: 'ENTER TIME',
          active: false,
          label: 'Enter time',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '44145',
        },
      ],
    },
    '45098': {
      code: '45098',
      active: false,
      question: 'DESCRIBE THE DAMAGE',
      label: 'Describe the damage',
      multipleAnswers: false,
      answers: [
        {
          code: '182338',
          response: 'MINOR',
          active: false,
          label: 'Minor',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44150',
        },
        {
          code: '182339',
          response: 'SERIOUS',
          active: false,
          label: 'Serious',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44150',
        },
        {
          code: '182337',
          response: 'EXTENSIVE',
          active: false,
          label: 'Extensive',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44150',
        },
      ],
    },
    '45127': {
      code: '45127',
      active: false,
      question: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      label: 'Was the telephone/it system shut down during the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '182461',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44985',
        },
        {
          code: '182462',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
      ],
    },
    '45128': {
      code: '45128',
      active: false,
      question: 'DESCRIBE THE INCIDENT AS EITHER ACTIVE OR PASSIVE',
      label: 'Describe the incident as either active or passive',
      multipleAnswers: false,
      answers: [
        {
          code: '182463',
          response: 'ACTIVE',
          active: false,
          label: 'Active',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44780',
        },
        {
          code: '182464',
          response: 'PASSIVE',
          active: false,
          label: 'Passive',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44780',
        },
      ],
    },
    '45155': {
      code: '45155',
      active: false,
      question: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          code: '182583',
          response: 'FRACTURE',
          active: false,
          label: 'Fracture',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182585',
          response: 'SCALD OR BURN',
          active: false,
          label: 'Scald or burn',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182586',
          response: 'STABBING',
          active: false,
          label: 'Stabbing',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182580',
          response: 'CRUSHING',
          active: false,
          label: 'Crushing',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182582',
          response: 'EXTENSIVE/MULTIPLE BRUISING',
          active: false,
          label: 'Extensive/multiple bruising',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182577',
          response: 'BLACK EYE',
          active: false,
          label: 'Black eye',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182578',
          response: 'BROKEN NOSE',
          active: false,
          label: 'Broken nose',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182579',
          response: 'BROKEN TEETH',
          active: false,
          label: 'Broken teeth',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182581',
          response: 'CUTS REQUIRING SUTURES',
          active: false,
          label: 'Cuts requiring sutures',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182576',
          response: 'BITES',
          active: false,
          label: 'Bites',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182584',
          response: 'GUN SHOT WOUND',
          active: false,
          label: 'Gun shot wound',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
        {
          code: '182587',
          response: 'TEMPORARY/PERMANENT BLINDNESS',
          active: false,
          label: 'Temporary/permanent blindness',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45175',
        },
      ],
    },
    '45163': {
      code: '45163',
      active: false,
      question: 'INDICATE THE NATURE OF THE SHUT DOWN',
      label: 'Indicate the nature of the shut down',
      multipleAnswers: true,
      answers: [
        {
          code: '182605',
          response: 'TELEPHONY',
          active: false,
          label: 'Telephony',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '45028',
        },
        {
          code: '182604',
          response: 'IT',
          active: false,
          label: 'IT',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: '45028',
        },
      ],
    },
    '45175': {
      code: '45175',
      active: false,
      question: 'WAS A MINOR INJURY SUSTAINED',
      label: 'Was a minor injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          code: '182643',
          response: 'YES',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44394',
        },
        {
          code: '182644',
          response: 'NO',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44462',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default INCIDENT_AT_HEIGHT_1
