// Key or lock compromise v3 (live from 2026-08-01): a branching flow defined by the Safety team.
// A single triage question routes to a type/method pair for keys, locks, doors or gates,
// handcuffs, or any other locking device, and every branch finishes on a shared risk-level
// question. Replaces the legacy NOMIS questionnaire's single mixed checkbox list along with its
// remedial-action and cost questions.
//
// Every question is single-answer: the triage question branches, and a multiple-answer question
// whose answers lead to different next questions is rejected by validateConfig().
//
// Every question/answer code is freshly allocated (globally unique) so the config can be
// back-synced to NOMIS without PK clashes.

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

/** Shared class-of-lock definitions, shown as hint text under the class options on Q2a and Q2b */
const CLASS_1_HINT =
  'Used in the highest security areas to create a strong and secure perimeter. They protect important entry and exit points, such as cell doors, prison entrances, and perimeter gates.'
const CLASS_2_HINT =
  'Used where security is still important but a lower level of control is needed. They are typically fitted to internal doors, gates, and buildings within the prison’s secure perimeter.'
const CLASS_3_HINT =
  'Used in lower-risk areas for everyday access control. They are commonly found on offices, staff facilities, and buildings outside the prison’s secure perimeter.'

export const KEY_OR_LOCK_3: IncidentTypeConfiguration = {
  incidentType: 'KEY_OR_LOCK_3',
  active: true,
  startingQuestionCode: '900008',
  questions: {
    '900008': {
      code: '900008',
      active: true,
      question: 'key_lock_incident_type',
      label: 'What type of key lock incident occurred?',
      multipleAnswers: false,
      answers: [
        {
          code: '950042',
          response: 'Key',
          active: true,
          label: 'Key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900009',
        },
        {
          code: '950043',
          response: 'Lock',
          active: true,
          label: 'Lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900011',
        },
        {
          code: '950044',
          response: 'Door or gate',
          active: true,
          label: 'Door or gate',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900013',
        },
        {
          code: '950045',
          response: 'Handcuffs',
          active: true,
          label: 'Handcuffs',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900015',
        },
        {
          code: '950046',
          response: 'Other',
          active: true,
          label: 'Other',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900017',
        },
      ],
    },
    '900009': {
      code: '900009',
      active: true,
      question: 'key_type',
      label: 'What type of key was compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950047',
          response: 'Brent keys',
          active: true,
          label: 'Brent keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950048',
          response: 'Class 1 pass key',
          active: true,
          label: 'Class 1 pass key',
          responseHint: CLASS_1_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950049',
          response: 'Class 2 pass key',
          active: true,
          label: 'Class 2 pass key',
          responseHint: CLASS_2_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950050',
          response: 'Class 3 A1 Suite key',
          active: true,
          label: 'Class 3 A1 Suite key',
          responseHint: CLASS_3_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950051',
          response: 'Class 3 Accountable key',
          active: true,
          label: 'Class 3 Accountable key',
          responseHint: CLASS_3_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950052',
          response: 'Cell key',
          active: true,
          label: 'Cell key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950053',
          response: 'Escort chain key',
          active: true,
          label: 'Escort chain key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950054',
          response: 'Handcuff key',
          active: true,
          label: 'Handcuff key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950055',
          response: 'Magnetic keys',
          active: true,
          label: 'Magnetic keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950056',
          response: 'Transport vehicle key',
          active: true,
          label: 'Transport vehicle key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
        {
          code: '950057',
          response: 'Other',
          active: true,
          label: 'Other',
          commentRequested: true,
          commentLabel: 'Provide details',
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '900010',
        },
      ],
    },
    '900010': {
      code: '900010',
      active: true,
      question: 'key_compromise_method',
      label: 'How was key compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950059',
          response: 'Damaged',
          active: true,
          label: 'Damaged',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950058',
          response: 'Attempted key snatch',
          active: true,
          label: 'Attempted key snatch',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950060',
          response: 'Details of the key recorded by the media or other unauthorised organisation',
          active: true,
          label: 'Details of the key recorded by the media or other unauthorised organisation',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950061',
          response: 'Evidence of creating or attempting to make a duplicate of key',
          active: true,
          label: 'Evidence of creating or attempting to make a duplicate of key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950062',
          response: 'Key issued to wrong person',
          active: true,
          label: 'Key issued to wrong person',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950063',
          response: 'Key(s) snatched',
          active: true,
          label: 'Key(s) snatched',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950064',
          response: 'Key taken out of establishment',
          active: true,
          label: 'Key taken out of establishment',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950065',
          response: 'Lost or missing',
          active: true,
          label: 'Lost or missing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950066',
          response: 'Replica key found',
          active: true,
          label: 'Replica key found',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
      ],
    },
    '900011': {
      code: '900011',
      active: true,
      question: 'lock_type',
      label: 'What type of lock was compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950067',
          response: 'Class 1 lock',
          active: true,
          label: 'Class 1 lock',
          responseHint: CLASS_1_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950068',
          response: 'Class 2 lock',
          active: true,
          label: 'Class 2 lock',
          responseHint: CLASS_2_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950069',
          response: 'Cell lock',
          active: true,
          label: 'Cell lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950070',
          response: 'Class 3 A1 Suite lock',
          active: true,
          label: 'Class 3 A1 Suite lock',
          responseHint: CLASS_3_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950071',
          response: 'Class 3 Accountable lock',
          active: true,
          label: 'Class 3 Accountable lock',
          responseHint: CLASS_3_HINT,
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950072',
          response: 'Electronic lock system',
          active: true,
          label: 'Electronic lock system',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950073',
          response: 'Magnetic lock',
          active: true,
          label: 'Magnetic lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950074',
          response: 'Padlock',
          active: true,
          label: 'Padlock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
        {
          code: '950075',
          response: 'Other',
          active: true,
          label: 'Other',
          commentRequested: true,
          commentLabel: 'Provide details',
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '900012',
        },
      ],
    },
    '900012': {
      code: '900012',
      active: true,
      question: 'lock_compromise_method',
      label: 'How was lock compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950080',
          response: 'Malicious damage',
          active: true,
          label: 'Malicious damage',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950076',
          response: 'Evidence of tampering',
          active: true,
          label: 'Evidence of tampering',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950077',
          response: 'Lock completely removed',
          active: true,
          label: 'Lock completely removed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950078',
          response: 'Lock partially removed',
          active: true,
          label: 'Lock partially removed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950079',
          response: 'Lock picked',
          active: true,
          label: 'Lock picked',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950081',
          response: 'Padlock missing',
          active: true,
          label: 'Padlock missing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950082',
          response: 'Worn lock (not malicious)',
          active: true,
          label: 'Worn lock (not malicious)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950083',
          response: 'Other',
          active: true,
          label: 'Other',
          commentRequested: true,
          commentLabel: 'Provide details',
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
      ],
    },
    '900013': {
      code: '900013',
      active: true,
      question: 'door_gate_type',
      label: 'What type of door or gate was compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950084',
          response: 'Cell door',
          active: true,
          label: 'Cell door',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900014',
        },
        {
          code: '950085',
          response: 'Outer gate',
          active: true,
          label: 'Outer gate',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900014',
        },
        {
          code: '950086',
          response: 'Other door or gate',
          active: true,
          label: 'Other door or gate',
          commentRequested: true,
          commentLabel: 'Provide details',
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '900014',
        },
      ],
    },
    '900014': {
      code: '900014',
      active: true,
      question: 'door_gate_compromise_method',
      label: 'How was door or gate compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950089',
          response: 'Damaged',
          active: true,
          label: 'Damaged',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950087',
          response: 'Access blocked',
          active: true,
          label: 'Access blocked',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950088',
          response: 'Blockage preventing closure',
          active: true,
          label: 'Blockage preventing closure',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950090',
          response: 'Left open',
          active: true,
          label: 'Left open',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950091',
          response: 'Removed or missing',
          active: true,
          label: 'Removed or missing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
      ],
    },
    '900015': {
      code: '900015',
      active: true,
      question: 'handcuffs_type',
      label: 'What type of handcuffs were compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950092',
          response: 'Escort chain',
          active: true,
          label: 'Escort chain',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900016',
        },
        {
          code: '950093',
          response: 'Rigid bar handcuffs',
          active: true,
          label: 'Rigid bar handcuffs',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900016',
        },
        {
          code: '950094',
          response: 'Other',
          active: true,
          label: 'Other',
          commentRequested: true,
          commentLabel: 'Provide details',
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '900016',
        },
      ],
    },
    '900016': {
      code: '900016',
      active: true,
      question: 'handcuffs_compromise_method',
      label: 'How were handcuffs compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950095',
          response: 'Damaged',
          active: true,
          label: 'Damaged',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950096',
          response: 'Lost or missing',
          active: true,
          label: 'Lost or missing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
        {
          code: '950097',
          response: "In prisoners' possession (not including them wearing them)",
          active: true,
          label: "In prisoners' possession (not including them wearing them)",
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
      ],
    },
    '900017': {
      code: '900017',
      active: true,
      question: 'other_device_type',
      label: 'What other locking device or item was compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950098',
          response: 'Other locking device or item',
          active: true,
          label: 'Other locking device or item',
          commentRequested: true,
          commentLabel: 'Provide details',
          commentMultiline: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '900018',
        },
      ],
    },
    '900018': {
      code: '900018',
      active: true,
      question: 'other_device_compromise_method',
      label: 'How was this device compromised?',
      multipleAnswers: false,
      answers: [
        {
          code: '950099',
          response: 'How the device was compromised',
          active: true,
          label: 'How the device was compromised',
          commentRequested: true,
          commentLabel: 'Provide details',
          commentMultiline: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '900019',
        },
      ],
    },
    '900019': {
      code: '900019',
      active: true,
      question: 'risk_level',
      label: 'What risk level has this incident been assessed as?',
      multipleAnswers: false,
      answers: [
        {
          code: '950100',
          response: 'Level 1',
          active: true,
          label:
            'Level 1: High risk of disclosure, investigations taking place, situation being monitored. Relock essential.',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '950101',
          response: 'Level 2',
          active: true,
          label:
            'Level 2: Medium risk of disclosure, situation being monitored to establish if a relock is necessary. Relock possible.',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '950102',
          response: 'Level 3',
          active: true,
          label:
            'Level 3: Low risk of disclosure, minor incident that may have disclosed the key or lock systems. Small chance of relock.',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '950103',
          response: 'Level 4',
          active: true,
          label:
            'Level 4: Very low risk of disclosure, but a notifiable minor incident that may have compromised the key or lock systems but has not led to a disclosure. No relock.',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '950104',
          response: 'Level 5',
          active: true,
          label: 'Level 5: No risk of disclosure. No relock.',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default KEY_OR_LOCK_3
