// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:49.972Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const KEY_OR_LOCK_2: IncidentTypeConfiguration = {
  incidentType: 'KEY_OR_LOCK_2',
  active: true,
  startingQuestionCode: '45196',
  questions: {
    '45196': {
      code: '45196',
      active: true,
      question: 'Describe the nature of the Incident',
      label: 'Describe the nature of the incident',
      multipleAnswers: true,
      answers: [
        {
          code: '182748',
          response: 'Keys taken out of the establishment',
          active: false,
          label: 'Keys taken out of the establishment',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182749',
          response: 'Keys lost',
          active: false,
          label: 'Keys lost',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182750',
          response: 'Key left unattended in prison',
          active: false,
          label: 'Key left unattended in prison',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182751',
          response: 'Key issued to wrong person',
          active: false,
          label: 'Key issued to wrong person',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182752',
          response: 'Doors/Gates/Cell door left unlocked',
          active: false,
          label: 'Doors/gates/cell door left unlocked',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182753',
          response: 'Loss of handcuffs',
          active: false,
          label: 'Loss of handcuffs',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182754',
          response: 'Loss of escort chain',
          active: false,
          label: 'Loss of escort chain',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182755',
          response: 'Other handcuff key/lock issues',
          active: false,
          label: 'Other handcuff key/lock issues',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182756',
          response: 'Broken/Damaged keys',
          active: false,
          label: 'Broken/damaged keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182757',
          response: 'Worn locks (not malicious)',
          active: false,
          label: 'Worn locks (not malicious)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182758',
          response: 'Malicious damage to/blockage of locks',
          active: false,
          label: 'Malicious damage to/blockage of locks',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182759',
          response: 'Lock picked',
          active: false,
          label: 'Lock picked',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182760',
          response: 'Part of lock removed',
          active: false,
          label: 'Part of lock removed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182761',
          response: 'Complete lock removed',
          active: false,
          label: 'Complete lock removed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182762',
          response: 'Electronics overcome (electronic door)',
          active: false,
          label: 'Electronics overcome (electronic door)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182763',
          response: 'Electronics failure (electronic door)',
          active: false,
          label: 'Electronics failure (electronic door)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182764',
          response: 'Replica key found/used',
          active: false,
          label: 'Replica key found/used',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182765',
          response: 'Key viewed by prisoner',
          active: false,
          label: 'Key viewed by prisoner',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182766',
          response: 'Other: (anything else including prisoner grabbing key chain, etc)',
          active: false,
          label: 'Other: (anything else including prisoner grabbing key chain, etc)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182945',
          response: 'Keys taken out of the establishment',
          active: true,
          label: 'Keys taken out of the establishment',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182946',
          response: 'Keys lost',
          active: true,
          label: 'Keys lost',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182947',
          response: 'Key left unattended in prison',
          active: true,
          label: 'Key left unattended in prison',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182948',
          response: 'Key issued to wrong person',
          active: true,
          label: 'Key issued to wrong person',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182949',
          response: 'Doors/Gates/cell door left unlocked',
          active: true,
          label: 'Doors/gates/cell door left unlocked',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182950',
          response: 'Loss of handcuffs',
          active: true,
          label: 'Loss of handcuffs',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182951',
          response: 'Loss of escort chain',
          active: true,
          label: 'Loss of escort chain',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182952',
          response: 'Other handcuff key/lock issues',
          active: true,
          label: 'Other handcuff key/lock issues',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182953',
          response: 'Broken/Damaged keys',
          active: true,
          label: 'Broken/damaged keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182954',
          response: 'Worn locks (not malicious)',
          active: true,
          label: 'Worn locks (not malicious)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182955',
          response: 'Malicious damage to/blockage of locks',
          active: true,
          label: 'Malicious damage to/blockage of locks',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182956',
          response: 'Lock picked',
          active: true,
          label: 'Lock picked',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182957',
          response: 'Part of lock removed',
          active: true,
          label: 'Part of lock removed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182958',
          response: 'Complete lock removed',
          active: true,
          label: 'Complete lock removed',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182959',
          response: 'Electronics overcome (electronic door)',
          active: true,
          label: 'Electronics overcome (electronic door)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182960',
          response: 'Electronics failure (electronic door)',
          active: true,
          label: 'Electronics failure (electronic door)',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182961',
          response: 'Replica key found/used',
          active: true,
          label: 'Replica key found/used',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182962',
          response: 'Key viewed by prisoner',
          active: true,
          label: 'Key viewed by prisoner',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
        {
          code: '182963',
          response: 'Other  (anything else including prisoner grabbing key chain, etc)',
          active: true,
          label: 'Other (anything else including prisoner grabbing key chain, etc)',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45197',
        },
      ],
    },
    '45197': {
      code: '45197',
      active: true,
      question: 'Describe the type of key or lock',
      label: 'Describe the type of key or lock',
      multipleAnswers: true,
      answers: [
        {
          code: '182767',
          response: 'Class 1 pass key',
          active: false,
          label: 'Class 1 pass key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182768',
          response: 'Class 2 pass key',
          active: false,
          label: 'Class 2 pass key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182769',
          response: 'Cell key',
          active: false,
          label: 'Cell key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182770',
          response: 'Class 3 A1 Suite key',
          active: false,
          label: 'Class 3 A1 suite key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182771',
          response: 'Class 3 Accountable key',
          active: false,
          label: 'Class 3 accountable key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182772',
          response: 'Handcuff key',
          active: false,
          label: 'Handcuff key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182773',
          response: 'Escort Chain key',
          active: false,
          label: 'Escort chain key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182774',
          response: 'Class 1 Lock',
          active: false,
          label: 'Class 1 lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182775',
          response: 'Class 2 Lock',
          active: false,
          label: 'Class 2 lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182776',
          response: 'Cell Lock',
          active: false,
          label: 'Cell lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182777',
          response: 'Class 3 A1 Suite Lock',
          active: false,
          label: 'Class 3 A1 suite lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182778',
          response: 'Class 3 Accountable Lock',
          active: false,
          label: 'Class 3 accountable lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182779',
          response: 'Handcuffs',
          active: false,
          label: 'Handcuffs',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182780',
          response: 'Escort chain',
          active: false,
          label: 'Escort chain',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182781',
          response: 'Electronic Lock System',
          active: false,
          label: 'Electronic lock system',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182782',
          response: 'Magnetic Keys',
          active: false,
          label: 'Magnetic keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182783',
          response: 'Magnetic Lock',
          active: false,
          label: 'Magnetic lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182784',
          response: 'Cell Door',
          active: false,
          label: 'Cell door',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182785',
          response: 'Brent Keys',
          active: false,
          label: 'Brent keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182786',
          response: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182964',
          response: 'Class 1 pass key',
          active: true,
          label: 'Class 1 pass key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182965',
          response: 'Class 2 pass key',
          active: true,
          label: 'Class 2 pass key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182966',
          response: 'Cell key',
          active: true,
          label: 'Cell key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182967',
          response: 'Class 3 A1 Suite key',
          active: true,
          label: 'Class 3 A1 suite key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182968',
          response: 'Class 3 Accountable key',
          active: true,
          label: 'Class 3 accountable key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182969',
          response: 'Handcuff key',
          active: true,
          label: 'Handcuff key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182970',
          response: 'Escort Chain key',
          active: true,
          label: 'Escort chain key',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182971',
          response: 'Class 1 Lock',
          active: true,
          label: 'Class 1 lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182972',
          response: 'Class 2 Lock',
          active: true,
          label: 'Class 2 lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182973',
          response: 'Cell Lock',
          active: true,
          label: 'Cell lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182974',
          response: 'Class 3 A1 Suite Lock',
          active: true,
          label: 'Class 3 A1 suite lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182975',
          response: 'Class 3 Accountable Lock',
          active: true,
          label: 'Class 3 accountable lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182976',
          response: 'Handcuffs',
          active: true,
          label: 'Handcuffs',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182977',
          response: 'Escort chain',
          active: true,
          label: 'Escort chain',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182978',
          response: 'Electronic Lock System',
          active: true,
          label: 'Electronic lock system',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182979',
          response: 'Magnetic Keys',
          active: true,
          label: 'Magnetic keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182980',
          response: 'Magnetic Lock',
          active: true,
          label: 'Magnetic lock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182981',
          response: 'Cell Door',
          active: true,
          label: 'Cell door',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182982',
          response: 'Brent Keys',
          active: true,
          label: 'Brent keys',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
        {
          code: '182983',
          response: 'Other :  Specify',
          active: true,
          label: 'Other : specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45198',
        },
      ],
    },
    '45198': {
      code: '45198',
      active: true,
      question: 'Incident Level: 1-5. 1 High Risk, 5 No Risk',
      label: 'Incident level: 1-5. 1 high risk, 5 no risk',
      multipleAnswers: false,
      answers: [
        {
          code: '182787',
          response: 'Enter Value:',
          active: false,
          label: 'Enter value:',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182984',
          response: 'Enter Value:',
          active: true,
          label: 'Enter value:',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45199',
        },
      ],
    },
    '45199': {
      code: '45199',
      active: true,
      question: 'Has any remedial action been taken?',
      label: 'Has any remedial action been taken?',
      multipleAnswers: false,
      answers: [
        {
          code: '182788',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182789',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182985',
          response: 'Yes',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45200',
        },
        {
          code: '182986',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45200',
        },
        {
          code: '184687',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45202',
        },
        {
          code: '188684',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '190684',
          response: 'No',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45202',
        },
      ],
    },
    '45200': {
      code: '45200',
      active: true,
      question: 'Describe the remedial action taken',
      label: 'Describe the remedial action taken',
      multipleAnswers: false,
      answers: [
        {
          code: '182790',
          response: 'Complete relock',
          active: false,
          label: 'Complete relock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182791',
          response: 'Partial relock',
          active: false,
          label: 'Partial relock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182792',
          response: 'Complete replacement',
          active: false,
          label: 'Complete replacement',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182793',
          response: 'Partial replacement',
          active: false,
          label: 'Partial replacement',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182794',
          response: 'Forensic testing',
          active: false,
          label: 'Forensic testing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182987',
          response: 'Complete relock',
          active: true,
          label: 'Complete relock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45201',
        },
        {
          code: '182988',
          response: 'Partial relock',
          active: true,
          label: 'Partial relock',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45201',
        },
        {
          code: '182989',
          response: 'Complete replacement',
          active: true,
          label: 'Complete replacement',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45201',
        },
        {
          code: '182990',
          response: 'Partial replacement',
          active: true,
          label: 'Partial replacement',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45201',
        },
        {
          code: '182991',
          response: 'Forensic testing',
          active: true,
          label: 'Forensic testing',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45201',
        },
        {
          code: '188685',
          response: 'Other',
          active: true,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45201',
        },
      ],
    },
    '45201': {
      code: '45201',
      active: true,
      question: 'Estimated cost of this action',
      label: 'Estimated cost of this action',
      multipleAnswers: false,
      answers: [
        {
          code: '182795',
          response: '£',
          active: false,
          label: '£',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182992',
          response: '£',
          active: true,
          label: '£',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45202',
        },
        {
          code: '190687',
          response: 'N/A',
          active: true,
          label: 'N/A',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45202',
        },
      ],
    },
    '45202': {
      code: '45202',
      active: true,
      question: 'Have the lost item (s) been found?',
      label: 'Have the lost item (s) been found?',
      multipleAnswers: false,
      answers: [
        {
          code: '182796',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182797',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182993',
          response: 'Yes',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45203',
        },
        {
          code: '182994',
          response: 'No',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45203',
        },
        {
          code: '190686',
          response: 'N/A',
          active: true,
          label: 'N/A',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45203',
        },
      ],
    },
    '45203': {
      code: '45203',
      active: true,
      question: 'Has a replica key been found?',
      label: 'Has a replica key been found?',
      multipleAnswers: false,
      answers: [
        {
          code: '182798',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182799',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182995',
          response: 'Yes',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45204',
        },
        {
          code: '182996',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45204',
        },
        {
          code: '184688',
          response: 'No',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45205',
        },
        {
          code: '190688',
          response: 'N/A',
          active: true,
          label: 'N/A',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45205',
        },
      ],
    },
    '45204': {
      code: '45204',
      active: true,
      question: 'What action was taken to find these items?',
      label: 'What action was taken to find these items?',
      multipleAnswers: false,
      answers: [
        {
          code: '182800',
          response: 'Full close down search',
          active: false,
          label: 'Full close down search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182801',
          response: 'Partial search',
          active: false,
          label: 'Partial search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182802',
          response: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182997',
          response: 'Full close down search',
          active: true,
          label: 'Full close down search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45205',
        },
        {
          code: '182998',
          response: 'Partial search',
          active: true,
          label: 'Partial search',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45205',
        },
        {
          code: '182999',
          response: 'Other: Please specify',
          active: true,
          label: 'Other: please specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45205',
        },
      ],
    },
    '45205': {
      code: '45205',
      active: true,
      question: 'Were tools used in the Incident?',
      label: 'Were tools used in the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '182803',
          response: 'Yes',
          active: false,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182804',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '183000',
          response: 'Yes',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45206',
        },
        {
          code: '183001',
          response: 'No',
          active: false,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45206',
        },
        {
          code: '190685',
          response: 'No',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
      ],
    },
    '45206': {
      code: '45206',
      active: true,
      question: 'What tools/foreign objects were used?',
      label: 'What tools/foreign objects were used?',
      multipleAnswers: true,
      answers: [
        {
          code: '182805',
          response: 'Hacksaw blade',
          active: false,
          label: 'Hacksaw blade',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182806',
          response: 'Other Blade',
          active: false,
          label: 'Other blade',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182807',
          response: 'Wire cutters',
          active: false,
          label: 'Wire cutters',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182808',
          response: 'Bolt cutters',
          active: false,
          label: 'Bolt cutters',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182809',
          response: 'Digging tool',
          active: false,
          label: 'Digging tool',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182810',
          response: 'Crow bar',
          active: false,
          label: 'Crow bar',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182811',
          response: 'Improvised tool',
          active: false,
          label: 'Improvised tool',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182812',
          response: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182813',
          response: 'Not Known',
          active: false,
          label: 'Not known',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '183002',
          response: 'Hacksaw blade',
          active: true,
          label: 'Hacksaw blade',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183003',
          response: 'Other blade',
          active: true,
          label: 'Other blade',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183004',
          response: 'Wire cutters',
          active: true,
          label: 'Wire cutters',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183005',
          response: 'Bolt cutters',
          active: true,
          label: 'Bolt cutters',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183006',
          response: 'Digging tool',
          active: true,
          label: 'Digging tool',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183007',
          response: 'Crow bar',
          active: true,
          label: 'Crow bar',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183008',
          response: 'Improvised tool',
          active: true,
          label: 'Improvised tool',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183009',
          response: 'Other: Please specify',
          active: true,
          label: 'Other: please specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
        {
          code: '183010',
          response: 'Not Known',
          active: true,
          label: 'Not known',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45207',
        },
      ],
    },
    '45207': {
      code: '45207',
      active: true,
      question: 'What was the source of the tools/foreign object?',
      label: 'What was the source of the tools/foreign object?',
      multipleAnswers: false,
      answers: [
        {
          code: '182814',
          response: 'Works Department',
          active: false,
          label: 'Works department',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182815',
          response: 'Contractors',
          active: false,
          label: 'Contractors',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182816',
          response: 'Education',
          active: false,
          label: 'Education',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182817',
          response: 'Heathcare Centre',
          active: false,
          label: 'Heathcare centre',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182818',
          response: 'Farms and Gardens',
          active: false,
          label: 'Farms and gardens',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182819',
          response: 'Staff',
          active: false,
          label: 'Staff',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182820',
          response: 'Visitor',
          active: false,
          label: 'Visitor',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182821',
          response: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182822',
          response: 'Not Known',
          active: false,
          label: 'Not known',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '183011',
          response: 'Works Department',
          active: true,
          label: 'Works department',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183012',
          response: 'Contractors',
          active: true,
          label: 'Contractors',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183013',
          response: 'Education',
          active: true,
          label: 'Education',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183014',
          response: 'Health Care Centre',
          active: true,
          label: 'Health care centre',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183015',
          response: 'Farms and Gardens',
          active: true,
          label: 'Farms and gardens',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183016',
          response: 'Staff',
          active: true,
          label: 'Staff',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183017',
          response: 'Visitor',
          active: true,
          label: 'Visitor',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183018',
          response: 'Other: Please specify',
          active: true,
          label: 'Other: please specify',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
        {
          code: '183019',
          response: 'Not Known',
          active: true,
          label: 'Not known',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: '45208',
        },
      ],
    },
    '45208': {
      code: '45208',
      active: true,
      question: 'Has the Key Lock Incident been reported to NOU?',
      label: 'Has the key lock incident been reported to NOU?',
      multipleAnswers: true,
      answers: [
        {
          code: '182823',
          response: 'Yes: Date',
          active: true,
          label: 'Yes: date',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: true,
          nextQuestionCode: null,
        },
        {
          code: '182824',
          response: 'No',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateMandatory: false,
          nextQuestionCode: null,
        },
        {
          code: '182825',
          response: 'Incident Ref No:',
          active: true,
          label: 'Incident ref no:',
          commentRequested: true,
          commentMandatory: true,
          dateMandatory: false,
          nextQuestionCode: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default KEY_OR_LOCK_2
