// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-12-04T17:17:28.427Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const KEY_LOCK_INCIDENT: IncidentTypeConfiguration = {
  incidentType: 'KEY_LOCK_INCIDENT',
  active: true,
  startingQuestionId: '45196',
  questions: {
    '45196': {
      id: '45196',
      active: true,
      code: 'Describe the nature of the Incident',
      label: 'Describe the nature of the incident',
      multipleAnswers: true,
      answers: [
        {
          id: '182748',
          code: 'Keys taken out of the establishment',
          active: false,
          label: 'Keys taken out of the establishment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182749',
          code: 'Keys lost',
          active: false,
          label: 'Keys lost',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182750',
          code: 'Key left unattended in prison',
          active: false,
          label: 'Key left unattended in prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182751',
          code: 'Key issued to wrong person',
          active: false,
          label: 'Key issued to wrong person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182752',
          code: 'Doors/Gates/Cell door left unlocked',
          active: false,
          label: 'Doors/gates/cell door left unlocked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182753',
          code: 'Loss of handcuffs',
          active: false,
          label: 'Loss of handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182754',
          code: 'Loss of escort chain',
          active: false,
          label: 'Loss of escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182755',
          code: 'Other handcuff key/lock issues',
          active: false,
          label: 'Other handcuff key/lock issues',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182756',
          code: 'Broken/Damaged keys',
          active: false,
          label: 'Broken/damaged keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182757',
          code: 'Worn locks (not malicious)',
          active: false,
          label: 'Worn locks (not malicious)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182758',
          code: 'Malicious damage to/blockage of locks',
          active: false,
          label: 'Malicious damage to/blockage of locks',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182759',
          code: 'Lock picked',
          active: false,
          label: 'Lock picked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182760',
          code: 'Part of lock removed',
          active: false,
          label: 'Part of lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182761',
          code: 'Complete lock removed',
          active: false,
          label: 'Complete lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182762',
          code: 'Electronics overcome (electronic door)',
          active: false,
          label: 'Electronics overcome (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182763',
          code: 'Electronics failure (electronic door)',
          active: false,
          label: 'Electronics failure (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182764',
          code: 'Replica key found/used',
          active: false,
          label: 'Replica key found/used',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182765',
          code: 'Key viewed by prisoner',
          active: false,
          label: 'Key viewed by prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182766',
          code: 'Other: (anything else including prisoner grabbing key chain, etc)',
          active: false,
          label: 'Other: (anything else including prisoner grabbing key chain, etc)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182945',
          code: 'Keys taken out of the establishment',
          active: true,
          label: 'Keys taken out of the establishment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182946',
          code: 'Keys lost',
          active: true,
          label: 'Keys lost',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182947',
          code: 'Key left unattended in prison',
          active: true,
          label: 'Key left unattended in prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182948',
          code: 'Key issued to wrong person',
          active: true,
          label: 'Key issued to wrong person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182949',
          code: 'Doors/Gates/cell door left unlocked',
          active: true,
          label: 'Doors/gates/cell door left unlocked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182950',
          code: 'Loss of handcuffs',
          active: true,
          label: 'Loss of handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182951',
          code: 'Loss of escort chain',
          active: true,
          label: 'Loss of escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182952',
          code: 'Other handcuff key/lock issues',
          active: true,
          label: 'Other handcuff key/lock issues',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182953',
          code: 'Broken/Damaged keys',
          active: true,
          label: 'Broken/damaged keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182954',
          code: 'Worn locks (not malicious)',
          active: true,
          label: 'Worn locks (not malicious)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182955',
          code: 'Malicious damage to/blockage of locks',
          active: true,
          label: 'Malicious damage to/blockage of locks',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182956',
          code: 'Lock picked',
          active: true,
          label: 'Lock picked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182957',
          code: 'Part of lock removed',
          active: true,
          label: 'Part of lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182958',
          code: 'Complete lock removed',
          active: true,
          label: 'Complete lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182959',
          code: 'Electronics overcome (electronic door)',
          active: true,
          label: 'Electronics overcome (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182960',
          code: 'Electronics failure (electronic door)',
          active: true,
          label: 'Electronics failure (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182961',
          code: 'Replica key found/used',
          active: true,
          label: 'Replica key found/used',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182962',
          code: 'Key viewed by prisoner',
          active: true,
          label: 'Key viewed by prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          id: '182963',
          code: 'Other  (anything else including prisoner grabbing key chain, etc)',
          active: true,
          label: 'Other (anything else including prisoner grabbing key chain, etc)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45197',
        },
      ],
    },
    '45197': {
      id: '45197',
      active: true,
      code: 'Describe the type of key or lock',
      label: 'Describe the type of key or lock',
      multipleAnswers: true,
      answers: [
        {
          id: '182767',
          code: 'Class 1 pass key',
          active: false,
          label: 'Class 1 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182768',
          code: 'Class 2 pass key',
          active: false,
          label: 'Class 2 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182769',
          code: 'Cell key',
          active: false,
          label: 'Cell key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182770',
          code: 'Class 3 A1 Suite key',
          active: false,
          label: 'Class 3 A1 suite key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182771',
          code: 'Class 3 Accountable key',
          active: false,
          label: 'Class 3 accountable key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182772',
          code: 'Handcuff key',
          active: false,
          label: 'Handcuff key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182773',
          code: 'Escort Chain key',
          active: false,
          label: 'Escort chain key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182774',
          code: 'Class 1 Lock',
          active: false,
          label: 'Class 1 lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182775',
          code: 'Class 2 Lock',
          active: false,
          label: 'Class 2 lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182776',
          code: 'Cell Lock',
          active: false,
          label: 'Cell lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182777',
          code: 'Class 3 A1 Suite Lock',
          active: false,
          label: 'Class 3 A1 suite lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182778',
          code: 'Class 3 Accountable Lock',
          active: false,
          label: 'Class 3 accountable lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182779',
          code: 'Handcuffs',
          active: false,
          label: 'Handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182780',
          code: 'Escort chain',
          active: false,
          label: 'Escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182781',
          code: 'Electronic Lock System',
          active: false,
          label: 'Electronic lock system',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182782',
          code: 'Magnetic Keys',
          active: false,
          label: 'Magnetic keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182783',
          code: 'Magnetic Lock',
          active: false,
          label: 'Magnetic lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182784',
          code: 'Cell Door',
          active: false,
          label: 'Cell door',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182785',
          code: 'Brent Keys',
          active: false,
          label: 'Brent keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182786',
          code: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182964',
          code: 'Class 1 pass key',
          active: true,
          label: 'Class 1 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182965',
          code: 'Class 2 pass key',
          active: true,
          label: 'Class 2 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182966',
          code: 'Cell key',
          active: true,
          label: 'Cell key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182967',
          code: 'Class 3 A1 Suite key',
          active: true,
          label: 'Class 3 A1 suite key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182968',
          code: 'Class 3 Accountable key',
          active: true,
          label: 'Class 3 accountable key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182969',
          code: 'Handcuff key',
          active: true,
          label: 'Handcuff key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182970',
          code: 'Escort Chain key',
          active: true,
          label: 'Escort chain key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182971',
          code: 'Class 1 Lock',
          active: true,
          label: 'Class 1 lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182972',
          code: 'Class 2 Lock',
          active: true,
          label: 'Class 2 lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182973',
          code: 'Cell Lock',
          active: true,
          label: 'Cell lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182974',
          code: 'Class 3 A1 Suite Lock',
          active: true,
          label: 'Class 3 A1 suite lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182975',
          code: 'Class 3 Accountable Lock',
          active: true,
          label: 'Class 3 accountable lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182976',
          code: 'Handcuffs',
          active: true,
          label: 'Handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182977',
          code: 'Escort chain',
          active: true,
          label: 'Escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182978',
          code: 'Electronic Lock System',
          active: true,
          label: 'Electronic lock system',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182979',
          code: 'Magnetic Keys',
          active: true,
          label: 'Magnetic keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182980',
          code: 'Magnetic Lock',
          active: true,
          label: 'Magnetic lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182981',
          code: 'Cell Door',
          active: true,
          label: 'Cell door',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182982',
          code: 'Brent Keys',
          active: true,
          label: 'Brent keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          id: '182983',
          code: 'Other :  Specify',
          active: true,
          label: 'Other : specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45198',
        },
      ],
    },
    '45198': {
      id: '45198',
      active: true,
      code: 'Incident Level: 1-5. 1 High Risk, 5 No Risk',
      label: 'Incident level: 1-5. 1 high risk, 5 no risk',
      multipleAnswers: false,
      answers: [
        {
          id: '182787',
          code: 'Enter Value:',
          active: false,
          label: 'Enter value:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182984',
          code: 'Enter Value:',
          active: true,
          label: 'Enter value:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45199',
        },
      ],
    },
    '45199': {
      id: '45199',
      active: true,
      code: 'Has any remedial action been taken?',
      label: 'Has any remedial action been taken?',
      multipleAnswers: false,
      answers: [
        {
          id: '182788',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182789',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182985',
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45200',
        },
        {
          id: '182986',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45200',
        },
        {
          id: '184687',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45202',
        },
        {
          id: '188684',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '190684',
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45202',
        },
      ],
    },
    '45200': {
      id: '45200',
      active: true,
      code: 'Describe the remedial action taken',
      label: 'Describe the remedial action taken',
      multipleAnswers: false,
      answers: [
        {
          id: '182790',
          code: 'Complete relock',
          active: false,
          label: 'Complete relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182791',
          code: 'Partial relock',
          active: false,
          label: 'Partial relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182792',
          code: 'Complete replacement',
          active: false,
          label: 'Complete replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182793',
          code: 'Partial replacement',
          active: false,
          label: 'Partial replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182794',
          code: 'Forensic testing',
          active: false,
          label: 'Forensic testing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182987',
          code: 'Complete relock',
          active: true,
          label: 'Complete relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          id: '182988',
          code: 'Partial relock',
          active: true,
          label: 'Partial relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          id: '182989',
          code: 'Complete replacement',
          active: true,
          label: 'Complete replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          id: '182990',
          code: 'Partial replacement',
          active: true,
          label: 'Partial replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          id: '182991',
          code: 'Forensic testing',
          active: true,
          label: 'Forensic testing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          id: '188685',
          code: 'Other',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45201',
        },
      ],
    },
    '45201': {
      id: '45201',
      active: true,
      code: 'Estimated cost of this action',
      label: 'Estimated cost of this action',
      multipleAnswers: false,
      answers: [
        {
          id: '182795',
          code: '£',
          active: false,
          label: '£',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182992',
          code: '£',
          active: true,
          label: '£',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45202',
        },
        {
          id: '190687',
          code: 'N/A',
          active: true,
          label: 'N/A',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45202',
        },
      ],
    },
    '45202': {
      id: '45202',
      active: true,
      code: 'Have the lost item (s) been found?',
      label: 'Have the lost item (s) been found?',
      multipleAnswers: false,
      answers: [
        {
          id: '182796',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182797',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182993',
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45203',
        },
        {
          id: '182994',
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45203',
        },
        {
          id: '190686',
          code: 'N/A',
          active: true,
          label: 'N/A',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45203',
        },
      ],
    },
    '45203': {
      id: '45203',
      active: true,
      code: 'Has a replica key been found?',
      label: 'Has a replica key been found?',
      multipleAnswers: false,
      answers: [
        {
          id: '182798',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182799',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182995',
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45204',
        },
        {
          id: '182996',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45204',
        },
        {
          id: '184688',
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
        {
          id: '190688',
          code: 'N/A',
          active: true,
          label: 'N/A',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
      ],
    },
    '45204': {
      id: '45204',
      active: true,
      code: 'What action was taken to find these items?',
      label: 'What action was taken to find these items?',
      multipleAnswers: false,
      answers: [
        {
          id: '182800',
          code: 'Full close down search',
          active: false,
          label: 'Full close down search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182801',
          code: 'Partial search',
          active: false,
          label: 'Partial search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182802',
          code: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182997',
          code: 'Full close down search',
          active: true,
          label: 'Full close down search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
        {
          id: '182998',
          code: 'Partial search',
          active: true,
          label: 'Partial search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
        {
          id: '182999',
          code: 'Other: Please specify',
          active: true,
          label: 'Other: please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45205',
        },
      ],
    },
    '45205': {
      id: '45205',
      active: true,
      code: 'Were tools used in the Incident?',
      label: 'Were tools used in the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '182803',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182804',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '183000',
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45206',
        },
        {
          id: '183001',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45206',
        },
        {
          id: '190685',
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
      ],
    },
    '45206': {
      id: '45206',
      active: true,
      code: 'What tools/foreign objects were used?',
      label: 'What tools/foreign objects were used?',
      multipleAnswers: true,
      answers: [
        {
          id: '182805',
          code: 'Hacksaw blade',
          active: false,
          label: 'Hacksaw blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182806',
          code: 'Other Blade',
          active: false,
          label: 'Other blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182807',
          code: 'Wire cutters',
          active: false,
          label: 'Wire cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182808',
          code: 'Bolt cutters',
          active: false,
          label: 'Bolt cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182809',
          code: 'Digging tool',
          active: false,
          label: 'Digging tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182810',
          code: 'Crow bar',
          active: false,
          label: 'Crow bar',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182811',
          code: 'Improvised tool',
          active: false,
          label: 'Improvised tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182812',
          code: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182813',
          code: 'Not Known',
          active: false,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '183002',
          code: 'Hacksaw blade',
          active: true,
          label: 'Hacksaw blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183003',
          code: 'Other blade',
          active: true,
          label: 'Other blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183004',
          code: 'Wire cutters',
          active: true,
          label: 'Wire cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183005',
          code: 'Bolt cutters',
          active: true,
          label: 'Bolt cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183006',
          code: 'Digging tool',
          active: true,
          label: 'Digging tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183007',
          code: 'Crow bar',
          active: true,
          label: 'Crow bar',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183008',
          code: 'Improvised tool',
          active: true,
          label: 'Improvised tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183009',
          code: 'Other: Please specify',
          active: true,
          label: 'Other: please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          id: '183010',
          code: 'Not Known',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
      ],
    },
    '45207': {
      id: '45207',
      active: true,
      code: 'What was the source of the tools/foreign object?',
      label: 'What was the source of the tools/foreign object?',
      multipleAnswers: false,
      answers: [
        {
          id: '182814',
          code: 'Works Department',
          active: false,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182815',
          code: 'Contractors',
          active: false,
          label: 'Contractors',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182816',
          code: 'Education',
          active: false,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182817',
          code: 'Heathcare Centre',
          active: false,
          label: 'Heathcare centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182818',
          code: 'Farms and Gardens',
          active: false,
          label: 'Farms and gardens',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182819',
          code: 'Staff',
          active: false,
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182820',
          code: 'Visitor',
          active: false,
          label: 'Visitor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182821',
          code: 'Other: Specify',
          active: false,
          label: 'Other: specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182822',
          code: 'Not Known',
          active: false,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '183011',
          code: 'Works Department',
          active: true,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183012',
          code: 'Contractors',
          active: true,
          label: 'Contractors',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183013',
          code: 'Education',
          active: true,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183014',
          code: 'Health Care Centre',
          active: true,
          label: 'Health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183015',
          code: 'Farms and Gardens',
          active: true,
          label: 'Farms and gardens',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183016',
          code: 'Staff',
          active: true,
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183017',
          code: 'Visitor',
          active: true,
          label: 'Visitor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183018',
          code: 'Other: Please specify',
          active: true,
          label: 'Other: please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          id: '183019',
          code: 'Not Known',
          active: true,
          label: 'Not known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
      ],
    },
    '45208': {
      id: '45208',
      active: true,
      code: 'Has the Key Lock Incident been reported to NOU?',
      label: 'Has the key lock incident been reported to NOU?',
      multipleAnswers: true,
      answers: [
        {
          id: '182823',
          code: 'Yes: Date',
          active: true,
          label: 'Yes: date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          id: '182824',
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '182825',
          code: 'Incident Ref No:',
          active: true,
          label: 'Incident ref no:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default KEY_LOCK_INCIDENT
