// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-20T16:52:38.770Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const KEY_LOCK_INCIDENT: IncidentTypeConfiguration = {
  incidentType: 'KEY_LOCK_INCIDENT',
  active: true,
  startingQuestionId: '45196',
  questions: {
    '45196': {
      id: '45196',
      active: true,
      code: 'Describe the nature of the Incident',
      label: 'Describe the nature of the Incident',
      multipleAnswers: true,
      answers: [
        {
          code: 'Keys taken out of the establishment',
          active: false,
          label: 'Keys taken out of the establishment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Keys lost',
          active: false,
          label: 'Keys lost',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Key left unattended in prison',
          active: false,
          label: 'Key left unattended in prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Key issued to wrong person',
          active: false,
          label: 'Key issued to wrong person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Doors/Gates/Cell door left unlocked',
          active: false,
          label: 'Doors/Gates/Cell door left unlocked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Loss of handcuffs',
          active: false,
          label: 'Loss of handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Loss of escort chain',
          active: false,
          label: 'Loss of escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Other handcuff key/lock issues',
          active: false,
          label: 'Other handcuff key/lock issues',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Broken/Damaged keys',
          active: false,
          label: 'Broken/Damaged keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Worn locks (not malicious)',
          active: false,
          label: 'Worn locks (not malicious)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Malicious damage to/blockage of locks',
          active: false,
          label: 'Malicious damage to/blockage of locks',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Lock picked',
          active: false,
          label: 'Lock picked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Part of lock removed',
          active: false,
          label: 'Part of lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Complete lock removed',
          active: false,
          label: 'Complete lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Electronics overcome (electronic door)',
          active: false,
          label: 'Electronics overcome (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Electronics failure (electronic door)',
          active: false,
          label: 'Electronics failure (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Replica key found/used',
          active: false,
          label: 'Replica key found/used',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Key viewed by prisoner',
          active: false,
          label: 'Key viewed by prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Other: (anything else including prisoner grabbing key chain, etc)',
          active: false,
          label: 'Other: (anything else including prisoner grabbing key chain, etc)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Keys taken out of the establishment',
          active: true,
          label: 'Keys taken out of the establishment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Keys lost',
          active: true,
          label: 'Keys lost',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Key left unattended in prison',
          active: true,
          label: 'Key left unattended in prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Key issued to wrong person',
          active: true,
          label: 'Key issued to wrong person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Doors/Gates/cell door left unlocked',
          active: true,
          label: 'Doors/Gates/cell door left unlocked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Loss of handcuffs',
          active: true,
          label: 'Loss of handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Loss of escort chain',
          active: true,
          label: 'Loss of escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Other handcuff key/lock issues',
          active: true,
          label: 'Other handcuff key/lock issues',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Broken/Damaged keys',
          active: true,
          label: 'Broken/Damaged keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Worn locks (not malicious)',
          active: true,
          label: 'Worn locks (not malicious)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Malicious damage to/blockage of locks',
          active: true,
          label: 'Malicious damage to/blockage of locks',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Lock picked',
          active: true,
          label: 'Lock picked',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Part of lock removed',
          active: true,
          label: 'Part of lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Complete lock removed',
          active: true,
          label: 'Complete lock removed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Electronics overcome (electronic door)',
          active: true,
          label: 'Electronics overcome (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Electronics failure (electronic door)',
          active: true,
          label: 'Electronics failure (electronic door)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Replica key found/used',
          active: true,
          label: 'Replica key found/used',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Key viewed by prisoner',
          active: true,
          label: 'Key viewed by prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45197',
        },
        {
          code: 'Other  (anything else including prisoner grabbing key chain, etc)',
          active: true,
          label: 'Other  (anything else including prisoner grabbing key chain, etc)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45197',
        },
      ],
    },
    '45197': {
      id: '45197',
      active: true,
      code: 'Describe the type of key or lock',
      label: 'Describe the type of key or lock',
      multipleAnswers: true,
      answers: [
        {
          code: 'Class 1 pass key',
          active: false,
          label: 'Class 1 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 2 pass key',
          active: false,
          label: 'Class 2 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Cell key',
          active: false,
          label: 'Cell key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 3 A1 Suite key',
          active: false,
          label: 'Class 3 A1 Suite key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 3 Accountable key',
          active: false,
          label: 'Class 3 Accountable key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Handcuff key',
          active: false,
          label: 'Handcuff key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Escort Chain key',
          active: false,
          label: 'Escort Chain key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 1 Lock',
          active: false,
          label: 'Class 1 Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 2 Lock',
          active: false,
          label: 'Class 2 Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Cell Lock',
          active: false,
          label: 'Cell Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 3 A1 Suite Lock',
          active: false,
          label: 'Class 3 A1 Suite Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 3 Accountable Lock',
          active: false,
          label: 'Class 3 Accountable Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Handcuffs',
          active: false,
          label: 'Handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Escort chain',
          active: false,
          label: 'Escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Electronic Lock System',
          active: false,
          label: 'Electronic Lock System',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Magnetic Keys',
          active: false,
          label: 'Magnetic Keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Magnetic Lock',
          active: false,
          label: 'Magnetic Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Cell Door',
          active: false,
          label: 'Cell Door',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Brent Keys',
          active: false,
          label: 'Brent Keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Other: Specify',
          active: false,
          label: 'Other: Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Class 1 pass key',
          active: true,
          label: 'Class 1 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Class 2 pass key',
          active: true,
          label: 'Class 2 pass key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Cell key',
          active: true,
          label: 'Cell key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Class 3 A1 Suite key',
          active: true,
          label: 'Class 3 A1 Suite key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Class 3 Accountable key',
          active: true,
          label: 'Class 3 Accountable key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Handcuff key',
          active: true,
          label: 'Handcuff key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Escort Chain key',
          active: true,
          label: 'Escort Chain key',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Class 1 Lock',
          active: true,
          label: 'Class 1 Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Class 2 Lock',
          active: true,
          label: 'Class 2 Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Cell Lock',
          active: true,
          label: 'Cell Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Class 3 A1 Suite Lock',
          active: true,
          label: 'Class 3 A1 Suite Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Class 3 Accountable Lock',
          active: true,
          label: 'Class 3 Accountable Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Handcuffs',
          active: true,
          label: 'Handcuffs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Escort chain',
          active: true,
          label: 'Escort chain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Electronic Lock System',
          active: true,
          label: 'Electronic Lock System',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Magnetic Keys',
          active: true,
          label: 'Magnetic Keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Magnetic Lock',
          active: true,
          label: 'Magnetic Lock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Cell Door',
          active: true,
          label: 'Cell Door',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Brent Keys',
          active: true,
          label: 'Brent Keys',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45198',
        },
        {
          code: 'Other :  Specify',
          active: true,
          label: 'Other :  Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45198',
        },
      ],
    },
    '45198': {
      id: '45198',
      active: true,
      code: 'Incident Level: 1-5. 1 High Risk, 5 No Risk',
      label: 'Incident Level: 1-5. 1 High Risk, 5 No Risk',
      multipleAnswers: false,
      answers: [
        {
          code: 'Enter Value:',
          active: false,
          label: 'Enter Value:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Enter Value:',
          active: true,
          label: 'Enter Value:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45199',
        },
      ],
    },
    '45199': {
      id: '45199',
      active: true,
      code: 'Has any remedial action been taken?',
      label: 'Has any remedial action been taken?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45200',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45200',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45202',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45202',
        },
      ],
    },
    '45200': {
      id: '45200',
      active: true,
      code: 'Describe the remedial action taken',
      label: 'Describe the remedial action taken',
      multipleAnswers: false,
      answers: [
        {
          code: 'Complete relock',
          active: false,
          label: 'Complete relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Partial relock',
          active: false,
          label: 'Partial relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Complete replacement',
          active: false,
          label: 'Complete replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Partial replacement',
          active: false,
          label: 'Partial replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Forensic testing',
          active: false,
          label: 'Forensic testing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Complete relock',
          active: true,
          label: 'Complete relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          code: 'Partial relock',
          active: true,
          label: 'Partial relock',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          code: 'Complete replacement',
          active: true,
          label: 'Complete replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          code: 'Partial replacement',
          active: true,
          label: 'Partial replacement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          code: 'Forensic testing',
          active: true,
          label: 'Forensic testing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45201',
        },
        {
          code: 'Other',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45201',
        },
      ],
    },
    '45201': {
      id: '45201',
      active: true,
      code: 'Estimated cost of this action',
      label: 'Estimated cost of this action',
      multipleAnswers: false,
      answers: [
        {
          code: '£',
          active: false,
          label: '£',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£',
          active: true,
          label: '£',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45202',
        },
        {
          code: 'N/A',
          active: true,
          label: 'N/A',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45202',
        },
      ],
    },
    '45202': {
      id: '45202',
      active: true,
      code: 'Have the lost item (s) been found?',
      label: 'Have the lost item (s) been found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45203',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45203',
        },
        {
          code: 'N/A',
          active: true,
          label: 'N/A',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45203',
        },
      ],
    },
    '45203': {
      id: '45203',
      active: true,
      code: 'Has a replica key been found?',
      label: 'Has a replica key been found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45204',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45204',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
        {
          code: 'N/A',
          active: true,
          label: 'N/A',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
      ],
    },
    '45204': {
      id: '45204',
      active: true,
      code: 'What action was taken to find these items?',
      label: 'What action was taken to find these items?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Full close down search',
          active: false,
          label: 'Full close down search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Partial search',
          active: false,
          label: 'Partial search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Other: Specify',
          active: false,
          label: 'Other: Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Full close down search',
          active: true,
          label: 'Full close down search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
        {
          code: 'Partial search',
          active: true,
          label: 'Partial search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45205',
        },
        {
          code: 'Other: Please specify',
          active: true,
          label: 'Other: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45205',
        },
      ],
    },
    '45205': {
      id: '45205',
      active: true,
      code: 'Were tools used in the Incident?',
      label: 'Were tools used in the Incident?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45206',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45206',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
      ],
    },
    '45206': {
      id: '45206',
      active: true,
      code: 'What tools/foreign objects were used?',
      label: 'What tools/foreign objects were used?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Hacksaw blade',
          active: false,
          label: 'Hacksaw blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Other Blade',
          active: false,
          label: 'Other Blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Wire cutters',
          active: false,
          label: 'Wire cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Bolt cutters',
          active: false,
          label: 'Bolt cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Digging tool',
          active: false,
          label: 'Digging tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Crow bar',
          active: false,
          label: 'Crow bar',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Improvised tool',
          active: false,
          label: 'Improvised tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Other: Specify',
          active: false,
          label: 'Other: Specify',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Not Known',
          active: false,
          label: 'Not Known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Hacksaw blade',
          active: true,
          label: 'Hacksaw blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Other blade',
          active: true,
          label: 'Other blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Wire cutters',
          active: true,
          label: 'Wire cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Bolt cutters',
          active: true,
          label: 'Bolt cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Digging tool',
          active: true,
          label: 'Digging tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Crow bar',
          active: true,
          label: 'Crow bar',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Improvised tool',
          active: true,
          label: 'Improvised tool',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Other: Please specify',
          active: true,
          label: 'Other: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45207',
        },
        {
          code: 'Not Known',
          active: true,
          label: 'Not Known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45207',
        },
      ],
    },
    '45207': {
      id: '45207',
      active: true,
      code: 'What was the source of the tools/foreign object?',
      label: 'What was the source of the tools/foreign object?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Works Department',
          active: false,
          label: 'Works Department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Contractors',
          active: false,
          label: 'Contractors',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Education',
          active: false,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Heathcare Centre',
          active: false,
          label: 'Heathcare Centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Farms and Gardens',
          active: false,
          label: 'Farms and Gardens',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Staff',
          active: false,
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Visitor',
          active: false,
          label: 'Visitor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Other: Specify',
          active: false,
          label: 'Other: Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Not Known',
          active: false,
          label: 'Not Known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Works Department',
          active: true,
          label: 'Works Department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Contractors',
          active: true,
          label: 'Contractors',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Education',
          active: true,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Health Care Centre',
          active: true,
          label: 'Health Care Centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Farms and Gardens',
          active: true,
          label: 'Farms and Gardens',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Staff',
          active: true,
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Visitor',
          active: true,
          label: 'Visitor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Other: Please specify',
          active: true,
          label: 'Other: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45208',
        },
        {
          code: 'Not Known',
          active: true,
          label: 'Not Known',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45208',
        },
      ],
    },
    '45208': {
      id: '45208',
      active: true,
      code: 'Has the Key Lock Incident been reported to NOU?',
      label: 'Has the Key Lock Incident been reported to NOU?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Yes: Date',
          active: true,
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Incident Ref No:',
          active: true,
          label: 'Incident Ref No:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default KEY_LOCK_INCIDENT
