// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-16T15:42:06.482Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_FINDS1: IncidentTypeConfiguration = {
  incidentType: 'OLD_FINDS1',
  active: false,
  startingQuestionId: '51230',
  questions: {
    '51230': {
      id: '51230',
      code: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT?',
      label: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT?',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO FURTHER ACTION',
          label: 'NO FURTHER ACTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51231',
        },
        {
          code: 'IEP REGRESSION',
          label: 'IEP REGRESSION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51231',
        },
        {
          code: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          label: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51231',
        },
        {
          code: 'POLICE REFERRAL',
          label: 'POLICE REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51231',
        },
        {
          code: 'CPS REFERRAL',
          label: 'CPS REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51231',
        },
        {
          code: 'PROSECUTION REFERRAL',
          label: 'PROSECUTION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51231',
        },
      ],
    },
    '51231': {
      id: '51231',
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES?',
      label: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51232',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51232',
        },
      ],
    },
    '51232': {
      id: '51232',
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      label: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51233',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
      ],
    },
    '51233': {
      id: '51233',
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'ASSOCIATION AREA',
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'CELL',
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'CHAPEL',
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'CROWN COURT',
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'DINING ROOM',
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'DORMITORY',
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'EDUCATION',
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'ELSEWHERE',
          label: 'ELSEWHERE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'EXERCISE YARD',
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'FUNERAL',
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'GATE',
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'GYM',
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'HEALTH CARE CENTRE',
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'KITCHEN',
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'MAGISTRATES COURT',
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'OFFICE',
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'RECEPTION',
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'RECESS',
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'SEGREGATION UNIT',
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'SHOWERS/CHANGING ROOM',
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'SPECIAL UNIT',
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'SPORTS FIELD',
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'VEHICLE',
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'VISITS',
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'WEDDINGS',
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'WING',
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'WITHIN PERIMETER',
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'WORKS DEPARTMENT',
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'WORKSHOP',
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'INDUCTION/FIRST NIGHT CENTRE',
          label: 'INDUCTION/FIRST NIGHT CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'MAIL ROOM',
          label: 'MAIL ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'EXTERNAL ROOF',
          label: 'EXTERNAL ROOF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
        {
          code: 'VULNERABLE PRISONERS UNIT (VPU)',
          label: 'VULNERABLE PRISONERS UNIT (VPU)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51234',
        },
      ],
    },
    '51234': {
      id: '51234',
      code: 'WAS A DRUG FOUND?',
      label: 'WAS A DRUG FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51235',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51240',
        },
      ],
    },
    '51235': {
      id: '51235',
      code: 'DESCRIBE THE DRUG FOUND',
      label: 'DESCRIBE THE DRUG FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'AMPHETAMINES',
          label: 'AMPHETAMINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'BARBITURATES',
          label: 'BARBITURATES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'BENZODIAZEPINES',
          label: 'BENZODIAZEPINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'BUPRENORPHINE/SUBUTEX',
          label: 'BUPRENORPHINE/SUBUTEX',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'CANNABIS',
          label: 'CANNABIS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'CANNABIS PLANT',
          label: 'CANNABIS PLANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'COCAINE',
          label: 'COCAINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'CRACK',
          label: 'CRACK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'HEROIN',
          label: 'HEROIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'LSD',
          label: 'LSD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'METHADONE',
          label: 'METHADONE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'PREGABALIN',
          label: 'PREGABALIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'TRANQUILISERS',
          label: 'TRANQUILISERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'TRAMADOL',
          label: 'TRAMADOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'GABAPENTIN',
          label: 'GABAPENTIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'NPS: SPICE',
          label: 'NPS: SPICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'NPS: BLACK MAMBA',
          label: 'NPS: BLACK MAMBA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'NPS: OTHER',
          label: 'NPS: OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'STEROIDS',
          label: 'STEROIDS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51236',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51236',
        },
      ],
    },
    '51236': {
      id: '51236',
      code: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND',
      label: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: '<1G',
          label: '<1G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '2G TO 5G',
          label: '2G TO 5G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '6G TO 10G',
          label: '6G TO 10G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '11G TO 20G',
          label: '11G TO 20G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '21G TO 30G',
          label: '21G TO 30G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '31G TO 40G',
          label: '31G TO 40G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '41G TO 50G',
          label: '41G TO 50G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '50G TO 100G',
          label: '50G TO 100G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '101G TO 200G',
          label: '101G TO 200G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '201G TO 300G',
          label: '201G TO 300G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '301G TO 400G',
          label: '301G TO 400G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '401G TO 500G',
          label: '401G TO 500G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: '501G TO 1,000G',
          label: '501G TO 1,000G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: 'MORE THAN 1KG',
          label: 'MORE THAN 1KG',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51237',
        },
      ],
    },
    '51237': {
      id: '51237',
      code: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      label: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51238',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51239',
        },
      ],
    },
    '51238': {
      id: '51238',
      code: 'HOW WAS THE SUBSTANCE ANALYSED?',
      label: 'HOW WAS THE SUBSTANCE ANALYSED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'FORENSIC LABORATORY',
          label: 'FORENSIC LABORATORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51239',
        },
        {
          code: 'LOCAL WITH BDH KIT OR SIMILAR',
          label: 'LOCAL WITH BDH KIT OR SIMILAR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51239',
        },
      ],
    },
    '51239': {
      id: '51239',
      code: 'TO WHICH POLICE STATION WERE SEIZED DRUGS SENT FOR DESTRUCTION?',
      label: 'TO WHICH POLICE STATION WERE SEIZED DRUGS SENT FOR DESTRUCTION?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NAME',
          label: 'NAME',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51240',
        },
      ],
    },
    '51240': {
      id: '51240',
      code: 'WAS DRUG EQUIPMENT FOUND?',
      label: 'WAS DRUG EQUIPMENT FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51241',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51242',
        },
      ],
    },
    '51241': {
      id: '51241',
      code: 'DESCRIBE DRUG EQUIPMENT FOUND',
      label: 'DESCRIBE DRUG EQUIPMENT FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'AUTHENTIC NEEDLE',
          label: 'AUTHENTIC NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51242',
        },
        {
          code: 'AUTHENTIC SYRINGE',
          label: 'AUTHENTIC SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51242',
        },
        {
          code: 'IMPROVISED NEEDLE',
          label: 'IMPROVISED NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51242',
        },
        {
          code: 'IMPROVISED SYRINGE',
          label: 'IMPROVISED SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51242',
        },
        {
          code: 'PIPE(S)',
          label: 'PIPE(S)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51242',
        },
        {
          code: 'ROACH',
          label: 'ROACH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51242',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51242',
        },
      ],
    },
    '51242': {
      id: '51242',
      code: 'WAS A MOBILE PHONE RELATED ITEM FOUND?',
      label: 'WAS A MOBILE PHONE RELATED ITEM FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51243',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51253',
        },
      ],
    },
    '51243': {
      id: '51243',
      code: 'WAS A MOBILE PHONE FOUND?',
      label: 'WAS A MOBILE PHONE FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51244',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
      ],
    },
    '51244': {
      id: '51244',
      code: 'ENTER NUMBER OF MOBILES FOUND',
      label: 'ENTER NUMBER OF MOBILES FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: '0',
          label: '0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: 'MORE THAN 20',
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51245',
        },
      ],
    },
    '51245': {
      id: '51245',
      code: 'WAS A SIM CARD FOUND?',
      label: 'WAS A SIM CARD FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51246',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
      ],
    },
    '51246': {
      id: '51246',
      code: 'ENTER NUMBER OF SIM CARDS FOUND',
      label: 'ENTER NUMBER OF SIM CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: '0',
          label: '0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: 'MORE THAN 20',
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51247',
        },
      ],
    },
    '51247': {
      id: '51247',
      code: 'WAS A MEMORY CARD FOUND?',
      label: 'WAS A MEMORY CARD FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51248',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
      ],
    },
    '51248': {
      id: '51248',
      code: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      label: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: '0',
          label: '0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: 'MORE THAN 20',
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51249',
        },
      ],
    },
    '51249': {
      id: '51249',
      code: 'WAS A CHARGER FOUND?',
      label: 'WAS A CHARGER FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51250',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51250',
        },
      ],
    },
    '51250': {
      id: '51250',
      code: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      label: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES: PLEASE SPECIFY',
          label: 'YES: PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51251',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51251',
        },
      ],
    },
    '51251': {
      id: '51251',
      code: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO NDTSG?',
      label: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO NDTSG?',
      multipleAnswers: true,
      answers: [
        {
          code: 'YES: DATE',
          label: 'YES: DATE',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '51252',
        },
        {
          code: 'EVIDENCE BAG NUMBER',
          label: 'EVIDENCE BAG NUMBER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51252',
        },
        {
          code: 'NO: PLEASE STATE WHY',
          label: 'NO: PLEASE STATE WHY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51252',
        },
      ],
    },
    '51252': {
      id: '51252',
      code: 'HAS PHONE/SIM/EQUIPMENT BEEN RETAINED BY POLICE?',
      label: 'HAS PHONE/SIM/EQUIPMENT BEEN RETAINED BY POLICE?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51253',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51253',
        },
      ],
    },
    '51253': {
      id: '51253',
      code: 'WAS A WEAPON FOUND?',
      label: 'WAS A WEAPON FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51254',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51255',
        },
      ],
    },
    '51254': {
      id: '51254',
      code: 'DESCRIBE THE WEAPON',
      label: 'DESCRIBE THE WEAPON',
      multipleAnswers: true,
      answers: [
        {
          code: 'BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC)',
          label: 'BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51255',
        },
        {
          code: 'KNIFE/BLADED ARTICLE',
          label: 'KNIFE/BLADED ARTICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51255',
        },
        {
          code: 'FIREARM (FAKE GUNS, AMMUNITION, CHEMICAL INCAPACITANT ETC)',
          label: 'FIREARM (FAKE GUNS, AMMUNITION, CHEMICAL INCAPACITANT ETC)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51255',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51255',
        },
      ],
    },
    '51255': {
      id: '51255',
      code: 'WAS ANY ALCOHOL/HOOCH FOUND?',
      label: 'WAS ANY ALCOHOL/HOOCH FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51256',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
      ],
    },
    '51256': {
      id: '51256',
      code: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND?',
      label: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: '< 1 LITRE',
          label: '< 1 LITRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: '1 TO 2 LITRES',
          label: '1 TO 2 LITRES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: '2 TO 3 LITRES',
          label: '2 TO 3 LITRES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: '3 TO 4 LITRES',
          label: '3 TO 4 LITRES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: '4 TO 5 LITRES',
          label: '4 TO 5 LITRES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: '6 TO 10 LITRES',
          label: '6 TO 10 LITRES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: '11 TO 20 LITRES',
          label: '11 TO 20 LITRES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: 'MORE THAN 20 LITRES',
          label: 'MORE THAN 20 LITRES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51257',
        },
      ],
    },
    '51257': {
      id: '51257',
      code: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      label: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51258',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51258',
        },
      ],
    },
    '51258': {
      id: '51258',
      code: 'WERE ANY OTHER REPORTABLE ITEMS FOUND?',
      label: 'WERE ANY OTHER REPORTABLE ITEMS FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51259',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51260',
        },
      ],
    },
    '51259': {
      id: '51259',
      code: 'DESCRIBE THE ITEM',
      label: 'DESCRIBE THE ITEM',
      multipleAnswers: false,
      answers: [
        {
          code: 'PLEASE SPECIFY',
          label: 'PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51260',
        },
      ],
    },
    '51260': {
      id: '51260',
      code: 'DESCRIBE HOW THE ITEM WAS FOUND',
      label: 'DESCRIBE HOW THE ITEM WAS FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'BOSS CHAIR',
          label: 'BOSS CHAIR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'CELL SEARCH',
          label: 'CELL SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'CRIME SCENE',
          label: 'CRIME SCENE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'DOG SEARCH',
          label: 'DOG SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'HIGH SENSITIVITY WAND',
          label: 'HIGH SENSITIVITY WAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'INFORMATION RECEIVED',
          label: 'INFORMATION RECEIVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'INTELLIGENCE LED SEARCH',
          label: 'INTELLIGENCE LED SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'ITEM OBSERVED',
          label: 'ITEM OBSERVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'MOBILE PHONE SIGNAL DETECTOR',
          label: 'MOBILE PHONE SIGNAL DETECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'MOBILE PHONE ROD',
          label: 'MOBILE PHONE ROD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'OTHER SEARCH (INMATE)',
          label: 'OTHER SEARCH (INMATE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'OTHER SEARCH (PREMISES)',
          label: 'OTHER SEARCH (PREMISES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'OTHER SEARCH (VISITOR)',
          label: 'OTHER SEARCH (VISITOR)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'PRE-OCCUPATION SEARCH',
          label: 'PRE-OCCUPATION SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'UNUSUAL BEHAVIOUR',
          label: 'UNUSUAL BEHAVIOUR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51261',
        },
        {
          code: 'DRONE RECOVERY',
          label: 'DRONE RECOVERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51261',
        },
      ],
    },
    '51261': {
      id: '51261',
      code: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      label: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'VISITOR (FRIEND)',
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'VISITOR (OFFICIAL)',
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'VISITOR (RELATIVE)',
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'POST (RULE 39)',
          label: 'POST (RULE 39)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'POST (OTHER)',
          label: 'POST (OTHER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'THROWN IN',
          label: 'THROWN IN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'DRONE/UAV',
          label: 'DRONE/UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51262',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51262',
        },
      ],
    },
    '51262': {
      id: '51262',
      code: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      label: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51263',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51263',
        },
        {
          code: 'VISITOR (FRIEND)',
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51263',
        },
        {
          code: 'VISITOR (OFFICIAL)',
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51263',
        },
        {
          code: 'VISITOR (RELATIVE)',
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51263',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51263',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51263',
        },
        {
          code: 'NOT APPLICABLE',
          label: 'NOT APPLICABLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51263',
        },
      ],
    },
    '51263': {
      id: '51263',
      code: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      label: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NOT CONCEALED',
          label: 'NOT CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'BED/BEDDING',
          label: 'BED/BEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'BOOK/PAPERS',
          label: 'BOOK/PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'CELL/BUILDING FABRIC',
          label: 'CELL/BUILDING FABRIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'FOOD/CONTAINER',
          label: 'FOOD/CONTAINER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'IN CLOTHING',
          label: 'IN CLOTHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'IN HAND',
          label: 'IN HAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'IN MOUTH',
          label: 'IN MOUTH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'INTERNALLY/PLUGGED',
          label: 'INTERNALLY/PLUGGED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'LETTER/PARCEL',
          label: 'LETTER/PARCEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'LIGHT FITTINGS',
          label: 'LIGHT FITTINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'PIPEWORK',
          label: 'PIPEWORK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'RULE 39/LEGAL PAPERS',
          label: 'RULE 39/LEGAL PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'TV/RADIO/DVD/CONSOLES ETC',
          label: 'TV/RADIO/DVD/CONSOLES ETC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
        {
          code: 'OTHER',
          label: 'OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51264',
        },
      ],
    },
    '51264': {
      id: '51264',
      code: 'IS THE ITEM HEAVILY CONTAMINATED (E.G. BLOOD OR FAECES)?',
      label: 'IS THE ITEM HEAVILY CONTAMINATED (E.G. BLOOD OR FAECES)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51265',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51265',
        },
      ],
    },
    '51265': {
      id: '51265',
      code: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE?',
      label: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51266',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51268',
        },
      ],
    },
    '51266': {
      id: '51266',
      code: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      label: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      multipleAnswers: false,
      answers: [
        {
          code: 'AFTER ENTERING PRISON',
          label: 'AFTER ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51267',
        },
        {
          code: 'BEFORE ENTERING PRISON',
          label: 'BEFORE ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51267',
        },
      ],
    },
    '51267': {
      id: '51267',
      code: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN?',
      label: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'PLEASE SPECIFY',
          label: 'PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51268',
        },
      ],
    },
    '51268': {
      id: '51268',
      code: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      label: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51269',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51270',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51270',
        },
      ],
    },
    '51269': {
      id: '51269',
      code: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      label: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      multipleAnswers: false,
      answers: [
        {
          code: 'COMMUNITY VISIT',
          label: 'COMMUNITY VISIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51270',
        },
        {
          code: 'COMPASSIONATE',
          label: 'COMPASSIONATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51270',
        },
        {
          code: 'FACILITY',
          label: 'FACILITY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51270',
        },
        {
          code: 'RESETTLEMENT',
          label: 'RESETTLEMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51270',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51270',
        },
      ],
    },
    '51270': {
      id: '51270',
      code: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND (DRUGS, MOBILE PHONES ETC)',
      label: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND (DRUGS, MOBILE PHONES ETC)',
      multipleAnswers: false,
      answers: [
        {
          code: '£0',
          label: '£0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1 TO £100',
          label: '£1 TO £100',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£101 TO £200',
          label: '£101 TO £200',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£201 TO £300',
          label: '£201 TO £300',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£301 TO £400',
          label: '£301 TO £400',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£401 TO £500',
          label: '£401 TO £500',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£501 TO £1000',
          label: '£501 TO £1000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1001 TO £5000',
          label: '£1001 TO £5000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£5001 TO £10,000',
          label: '£5001 TO £10,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£10,001 TO £20,000',
          label: '£10,001 TO £20,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£20,001 TO £30,000',
          label: '£20,001 TO £30,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£30,001 TO £40,000',
          label: '£30,001 TO £40,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£40,001 TO £50,000',
          label: '£40,001 TO £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'MORE THAN £50,000',
          label: 'MORE THAN £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '57223': {
      id: '57223',
      code: 'WAS ANY TOBACCO FOUND',
      label: 'WAS ANY TOBACCO FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57224',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57226',
        },
      ],
    },
    '57224': {
      id: '57224',
      code: 'DESCRIBE THE TOBACCO FOUND',
      label: 'DESCRIBE THE TOBACCO FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'LOOSE TOBACCO',
          label: 'LOOSE TOBACCO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57225',
        },
        {
          code: 'CIGARETTES/CIGARS',
          label: 'CIGARETTES/CIGARS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57225',
        },
        {
          code: 'OTHER (including packaging and roaches)',
          label: 'OTHER (including packaging and roaches)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57225',
        },
      ],
    },
    '57225': {
      id: '57225',
      code: 'APPROX WEIGHT OF TOBACCO',
      label: 'APPROX WEIGHT OF TOBACCO',
      multipleAnswers: false,
      answers: [
        {
          code: 'UP TO 1 GRAMME',
          label: 'UP TO 1 GRAMME',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57226',
        },
        {
          code: '2g TO 5g',
          label: '2g TO 5g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57226',
        },
        {
          code: '6g to 10g',
          label: '6g to 10g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57226',
        },
        {
          code: '10g +',
          label: '10g +',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57226',
        },
      ],
    },
    '57226': {
      id: '57226',
      code: 'WERE ANY OTHER REPORTABLE ITEMS FOUND',
      label: 'WERE ANY OTHER REPORTABLE ITEMS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57227',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57228',
        },
      ],
    },
    '57227': {
      id: '57227',
      code: 'DESCRIBE THE ITEM',
      label: 'DESCRIBE THE ITEM',
      multipleAnswers: false,
      answers: [
        {
          code: 'PLEASE SPECIFY',
          label: 'PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57228',
        },
      ],
    },
    '57228': {
      id: '57228',
      code: 'DESCRIBE HOW THE ITEM WAS FOUND',
      label: 'DESCRIBE HOW THE ITEM WAS FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'BOSS CHAIR',
          label: 'BOSS CHAIR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57229',
        },
        {
          code: 'CELL SEARCH',
          label: 'CELL SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57229',
        },
        {
          code: 'CRIME SCENE',
          label: 'CRIME SCENE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57229',
        },
        {
          code: 'DOG SEARCH',
          label: 'DOG SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57229',
        },
        {
          code: 'DRONE RECOVERY',
          label: 'DRONE RECOVERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57229',
        },
        {
          code: 'HIGH SENSITIVITY WAND',
          label: 'HIGH SENSITIVITY WAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'INFORMATION RECEIVED',
          label: 'INFORMATION RECEIVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'NTELLIGENCE LED SEARCH',
          label: 'NTELLIGENCE LED SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'ITEM OBSERVED',
          label: 'ITEM OBSERVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'MOBILE PHONE SIGNAL DETECTOR',
          label: 'MOBILE PHONE SIGNAL DETECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'MOBILE PHONE ROD',
          label: 'MOBILE PHONE ROD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'OTHER SEARCH (INMATE)',
          label: 'OTHER SEARCH (INMATE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'OTHER SEARCH (PREMISES)',
          label: 'OTHER SEARCH (PREMISES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'OTHER SEARCH (VISITOR)',
          label: 'OTHER SEARCH (VISITOR)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'PRE-OCCUPATION SEARCH',
          label: 'PRE-OCCUPATION SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'UNUSUAL BEHAVIOUR',
          label: 'UNUSUAL BEHAVIOUR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57230',
        },
      ],
    },
    '57229': {
      id: '57229',
      code: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      label: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'VISITOR (FRIEND)',
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'VISITOR (RELATIVE)',
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'VISITOR (OFFICIAL)',
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'POST (RULE39)',
          label: 'POST (RULE39)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'POST (OTHER)',
          label: 'POST (OTHER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'DRONE/UAV',
          label: 'DRONE/UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'OTHER (PLEASE SPECIFY',
          label: 'OTHER (PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
        {
          code: 'THROWN IN',
          label: 'THROWN IN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57230',
        },
      ],
    },
    '57230': {
      id: '57230',
      code: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN',
      label: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57231',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57231',
        },
        {
          code: 'VISITOR (FRIEND)',
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57231',
        },
        {
          code: 'VISITOR (OFFICIAL)',
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57231',
        },
        {
          code: 'VISITOR (RELATIVE)',
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57231',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57231',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57231',
        },
        {
          code: 'NOT APPLICABLE',
          label: 'NOT APPLICABLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57231',
        },
      ],
    },
    '57231': {
      id: '57231',
      code: 'WHAT WAS THE METHOD OF CONCEALMENT',
      label: 'WHAT WAS THE METHOD OF CONCEALMENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'NOT CONCEALED',
          label: 'NOT CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'NOT CONCEALED',
          label: 'NOT CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'BED/BEDDING',
          label: 'BED/BEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'BOOK/PAPERS',
          label: 'BOOK/PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'CELL/BUILDING FABRIC',
          label: 'CELL/BUILDING FABRIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'FOOD/CONTAINER',
          label: 'FOOD/CONTAINER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'IN CLOTHING',
          label: 'IN CLOTHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'IN HAND',
          label: 'IN HAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'IN MOUTH',
          label: 'IN MOUTH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'INTERNALLY/PLUGGED',
          label: 'INTERNALLY/PLUGGED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'LETTER/PARCEL',
          label: 'LETTER/PARCEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'LIGHT FITTINGS',
          label: 'LIGHT FITTINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'PIPEWORK',
          label: 'PIPEWORK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'RULE 39/LEGAL PAPERS',
          label: 'RULE 39/LEGAL PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'TV/RADIO/DVD/CONSOLES ETC.',
          label: 'TV/RADIO/DVD/CONSOLES ETC.',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57232',
        },
        {
          code: 'OTHER',
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57232',
        },
      ],
    },
    '57232': {
      id: '57232',
      code: 'IS THE ITEM HEAVILY CONTAMINATED (E.G. BLOOD,  FAECES)',
      label: 'IS THE ITEM HEAVILY CONTAMINATED (E.G. BLOOD,  FAECES)',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57233',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57233',
        },
      ],
    },
    '57233': {
      id: '57233',
      code: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE',
      label: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57234',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57234',
        },
      ],
    },
    '57234': {
      id: '57234',
      code: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      label: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      multipleAnswers: false,
      answers: [
        {
          code: 'AFTER ENTERING PRISON',
          label: 'AFTER ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57235',
        },
        {
          code: 'BEFORE ENTERING PRISON',
          label: 'BEFORE ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57235',
        },
      ],
    },
    '57235': {
      id: '57235',
      code: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN TO',
      label: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN TO',
      multipleAnswers: false,
      answers: [
        {
          code: 'SPECIFY',
          label: 'SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57236',
        },
      ],
    },
    '57236': {
      id: '57236',
      code: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE',
      label: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57237',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57238',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57238',
        },
      ],
    },
    '57237': {
      id: '57237',
      code: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      label: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      multipleAnswers: false,
      answers: [
        {
          code: 'COMMUNITY VISIT',
          label: 'COMMUNITY VISIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57238',
        },
        {
          code: 'COMPASSIONATE',
          label: 'COMPASSIONATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57238',
        },
        {
          code: 'FACILTY',
          label: 'FACILTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57238',
        },
        {
          code: 'RESETTLEMENT',
          label: 'RESETTLEMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57238',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57238',
        },
      ],
    },
    '57238': {
      id: '57238',
      code: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND (DRUGS, MOBILE PHONES ETC.)',
      label: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND (DRUGS, MOBILE PHONES ETC.)',
      multipleAnswers: false,
      answers: [
        {
          code: '£0',
          label: '£0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1 to £100',
          label: '£1 to £100',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£101 to £200',
          label: '£101 to £200',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£201 to £300',
          label: '£201 to £300',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£301 to £400',
          label: '£301 to £400',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£401 to £500',
          label: '£401 to £500',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£501 to £1,000',
          label: '£501 to £1,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1,001 to £5,000',
          label: '£1,001 to £5,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£5,001 to £10,000',
          label: '£5,001 to £10,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£10,001 to £20,000',
          label: '£10,001 to £20,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£20,001 to £30,000',
          label: '£20,001 to £30,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£30,001 to £40,000',
          label: '£30,001 to £40,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£40,001 to £50,000',
          label: '£40,001 to £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'More than £50,000',
          label: 'More than £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default OLD_FINDS1
