// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-12-09T14:24:03.375Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_BARRICADE: IncidentTypeConfiguration = {
  incidentType: 'OLD_BARRICADE',
  active: false,
  startingQuestionId: '44439',
  questions: {
    '44174': {
      id: '44174',
      active: false,
      code: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'Who was detained in outside hospital?',
      multipleAnswers: true,
      answers: [
        {
          id: '179077',
          code: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179076',
          code: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179073',
          code: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179075',
          code: 'POLICE',
          active: false,
          label: 'Police',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179074',
          code: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
      ],
    },
    '44185': {
      id: '44185',
      active: false,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          id: '179100',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44263',
        },
        {
          id: '179099',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44263',
        },
      ],
    },
    '44191': {
      id: '44191',
      active: false,
      code: 'WAS A DOOR JACK USED',
      label: 'Was a door jack used?',
      multipleAnswers: false,
      answers: [
        {
          id: '179116',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44860',
        },
        {
          id: '179115',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44860',
        },
      ],
    },
    '44206': {
      id: '44206',
      active: false,
      code: 'WAS THE SYSTEM COMPROMISED?',
      label: 'Was the system compromised?',
      multipleAnswers: false,
      answers: [
        {
          id: '179185',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44987',
        },
        {
          id: '179186',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44632',
        },
      ],
    },
    '44222': {
      id: '44222',
      active: false,
      code: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      label: 'Are any staff on sick leave as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '179218',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44665',
        },
        {
          id: '179217',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44665',
        },
      ],
    },
    '44227': {
      id: '44227',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      label: 'Was the telephone/it system shut down during the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '179237',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44629',
        },
        {
          id: '179238',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44263': {
      id: '44263',
      active: false,
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          id: '179352',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44532',
        },
        {
          id: '179353',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
      ],
    },
    '44348': {
      id: '44348',
      active: false,
      code: 'DESCRIBE THE DAMAGE',
      label: 'Describe the damage',
      multipleAnswers: false,
      answers: [
        {
          id: '179670',
          code: 'EXTENSIVE',
          active: false,
          label: 'Extensive',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44413',
        },
        {
          id: '179671',
          code: 'MINOR',
          active: false,
          label: 'Minor',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44413',
        },
        {
          id: '179672',
          code: 'SERIOUS',
          active: false,
          label: 'Serious',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44413',
        },
      ],
    },
    '44357': {
      id: '44357',
      active: false,
      code: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'Is the incident the subject of a police investigation?',
      multipleAnswers: false,
      answers: [
        {
          id: '179702',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44879',
        },
        {
          id: '179703',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
      ],
    },
    '44378': {
      id: '44378',
      active: false,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'Was damage caused to prison property?',
      multipleAnswers: false,
      answers: [
        {
          id: '179782',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44348',
        },
        {
          id: '179783',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45171',
        },
      ],
    },
    '44401': {
      id: '44401',
      active: false,
      code: 'WAS THE KEYWORD REQUESTED?',
      label: 'Was the keyword requested?',
      multipleAnswers: false,
      answers: [
        {
          id: '179844',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44932',
        },
        {
          id: '179845',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
      ],
    },
    '44413': {
      id: '44413',
      active: false,
      code: 'ESTIMATED COST OF DAMAGE',
      label: 'Estimated cost of damage',
      multipleAnswers: false,
      answers: [
        {
          id: '179884',
          code: 'ENTER AMOUNT IN POUND STERLING',
          active: false,
          label: 'Enter amount in pound sterling',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45171',
        },
      ],
    },
    '44439': {
      id: '44439',
      active: false,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '179942',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44357',
        },
        {
          id: '179943',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
      ],
    },
    '44461': {
      id: '44461',
      active: false,
      code: 'DESCRIBE WEAPONS USED',
      label: 'Describe weapons used',
      multipleAnswers: true,
      answers: [
        {
          id: '180020',
          code: 'FIREARM',
          active: false,
          label: 'Firearm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180017',
          code: 'CHEMICAL INCAPACITANT',
          active: false,
          label: 'Chemical incapacitant',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180022',
          code: 'KNIFE/BLADE',
          active: false,
          label: 'Knife/blade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180025',
          code: 'OTHER SHARP INSTRUMENT',
          active: false,
          label: 'Other sharp instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180016',
          code: 'BLUNT INSTRUMENT',
          active: false,
          label: 'Blunt instrument',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180023',
          code: 'LIGATURE',
          active: false,
          label: 'Ligature',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180018',
          code: 'DANGEROUS LIQUID',
          active: false,
          label: 'Dangerous liquid',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180019',
          code: 'EXCRETA/URINE',
          active: false,
          label: 'Excreta/urine',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180026',
          code: 'SPITTING',
          active: false,
          label: 'Spitting',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180021',
          code: 'FOOD',
          active: false,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180028',
          code: 'THROWN FURNITURE',
          active: false,
          label: 'Thrown furniture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180027',
          code: 'THROWN EQUIPMENT',
          active: false,
          label: 'Thrown equipment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180024',
          code: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44378',
        },
      ],
    },
    '44482': {
      id: '44482',
      active: false,
      code: 'QUOTE THE VANTIVE CASE NUMBER',
      label: 'Quote the Vantive case number',
      multipleAnswers: false,
      answers: [
        {
          id: '180153',
          code: 'ENTER NUMBER',
          active: false,
          label: 'Enter number',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44401',
        },
      ],
    },
    '44492': {
      id: '44492',
      active: false,
      code: 'WHO AUTHORISED THE SHUT DOWN?',
      label: 'Who authorised the shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '180186',
          code: 'GOVERNOR',
          active: false,
          label: 'Governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44206',
        },
        {
          id: '180184',
          code: 'DEPUTY GOVERNOR',
          active: false,
          label: 'Deputy governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44206',
        },
        {
          id: '180185',
          code: 'DUTY GOVERNOR',
          active: false,
          label: 'Duty governor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44206',
        },
        {
          id: '180187',
          code: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44206',
        },
      ],
    },
    '44505': {
      id: '44505',
      active: false,
      code: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'Describe how the incident was resolved',
      multipleAnswers: false,
      answers: [
        {
          id: '180239',
          code: 'NEGOTIATION',
          active: false,
          label: 'Negotiation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44191',
        },
        {
          id: '180238',
          code: 'INTERVENTION',
          active: false,
          label: 'Intervention',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44191',
        },
        {
          id: '180240',
          code: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44191',
        },
      ],
    },
    '44515': {
      id: '44515',
      active: false,
      code: 'WERE WEAPONS USED BY THE PERPETRATOR',
      label: 'Were weapons used by the perpetrator?',
      multipleAnswers: false,
      answers: [
        {
          id: '180264',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44461',
        },
        {
          id: '180265',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
      ],
    },
    '44530': {
      id: '44530',
      active: false,
      code: 'INDICATE THE NATURE OF THE SHUT DOWN',
      label: 'Indicate the nature of the shut down',
      multipleAnswers: true,
      answers: [
        {
          id: '180351',
          code: 'TELEPHONY',
          active: false,
          label: 'Telephony',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44666',
        },
        {
          id: '180350',
          code: 'IT',
          active: false,
          label: 'It',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44666',
        },
      ],
    },
    '44532': {
      id: '44532',
      active: false,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '180354',
          code: 'ADMINISTRATION',
          active: false,
          label: 'Administration',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180355',
          code: 'ASSOCIATION AREA',
          active: false,
          label: 'Association area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180356',
          code: 'CELL',
          active: false,
          label: 'Cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180357',
          code: 'CHAPEL',
          active: false,
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180359',
          code: 'DINING ROOM',
          active: false,
          label: 'Dining room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180360',
          code: 'DORMITORY',
          active: false,
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180361',
          code: 'EDUCATION',
          active: false,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180363',
          code: 'EXERCISE YARD',
          active: false,
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180365',
          code: 'GATE',
          active: false,
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180366',
          code: 'GYM',
          active: false,
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180367',
          code: 'HEALTH CARE CENTRE',
          active: false,
          label: 'Health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180370',
          code: 'KITCHEN',
          active: false,
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180372',
          code: 'OFFICE',
          active: false,
          label: 'Office',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180374',
          code: 'RECEPTION',
          active: false,
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180375',
          code: 'RECESS',
          active: false,
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180376',
          code: 'SEGREGATION UNIT',
          active: false,
          label: 'Segregation unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180378',
          code: 'SPECIAL UNIT',
          active: false,
          label: 'Special unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180377',
          code: 'SHOWERS/CHANGING ROOM',
          active: false,
          label: 'Showers/changing room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180381',
          code: 'VISITS',
          active: false,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180383',
          code: 'WING',
          active: false,
          label: 'Wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180385',
          code: 'WORKS DEPARTMENT',
          active: false,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180386',
          code: 'WORKSHOP',
          active: false,
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180384',
          code: 'WITHIN PERIMETER',
          active: false,
          label: 'Within perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180362',
          code: 'ELSEWHERE (ENTER DETAILS)',
          active: false,
          label: 'Elsewhere (enter details)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180364',
          code: 'FUNERAL',
          active: false,
          label: 'Funeral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180368',
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: false,
          label: 'Hospital outside (patient)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180369',
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: false,
          label: 'Hospital outside (visiting)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180373',
          code: 'OUTSIDE WORKING PARTY',
          active: false,
          label: 'Outside working party',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180379',
          code: 'SPORTS FIELD',
          active: false,
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180380',
          code: 'VEHICLE',
          active: false,
          label: 'Vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180382',
          code: 'WEDDINGS',
          active: false,
          label: 'Weddings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180371',
          code: 'MAGISTRATES COURT',
          active: false,
          label: 'Magistrates court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180358',
          code: 'CROWN COURT',
          active: false,
          label: 'Crown court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
      ],
    },
    '44563': {
      id: '44563',
      active: false,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'Enter description of person(s) injured',
      multipleAnswers: true,
      answers: [
        {
          id: '180471',
          code: 'STAFF',
          active: false,
          label: 'Staff',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180470',
          code: 'PRISONERS',
          active: false,
          label: 'Prisoners',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180467',
          code: 'CIVILIAN GRADES',
          active: false,
          label: 'Civilian grades',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180469',
          code: 'POLICE',
          active: false,
          label: 'Police',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180468',
          code: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'External civilians',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
      ],
    },
    '44620': {
      id: '44620',
      active: false,
      code: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE IT AND T SERVICE SUPPLIER?',
      label: 'Was the system re-activated locally or by the it and t service supplier?',
      multipleAnswers: false,
      answers: [
        {
          id: '180657',
          code: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '180658',
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44629': {
      id: '44629',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'Was the telephone/it system shut down locally or by the service supplier?',
      multipleAnswers: false,
      answers: [
        {
          id: '180692',
          code: 'LOCAL',
          active: false,
          label: 'Local',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
        {
          id: '180691',
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'Service supplier',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44482',
        },
      ],
    },
    '44632': {
      id: '44632',
      active: false,
      code: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      label: 'When was the system re-activated?',
      multipleAnswers: false,
      answers: [
        {
          id: '180698',
          code: 'ENTER COMMENT AND DATE',
          active: false,
          label: 'Enter comment and date',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '44620',
        },
      ],
    },
    '44634': {
      id: '44634',
      active: false,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'Which minor injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '180704',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: false,
          label: 'Grazes, scratches or abrasions',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180705',
          code: 'MINOR BRUISES',
          active: false,
          label: 'Minor bruises',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180708',
          code: 'SWELLINGS',
          active: false,
          label: 'Swellings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180707',
          code: 'SUPERFICIAL CUTS',
          active: false,
          label: 'Superficial cuts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180706',
          code: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44563',
        },
      ],
    },
    '44665': {
      id: '44665',
      active: false,
      code: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      label: 'Was there an apparent reason for the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '180805',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44704',
        },
        {
          id: '180806',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
      ],
    },
    '44666': {
      id: '44666',
      active: false,
      code: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      label: 'What time was the system shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '180807',
          code: 'ENTER TIME',
          active: false,
          label: 'Enter time',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44947',
        },
      ],
    },
    '44704': {
      id: '44704',
      active: false,
      code: 'DESCRIBE THE APPARENT REASON FOR THE INCIDENT',
      label: 'Describe the apparent reason for the incident',
      multipleAnswers: true,
      answers: [
        {
          id: '180961',
          code: 'FACILITIES',
          active: false,
          label: 'Facilities',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180962',
          code: 'FOOD',
          active: false,
          label: 'Food',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180964',
          code: 'PAY',
          active: false,
          label: 'Pay',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180966',
          code: 'VISITS',
          active: false,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180965',
          code: 'TIME OUT OF CELL',
          active: false,
          label: 'Time out of cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180963',
          code: 'OTHER',
          active: false,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44505',
        },
      ],
    },
    '44722': {
      id: '44722',
      active: false,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'Which serious injuries were sustained?',
      multipleAnswers: true,
      answers: [
        {
          id: '181014',
          code: 'FRACTURE',
          active: false,
          label: 'Fracture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181016',
          code: 'SCALD OR BURN',
          active: false,
          label: 'Scald or burn',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181017',
          code: 'STABBING',
          active: false,
          label: 'Stabbing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181011',
          code: 'CRUSHING',
          active: false,
          label: 'Crushing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181013',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: false,
          label: 'Extensive/multiple bruising',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181008',
          code: 'BLACK EYE',
          active: false,
          label: 'Black eye',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181009',
          code: 'BROKEN NOSE',
          active: false,
          label: 'Broken nose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181010',
          code: 'BROKEN TEETH',
          active: false,
          label: 'Broken teeth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181012',
          code: 'CUTS REQUIRING SUTURES',
          active: false,
          label: 'Cuts requiring sutures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181007',
          code: 'BITES',
          active: false,
          label: 'Bites',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181015',
          code: 'GUN SHOT WOUND',
          active: false,
          label: 'Gun shot wound',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181018',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: false,
          label: 'Temporary/permanent blindness',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
      ],
    },
    '44796': {
      id: '44796',
      active: false,
      code: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'Did injuries result in detention in outside hospital as an in-patient?',
      multipleAnswers: false,
      answers: [
        {
          id: '181249',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44174',
        },
        {
          id: '181250',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45071',
        },
      ],
    },
    '44816': {
      id: '44816',
      active: false,
      code: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "Is the incident subject to a governor's adjudication?",
      multipleAnswers: false,
      answers: [
        {
          id: '181297',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44914',
        },
        {
          id: '181296',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44914',
        },
      ],
    },
    '44860': {
      id: '44860',
      active: false,
      code: 'WERE WATER HOSES USED',
      label: 'Were water hoses used?',
      multipleAnswers: false,
      answers: [
        {
          id: '181438',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45022',
        },
        {
          id: '181437',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45022',
        },
      ],
    },
    '44879': {
      id: '44879',
      active: false,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'Has any prosecution taken place or is any pending?',
      multipleAnswers: false,
      answers: [
        {
          id: '181516',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
        {
          id: '181515',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
      ],
    },
    '44914': {
      id: '44914',
      active: false,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181631',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44185',
        },
        {
          id: '181630',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44185',
        },
      ],
    },
    '44932': {
      id: '44932',
      active: false,
      code: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      label: 'Has the service supplier been notified of a replacement keyword?',
      multipleAnswers: false,
      answers: [
        {
          id: '181728',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
        {
          id: '181727',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
      ],
    },
    '44938': {
      id: '44938',
      active: false,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'Were any injuries received during this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '181749',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45075',
        },
        {
          id: '181750',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45071',
        },
      ],
    },
    '44947': {
      id: '44947',
      active: false,
      code: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      label: 'Was this a full or partial shut down?',
      multipleAnswers: false,
      answers: [
        {
          id: '181779',
          code: 'FULL',
          active: false,
          label: 'Full',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44492',
        },
        {
          id: '181780',
          code: 'PARTIAL',
          active: false,
          label: 'Partial',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44492',
        },
      ],
    },
    '44987': {
      id: '44987',
      active: false,
      code: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      label: 'Describe what was compromised and by whom',
      multipleAnswers: false,
      answers: [
        {
          id: '181924',
          code: 'DESCRIBE COMPROMISE',
          active: false,
          label: 'Describe compromise',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44632',
        },
      ],
    },
    '45022': {
      id: '45022',
      active: false,
      code: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      label: 'Was control and restraints employed?',
      multipleAnswers: false,
      answers: [
        {
          id: '182031',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44515',
        },
        {
          id: '182030',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44515',
        },
      ],
    },
    '45071': {
      id: '45071',
      active: false,
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'Are there any staff now off duty as a result of this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '182259',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44222',
        },
        {
          id: '182258',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44222',
        },
      ],
    },
    '45075': {
      id: '45075',
      active: false,
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'Was a serious injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '182270',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44722',
        },
        {
          id: '182271',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
      ],
    },
    '45083': {
      id: '45083',
      active: false,
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'Was a minor injury sustained?',
      multipleAnswers: false,
      answers: [
        {
          id: '182288',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44634',
        },
        {
          id: '182289',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
      ],
    },
    '45086': {
      id: '45086',
      active: false,
      code: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'Is the incident the subject of an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          id: '182296',
          code: 'YES',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44816',
        },
        {
          id: '182295',
          code: 'NO',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44816',
        },
      ],
    },
    '45171': {
      id: '45171',
      active: false,
      code: 'DURATION OF INCIDENT IN HOURS',
      label: 'Duration of incident in hours',
      multipleAnswers: false,
      answers: [
        {
          id: '182628',
          code: 'ENTER HOURS',
          active: false,
          label: 'Enter hours',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44227',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default OLD_BARRICADE
