// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-16T15:42:02.719Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_DRONE_SIGHTING: IncidentTypeConfiguration = {
  incidentType: 'OLD_DRONE_SIGHTING',
  active: false,
  startingQuestionId: '57179',
  questions: {
    '57179': {
      id: '57179',
      code: 'Was a drone sighted in mid-flight',
      label: 'Was a drone sighted in mid-flight',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57180',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57193',
        },
      ],
    },
    '57180': {
      id: '57180',
      code: 'What time was the drone(s) sighted.',
      label: 'What time was the drone(s) sighted.',
      multipleAnswers: false,
      answers: [
        {
          code: '12am to 6am',
          label: '12am to 6am',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57181',
        },
        {
          code: '6am to 12pm',
          label: '6am to 12pm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57181',
        },
        {
          code: '12pm to 6pm',
          label: '12pm to 6pm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57181',
        },
        {
          code: '6pm to 12am',
          label: '6pm to 12am',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57181',
        },
      ],
    },
    '57181': {
      id: '57181',
      code: 'Number of drones observed',
      label: 'Number of drones observed',
      multipleAnswers: false,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57184',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57184',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57184',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57184',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57184',
        },
        {
          code: '6+',
          label: '6+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57184',
        },
      ],
    },
    '57184': {
      id: '57184',
      code: 'Where was the drone(s) sighted',
      label: 'Where was the drone(s) sighted',
      multipleAnswers: true,
      answers: [
        {
          code: 'Beyond the external perimeter border',
          label: 'Beyond the external perimeter border',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57185',
        },
        {
          code: 'Exercise yard',
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57185',
        },
        {
          code: 'External roof',
          label: 'External roof',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57185',
        },
        {
          code: 'Gate',
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57185',
        },
        {
          code: 'Near cell window',
          label: 'Near cell window',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57185',
        },
        {
          code: 'Sports Field',
          label: 'Sports Field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57185',
        },
        {
          code: 'Within Perimeter',
          label: 'Within Perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57185',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57185',
        },
      ],
    },
    '57185': {
      id: '57185',
      code: 'For drone(s) sighted beyond perimeter border, how close did the nearest drone get to the wall',
      label: 'For drone(s) sighted beyond perimeter border, how close did the nearest drone get to the wall',
      multipleAnswers: false,
      answers: [
        {
          code: 'Not applicable',
          label: 'Not applicable',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57186',
        },
        {
          code: '0 to less than 10 metres',
          label: '0 to less than 10 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57186',
        },
        {
          code: '10 to less than 100 metres',
          label: '10 to less than 100 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57186',
        },
        {
          code: '100 to less than 200 metres',
          label: '100 to less than 200 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57186',
        },
        {
          code: '200 metres or more',
          label: '200 metres or more',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57186',
        },
      ],
    },
    '57186': {
      id: '57186',
      code: 'What was the estimated speed of the drone(s)',
      label: 'What was the estimated speed of the drone(s)',
      multipleAnswers: false,
      answers: [
        {
          code: 'Static',
          label: 'Static',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57187',
        },
        {
          code: 'Walking pace',
          label: 'Walking pace',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57187',
        },
        {
          code: 'Running pace',
          label: 'Running pace',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57187',
        },
        {
          code: 'Faster than running',
          label: 'Faster than running',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57187',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57187',
        },
      ],
    },
    '57187': {
      id: '57187',
      code: 'What was the flying pattern of the drone(s)',
      label: 'What was the flying pattern of the drone(s)',
      multipleAnswers: true,
      answers: [
        {
          code: 'Hovering',
          label: 'Hovering',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57188',
        },
        {
          code: 'Circling a point',
          label: 'Circling a point',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57188',
        },
        {
          code: 'Straight flight',
          label: 'Straight flight',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57188',
        },
        {
          code: 'Direct attack',
          label: 'Direct attack',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57188',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57188',
        },
      ],
    },
    '57188': {
      id: '57188',
      code: 'How many times has the drone(s) been seen here before',
      label: 'How many times has the drone(s) been seen here before',
      multipleAnswers: false,
      answers: [
        {
          code: 'Not believed to have been seen before',
          label: 'Not believed to have been seen before',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57189',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57189',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57189',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57189',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57189',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57189',
        },
        {
          code: '6 or more (please Specify)',
          label: '6 or more (please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57189',
        },
      ],
    },
    '57189': {
      id: '57189',
      code: 'What were the weather conditions at the time of the sighting',
      label: 'What were the weather conditions at the time of the sighting',
      multipleAnswers: true,
      answers: [
        {
          code: 'Clear visibility',
          label: 'Clear visibility',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
        {
          code: 'Poor visibility',
          label: 'Poor visibility',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
        {
          code: 'Light',
          label: 'Light',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
        {
          code: 'Dark',
          label: 'Dark',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
        {
          code: 'Rain',
          label: 'Rain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
        {
          code: 'High wind',
          label: 'High wind',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
        {
          code: 'Low wind',
          label: 'Low wind',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
        {
          code: 'Calm',
          label: 'Calm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57192',
        },
      ],
    },
    '57192': {
      id: '57192',
      code: 'Was the drone(s) recovered - Sighting and Recovery',
      label: 'Was the drone(s) recovered - Sighting and Recovery',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57194',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
      ],
    },
    '57193': {
      id: '57193',
      code: 'Was a drone recovered - Recovery only',
      label: 'Was a drone recovered - Recovery only',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57194',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '57194': {
      id: '57194',
      code: 'How many drone(s) was recovered',
      label: 'How many drone(s) was recovered',
      multipleAnswers: false,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57197',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57197',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57197',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57197',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57197',
        },
        {
          code: '6+',
          label: '6+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57197',
        },
      ],
    },
    '57197': {
      id: '57197',
      code: 'Where was the drone(s) recovered',
      label: 'Where was the drone(s) recovered',
      multipleAnswers: true,
      answers: [
        {
          code: 'Exercise yard',
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
        {
          code: 'External roof',
          label: 'External roof',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
        {
          code: 'Gate',
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
        {
          code: 'Near cell window',
          label: 'Near cell window',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
        {
          code: 'External perimeter border',
          label: 'External perimeter border',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
        {
          code: 'Sports field',
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
        {
          code: 'Within perimeter',
          label: 'Within perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
        {
          code: 'Other (please specify)',
          label: 'Other (please specify)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57198',
        },
      ],
    },
    '57198': {
      id: '57198',
      code: 'What was the drone(s) type/airframe shape',
      label: 'What was the drone(s) type/airframe shape',
      multipleAnswers: true,
      answers: [
        {
          code: 'Multicopter Square',
          label: 'Multicopter Square',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Multicopter Circular',
          label: 'Multicopter Circular',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Multicopter X-Shape',
          label: 'Multicopter X-Shape',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Multicopter Hourglass',
          label: 'Multicopter Hourglass',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Multicopter Other',
          label: 'Multicopter Other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Fixed wing Standard aircraft',
          label: 'Fixed wing Standard aircraft',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Fixed wing Delta-wing',
          label: 'Fixed wing Delta-wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Fixed wing Other',
          label: 'Fixed wing Other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57199',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57199',
        },
      ],
    },
    '57199': {
      id: '57199',
      code: 'What is the drone model',
      label: 'What is the drone model',
      multipleAnswers: true,
      answers: [
        {
          code: 'DJI Phantom',
          label: 'DJI Phantom',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'Syma X8C Venture',
          label: 'Syma X8C Venture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'DIY Racing UAV',
          label: 'DIY Racing UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'T600 Inspire 1',
          label: 'T600 Inspire 1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'Century NEO660',
          label: 'Century NEO660',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'X-8 Flyingwing',
          label: 'X-8 Flyingwing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'TALON X-UAV',
          label: 'TALON X-UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'Sky Hunter',
          label: 'Sky Hunter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'Piper model aircraft',
          label: 'Piper model aircraft',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57200',
        },
      ],
    },
    '57200': {
      id: '57200',
      code: 'How many motors does the drone(s) have',
      label: 'How many motors does the drone(s) have',
      multipleAnswers: true,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '8+',
          label: '8+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: '8+',
          label: '8+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57201',
        },
      ],
    },
    '57201': {
      id: '57201',
      code: 'What was the approximate length of the drone(s)',
      label: 'What was the approximate length of the drone(s)',
      multipleAnswers: true,
      answers: [
        {
          code: '0 to less than 1m',
          label: '0 to less than 1m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57202',
        },
        {
          code: '1m to less than 2m',
          label: '1m to less than 2m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57202',
        },
        {
          code: '2m to less than 3m',
          label: '2m to less than 3m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57202',
        },
        {
          code: '3m or longer',
          label: '3m or longer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57202',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57202',
        },
      ],
    },
    '57202': {
      id: '57202',
      code: 'What was the approximate width of the drone(s)',
      label: 'What was the approximate width of the drone(s)',
      multipleAnswers: true,
      answers: [
        {
          code: '0 to less than 1m',
          label: '0 to less than 1m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57203',
        },
        {
          code: '1m to less than 2m',
          label: '1m to less than 2m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57203',
        },
        {
          code: '2m to less than 3m',
          label: '2m to less than 3m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57203',
        },
        {
          code: '3m or longer',
          label: '3m or longer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57203',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57203',
        },
      ],
    },
    '57203': {
      id: '57203',
      code: 'What modifications were made to the drone(s)',
      label: 'What modifications were made to the drone(s)',
      multipleAnswers: true,
      answers: [
        {
          code: 'Painted black',
          label: 'Painted black',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57204',
        },
        {
          code: 'Removed camera',
          label: 'Removed camera',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57204',
        },
        {
          code: 'Added hook',
          label: 'Added hook',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57204',
        },
        {
          code: 'Covered lights',
          label: 'Covered lights',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57204',
        },
        {
          code: 'Other (please specify)',
          label: 'Other (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57204',
        },
        {
          code: 'None',
          label: 'None',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57204',
        },
      ],
    },
    '57204': {
      id: '57204',
      code: 'How was the drone(s) recovered',
      label: 'How was the drone(s) recovered',
      multipleAnswers: true,
      answers: [
        {
          code: 'Intercepted',
          label: 'Intercepted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57205',
        },
        {
          code: 'Crashed',
          label: 'Crashed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57205',
        },
      ],
    },
    '57205': {
      id: '57205',
      code: 'Did the drone(s) carry any package(s)',
      label: 'Did the drone(s) carry any package(s)',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57206',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57210',
        },
      ],
    },
    '57206': {
      id: '57206',
      code: 'Was the package(s) recovered',
      label: 'Was the package(s) recovered',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes (please enter the Finds Report incident number)',
          label: 'Yes (please enter the Finds Report incident number)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57207',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57210',
        },
      ],
    },
    '57207': {
      id: '57207',
      code: 'Total weight of the package(s)',
      label: 'Total weight of the package(s)',
      multipleAnswers: false,
      answers: [
        {
          code: '0 to less than 100g',
          label: '0 to less than 100g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '100g to less than 200g',
          label: '100g to less than 200g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '200g to less than 300g',
          label: '200g to less than 300g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '300g to less than 400g',
          label: '300g to less than 400g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '400g to less than 500g',
          label: '400g to less than 500g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '500g to less than 1kg',
          label: '500g to less than 1kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '1kg to less than 2kg',
          label: '1kg to less than 2kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '2kg to less than 3kg',
          label: '2kg to less than 3kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '3kg to less than 4kg',
          label: '3kg to less than 4kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '4kg to less than 5kg',
          label: '4kg to less than 5kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '5kg to less than 6kg',
          label: '5kg to less than 6kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '6kg to less than 7kg',
          label: '6kg to less than 7kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '7kg to less than 8kg',
          label: '7kg to less than 8kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '8kg to less than 9kg',
          label: '8kg to less than 9kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: '9kg to less than 10kg',
          label: '9kg to less than 10kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: 'More than 10kg',
          label: 'More than 10kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57208',
        },
      ],
    },
    '57208': {
      id: '57208',
      code: 'What items were in the package(s)',
      label: 'What items were in the package(s)',
      multipleAnswers: true,
      answers: [
        {
          code: 'Cameras',
          label: 'Cameras',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57209',
        },
        {
          code: 'Mobile phone devices',
          label: 'Mobile phone devices',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57209',
        },
        {
          code: 'Drugs',
          label: 'Drugs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57209',
        },
        {
          code: 'Weapons',
          label: 'Weapons',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57209',
        },
        {
          code: 'Alcohol/hooch',
          label: 'Alcohol/hooch',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57209',
        },
        {
          code: 'Tobacco',
          label: 'Tobacco',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57209',
        },
        {
          code: 'Other (please specify)',
          label: 'Other (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57209',
        },
      ],
    },
    '57209': {
      id: '57209',
      code: 'Enter the Finds incident number',
      label: 'Enter the Finds incident number',
      multipleAnswers: false,
      answers: [
        {
          code: 'Please specify',
          label: 'Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57210',
        },
      ],
    },
    '57210': {
      id: '57210',
      code: 'Were any photos taken of the drone and/or payload',
      label: 'Were any photos taken of the drone and/or payload',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes (specify where sent)',
          label: 'Yes (specify where sent)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57211',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57211',
        },
      ],
    },
    '57211': {
      id: '57211',
      code: 'Was the pilot identified',
      label: 'Was the pilot identified',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57212',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57215',
        },
      ],
    },
    '57212': {
      id: '57212',
      code: 'Do you know if the pilot was using line of sight',
      label: 'Do you know if the pilot was using line of sight',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57213',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57213',
        },
      ],
    },
    '57213': {
      id: '57213',
      code: 'Do you know the distance of the pilot from the prison',
      label: 'Do you know the distance of the pilot from the prison',
      multipleAnswers: false,
      answers: [
        {
          code: '0 to less than 10 metres',
          label: '0 to less than 10 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '10 to less than 100 metres',
          label: '10 to less than 100 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '100 to less than 200 metres',
          label: '100 to less than 200 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '200 metres or more',
          label: '200 metres or more',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57214',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57215',
        },
      ],
    },
    '57214': {
      id: '57214',
      code: 'What was the distance',
      label: 'What was the distance',
      multipleAnswers: false,
      answers: [
        {
          code: '0 to less than 10 metres',
          label: '0 to less than 10 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57215',
        },
        {
          code: '10 to less than 100 metres',
          label: '10 to less than 100 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57215',
        },
        {
          code: '100 to less than 200 metres',
          label: '100 to less than 200 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57215',
        },
        {
          code: '200 metres or more',
          label: '200 metres or more',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57215',
        },
      ],
    },
    '57215': {
      id: '57215',
      code: 'Were the police contacted',
      label: 'Were the police contacted',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57216',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57216',
        },
      ],
    },
    '57216': {
      id: '57216',
      code: 'To the extent of your knowledge, was the pilot apprehended',
      label: 'To the extent of your knowledge, was the pilot apprehended',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '57219': {
      id: '57219',
      code: 'Do you know the distance of the pilot from the prison?',
      label: 'Do you know the distance of the pilot from the prison?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57214',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57215',
        },
      ],
    },
  },
} as const

export default OLD_DRONE_SIGHTING
