// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-10-15T17:17:15.242Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_BARRICADE: IncidentTypeConfiguration = {
  incidentType: 'OLD_BARRICADE',
  active: false,
  startingQuestionId: '44439',
  questions: {
    '44174': {
      id: '44174',
      active: false,
      code: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      multipleAnswers: true,
      answers: [
        {
          id: '179077',
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179076',
          code: 'PRISONERS',
          active: false,
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179073',
          code: 'CIVILIAN GRADES',
          active: false,
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179075',
          code: 'POLICE',
          active: false,
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
        {
          id: '179074',
          code: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45071',
        },
      ],
    },
    '44185': {
      id: '44185',
      active: false,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          id: '179100',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44263',
        },
        {
          id: '179099',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44263',
        },
      ],
    },
    '44191': {
      id: '44191',
      active: false,
      code: 'WAS A DOOR JACK USED',
      label: 'WAS A DOOR JACK USED',
      multipleAnswers: false,
      answers: [
        {
          id: '179116',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44860',
        },
        {
          id: '179115',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44860',
        },
      ],
    },
    '44206': {
      id: '44206',
      active: false,
      code: 'WAS THE SYSTEM COMPROMISED?',
      label: 'WAS THE SYSTEM COMPROMISED?',
      multipleAnswers: false,
      answers: [
        {
          id: '179185',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44987',
        },
        {
          id: '179186',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44632',
        },
      ],
    },
    '44222': {
      id: '44222',
      active: false,
      code: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      label: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '179218',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44665',
        },
        {
          id: '179217',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44665',
        },
      ],
    },
    '44227': {
      id: '44227',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      label: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      multipleAnswers: false,
      answers: [
        {
          id: '179237',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44629',
        },
        {
          id: '179238',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44263': {
      id: '44263',
      active: false,
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      label: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      multipleAnswers: false,
      answers: [
        {
          id: '179352',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44532',
        },
        {
          id: '179353',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
      ],
    },
    '44348': {
      id: '44348',
      active: false,
      code: 'DESCRIBE THE DAMAGE',
      label: 'DESCRIBE THE DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          id: '179670',
          code: 'EXTENSIVE',
          active: false,
          label: 'EXTENSIVE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44413',
        },
        {
          id: '179671',
          code: 'MINOR',
          active: false,
          label: 'MINOR',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44413',
        },
        {
          id: '179672',
          code: 'SERIOUS',
          active: false,
          label: 'SERIOUS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44413',
        },
      ],
    },
    '44357': {
      id: '44357',
      active: false,
      code: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          id: '179702',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44879',
        },
        {
          id: '179703',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
      ],
    },
    '44378': {
      id: '44378',
      active: false,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      multipleAnswers: false,
      answers: [
        {
          id: '179782',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44348',
        },
        {
          id: '179783',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45171',
        },
      ],
    },
    '44401': {
      id: '44401',
      active: false,
      code: 'WAS THE KEYWORD REQUESTED?',
      label: 'WAS THE KEYWORD REQUESTED?',
      multipleAnswers: false,
      answers: [
        {
          id: '179844',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44932',
        },
        {
          id: '179845',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
      ],
    },
    '44413': {
      id: '44413',
      active: false,
      code: 'ESTIMATED COST OF DAMAGE',
      label: 'ESTIMATED COST OF DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          id: '179884',
          code: 'ENTER AMOUNT IN POUND STERLING',
          active: false,
          label: 'ENTER AMOUNT IN POUND STERLING',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45171',
        },
      ],
    },
    '44439': {
      id: '44439',
      active: false,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '179942',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44357',
        },
        {
          id: '179943',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
      ],
    },
    '44461': {
      id: '44461',
      active: false,
      code: 'DESCRIBE WEAPONS USED',
      label: 'DESCRIBE WEAPONS USED',
      multipleAnswers: true,
      answers: [
        {
          id: '180020',
          code: 'FIREARM',
          active: false,
          label: 'FIREARM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180017',
          code: 'CHEMICAL INCAPACITANT',
          active: false,
          label: 'CHEMICAL INCAPACITANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180022',
          code: 'KNIFE/BLADE',
          active: false,
          label: 'KNIFE/BLADE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180025',
          code: 'OTHER SHARP INSTRUMENT',
          active: false,
          label: 'OTHER SHARP INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180016',
          code: 'BLUNT INSTRUMENT',
          active: false,
          label: 'BLUNT INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180023',
          code: 'LIGATURE',
          active: false,
          label: 'LIGATURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180018',
          code: 'DANGEROUS LIQUID',
          active: false,
          label: 'DANGEROUS LIQUID',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180019',
          code: 'EXCRETA/URINE',
          active: false,
          label: 'EXCRETA/URINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180026',
          code: 'SPITTING',
          active: false,
          label: 'SPITTING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180021',
          code: 'FOOD',
          active: false,
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180028',
          code: 'THROWN FURNITURE',
          active: false,
          label: 'THROWN FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180027',
          code: 'THROWN EQUIPMENT',
          active: false,
          label: 'THROWN EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
        {
          id: '180024',
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44378',
        },
      ],
    },
    '44482': {
      id: '44482',
      active: false,
      code: 'QUOTE THE VANTIVE CASE NUMBER',
      label: 'QUOTE THE VANTIVE CASE NUMBER',
      multipleAnswers: false,
      answers: [
        {
          id: '180153',
          code: 'ENTER NUMBER',
          active: false,
          label: 'ENTER NUMBER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44401',
        },
      ],
    },
    '44492': {
      id: '44492',
      active: false,
      code: 'WHO AUTHORISED THE SHUT DOWN?',
      label: 'WHO AUTHORISED THE SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          id: '180186',
          code: 'GOVERNOR',
          active: false,
          label: 'GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44206',
        },
        {
          id: '180184',
          code: 'DEPUTY GOVERNOR',
          active: false,
          label: 'DEPUTY GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44206',
        },
        {
          id: '180185',
          code: 'DUTY GOVERNOR',
          active: false,
          label: 'DUTY GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44206',
        },
        {
          id: '180187',
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44206',
        },
      ],
    },
    '44505': {
      id: '44505',
      active: false,
      code: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      multipleAnswers: false,
      answers: [
        {
          id: '180239',
          code: 'NEGOTIATION',
          active: false,
          label: 'NEGOTIATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44191',
        },
        {
          id: '180238',
          code: 'INTERVENTION',
          active: false,
          label: 'INTERVENTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44191',
        },
        {
          id: '180240',
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44191',
        },
      ],
    },
    '44515': {
      id: '44515',
      active: false,
      code: 'WERE WEAPONS USED BY THE PERPETRATOR',
      label: 'WERE WEAPONS USED BY THE PERPETRATOR',
      multipleAnswers: false,
      answers: [
        {
          id: '180264',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44461',
        },
        {
          id: '180265',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44378',
        },
      ],
    },
    '44530': {
      id: '44530',
      active: false,
      code: 'INDICATE THE NATURE OF THE SHUT DOWN',
      label: 'INDICATE THE NATURE OF THE SHUT DOWN',
      multipleAnswers: true,
      answers: [
        {
          id: '180351',
          code: 'TELEPHONY',
          active: false,
          label: 'TELEPHONY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44666',
        },
        {
          id: '180350',
          code: 'IT',
          active: false,
          label: 'IT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44666',
        },
      ],
    },
    '44532': {
      id: '44532',
      active: false,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '180354',
          code: 'ADMINISTRATION',
          active: false,
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180355',
          code: 'ASSOCIATION AREA',
          active: false,
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180356',
          code: 'CELL',
          active: false,
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180357',
          code: 'CHAPEL',
          active: false,
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180359',
          code: 'DINING ROOM',
          active: false,
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180360',
          code: 'DORMITORY',
          active: false,
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180361',
          code: 'EDUCATION',
          active: false,
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180363',
          code: 'EXERCISE YARD',
          active: false,
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180365',
          code: 'GATE',
          active: false,
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180366',
          code: 'GYM',
          active: false,
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180367',
          code: 'HEALTH CARE CENTRE',
          active: false,
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180370',
          code: 'KITCHEN',
          active: false,
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180372',
          code: 'OFFICE',
          active: false,
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180374',
          code: 'RECEPTION',
          active: false,
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180375',
          code: 'RECESS',
          active: false,
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180376',
          code: 'SEGREGATION UNIT',
          active: false,
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180378',
          code: 'SPECIAL UNIT',
          active: false,
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180377',
          code: 'SHOWERS/CHANGING ROOM',
          active: false,
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180381',
          code: 'VISITS',
          active: false,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180383',
          code: 'WING',
          active: false,
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180385',
          code: 'WORKS DEPARTMENT',
          active: false,
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180386',
          code: 'WORKSHOP',
          active: false,
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180384',
          code: 'WITHIN PERIMETER',
          active: false,
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180362',
          code: 'ELSEWHERE (ENTER DETAILS)',
          active: false,
          label: 'ELSEWHERE (ENTER DETAILS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180364',
          code: 'FUNERAL',
          active: false,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180368',
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: false,
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180369',
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: false,
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180373',
          code: 'OUTSIDE WORKING PARTY',
          active: false,
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180379',
          code: 'SPORTS FIELD',
          active: false,
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180380',
          code: 'VEHICLE',
          active: false,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180382',
          code: 'WEDDINGS',
          active: false,
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180371',
          code: 'MAGISTRATES COURT',
          active: false,
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
        {
          id: '180358',
          code: 'CROWN COURT',
          active: false,
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44938',
        },
      ],
    },
    '44563': {
      id: '44563',
      active: false,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      multipleAnswers: true,
      answers: [
        {
          id: '180471',
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180470',
          code: 'PRISONERS',
          active: false,
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180467',
          code: 'CIVILIAN GRADES',
          active: false,
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180469',
          code: 'POLICE',
          active: false,
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
        {
          id: '180468',
          code: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44796',
        },
      ],
    },
    '44620': {
      id: '44620',
      active: false,
      code: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE IT AND T SERVICE SUPPLIER?',
      label: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE IT AND T SERVICE SUPPLIER?',
      multipleAnswers: false,
      answers: [
        {
          id: '180657',
          code: 'LOCAL',
          active: false,
          label: 'LOCAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '180658',
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'SERVICE SUPPLIER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44629': {
      id: '44629',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      multipleAnswers: false,
      answers: [
        {
          id: '180692',
          code: 'LOCAL',
          active: false,
          label: 'LOCAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
        {
          id: '180691',
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'SERVICE SUPPLIER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44482',
        },
      ],
    },
    '44632': {
      id: '44632',
      active: false,
      code: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      label: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      multipleAnswers: false,
      answers: [
        {
          id: '180698',
          code: 'ENTER COMMENT AND DATE',
          active: false,
          label: 'ENTER COMMENT AND DATE',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '44620',
        },
      ],
    },
    '44634': {
      id: '44634',
      active: false,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '180704',
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: false,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180705',
          code: 'MINOR BRUISES',
          active: false,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180708',
          code: 'SWELLINGS',
          active: false,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180707',
          code: 'SUPERFICIAL CUTS',
          active: false,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
        {
          id: '180706',
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44563',
        },
      ],
    },
    '44665': {
      id: '44665',
      active: false,
      code: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      label: 'WAS THERE AN APPARENT REASON FOR THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '180805',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44704',
        },
        {
          id: '180806',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
      ],
    },
    '44666': {
      id: '44666',
      active: false,
      code: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      label: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          id: '180807',
          code: 'ENTER TIME',
          active: false,
          label: 'ENTER TIME',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44947',
        },
      ],
    },
    '44704': {
      id: '44704',
      active: false,
      code: 'DESCRIBE THE APPARENT REASON FOR THE INCIDENT',
      label: 'DESCRIBE THE APPARENT REASON FOR THE INCIDENT',
      multipleAnswers: true,
      answers: [
        {
          id: '180961',
          code: 'FACILITIES',
          active: false,
          label: 'FACILITIES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180962',
          code: 'FOOD',
          active: false,
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180964',
          code: 'PAY',
          active: false,
          label: 'PAY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180966',
          code: 'VISITS',
          active: false,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180965',
          code: 'TIME OUT OF CELL',
          active: false,
          label: 'TIME OUT OF CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44505',
        },
        {
          id: '180963',
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44505',
        },
      ],
    },
    '44722': {
      id: '44722',
      active: false,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          id: '181014',
          code: 'FRACTURE',
          active: false,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181016',
          code: 'SCALD OR BURN',
          active: false,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181017',
          code: 'STABBING',
          active: false,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181011',
          code: 'CRUSHING',
          active: false,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181013',
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: false,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181008',
          code: 'BLACK EYE',
          active: false,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181009',
          code: 'BROKEN NOSE',
          active: false,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181010',
          code: 'BROKEN TEETH',
          active: false,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181012',
          code: 'CUTS REQUIRING SUTURES',
          active: false,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181007',
          code: 'BITES',
          active: false,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181015',
          code: 'GUN SHOT WOUND',
          active: false,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
        {
          id: '181018',
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: false,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
      ],
    },
    '44796': {
      id: '44796',
      active: false,
      code: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      multipleAnswers: false,
      answers: [
        {
          id: '181249',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44174',
        },
        {
          id: '181250',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45071',
        },
      ],
    },
    '44816': {
      id: '44816',
      active: false,
      code: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      multipleAnswers: false,
      answers: [
        {
          id: '181297',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44914',
        },
        {
          id: '181296',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44914',
        },
      ],
    },
    '44860': {
      id: '44860',
      active: false,
      code: 'WERE WATER HOSES USED',
      label: 'WERE WATER HOSES USED',
      multipleAnswers: false,
      answers: [
        {
          id: '181438',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45022',
        },
        {
          id: '181437',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45022',
        },
      ],
    },
    '44879': {
      id: '44879',
      active: false,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      multipleAnswers: false,
      answers: [
        {
          id: '181516',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
        {
          id: '181515',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45086',
        },
      ],
    },
    '44914': {
      id: '44914',
      active: false,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '181631',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44185',
        },
        {
          id: '181630',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44185',
        },
      ],
    },
    '44932': {
      id: '44932',
      active: false,
      code: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      label: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      multipleAnswers: false,
      answers: [
        {
          id: '181728',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
        {
          id: '181727',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44530',
        },
      ],
    },
    '44938': {
      id: '44938',
      active: false,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '181749',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45075',
        },
        {
          id: '181750',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45071',
        },
      ],
    },
    '44947': {
      id: '44947',
      active: false,
      code: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      label: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          id: '181779',
          code: 'FULL',
          active: false,
          label: 'FULL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44492',
        },
        {
          id: '181780',
          code: 'PARTIAL',
          active: false,
          label: 'PARTIAL',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44492',
        },
      ],
    },
    '44987': {
      id: '44987',
      active: false,
      code: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      label: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      multipleAnswers: false,
      answers: [
        {
          id: '181924',
          code: 'DESCRIBE COMPROMISE',
          active: false,
          label: 'DESCRIBE COMPROMISE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44632',
        },
      ],
    },
    '45022': {
      id: '45022',
      active: false,
      code: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      label: 'WAS CONTROL AND RESTRAINTS EMPLOYED',
      multipleAnswers: false,
      answers: [
        {
          id: '182031',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44515',
        },
        {
          id: '182030',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44515',
        },
      ],
    },
    '45071': {
      id: '45071',
      active: false,
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          id: '182259',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44222',
        },
        {
          id: '182258',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44222',
        },
      ],
    },
    '45075': {
      id: '45075',
      active: false,
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'WAS A SERIOUS INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          id: '182270',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44722',
        },
        {
          id: '182271',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45083',
        },
      ],
    },
    '45083': {
      id: '45083',
      active: false,
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'WAS A MINOR INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          id: '182288',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44634',
        },
        {
          id: '182289',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44563',
        },
      ],
    },
    '45086': {
      id: '45086',
      active: false,
      code: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          id: '182296',
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44816',
        },
        {
          id: '182295',
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44816',
        },
      ],
    },
    '45171': {
      id: '45171',
      active: false,
      code: 'DURATION OF INCIDENT IN HOURS',
      label: 'DURATION OF INCIDENT IN HOURS',
      multipleAnswers: false,
      answers: [
        {
          id: '182628',
          code: 'ENTER HOURS',
          active: false,
          label: 'ENTER HOURS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44227',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default OLD_BARRICADE
