// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-20T16:52:29.817Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_FINDS2: IncidentTypeConfiguration = {
  incidentType: 'OLD_FINDS2',
  active: false,
  startingQuestionId: '51184',
  questions: {
    '51184': {
      id: '51184',
      active: false,
      code: 'What was the main management outcome of this incident?',
      label: 'What was the main management outcome of this incident?',
      multipleAnswers: true,
      answers: [
        {
          code: 'No Further Action',
          active: false,
          label: 'No Further Action',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51185',
        },
        {
          code: 'IEP Regression',
          active: false,
          label: 'IEP Regression',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51185',
        },
        {
          code: 'Placed on report/adjudication referral',
          active: false,
          label: 'Placed on report/adjudication referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51185',
        },
        {
          code: 'Police referral',
          active: false,
          label: 'Police referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51185',
        },
        {
          code: 'CPS referral',
          active: false,
          label: 'CPS referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51185',
        },
        {
          code: 'Prosecution referral',
          active: false,
          label: 'Prosecution referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51185',
        },
      ],
    },
    '51185': {
      id: '51185',
      active: false,
      code: 'Is any member of staff facing disciplinary charges?',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51186',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51186',
        },
      ],
    },
    '51186': {
      id: '51186',
      active: false,
      code: 'Is the location of the incident known?',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51187',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
      ],
    },
    '51187': {
      id: '51187',
      active: false,
      code: 'What was the location of the incident?',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Administration',
          active: false,
          label: 'Administration',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Association Area',
          active: false,
          label: 'Association Area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Cell',
          active: false,
          label: 'Cell',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Chapel',
          active: false,
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Crown Court',
          active: false,
          label: 'Crown Court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Dining Room',
          active: false,
          label: 'Dining Room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Dormitory',
          active: false,
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Education',
          active: false,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Elsewhere',
          active: false,
          label: 'Elsewhere',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Exercise Yard',
          active: false,
          label: 'Exercise Yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Funeral',
          active: false,
          label: 'Funeral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Gate',
          active: false,
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Gym',
          active: false,
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Health Care Centre',
          active: false,
          label: 'Health Care Centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Hospital Outside (Patient)',
          active: false,
          label: 'Hospital Outside (Patient)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Hospital Outside (Visiting)',
          active: false,
          label: 'Hospital Outside (Visiting)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Kitchen',
          active: false,
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Magistrates Court',
          active: false,
          label: 'Magistrates Court',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Office',
          active: false,
          label: 'Office',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Outside Working Party',
          active: false,
          label: 'Outside Working Party',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Reception',
          active: false,
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Recess',
          active: false,
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Segregation Unit',
          active: false,
          label: 'Segregation Unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Showers/Changing Room',
          active: false,
          label: 'Showers/Changing Room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Special Unit',
          active: false,
          label: 'Special Unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Sports Field',
          active: false,
          label: 'Sports Field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Vehicle',
          active: false,
          label: 'Vehicle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Visits',
          active: false,
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Weddings',
          active: false,
          label: 'Weddings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Wing',
          active: false,
          label: 'Wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Within Perimeter',
          active: false,
          label: 'Within Perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Works Department',
          active: false,
          label: 'Works Department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Workshop',
          active: false,
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Induction / 1st Night Centre',
          active: false,
          label: 'Induction / 1st Night Centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Mail Room',
          active: false,
          label: 'Mail Room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'External Roof',
          active: false,
          label: 'External Roof',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
        {
          code: 'Vulnerable Prisoners Unit (VPU)',
          active: false,
          label: 'Vulnerable Prisoners Unit (VPU)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51188',
        },
      ],
    },
    '51188': {
      id: '51188',
      active: false,
      code: 'Was a drug found?',
      label: 'Was a drug found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51189',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51194',
        },
      ],
    },
    '51189': {
      id: '51189',
      active: false,
      code: 'Describe the drug found',
      label: 'Describe the drug found',
      multipleAnswers: true,
      answers: [
        {
          code: 'Amphetamines',
          active: false,
          label: 'Amphetamines',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Barbiturates',
          active: false,
          label: 'Barbiturates',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Benzodiazepines',
          active: false,
          label: 'Benzodiazepines',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Buprenorphine/Subutex',
          active: false,
          label: 'Buprenorphine/Subutex',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Cannabis',
          active: false,
          label: 'Cannabis',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Cannabis Plant',
          active: false,
          label: 'Cannabis Plant',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Cocaine',
          active: false,
          label: 'Cocaine',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Crack',
          active: false,
          label: 'Crack',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Heroin',
          active: false,
          label: 'Heroin',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'LSD',
          active: false,
          label: 'LSD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Methadone',
          active: false,
          label: 'Methadone',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Pregabalin',
          active: false,
          label: 'Pregabalin',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Tranquilisers',
          active: false,
          label: 'Tranquilisers',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Tramadol',
          active: false,
          label: 'Tramadol',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Gabapentin',
          active: false,
          label: 'Gabapentin',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'NPS: Spice',
          active: false,
          label: 'NPS: Spice',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'NPS: Black Mamba',
          active: false,
          label: 'NPS: Black Mamba',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'NPS: Other',
          active: false,
          label: 'NPS: Other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Steroids',
          active: false,
          label: 'Steroids',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Other (please specify)',
          active: false,
          label: 'Other (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51190',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51190',
        },
      ],
    },
    '51190': {
      id: '51190',
      active: false,
      code: 'What was the estimated weight of all drugs/substances found?',
      label: 'What was the estimated weight of all drugs/substances found?',
      multipleAnswers: false,
      answers: [
        {
          code: '<1g',
          active: false,
          label: '<1g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '2g to 5g',
          active: false,
          label: '2g to 5g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '6g to 10g',
          active: false,
          label: '6g to 10g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '11g to 20g',
          active: false,
          label: '11g to 20g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '21g to 30g',
          active: false,
          label: '21g to 30g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '31g to 40g',
          active: false,
          label: '31g to 40g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '41g to 50g',
          active: false,
          label: '41g to 50g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '51g to 100g',
          active: false,
          label: '51g to 100g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '101g to 200g',
          active: false,
          label: '101g to 200g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '201g to 300g',
          active: false,
          label: '201g to 300g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '301g to 400g',
          active: false,
          label: '301g to 400g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '401g to 500g',
          active: false,
          label: '401g to 500g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: '501g to 1000g',
          active: false,
          label: '501g to 1000g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: 'More than 1Kg',
          active: false,
          label: 'More than 1Kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51191',
        },
      ],
    },
    '51191': {
      id: '51191',
      active: false,
      code: 'Was the substance found analysed?',
      label: 'Was the substance found analysed?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51192',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51193',
        },
      ],
    },
    '51192': {
      id: '51192',
      active: false,
      code: 'How was the substance analysed?',
      label: 'How was the substance analysed?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Forensic laboratory',
          active: false,
          label: 'Forensic laboratory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51193',
        },
        {
          code: 'Local with BDH kit or similar',
          active: false,
          label: 'Local with BDH kit or similar',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51193',
        },
      ],
    },
    '51193': {
      id: '51193',
      active: false,
      code: 'To which police station were seized drugs sent for destruction?',
      label: 'To which police station were seized drugs sent for destruction?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Name',
          active: false,
          label: 'Name',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51194',
        },
      ],
    },
    '51194': {
      id: '51194',
      active: false,
      code: 'Was drug equipment found?',
      label: 'Was drug equipment found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51195',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51196',
        },
      ],
    },
    '51195': {
      id: '51195',
      active: false,
      code: 'Describe drug equipment found?',
      label: 'Describe drug equipment found?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Authentic needle',
          active: false,
          label: 'Authentic needle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51196',
        },
        {
          code: 'Authentic syringe',
          active: false,
          label: 'Authentic syringe',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51196',
        },
        {
          code: 'Improvised needle',
          active: false,
          label: 'Improvised needle',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51196',
        },
        {
          code: 'Improvised syringe',
          active: false,
          label: 'Improvised syringe',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51196',
        },
        {
          code: 'Pipe(s)',
          active: false,
          label: 'Pipe(s)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51196',
        },
        {
          code: 'Roach',
          active: false,
          label: 'Roach',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51196',
        },
        {
          code: 'Other (please specify)',
          active: false,
          label: 'Other (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51196',
        },
      ],
    },
    '51196': {
      id: '51196',
      active: false,
      code: 'Was a mobile phone related item found?',
      label: 'Was a mobile phone related item found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51197',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51207',
        },
      ],
    },
    '51197': {
      id: '51197',
      active: false,
      code: 'Was a mobile phone found?',
      label: 'Was a mobile phone found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51198',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
      ],
    },
    '51198': {
      id: '51198',
      active: false,
      code: 'Enter number of mobiles found',
      label: 'Enter number of mobiles found',
      multipleAnswers: false,
      answers: [
        {
          code: '0',
          active: false,
          label: '0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '1',
          active: false,
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '2',
          active: false,
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '3',
          active: false,
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '4',
          active: false,
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '5',
          active: false,
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '6',
          active: false,
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '7',
          active: false,
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '8',
          active: false,
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '9',
          active: false,
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '10',
          active: false,
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '11',
          active: false,
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '12',
          active: false,
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '13',
          active: false,
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '14',
          active: false,
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '15',
          active: false,
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '16',
          active: false,
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '17',
          active: false,
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '18',
          active: false,
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: '20',
          active: false,
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: 'More than 20',
          active: false,
          label: 'More than 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51199',
        },
      ],
    },
    '51199': {
      id: '51199',
      active: false,
      code: 'Was a SIM card found?',
      label: 'Was a SIM card found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51200',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51200',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
      ],
    },
    '51200': {
      id: '51200',
      active: false,
      code: 'Enter number of SIM Cards found',
      label: 'Enter number of SIM Cards found',
      multipleAnswers: false,
      answers: [
        {
          code: '0',
          active: false,
          label: '0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '1',
          active: false,
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '2',
          active: false,
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '3',
          active: false,
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '4',
          active: false,
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '5',
          active: false,
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '6',
          active: false,
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '7',
          active: false,
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '8',
          active: false,
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '9',
          active: false,
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '10',
          active: false,
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '11',
          active: false,
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '12',
          active: false,
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '13',
          active: false,
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '14',
          active: false,
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '15',
          active: false,
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '16',
          active: false,
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '17',
          active: false,
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '18',
          active: false,
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '19',
          active: false,
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: '20',
          active: false,
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: 'More than 20',
          active: false,
          label: 'More than 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51201',
        },
      ],
    },
    '51201': {
      id: '51201',
      active: false,
      code: 'Was a memory card found?',
      label: 'Was a memory card found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51202',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
      ],
    },
    '51202': {
      id: '51202',
      active: false,
      code: 'Enter number of memory cards found',
      label: 'Enter number of memory cards found',
      multipleAnswers: false,
      answers: [
        {
          code: '0',
          active: false,
          label: '0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '1',
          active: false,
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '2',
          active: false,
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '3',
          active: false,
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '4',
          active: false,
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '5',
          active: false,
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '6',
          active: false,
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '7',
          active: false,
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '8',
          active: false,
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '9',
          active: false,
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '10',
          active: false,
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '11',
          active: false,
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '12',
          active: false,
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '13',
          active: false,
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '14',
          active: false,
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '15',
          active: false,
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '16',
          active: false,
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '17',
          active: false,
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '18',
          active: false,
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '19',
          active: false,
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: '20',
          active: false,
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: 'More than 20',
          active: false,
          label: 'More than 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51203',
        },
      ],
    },
    '51203': {
      id: '51203',
      active: false,
      code: 'Was a charger found?',
      label: 'Was a charger found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51204',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51204',
        },
      ],
    },
    '51204': {
      id: '51204',
      active: false,
      code: 'Was any other mobile phone/communication related item found?',
      label: 'Was any other mobile phone/communication related item found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes (please specify)',
          active: false,
          label: 'Yes (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51205',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51205',
        },
      ],
    },
    '51205': {
      id: '51205',
      active: false,
      code: 'Has Phone/SIM/Memory card been sent to NDTSG',
      label: 'Has Phone/SIM/Memory card been sent to NDTSG',
      multipleAnswers: true,
      answers: [
        {
          code: 'Yes (Date)',
          active: false,
          label: 'Yes (Date)',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '51206',
        },
        {
          code: 'Evidence Bag Number',
          active: false,
          label: 'Evidence Bag Number',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51206',
        },
        {
          code: 'No (please state why)',
          active: false,
          label: 'No (please state why)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51206',
        },
      ],
    },
    '51206': {
      id: '51206',
      active: false,
      code: 'Has Phone/SIM/Equipment been retained by police?',
      label: 'Has Phone/SIM/Equipment been retained by police?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51207',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51207',
        },
      ],
    },
    '51207': {
      id: '51207',
      active: false,
      code: 'Was a weapon found?',
      label: 'Was a weapon found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51208',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51209',
        },
      ],
    },
    '51208': {
      id: '51208',
      active: false,
      code: 'Describe the weapon',
      label: 'Describe the weapon',
      multipleAnswers: true,
      answers: [
        {
          code: 'Blunt Instrument (Cosh, Item in Sock, etc)',
          active: false,
          label: 'Blunt Instrument (Cosh, Item in Sock, etc)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51209',
        },
        {
          code: 'Knife / Bladed Article',
          active: false,
          label: 'Knife / Bladed Article',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51209',
        },
        {
          code: 'Firearm (Fake guns, ammunition, chemical incapacitant etc)',
          active: false,
          label: 'Firearm (Fake guns, ammunition, chemical incapacitant etc)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51209',
        },
        {
          code: 'Other (Please specify',
          active: false,
          label: 'Other (Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51209',
        },
      ],
    },
    '51209': {
      id: '51209',
      active: false,
      code: 'Was any alcohol/hooch found?',
      label: 'Was any alcohol/hooch found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51210',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
      ],
    },
    '51210': {
      id: '51210',
      active: false,
      code: 'What quantity of alcohol/hooch was found?',
      label: 'What quantity of alcohol/hooch was found?',
      multipleAnswers: false,
      answers: [
        {
          code: '< 1 Litre',
          active: false,
          label: '< 1 Litre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: '1 to 2 Litres',
          active: false,
          label: '1 to 2 Litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: '2 to 3 Litres',
          active: false,
          label: '2 to 3 Litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: '3 to 4 Litres',
          active: false,
          label: '3 to 4 Litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: '4 to 5 Litres',
          active: false,
          label: '4 to 5 Litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: '6 to 10 Litres',
          active: false,
          label: '6 to 10 Litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: '11 to 20 Litres',
          active: false,
          label: '11 to 20 Litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: 'More than 20 Litres',
          active: false,
          label: 'More than 20 Litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51211',
        },
      ],
    },
    '51211': {
      id: '51211',
      active: false,
      code: 'Was any distilling equipment found?',
      label: 'Was any distilling equipment found?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51213',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51214',
        },
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51212',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51212',
        },
      ],
    },
    '51212': {
      id: '51212',
      active: false,
      code: 'Were any other reportable items found',
      label: 'Were any other reportable items found',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51213',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51214',
        },
      ],
    },
    '51213': {
      id: '51213',
      active: false,
      code: 'Describe the item',
      label: 'Describe the item',
      multipleAnswers: false,
      answers: [
        {
          code: 'Please specify',
          active: false,
          label: 'Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51214',
        },
      ],
    },
    '51214': {
      id: '51214',
      active: false,
      code: 'Describe how the item was found',
      label: 'Describe how the item was found',
      multipleAnswers: true,
      answers: [
        {
          code: 'BOSS Chair',
          active: false,
          label: 'BOSS Chair',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Cell Search',
          active: false,
          label: 'Cell Search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Crime scene',
          active: false,
          label: 'Crime scene',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Dog search',
          active: false,
          label: 'Dog search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'High Sensitivity Wand',
          active: false,
          label: 'High Sensitivity Wand',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Information received',
          active: false,
          label: 'Information received',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Intelligence led search',
          active: false,
          label: 'Intelligence led search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Item observed',
          active: false,
          label: 'Item observed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Mobile phone signal detector',
          active: false,
          label: 'Mobile phone signal detector',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Mobile phone rod',
          active: false,
          label: 'Mobile phone rod',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Other search (inmate)',
          active: false,
          label: 'Other search (inmate)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Other search (premises)',
          active: false,
          label: 'Other search (premises)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Other search (visitor)',
          active: false,
          label: 'Other search (visitor)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Pre-occupation search',
          active: false,
          label: 'Pre-occupation search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Unusual behaviour',
          active: false,
          label: 'Unusual behaviour',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
        {
          code: 'Other (please specify)',
          active: false,
          label: 'Other (please specify)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51215',
        },
      ],
    },
    '51215': {
      id: '51215',
      active: false,
      code: 'Describe the method of entry into the establishment',
      label: 'Describe the method of entry into the establishment',
      multipleAnswers: true,
      answers: [
        {
          code: 'Prisoner',
          active: false,
          label: 'Prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Staff',
          active: false,
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Visitor (friend)',
          active: false,
          label: 'Visitor (friend)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Viistor (official)',
          active: false,
          label: 'Viistor (official)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Visitor (relative)',
          active: false,
          label: 'Visitor (relative)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Contractor',
          active: false,
          label: 'Contractor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Post (Rule 39)',
          active: false,
          label: 'Post (Rule 39)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Post (Other)',
          active: false,
          label: 'Post (Other)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Thrown in',
          active: false,
          label: 'Thrown in',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Drone / UAV',
          active: false,
          label: 'Drone / UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Other (please specify)',
          active: false,
          label: 'Other (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51216',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51216',
        },
      ],
    },
    '51216': {
      id: '51216',
      active: false,
      code: 'If found in possession, whose was it found in?',
      label: 'If found in possession, whose was it found in?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Prisoner',
          active: false,
          label: 'Prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51217',
        },
        {
          code: 'Staff',
          active: false,
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51217',
        },
        {
          code: 'Visitor (Friend)',
          active: false,
          label: 'Visitor (Friend)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51217',
        },
        {
          code: 'Visitor (Official)',
          active: false,
          label: 'Visitor (Official)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51217',
        },
        {
          code: 'Visitor (Relative)',
          active: false,
          label: 'Visitor (Relative)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51217',
        },
        {
          code: 'Contractor',
          active: false,
          label: 'Contractor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51217',
        },
        {
          code: 'Other (please specify)',
          active: false,
          label: 'Other (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51217',
        },
        {
          code: 'Not Applicable',
          active: false,
          label: 'Not Applicable',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51217',
        },
      ],
    },
    '51217': {
      id: '51217',
      active: false,
      code: 'What was the method of concealment?',
      label: 'What was the method of concealment?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Not concealed',
          active: false,
          label: 'Not concealed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Bed / bedding',
          active: false,
          label: 'Bed / bedding',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Book / Papers',
          active: false,
          label: 'Book / Papers',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Cell / Building Fabric',
          active: false,
          label: 'Cell / Building Fabric',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Food / Container',
          active: false,
          label: 'Food / Container',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'In Clothing',
          active: false,
          label: 'In Clothing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'In Hand',
          active: false,
          label: 'In Hand',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'In Mouth',
          active: false,
          label: 'In Mouth',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Internally / Plugged',
          active: false,
          label: 'Internally / Plugged',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Letter / Parcel',
          active: false,
          label: 'Letter / Parcel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Light Fittings',
          active: false,
          label: 'Light Fittings',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Pipework',
          active: false,
          label: 'Pipework',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Rule 39 / Legal Papers',
          active: false,
          label: 'Rule 39 / Legal Papers',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'TV / Radio / DVD / Consoles etc',
          active: false,
          label: 'TV / Radio / DVD / Consoles etc',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
        {
          code: 'Other',
          active: false,
          label: 'Other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51218',
        },
      ],
    },
    '51218': {
      id: '51218',
      active: false,
      code: 'Is the item heavily contaminated (eg Blood, Faeces)?',
      label: 'Is the item heavily contaminated (eg Blood, Faeces)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51219',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51219',
        },
      ],
    },
    '51219': {
      id: '51219',
      active: false,
      code: 'Was a visitor suspected of involvement and arrested by the police',
      label: 'Was a visitor suspected of involvement and arrested by the police',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51220',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51222',
        },
      ],
    },
    '51220': {
      id: '51220',
      active: false,
      code: 'Describe circumstances of visitors arrest',
      label: 'Describe circumstances of visitors arrest',
      multipleAnswers: false,
      answers: [
        {
          code: 'After entering prison',
          active: false,
          label: 'After entering prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51221',
        },
        {
          code: 'Before entering prison',
          active: false,
          label: 'Before entering prison',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51221',
        },
      ],
    },
    '51221': {
      id: '51221',
      active: false,
      code: 'To which police station was the visitor taken to?',
      label: 'To which police station was the visitor taken to?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Specify',
          active: false,
          label: 'Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '51222',
        },
      ],
    },
    '51222': {
      id: '51222',
      active: false,
      code: 'Were the items obtained on temporary release?',
      label: 'Were the items obtained on temporary release?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51223',
        },
        {
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51224',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51224',
        },
      ],
    },
    '51223': {
      id: '51223',
      active: false,
      code: 'Describe the type of temporary release?',
      label: 'Describe the type of temporary release?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Communtiy Visit',
          active: false,
          label: 'Communtiy Visit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51224',
        },
        {
          code: 'Compassionate',
          active: false,
          label: 'Compassionate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51224',
        },
        {
          code: 'Facility',
          active: false,
          label: 'Facility',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51224',
        },
        {
          code: 'Resettlement',
          active: false,
          label: 'Resettlement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51224',
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '51224',
        },
      ],
    },
    '51224': {
      id: '51224',
      active: false,
      code: 'What was the total estimated valie of the findings (drugs, mobile phones, etc)?',
      label: 'What was the total estimated valie of the findings (drugs, mobile phones, etc)?',
      multipleAnswers: false,
      answers: [
        {
          code: '£0',
          active: false,
          label: '£0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1 to £100',
          active: false,
          label: '£1 to £100',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£101 to £200',
          active: false,
          label: '£101 to £200',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£201 to £300',
          active: false,
          label: '£201 to £300',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£301 to £400',
          active: false,
          label: '£301 to £400',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£401 to £500',
          active: false,
          label: '£401 to £500',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£501 to £1,000',
          active: false,
          label: '£501 to £1,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1,001 to £5,000',
          active: false,
          label: '£1,001 to £5,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£5,001 to £10,000',
          active: false,
          label: '£5,001 to £10,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£10,001 to £20,000',
          active: false,
          label: '£10,001 to £20,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£20,001 to £30,000',
          active: false,
          label: '£20,001 to £30,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£30,001 to £40,000',
          active: false,
          label: '£30,001 to £40,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£40,001 to £50,000',
          active: false,
          label: '£40,001 to £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'More than £50,000',
          active: false,
          label: 'More than £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'Unknown',
          active: false,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default OLD_FINDS2
