// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-16T15:42:03.318Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_DRONE_SIGHTING1: IncidentTypeConfiguration = {
  incidentType: 'OLD_DRONE_SIGHTING1',
  active: false,
  startingQuestionId: '57253',
  questions: {
    '57253': {
      id: '57253',
      code: 'Was a drone sighted in mid-flight?',
      label: 'Was a drone sighted in mid-flight?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57254',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57263',
        },
      ],
    },
    '57254': {
      id: '57254',
      code: 'What time was the drone(s) sighted?',
      label: 'What time was the drone(s) sighted?',
      multipleAnswers: false,
      answers: [
        {
          code: '12am to 6am',
          label: '12am to 6am',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57255',
        },
        {
          code: '6am to 12pm',
          label: '6am to 12pm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57255',
        },
        {
          code: '12pm to 6pm',
          label: '12pm to 6pm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57255',
        },
        {
          code: '6pm to 12am',
          label: '6pm to 12am',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57255',
        },
      ],
    },
    '57255': {
      id: '57255',
      code: 'Number of drones observed?',
      label: 'Number of drones observed?',
      multipleAnswers: false,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57256',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57256',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57256',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57256',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57256',
        },
        {
          code: '6+',
          label: '6+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57256',
        },
      ],
    },
    '57256': {
      id: '57256',
      code: 'Where was the drone(s) sighted?',
      label: 'Where was the drone(s) sighted?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Beyond the external perimeter border',
          label: 'Beyond the external perimeter border',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57257',
        },
        {
          code: 'Exercise yard',
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57257',
        },
        {
          code: 'External Roof',
          label: 'External Roof',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57257',
        },
        {
          code: 'Gate',
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57257',
        },
        {
          code: 'Near Cell window',
          label: 'Near Cell window',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57257',
        },
        {
          code: 'Sports Field',
          label: 'Sports Field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57257',
        },
        {
          code: 'Within Perimeter',
          label: 'Within Perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57257',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57257',
        },
      ],
    },
    '57257': {
      id: '57257',
      code: 'For drone(s) sighted beyond perimeter border, how close did the nearest drone get to the wall?',
      label: 'For drone(s) sighted beyond perimeter border, how close did the nearest drone get to the wall?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Not applicable',
          label: 'Not applicable',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57258',
        },
        {
          code: '0 to less than 10 metres',
          label: '0 to less than 10 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57258',
        },
        {
          code: '10 to less than 100 metres',
          label: '10 to less than 100 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57258',
        },
        {
          code: '100 to less than 200 metres',
          label: '100 to less than 200 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57258',
        },
        {
          code: '200 metres or more',
          label: '200 metres or more',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57258',
        },
      ],
    },
    '57258': {
      id: '57258',
      code: 'What was the estimated speed of the drone(s)?',
      label: 'What was the estimated speed of the drone(s)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Static',
          label: 'Static',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57259',
        },
        {
          code: 'Walking pace',
          label: 'Walking pace',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57259',
        },
        {
          code: 'Running pace',
          label: 'Running pace',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57259',
        },
        {
          code: 'Faster than running',
          label: 'Faster than running',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57259',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57259',
        },
      ],
    },
    '57259': {
      id: '57259',
      code: 'What was the flying pattern of the drone(s)?',
      label: 'What was the flying pattern of the drone(s)?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Hovering',
          label: 'Hovering',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57260',
        },
        {
          code: 'Circling a point',
          label: 'Circling a point',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57260',
        },
        {
          code: 'Straight flight',
          label: 'Straight flight',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57260',
        },
        {
          code: 'Direct attack',
          label: 'Direct attack',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57260',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57260',
        },
      ],
    },
    '57260': {
      id: '57260',
      code: 'How many times has the drone(s) been seen here before?',
      label: 'How many times has the drone(s) been seen here before?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Not believed to have been seen before',
          label: 'Not believed to have been seen before',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57261',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57261',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57261',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57261',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57261',
        },
        {
          code: '6 or more (Please specify)',
          label: '6 or more (Please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57261',
        },
      ],
    },
    '57261': {
      id: '57261',
      code: 'What were the weather conditions at the time of the sighting?',
      label: 'What were the weather conditions at the time of the sighting?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Clear visibility',
          label: 'Clear visibility',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
        {
          code: 'Poor visibility',
          label: 'Poor visibility',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
        {
          code: 'Light',
          label: 'Light',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
        {
          code: 'Dark',
          label: 'Dark',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
        {
          code: 'Rain',
          label: 'Rain',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
        {
          code: 'High wind',
          label: 'High wind',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
        {
          code: 'Low wind',
          label: 'Low wind',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
        {
          code: 'Calm',
          label: 'Calm',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57262',
        },
      ],
    },
    '57262': {
      id: '57262',
      code: 'Was the drone(s) recovered?',
      label: 'Was the drone(s) recovered?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57264',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
      ],
    },
    '57263': {
      id: '57263',
      code: 'Was a drone recovered?',
      label: 'Was a drone recovered?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57264',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '57264': {
      id: '57264',
      code: 'How many drone(s) was recovered?',
      label: 'How many drone(s) was recovered?',
      multipleAnswers: false,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57265',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57265',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57265',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57265',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57265',
        },
        {
          code: '6+',
          label: '6+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57265',
        },
      ],
    },
    '57265': {
      id: '57265',
      code: 'Where was the drone(s) recovered?',
      label: 'Where was the drone(s) recovered?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Exercise yard',
          label: 'Exercise yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
        {
          code: 'External Roof',
          label: 'External Roof',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
        {
          code: 'Gate',
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
        {
          code: 'Near Cell window',
          label: 'Near Cell window',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
        {
          code: 'External perimeter border',
          label: 'External perimeter border',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
        {
          code: 'Sports Field',
          label: 'Sports Field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
        {
          code: 'Within Perimeter',
          label: 'Within Perimeter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57266',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57266',
        },
      ],
    },
    '57266': {
      id: '57266',
      code: 'What was the drone(s) type/airframe shape?',
      label: 'What was the drone(s) type/airframe shape?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Multicopter: Square',
          label: 'Multicopter: Square',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Multicopter: Circular',
          label: 'Multicopter: Circular',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Multicopter: X-Shape',
          label: 'Multicopter: X-Shape',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Multicopter: Hourglass',
          label: 'Multicopter: Hourglass',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Multicopter: Other',
          label: 'Multicopter: Other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Fixed wing: Standard aircraft',
          label: 'Fixed wing: Standard aircraft',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Fixed wing: Delta-wing',
          label: 'Fixed wing: Delta-wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Fixed wing: Other',
          label: 'Fixed wing: Other',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57267',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57267',
        },
      ],
    },
    '57267': {
      id: '57267',
      code: 'What is the drone model?',
      label: 'What is the drone model?',
      multipleAnswers: true,
      answers: [
        {
          code: 'DJI Phantom',
          label: 'DJI Phantom',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'Syma X8C Venture',
          label: 'Syma X8C Venture',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'DIY Racing UAV',
          label: 'DIY Racing UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'T600 Inspire 1',
          label: 'T600 Inspire 1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'Century NEO660',
          label: 'Century NEO660',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'X-8 Flyingwing',
          label: 'X-8 Flyingwing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'TALON X-UAV',
          label: 'TALON X-UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'Sky Hunter',
          label: 'Sky Hunter',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'Piper model aircraft',
          label: 'Piper model aircraft',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'Other (Please Specify)',
          label: 'Other (Please Specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57268',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57268',
        },
      ],
    },
    '57268': {
      id: '57268',
      code: 'How many motors does the drone(s) have?',
      label: 'How many motors does the drone(s) have?',
      multipleAnswers: true,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: '8+',
          label: '8+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57269',
        },
      ],
    },
    '57269': {
      id: '57269',
      code: 'What was the approximate length of the drone(s)?',
      label: 'What was the approximate length of the drone(s)?',
      multipleAnswers: true,
      answers: [
        {
          code: '0 to less than 1m',
          label: '0 to less than 1m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57270',
        },
        {
          code: '1m to less than 2m',
          label: '1m to less than 2m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57270',
        },
        {
          code: '2m to less than 3m',
          label: '2m to less than 3m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57270',
        },
        {
          code: '3m or longer',
          label: '3m or longer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57270',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57270',
        },
      ],
    },
    '57270': {
      id: '57270',
      code: 'What was the approximate width of the drone(s)?',
      label: 'What was the approximate width of the drone(s)?',
      multipleAnswers: true,
      answers: [
        {
          code: '0 to less than 1m',
          label: '0 to less than 1m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57271',
        },
        {
          code: '1m to less than 2m',
          label: '1m to less than 2m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57271',
        },
        {
          code: '2m to less than 3m',
          label: '2m to less than 3m',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57271',
        },
        {
          code: '3m or longer',
          label: '3m or longer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57271',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57271',
        },
      ],
    },
    '57271': {
      id: '57271',
      code: 'What modifications were made to the drone(s)?',
      label: 'What modifications were made to the drone(s)?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Painted black',
          label: 'Painted black',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57272',
        },
        {
          code: 'Removed camera',
          label: 'Removed camera',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57272',
        },
        {
          code: 'Added hook',
          label: 'Added hook',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57272',
        },
        {
          code: 'Covered lights',
          label: 'Covered lights',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57272',
        },
        {
          code: 'Other (Please specify)',
          label: 'Other (Please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57272',
        },
        {
          code: 'None',
          label: 'None',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57272',
        },
      ],
    },
    '57272': {
      id: '57272',
      code: 'How was the drone(s) recovered?',
      label: 'How was the drone(s) recovered?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Intercepted',
          label: 'Intercepted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57273',
        },
        {
          code: 'Crashed',
          label: 'Crashed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57273',
        },
      ],
    },
    '57273': {
      id: '57273',
      code: 'Did the drone(s) carry any package(s)?',
      label: 'Did the drone(s) carry any package(s)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57274',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
      ],
    },
    '57274': {
      id: '57274',
      code: 'Was the package(s) recovered?',
      label: 'Was the package(s) recovered?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes (please enter the Finds report incident number)',
          label: 'Yes (please enter the Finds report incident number)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57275',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
      ],
    },
    '57275': {
      id: '57275',
      code: 'Total weight of the package(s)?',
      label: 'Total weight of the package(s)?',
      multipleAnswers: false,
      answers: [
        {
          code: '0 to less than 100g',
          label: '0 to less than 100g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '100g to less than 200g',
          label: '100g to less than 200g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '200g to less than 300g',
          label: '200g to less than 300g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '300g to less than 400g',
          label: '300g to less than 400g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '400g to less than 500g',
          label: '400g to less than 500g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '500g to less than 1kg',
          label: '500g to less than 1kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '1kg to less than 2kg',
          label: '1kg to less than 2kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '2kg to less than 3kg',
          label: '2kg to less than 3kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '3kg to less than 4kg',
          label: '3kg to less than 4kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '4kg to less than 5kg',
          label: '4kg to less than 5kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '5kg to less than 6kg',
          label: '5kg to less than 6kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '6kg to less than 7kg',
          label: '6kg to less than 7kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '7kg to less than 8kg',
          label: '7kg to less than 8kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '8kg to less than 9kg',
          label: '8kg to less than 9kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: '9kg to less than 10kg',
          label: '9kg to less than 10kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: 'More than 10kg',
          label: 'More than 10kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
        {
          code: 'Unknown',
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57276',
        },
      ],
    },
    '57276': {
      id: '57276',
      code: 'What items were in the package(s)?',
      label: 'What items were in the package(s)?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Cameras',
          label: 'Cameras',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
        {
          code: 'Mobile phone devices',
          label: 'Mobile phone devices',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
        {
          code: 'Drugs',
          label: 'Drugs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
        {
          code: 'Weapons',
          label: 'Weapons',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
        {
          code: 'Alcohol/hooch',
          label: 'Alcohol/hooch',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
        {
          code: 'Tobacco',
          label: 'Tobacco',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57277',
        },
        {
          code: 'Other (please specify)',
          label: 'Other (please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57277',
        },
      ],
    },
    '57277': {
      id: '57277',
      code: 'Were any photos taken of the drone and/or payload?',
      label: 'Were any photos taken of the drone and/or payload?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes (specify where sent)',
          label: 'Yes (specify where sent)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57278',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57278',
        },
      ],
    },
    '57278': {
      id: '57278',
      code: 'Was the pilot identified?',
      label: 'Was the pilot identified?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57279',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57282',
        },
      ],
    },
    '57279': {
      id: '57279',
      code: 'Do you know if the pilot was using line of sight?',
      label: 'Do you know if the pilot was using line of sight?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57280',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57280',
        },
      ],
    },
    '57280': {
      id: '57280',
      code: 'Do you know the distance of the pilot from the prison?',
      label: 'Do you know the distance of the pilot from the prison?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57281',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57282',
        },
      ],
    },
    '57281': {
      id: '57281',
      code: 'What was the distance?',
      label: 'What was the distance?',
      multipleAnswers: false,
      answers: [
        {
          code: '0 to less than 10 metres',
          label: '0 to less than 10 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57282',
        },
        {
          code: '10 to less than 100 metres',
          label: '10 to less than 100 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57282',
        },
        {
          code: '100 to less than 200 metres',
          label: '100 to less than 200 metres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57282',
        },
        {
          code: '200 metres or more',
          label: '200 metres or more',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57282',
        },
      ],
    },
    '57282': {
      id: '57282',
      code: 'Were the police contacted?',
      label: 'Were the police contacted?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57283',
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57283',
        },
      ],
    },
    '57283': {
      id: '57283',
      code: 'To the extent of your knowledge, was the pilot apprehended?',
      label: 'To the extent of your knowledge, was the pilot apprehended?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'No',
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default OLD_DRONE_SIGHTING1
