// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-16T15:42:10.033Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_FINDS4: IncidentTypeConfiguration = {
  incidentType: 'OLD_FINDS4',
  active: false,
  startingQuestionId: '57284',
  questions: {
    '57284': {
      id: '57284',
      code: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT?',
      label: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT?',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO FURTHER ACTION',
          label: 'NO FURTHER ACTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          code: 'IEP REGRESSION',
          label: 'IEP REGRESSION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          code: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          label: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          code: 'POLICE REFERRAL',
          label: 'POLICE REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          code: 'CPS REFRRAL',
          label: 'CPS REFRRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          code: 'PROSECUTION REFERRAL',
          label: 'PROSECUTION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
      ],
    },
    '57285': {
      id: '57285',
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES?',
      label: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57286',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57286',
        },
      ],
    },
    '57286': {
      id: '57286',
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      label: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57287',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
      ],
    },
    '57287': {
      id: '57287',
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'ASSOCIATION AREA',
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'CELL',
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'CHAPEL',
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'CROWN COURT',
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'DINING ROOM',
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'DORMITORY',
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'EDUCATION',
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'ELSEWHERE',
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'EXERCISE YARD',
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'FUNERAL',
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'GATE',
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'GYM',
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'HEALTH CARE CENTRE',
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'KITCHEN',
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'MAGISTRATES COURT',
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'OFFICE',
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'RECEPTION',
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'RECESS',
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'SEGREGATION UNIT',
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'SHOWERS/CHANGING ROOM',
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'SPECIAL UNIT',
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'SPORTS FIELD',
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'VEHICLE',
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'VISITS',
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'WEDDINGS',
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'WING',
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'WITHIN PERIMETER',
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'WORKS DEPARTMENT',
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'WORKSHOP',
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'INDUCTION/1ST NIGHT CENTRE',
          label: 'INDUCTION/1ST NIGHT CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'MAIL ROOM',
          label: 'MAIL ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'EXTERNAL ROOF',
          label: 'EXTERNAL ROOF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          code: 'VULNERABLE PRISONERS UNIT (VPU)',
          label: 'VULNERABLE PRISONERS UNIT (VPU)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
      ],
    },
    '57288': {
      id: '57288',
      code: 'WAS A DRUG FOUND?',
      label: 'WAS A DRUG FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57289',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57294',
        },
      ],
    },
    '57289': {
      id: '57289',
      code: 'DESCRIBE THE DRUG FOUND',
      label: 'DESCRIBE THE DRUG FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'AMPHETAMINES',
          label: 'AMPHETAMINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'BARBITURATES',
          label: 'BARBITURATES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'BENZODIAZEPINES',
          label: 'BENZODIAZEPINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'BUPRENORPHINE/SUBUTEX',
          label: 'BUPRENORPHINE/SUBUTEX',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'CANNABIS',
          label: 'CANNABIS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'CANNABIS PLANT',
          label: 'CANNABIS PLANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'COCAINE',
          label: 'COCAINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'CRACK',
          label: 'CRACK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'HEROIN',
          label: 'HEROIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'LSD',
          label: 'LSD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'METHADONE',
          label: 'METHADONE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'PREGABALIN',
          label: 'PREGABALIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'TRANQUILISERS',
          label: 'TRANQUILISERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'TRAMADOL',
          label: 'TRAMADOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'GABAPENTIN',
          label: 'GABAPENTIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'NPS: SPICE',
          label: 'NPS: SPICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'NPS: BLACK MAMBA',
          label: 'NPS: BLACK MAMBA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'NPS: OTHER',
          label: 'NPS: OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'STEROIDS',
          label: 'STEROIDS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
      ],
    },
    '57290': {
      id: '57290',
      code: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND?',
      label: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: '<1g',
          label: '<1g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '2g to 5g',
          label: '2g to 5g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '6g to 10g',
          label: '6g to 10g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '11g to 20g',
          label: '11g to 20g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '21g to 30g',
          label: '21g to 30g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '31g to 40g',
          label: '31g to 40g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '41g to 50g',
          label: '41g to 50g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '51g to 100g',
          label: '51g to 100g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '101g to 200g',
          label: '101g to 200g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '201g to 300g',
          label: '201g to 300g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '301g to 400g',
          label: '301g to 400g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '401g to 500g',
          label: '401g to 500g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: '501g to 1,000g',
          label: '501g to 1,000g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: 'More than 1kg',
          label: 'More than 1kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
      ],
    },
    '57291': {
      id: '57291',
      code: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      label: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57292',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57293',
        },
      ],
    },
    '57292': {
      id: '57292',
      code: 'HOW WAS THE SUBSTANCE ANALYSED?',
      label: 'HOW WAS THE SUBSTANCE ANALYSED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'FORENSIC LABORATORY',
          label: 'FORENSIC LABORATORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57293',
        },
        {
          code: 'LOCAL WITH BDH KIT OR SIMILAR',
          label: 'LOCAL WITH BDH KIT OR SIMILAR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57293',
        },
      ],
    },
    '57293': {
      id: '57293',
      code: 'TO WHICH POLICE STATION WERE SEIZED DRUGS SENT FOR DESTRUCTION?',
      label: 'TO WHICH POLICE STATION WERE SEIZED DRUGS SENT FOR DESTRUCTION?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NAME',
          label: 'NAME',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57294',
        },
      ],
    },
    '57294': {
      id: '57294',
      code: 'WAS DRUG EQUIPMENT FOUND?',
      label: 'WAS DRUG EQUIPMENT FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57295',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
      ],
    },
    '57295': {
      id: '57295',
      code: 'DESCRIBE DRUG EQUIPMENT FOUND',
      label: 'DESCRIBE DRUG EQUIPMENT FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'AUTHENTIC NEEDLE',
          label: 'AUTHENTIC NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          code: 'AUTHENTIC SYRINGE',
          label: 'AUTHENTIC SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          code: 'IMPROVISED NEEDLE',
          label: 'IMPROVISED NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          code: 'IMPROVISED SYRINGE',
          label: 'IMPROVISED SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          code: 'PIPE(S)',
          label: 'PIPE(S)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          code: 'ROACH',
          label: 'ROACH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57296',
        },
      ],
    },
    '57296': {
      id: '57296',
      code: 'WAS A MOBILE PHONE RELATED ITEM FOUND?',
      label: 'WAS A MOBILE PHONE RELATED ITEM FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57297',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57307',
        },
      ],
    },
    '57297': {
      id: '57297',
      code: 'WAS A MOBILE PHONE FOUND?',
      label: 'WAS A MOBILE PHONE FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57298',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
      ],
    },
    '57298': {
      id: '57298',
      code: 'ENTER NUMBER OF MOBILES FOUND',
      label: 'ENTER NUMBER OF MOBILES FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: 'MORE THAN 20',
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
      ],
    },
    '57299': {
      id: '57299',
      code: 'WAS A SIM CARD FOUND?',
      label: 'WAS A SIM CARD FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57300',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
      ],
    },
    '57300': {
      id: '57300',
      code: 'ENTER NUMBER OF SIM CARDS FOUND',
      label: 'ENTER NUMBER OF SIM CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: 'MORE THAN 20',
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
      ],
    },
    '57301': {
      id: '57301',
      code: ' WAS A MEMORY CARD FOUND?',
      label: ' WAS A MEMORY CARD FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57302',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
      ],
    },
    '57302': {
      id: '57302',
      code: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      label: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: 'MORE THAN 20',
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
      ],
    },
    '57303': {
      id: '57303',
      code: 'WAS A CHARGER FOUND?',
      label: 'WAS A CHARGER FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57304',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57304',
        },
      ],
    },
    '57304': {
      id: '57304',
      code: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      label: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES (PLEASE SPECIFY)',
          label: 'YES (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57305',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57305',
        },
      ],
    },
    '57305': {
      id: '57305',
      code: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO NDTSG?',
      label: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO NDTSG?',
      multipleAnswers: true,
      answers: [
        {
          code: 'YES (PLEASE ENTER DATE)',
          label: 'YES (PLEASE ENTER DATE)',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '57306',
        },
        {
          code: 'EVIDENCE BAG (PLEASE ENTER BAG NUMBER)',
          label: 'EVIDENCE BAG (PLEASE ENTER BAG NUMBER)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57306',
        },
        {
          code: 'NO (PLEASE STATE WHY)',
          label: 'NO (PLEASE STATE WHY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57306',
        },
      ],
    },
    '57306': {
      id: '57306',
      code: 'HAS PHONE/SIM/EQUIPMENT BEEN RETAINED BY POLICE?',
      label: 'HAS PHONE/SIM/EQUIPMENT BEEN RETAINED BY POLICE?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57307',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57307',
        },
      ],
    },
    '57307': {
      id: '57307',
      code: 'WAS A WEAPON FOUND?',
      label: 'WAS A WEAPON FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57308',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
      ],
    },
    '57308': {
      id: '57308',
      code: 'DESCRIBE THE WEAPON',
      label: 'DESCRIBE THE WEAPON',
      multipleAnswers: true,
      answers: [
        {
          code: 'BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC.)',
          label: 'BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC.)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
        {
          code: 'KNIFE/BLADED ARTICLE',
          label: 'KNIFE/BLADED ARTICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
        {
          code: 'FIREARM (FAKE GUNS, AMMUNITION, CHEMIICAL INCAPACITANT ETC.)',
          label: 'FIREARM (FAKE GUNS, AMMUNITION, CHEMIICAL INCAPACITANT ETC.)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57309',
        },
      ],
    },
    '57309': {
      id: '57309',
      code: 'WAS ANY ALCOHOL/HOOCH FOUND?',
      label: 'WAS ANY ALCOHOL/HOOCH FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57310',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
      ],
    },
    '57310': {
      id: '57310',
      code: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND?',
      label: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: '< 1 litre',
          label: '< 1 litre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: '1 to 2 litres',
          label: '1 to 2 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: '2 to 3 litres',
          label: '2 to 3 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: '3 to 4 litres',
          label: '3 to 4 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: ' 4 to 5 litres',
          label: ' 4 to 5 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: '6 to 10 litres',
          label: '6 to 10 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: '11 to 20 litres',
          label: '11 to 20 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: 'More than 20 litres',
          label: 'More than 20 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
      ],
    },
    '57311': {
      id: '57311',
      code: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      label: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57312',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57312',
        },
      ],
    },
    '57312': {
      id: '57312',
      code: 'WAS ANY TOBACCO FOUND?',
      label: 'WAS ANY TOBACCO FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57313',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
      ],
    },
    '57313': {
      id: '57313',
      code: 'DESCRIBE THE TOBACCO FOUND',
      label: 'DESCRIBE THE TOBACCO FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'LOOSE TOBACCO',
          label: 'LOOSE TOBACCO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57314',
        },
        {
          code: 'CIGARETTES/CIGARS',
          label: 'CIGARETTES/CIGARS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57314',
        },
        {
          code: 'OTHER (INC PACKAGING AND ROACHES)',
          label: 'OTHER (INC PACKAGING AND ROACHES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57314',
        },
      ],
    },
    '57314': {
      id: '57314',
      code: 'APPROX WEIGHT OF TOBACCO?',
      label: 'APPROX WEIGHT OF TOBACCO?',
      multipleAnswers: false,
      answers: [
        {
          code: '<1g',
          label: '<1g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
        {
          code: '2g to 5g',
          label: '2g to 5g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
        {
          code: '6g to 10g',
          label: '6g to 10g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
        {
          code: '10g+',
          label: '10g+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
      ],
    },
    '57315': {
      id: '57315',
      code: 'WERE ANY OTHER REPORTABLE ITEMS FOUND?',
      label: 'WERE ANY OTHER REPORTABLE ITEMS FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57316',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57317',
        },
      ],
    },
    '57316': {
      id: '57316',
      code: 'DESCRIBE THE ITEM',
      label: 'DESCRIBE THE ITEM',
      multipleAnswers: false,
      answers: [
        {
          code: 'PLEASE SPECIFY',
          label: 'PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57317',
        },
      ],
    },
    '57317': {
      id: '57317',
      code: 'DESCRIBE HOW THE ITEM WAS FOUND?',
      label: 'DESCRIBE HOW THE ITEM WAS FOUND?',
      multipleAnswers: true,
      answers: [
        {
          code: 'BOSS CHAIR',
          label: 'BOSS CHAIR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'CELL SEARCH',
          label: 'CELL SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'CRIME SCENE',
          label: 'CRIME SCENE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'DOG SEARCH',
          label: 'DOG SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'DRONE RECOVERY',
          label: 'DRONE RECOVERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'HIGH SENSITIVITY WAND',
          label: 'HIGH SENSITIVITY WAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'INFORMATION RECEIVED',
          label: 'INFORMATION RECEIVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'INTELLIGENCE LED SEARCH',
          label: 'INTELLIGENCE LED SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'ITEM OBSERVED',
          label: 'ITEM OBSERVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'MOBILE PHONE SIGNAL DETECTOR',
          label: 'MOBILE PHONE SIGNAL DETECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'MOBILE PHONE ROD',
          label: 'MOBILE PHONE ROD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'OTHER SEARCH (INMATE)',
          label: 'OTHER SEARCH (INMATE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'OTHER SEARCH (PREMISES)',
          label: 'OTHER SEARCH (PREMISES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'OTHER SEARCH (VISITOR)',
          label: 'OTHER SEARCH (VISITOR)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'PRE-OCCUPATION SEARCH',
          label: 'PRE-OCCUPATION SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'UNUSUAL BEHAVIOUR',
          label: 'UNUSUAL BEHAVIOUR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57318',
        },
      ],
    },
    '57318': {
      id: '57318',
      code: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      label: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'VISITOR (FRIEND)',
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'VISITOR (OFFICIAL)',
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'VISITOR (RELATIVE)',
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'POST (RULE 39)',
          label: 'POST (RULE 39)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'POST (OTHER)',
          label: 'POST (OTHER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'THROWN IN',
          label: 'THROWN IN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'DRONE/UAV',
          label: 'DRONE/UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
      ],
    },
    '57319': {
      id: '57319',
      code: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      label: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          code: 'VISITOR (FRIEND)',
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          code: 'VISITOR (OFFICIAL)',
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          code: 'VISITOR (RELATIVE)',
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          code: 'NOT APPLICABLE',
          label: 'NOT APPLICABLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
      ],
    },
    '57320': {
      id: '57320',
      code: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      label: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NOT CONCEALED',
          label: 'NOT CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'BED/BEDDING',
          label: 'BED/BEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'BOOK/PAPERS',
          label: 'BOOK/PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'CELL/BUILDING FABRIC',
          label: 'CELL/BUILDING FABRIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'FOOD/CONTAINER',
          label: 'FOOD/CONTAINER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'IN CLOTHING',
          label: 'IN CLOTHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'IN HAND',
          label: 'IN HAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'IN MOUTH',
          label: 'IN MOUTH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'INTERNALLY/PLUGGED',
          label: 'INTERNALLY/PLUGGED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'LETTER/PARCEL',
          label: 'LETTER/PARCEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'LIGHT FITTINGS',
          label: 'LIGHT FITTINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'PIPEWORK',
          label: 'PIPEWORK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'RULE 39/LEGAL PAPERS',
          label: 'RULE 39/LEGAL PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'TV/RADIO/DVD/CONSOLES ETC.',
          label: 'TV/RADIO/DVD/CONSOLES ETC.',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57321',
        },
      ],
    },
    '57321': {
      id: '57321',
      code: 'IS THE ITEM HEAVILY CONTAMINATED? (E.G. BLOOD, FAECES)',
      label: 'IS THE ITEM HEAVILY CONTAMINATED? (E.G. BLOOD, FAECES)',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57322',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57322',
        },
      ],
    },
    '57322': {
      id: '57322',
      code: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE?',
      label: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57323',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57325',
        },
      ],
    },
    '57323': {
      id: '57323',
      code: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      label: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      multipleAnswers: false,
      answers: [
        {
          code: 'AFTER ENTERING PRISON',
          label: 'AFTER ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57324',
        },
        {
          code: 'BEFORE ENTERING PRISON',
          label: 'BEFORE ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57324',
        },
      ],
    },
    '57324': {
      id: '57324',
      code: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN TO?',
      label: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN TO?',
      multipleAnswers: false,
      answers: [
        {
          code: 'PLEASE SPECIFY',
          label: 'PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57325',
        },
      ],
    },
    '57325': {
      id: '57325',
      code: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      label: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57326',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
      ],
    },
    '57326': {
      id: '57326',
      code: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      label: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      multipleAnswers: false,
      answers: [
        {
          code: 'COMMUNITY VISIT',
          label: 'COMMUNITY VISIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          code: 'COMPASSIONATE',
          label: 'COMPASSIONATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          code: 'FACILITY',
          label: 'FACILITY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          code: 'RESETTLEMENT',
          label: 'RESETTLEMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
      ],
    },
    '57327': {
      id: '57327',
      code: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND? (DRUGS, MOBILE PHONES ETC.)',
      label: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND? (DRUGS, MOBILE PHONES ETC.)',
      multipleAnswers: false,
      answers: [
        {
          code: '£0',
          label: '£0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1 to £100',
          label: '£1 to £100',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£101 to £200',
          label: '£101 to £200',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£201 to £300',
          label: '£201 to £300',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£301 to £400',
          label: '£301 to £400',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£401 to £500',
          label: '£401 to £500',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£501 to £1,000',
          label: '£501 to £1,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£1,001 to £5,000',
          label: '£1,001 to £5,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£5,001 to £10,000',
          label: '£5,001 to £10,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£10,001 to £20,000',
          label: '£10,001 to £20,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£20,001 to £30,000',
          label: '£20,001 to £30,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£30,001 to £40,000',
          label: '£30,001 to £40,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: '£40,001 to £50,000',
          label: '£40,001 to £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'More than £50,000',
          label: 'More than £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default OLD_FINDS4
