// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-20T16:52:38.011Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_HOSTAGE: IncidentTypeConfiguration = {
  incidentType: 'OLD_HOSTAGE',
  active: false,
  startingQuestionId: '44318',
  questions: {
    '44137': {
      id: '44137',
      active: false,
      code: 'WAS A HOSTAGE NEGOTIATION ADVISER PRESENT',
      label: 'WAS A HOSTAGE NEGOTIATION ADVISER PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44365',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44365',
        },
      ],
    },
    '44210': {
      id: '44210',
      active: false,
      code: 'WERE IMB MEMBERS PRESENT',
      label: 'WERE IMB MEMBERS PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44452',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44452',
        },
      ],
    },
    '44213': {
      id: '44213',
      active: false,
      code: 'ESTIMATED COST OF DAMAGE',
      label: 'ESTIMATED COST OF DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          code: 'ENTER AMOUNT IN POUND STERLING',
          active: false,
          label: 'ENTER AMOUNT IN POUND STERLING',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44293',
        },
      ],
    },
    '44218': {
      id: '44218',
      active: false,
      code: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44235',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44347',
        },
      ],
    },
    '44234': {
      id: '44234',
      active: false,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45093',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45093',
        },
      ],
    },
    '44235': {
      id: '44235',
      active: false,
      code: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      multipleAnswers: true,
      answers: [
        {
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          code: 'PRISONERS',
          active: false,
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          code: 'CIVILIAN GRADES',
          active: false,
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          code: 'POLICE',
          active: false,
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44347',
        },
      ],
    },
    '44239': {
      id: '44239',
      active: false,
      code: 'WHO AUTHORISED THE SHUT DOWN?',
      label: 'WHO AUTHORISED THE SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'GOVERNOR',
          active: false,
          label: 'GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45076',
        },
        {
          code: 'DEPUTY GOVERNOR',
          active: false,
          label: 'DEPUTY GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45076',
        },
        {
          code: 'DUTY GOVERNOR',
          active: false,
          label: 'DUTY GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45076',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45076',
        },
      ],
    },
    '44257': {
      id: '44257',
      active: false,
      code: 'WERE WATER HOSES USED',
      label: 'WERE WATER HOSES USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44891',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44891',
        },
      ],
    },
    '44265': {
      id: '44265',
      active: false,
      code: 'WERE THE POLICE PRESENT',
      label: 'WERE THE POLICE PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44963',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44963',
        },
      ],
    },
    '44275': {
      id: '44275',
      active: false,
      code: 'INDICATE THE NATURE OF THE SHUT DOWN',
      label: 'INDICATE THE NATURE OF THE SHUT DOWN',
      multipleAnswers: true,
      answers: [
        {
          code: 'TELEPHONY',
          active: false,
          label: 'TELEPHONY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44788',
        },
        {
          code: 'IT',
          active: false,
          label: 'IT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44788',
        },
      ],
    },
    '44293': {
      id: '44293',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      label: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44805',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44311': {
      id: '44311',
      active: false,
      code: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      label: 'WAS DAMAGE CAUSED TO PRISON PROPERTY',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44600',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44293',
        },
      ],
    },
    '44318': {
      id: '44318',
      active: false,
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      label: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44463',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
      ],
    },
    '44322': {
      id: '44322',
      active: false,
      code: 'WAS THERE EVIDENCE OF COLLUSION',
      label: 'WAS THERE EVIDENCE OF COLLUSION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44137',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44137',
        },
      ],
    },
    '44335': {
      id: '44335',
      active: false,
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45101',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44347',
        },
      ],
    },
    '44347': {
      id: '44347',
      active: false,
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT',
      label: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44937',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44937',
        },
      ],
    },
    '44356': {
      id: '44356',
      active: false,
      code: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      label: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
      ],
    },
    '44365': {
      id: '44365',
      active: false,
      code: 'WAS A CANDR ADVISOR PRESENT',
      label: 'WAS A CANDR ADVISOR PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44959',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44959',
        },
      ],
    },
    '44403': {
      id: '44403',
      active: false,
      code: 'QUOTE THE VANTIVE CASE NUMBER',
      label: 'QUOTE THE VANTIVE CASE NUMBER',
      multipleAnswers: false,
      answers: [
        {
          code: 'NUMBER',
          active: false,
          label: 'NUMBER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44831',
        },
      ],
    },
    '44411': {
      id: '44411',
      active: false,
      code: 'DID A TACTICAL FIREARMS ADVISER ATTEND',
      label: 'DID A TACTICAL FIREARMS ADVISER ATTEND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44939',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44939',
        },
      ],
    },
    '44431': {
      id: '44431',
      active: false,
      code: 'WAS PHYSICAL VIOLENCE USED TOWARDS HOSTAGE',
      label: 'WAS PHYSICAL VIOLENCE USED TOWARDS HOSTAGE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44777',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44777',
        },
      ],
    },
    '44452': {
      id: '44452',
      active: false,
      code: 'WERE WEAPONS USED BY THE PERPETRATOR',
      label: 'WERE WEAPONS USED BY THE PERPETRATOR',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44474',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
      ],
    },
    '44463': {
      id: '44463',
      active: false,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          active: false,
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'ASSOCIATION AREA',
          active: false,
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'CELL',
          active: false,
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'CHAPEL',
          active: false,
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'DINING ROOM',
          active: false,
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'DORMITORY',
          active: false,
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'EDUCATION',
          active: false,
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'EXERCISE YARD',
          active: false,
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'GATE',
          active: false,
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'GYM',
          active: false,
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'HEALTH CARE CENTRE',
          active: false,
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'KITCHEN',
          active: false,
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'OFFICE',
          active: false,
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'RECEPTION',
          active: false,
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'RECESS',
          active: false,
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'SEGREGATION UNIT',
          active: false,
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'SPECIAL UNIT',
          active: false,
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'SHOWERS/CHANGING ROOM',
          active: false,
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'VISITS',
          active: false,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'WING',
          active: false,
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'WORKS DEPARTMENT',
          active: false,
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'WORKSHOP',
          active: false,
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'WITHIN PERIMETER',
          active: false,
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'ELSEWHERE',
          active: false,
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'FUNERAL',
          active: false,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: false,
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: false,
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          active: false,
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'SPORTS FIELD',
          active: false,
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'VEHICLE',
          active: false,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'WEDDINGS',
          active: false,
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'MAGISTRATES COURT',
          active: false,
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
        {
          code: 'CROWN COURT',
          active: true,
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44690',
        },
      ],
    },
    '44474': {
      id: '44474',
      active: false,
      code: 'DESCRIBE WEAPONS USED',
      label: 'DESCRIBE WEAPONS USED',
      multipleAnswers: true,
      answers: [
        {
          code: 'FIREARM',
          active: false,
          label: 'FIREARM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'CHEMICAL INCAPACITANT',
          active: false,
          label: 'CHEMICAL INCAPACITANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'KNIFE/BLADE',
          active: false,
          label: 'KNIFE/BLADE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'OTHER SHARP INSTRUMENT',
          active: false,
          label: 'OTHER SHARP INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'BLUNT INSTRUMENT',
          active: false,
          label: 'BLUNT INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'LIGATURE',
          active: false,
          label: 'LIGATURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'DANGEROUS LIQUID',
          active: false,
          label: 'DANGEROUS LIQUID',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'EXCRETA/URINE',
          active: false,
          label: 'EXCRETA/URINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'SPITTING',
          active: false,
          label: 'SPITTING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'FOOD',
          active: false,
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'THROWN FURNITURE',
          active: false,
          label: 'THROWN FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'THROWN EQUIPMENT',
          active: false,
          label: 'THROWN EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45162',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45162',
        },
      ],
    },
    '44488': {
      id: '44488',
      active: false,
      code: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE SERVICE SUPPLIER',
      multipleAnswers: false,
      answers: [
        {
          code: 'LOCAL',
          active: false,
          label: 'LOCAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'SERVICE SUPPLIER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44497': {
      id: '44497',
      active: false,
      code: 'WAS A BARRICADE USED',
      label: 'WAS A BARRICADE USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44614',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44431',
        },
      ],
    },
    '44555': {
      id: '44555',
      active: false,
      code: 'WAS THE AMBULANCE SERVICE PRESENT',
      label: 'WAS THE AMBULANCE SERVICE PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45078',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45078',
        },
      ],
    },
    '44564': {
      id: '44564',
      active: false,
      code: 'ENTER NUMBER OF PERPETRATORS',
      label: 'ENTER NUMBER OF PERPETRATORS',
      multipleAnswers: false,
      answers: [
        {
          code: 'NUMBER',
          active: false,
          label: 'NUMBER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45004',
        },
      ],
    },
    '44569': {
      id: '44569',
      active: false,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44335',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44335',
        },
      ],
    },
    '44585': {
      id: '44585',
      active: false,
      code: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      label: 'DESCRIBE HOW THE INCIDENT WAS RESOLVED',
      multipleAnswers: false,
      answers: [
        {
          code: 'INTERVENTION',
          active: false,
          label: 'INTERVENTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44814',
        },
        {
          code: 'NEGOTIATION',
          active: false,
          label: 'NEGOTIATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44891',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44891',
        },
      ],
    },
    '44600': {
      id: '44600',
      active: false,
      code: 'DESCRIBE THE DAMAGE',
      label: 'DESCRIBE THE DAMAGE',
      multipleAnswers: false,
      answers: [
        {
          code: 'MINOR',
          active: false,
          label: 'MINOR',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44213',
        },
        {
          code: 'SERIOUS',
          active: false,
          label: 'SERIOUS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44213',
        },
        {
          code: 'EXTENSIVE',
          active: false,
          label: 'EXTENSIVE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44213',
        },
      ],
    },
    '44608': {
      id: '44608',
      active: false,
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          active: false,
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          code: 'MINOR BRUISES',
          active: false,
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          code: 'SWELLINGS',
          active: false,
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          code: 'SUPERFICIAL CUTS',
          active: false,
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45059',
        },
      ],
    },
    '44611': {
      id: '44611',
      active: false,
      code: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      label: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      multipleAnswers: false,
      answers: [
        {
          code: 'DESCRIPTION',
          active: false,
          label: 'DESCRIPTION',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44817',
        },
      ],
    },
    '44613': {
      id: '44613',
      active: false,
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'WAS A MINOR INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44608',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45059',
        },
      ],
    },
    '44614': {
      id: '44614',
      active: false,
      code: 'WAS A HOSTAGE PART OF THE BARRICADE',
      label: 'WAS A HOSTAGE PART OF THE BARRICADE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44431',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44431',
        },
      ],
    },
    '44690': {
      id: '44690',
      active: false,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45135',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45135',
        },
      ],
    },
    '44693': {
      id: '44693',
      active: false,
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'FRACTURE',
          active: false,
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'SCALD OR BURN',
          active: false,
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'STABBING',
          active: false,
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'CRUSHING',
          active: false,
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          active: false,
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'BLACK EYE',
          active: false,
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'BROKEN NOSE',
          active: false,
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'BROKEN TEETH',
          active: false,
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'CUTS REQUIRING SUTURES',
          active: false,
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'BITES',
          active: false,
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'GUN SHOT WOUND',
          active: false,
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
        {
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          active: false,
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
      ],
    },
    '44711': {
      id: '44711',
      active: false,
      code: 'WERE HEALTH CARE CENTRE STAFF PRESENT',
      label: 'WERE HEALTH CARE CENTRE STAFF PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44555',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44555',
        },
      ],
    },
    '44777': {
      id: '44777',
      active: false,
      code: 'WAS THE HOSTAGE PHYSICALLY RESTRAINED BY THE PERPETRATOR',
      label: 'WAS THE HOSTAGE PHYSICALLY RESTRAINED BY THE PERPETRATOR',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44585',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44585',
        },
      ],
    },
    '44788': {
      id: '44788',
      active: false,
      code: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      label: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'ENTER TIME',
          active: false,
          label: 'ENTER TIME',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45012',
        },
      ],
    },
    '44805': {
      id: '44805',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      multipleAnswers: false,
      answers: [
        {
          code: 'LOCAL',
          active: false,
          label: 'LOCAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
        {
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'SERVICE SUPPLIER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44403',
        },
      ],
    },
    '44814': {
      id: '44814',
      active: false,
      code: 'WAS A DOOR JACK USED',
      label: 'WAS A DOOR JACK USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44257',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44257',
        },
      ],
    },
    '44817': {
      id: '44817',
      active: false,
      code: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      label: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'ENTER COMMENT AND DATE',
          active: false,
          label: 'ENTER COMMENT AND DATE',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '44488',
        },
      ],
    },
    '44823': {
      id: '44823',
      active: false,
      code: 'DESCRIBE STATUS OF PERPETRATORS',
      label: 'DESCRIBE STATUS OF PERPETRATORS',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONER',
          active: false,
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44497',
        },
        {
          code: 'VISITOR',
          active: false,
          label: 'VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44497',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44497',
        },
      ],
    },
    '44831': {
      id: '44831',
      active: false,
      code: 'WAS THE KEYWORD REQUESTED?',
      label: 'WAS THE KEYWORD REQUESTED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44356',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44275',
        },
      ],
    },
    '44891': {
      id: '44891',
      active: false,
      code: 'WAS THERE EVIDENCE OF THE STOCKHOLM SYNDROME',
      label: 'WAS THERE EVIDENCE OF THE STOCKHOLM SYNDROME',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44322',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44322',
        },
      ],
    },
    '44937': {
      id: '44937',
      active: false,
      code: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF INCIDENT',
      label: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44564',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44564',
        },
      ],
    },
    '44939': {
      id: '44939',
      active: false,
      code: 'WERE FIREARMS OFFICERS DEPLOYED',
      label: 'WERE FIREARMS OFFICERS DEPLOYED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44210',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44210',
        },
      ],
    },
    '44959': {
      id: '44959',
      active: false,
      code: 'WAS THE EMERGENCY RESPONSE VEHICLE PRESENT',
      label: 'WAS THE EMERGENCY RESPONSE VEHICLE PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45079',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45079',
        },
      ],
    },
    '44963': {
      id: '44963',
      active: false,
      code: 'WAS A TECHNICAL SUPPORT UNIT PRESENT',
      label: 'WAS A TECHNICAL SUPPORT UNIT PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44411',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44411',
        },
      ],
    },
    '45004': {
      id: '45004',
      active: false,
      code: 'ENTER NUMBER OF HOSTAGES',
      label: 'ENTER NUMBER OF HOSTAGES',
      multipleAnswers: false,
      answers: [
        {
          code: 'NUMBER',
          active: false,
          label: 'NUMBER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45143',
        },
      ],
    },
    '45012': {
      id: '45012',
      active: false,
      code: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      label: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'FULL',
          active: false,
          label: 'FULL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44239',
        },
        {
          code: 'PARTIAL',
          active: false,
          label: 'PARTIAL',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44239',
        },
      ],
    },
    '45059': {
      id: '45059',
      active: false,
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      multipleAnswers: true,
      answers: [
        {
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          code: 'PRISONERS',
          active: false,
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          code: 'CIVILIAN GRADES',
          active: false,
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          code: 'POLICE',
          active: false,
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          active: false,
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44218',
        },
      ],
    },
    '45076': {
      id: '45076',
      active: false,
      code: 'WAS THE SYSTEM COMPROMISED?',
      label: 'WAS THE SYSTEM COMPROMISED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44611',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44817',
        },
      ],
    },
    '45078': {
      id: '45078',
      active: false,
      code: 'WAS THE FIRE SERVICE PRESENT',
      label: 'WAS THE FIRE SERVICE PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45148',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45148',
        },
      ],
    },
    '45079': {
      id: '45079',
      active: false,
      code: 'WAS AN INCIDENT LIAISON OFFICER PRESENT',
      label: 'WAS AN INCIDENT LIAISON OFFICER PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45087',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45087',
        },
      ],
    },
    '45087': {
      id: '45087',
      active: false,
      code: 'WAS A MEDICAL OFFICER PRESENT',
      label: 'WAS A MEDICAL OFFICER PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44711',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44711',
        },
      ],
    },
    '45093': {
      id: '45093',
      active: false,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44569',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44569',
        },
      ],
    },
    '45101': {
      id: '45101',
      active: false,
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'WAS A SERIOUS INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44693',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44613',
        },
      ],
    },
    '45135': {
      id: '45135',
      active: false,
      code: 'THE INCIDENT IS SUBJECT TO',
      label: 'THE INCIDENT IS SUBJECT TO',
      multipleAnswers: true,
      answers: [
        {
          code: 'INVESTIGATION BY POLICE',
          active: false,
          label: 'INVESTIGATION BY POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
        {
          code: 'INVESTIGATION INTERNALLY',
          active: false,
          label: 'INVESTIGATION INTERNALLY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
        {
          code: "GOVERNOR'S ADJUDICATION",
          active: false,
          label: "GOVERNOR'S ADJUDICATION",
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
        {
          code: 'NO INVESTIGATION',
          active: false,
          label: 'NO INVESTIGATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44234',
        },
      ],
    },
    '45143': {
      id: '45143',
      active: false,
      code: 'DESCRIBE STATUS OF HOSTAGES',
      label: 'DESCRIBE STATUS OF HOSTAGES',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONER',
          active: false,
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          code: 'OFFICER',
          active: false,
          label: 'OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          code: 'CIVILIAN STAFF',
          active: false,
          label: 'CIVILIAN STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44823',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44823',
        },
      ],
    },
    '45148': {
      id: '45148',
      active: false,
      code: 'WERE WORKS SERVICES STAFF PRESENT',
      label: 'WERE WORKS SERVICES STAFF PRESENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44265',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44265',
        },
      ],
    },
    '45162': {
      id: '45162',
      active: false,
      code: 'DURATION OF INCIDENT IN HOURS',
      label: 'DURATION OF INCIDENT IN HOURS',
      multipleAnswers: false,
      answers: [
        {
          code: 'HOURS',
          active: false,
          label: 'HOURS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44311',
        },
      ],
    },
  },
} as const

export default OLD_HOSTAGE
