// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-10-15T17:17:36.088Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_TEMPORARY_RELEASE_FAILURE1: IncidentTypeConfiguration = {
  incidentType: 'OLD_TEMPORARY_RELEASE_FAILURE1',
  active: false,
  startingQuestionId: '49308',
  questions: {
    '49308': {
      id: '49308',
      active: false,
      code: 'What Type Of Temporary Licence Was Breached',
      label: 'What Type Of Temporary Licence Was Breached',
      multipleAnswers: false,
      answers: [
        {
          id: '195150',
          code: 'Resettlement Day',
          active: false,
          label: 'Resettlement Day',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49309',
        },
        {
          id: '195151',
          code: 'Resettlement Overnight',
          active: false,
          label: 'Resettlement Overnight',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49309',
        },
        {
          id: '195152',
          code: 'Childcare Resettlement',
          active: false,
          label: 'Childcare Resettlement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49309',
        },
        {
          id: '195153',
          code: 'Special Purpose',
          active: false,
          label: 'Special Purpose',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49309',
        },
      ],
    },
    '49309': {
      id: '49309',
      active: false,
      code: 'What Was The Specific Purpose Of Temporary Release',
      label: 'What Was The Specific Purpose Of Temporary Release',
      multipleAnswers: false,
      answers: [
        {
          id: '195154',
          code: 'Court / Legal / Police',
          active: false,
          label: 'Court / Legal / Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195155',
          code: 'CRL',
          active: false,
          label: 'CRL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195156',
          code: 'Funeral / Visiting A Dying Relative',
          active: false,
          label: 'Funeral / Visiting A Dying Relative',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195157',
          code: 'Maintaining Family Ties',
          active: false,
          label: 'Maintaining Family Ties',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195158',
          code: 'Other Compassionate Reason',
          active: false,
          label: 'Other Compassionate Reason',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195159',
          code: 'Other RDR Linked to Sentence Plan',
          active: false,
          label: 'Other RDR Linked to Sentence Plan',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195160',
          code: 'Outside Prison Activity (OPA)',
          active: false,
          label: 'Outside Prison Activity (OPA)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195161',
          code: 'Resettlement Overnight Release (ROR)',
          active: false,
          label: 'Resettlement Overnight Release (ROR)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
        {
          id: '195162',
          code: 'Training Or Education',
          active: false,
          label: 'Training Or Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49310',
        },
      ],
    },
    '49310': {
      id: '49310',
      active: false,
      code: 'Were The Police Informed Of The Incident',
      label: 'Were The Police Informed Of The Incident',
      multipleAnswers: false,
      answers: [
        {
          id: '195163',
          code: 'Yes (Enter Date)',
          active: false,
          label: 'Yes (Enter Date)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49311',
        },
        {
          id: '195164',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49311',
        },
      ],
    },
    '49311': {
      id: '49311',
      active: false,
      code: 'Is The Incident The Subject Of A Police Investigation',
      label: 'Is The Incident The Subject Of A Police Investigation',
      multipleAnswers: false,
      answers: [
        {
          id: '195165',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49312',
        },
        {
          id: '195166',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49312',
        },
      ],
    },
    '49312': {
      id: '49312',
      active: false,
      code: 'Is The Incident The Subject Of An Internal Investigation',
      label: 'Is The Incident The Subject Of An Internal Investigation',
      multipleAnswers: false,
      answers: [
        {
          id: '195167',
          code: 'Yes - Local Only',
          active: false,
          label: 'Yes - Local Only',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49313',
        },
        {
          id: '195168',
          code: 'Yes - DDC Commissioned',
          active: false,
          label: 'Yes - DDC Commissioned',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49313',
        },
        {
          id: '195169',
          code: 'Yes - SFO Investigation',
          active: false,
          label: 'Yes - SFO Investigation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49313',
        },
        {
          id: '195170',
          code: 'No (Enter Reasons)',
          active: false,
          label: 'No (Enter Reasons)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49313',
        },
      ],
    },
    '49313': {
      id: '49313',
      active: false,
      code: "Is the Incident Subject To A Governor's Adjudication",
      label: "Is the Incident Subject To A Governor's Adjudication",
      multipleAnswers: false,
      answers: [
        {
          id: '195171',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49314',
        },
        {
          id: '195172',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49314',
        },
      ],
    },
    '49314': {
      id: '49314',
      active: false,
      code: 'Is There Likely To Be Any Media Interest In This Incident',
      label: 'Is There Likely To Be Any Media Interest In This Incident',
      multipleAnswers: false,
      answers: [
        {
          id: '195173',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49315',
        },
        {
          id: '195174',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49315',
        },
      ],
    },
    '49315': {
      id: '49315',
      active: false,
      code: 'Has The Prison Service Press Office Been Informed',
      label: 'Has The Prison Service Press Office Been Informed',
      multipleAnswers: false,
      answers: [
        {
          id: '195175',
          code: 'Yes (Enter Date)',
          active: false,
          label: 'Yes (Enter Date)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49316',
        },
        {
          id: '195176',
          code: 'No (Enter Reason)',
          active: false,
          label: 'No (Enter Reason)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49316',
        },
      ],
    },
    '49316': {
      id: '49316',
      active: false,
      code: 'Is The Prisoner Subject To Restricted ROTL',
      label: 'Is The Prisoner Subject To Restricted ROTL',
      multipleAnswers: false,
      answers: [
        {
          id: '195177',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49317',
        },
        {
          id: '195178',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49319',
        },
      ],
    },
    '49317': {
      id: '49317',
      active: false,
      code: 'Has The Deputy Director Of Custody Been Informed',
      label: 'Has The Deputy Director Of Custody Been Informed',
      multipleAnswers: false,
      answers: [
        {
          id: '195179',
          code: 'Yes (Enter Date)',
          active: false,
          label: 'Yes (Enter Date)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49318',
        },
        {
          id: '195180',
          code: 'No (Enter Reason)',
          active: false,
          label: 'No (Enter Reason)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49318',
        },
      ],
    },
    '49318': {
      id: '49318',
      active: false,
      code: 'Have PPCS Been Informed',
      label: 'Have PPCS Been Informed',
      multipleAnswers: false,
      answers: [
        {
          id: '195181',
          code: 'Yes (Enter Date)',
          active: false,
          label: 'Yes (Enter Date)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49319',
        },
        {
          id: '195182',
          code: 'No (Enter Reasons)',
          active: false,
          label: 'No (Enter Reasons)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49319',
        },
      ],
    },
    '49319': {
      id: '49319',
      active: false,
      code: 'Was The Failure Of Temporary Licence Or Any Part Of The Breach Failing To Return Or Returning Late',
      label: 'Was The Failure Of Temporary Licence Or Any Part Of The Breach Failing To Return Or Returning Late',
      multipleAnswers: false,
      answers: [
        {
          id: '195183',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49320',
        },
        {
          id: '195184',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49324',
        },
      ],
    },
    '49320': {
      id: '49320',
      active: false,
      code: 'Was The Failure To Return Reported To The Police As The Offence Of Failure To Return From Temporary Licence',
      label:
        'Was The Failure To Return Reported To The Police As The Offence Of Failure To Return From Temporary Licence',
      multipleAnswers: false,
      answers: [
        {
          id: '195185',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49321',
        },
        {
          id: '195186',
          code: 'No (Enter Reasons)',
          active: false,
          label: 'No (Enter Reasons)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49321',
        },
      ],
    },
    '49321': {
      id: '49321',
      active: false,
      code: 'Did The Prisoner Surrender To HMPS Custody On The Same Day The Licence Expired',
      label: 'Did The Prisoner Surrender To HMPS Custody On The Same Day The Licence Expired',
      multipleAnswers: false,
      answers: [
        {
          id: '195187',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49322',
        },
        {
          id: '195188',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49322',
        },
      ],
    },
    '49322': {
      id: '49322',
      active: false,
      code: 'Has The Prisoner Been Recaptured',
      label: 'Has The Prisoner Been Recaptured',
      multipleAnswers: false,
      answers: [
        {
          id: '195189',
          code: 'Yes (Enter Date)',
          active: false,
          label: 'Yes (Enter Date)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49323',
        },
        {
          id: '195190',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49324',
        },
      ],
    },
    '49323': {
      id: '49323',
      active: false,
      code: 'How Was The Prisoner Recaptured',
      label: 'How Was The Prisoner Recaptured',
      multipleAnswers: false,
      answers: [
        {
          id: '195191',
          code: 'Surrender To HMPS',
          active: false,
          label: 'Surrender To HMPS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49324',
        },
        {
          id: '195192',
          code: 'Surrender To Police',
          active: false,
          label: 'Surrender To Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49324',
        },
        {
          id: '195193',
          code: 'Arrest By HMPS',
          active: false,
          label: 'Arrest By HMPS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49324',
        },
        {
          id: '195194',
          code: 'Arrest By Police',
          active: false,
          label: 'Arrest By Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49324',
        },
        {
          id: '195195',
          code: 'Other (Provide Details)',
          active: false,
          label: 'Other (Provide Details)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49324',
        },
      ],
    },
    '49324': {
      id: '49324',
      active: false,
      code: 'Was Any Part Of The Failure Failing To Comply With Any Other Licence Conditions (These Can Be Standard or Bespoke)',
      label:
        'Was Any Part Of The Failure Failing To Comply With Any Other Licence Conditions (These Can Be Standard or Bespoke)',
      multipleAnswers: false,
      answers: [
        {
          id: '195196',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49325',
        },
        {
          id: '195197',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
      ],
    },
    '49325': {
      id: '49325',
      active: false,
      code: 'Please Specify Which Conditions (Select As Many As Appropriate)',
      label: 'Please Specify Which Conditions (Select As Many As Appropriate)',
      multipleAnswers: true,
      answers: [
        {
          id: '195198',
          code: 'Alcohol',
          active: false,
          label: 'Alcohol',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
        {
          id: '195199',
          code: 'Gambling',
          active: false,
          label: 'Gambling',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
        {
          id: '195200',
          code: 'Drugs',
          active: false,
          label: 'Drugs',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
        {
          id: '195201',
          code: 'Location',
          active: false,
          label: 'Location',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
        {
          id: '195202',
          code: 'Social Media',
          active: false,
          label: 'Social Media',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
        {
          id: '195203',
          code: 'Bad Behaviour',
          active: false,
          label: 'Bad Behaviour',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
        {
          id: '195204',
          code: 'Media Contact',
          active: false,
          label: 'Media Contact',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49326',
        },
        {
          id: '195205',
          code: 'Other (Provide Details)',
          active: false,
          label: 'Other (Provide Details)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '49326',
        },
      ],
    },
    '49326': {
      id: '49326',
      active: false,
      code: 'Has The Prisoner Been Arrested (Including For The Offence Of Failure To Return)',
      label: 'Has The Prisoner Been Arrested (Including For The Offence Of Failure To Return)',
      multipleAnswers: false,
      answers: [
        {
          id: '195223',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49327',
        },
        {
          id: '195224',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49327',
        },
      ],
    },
    '49327': {
      id: '49327',
      active: false,
      code: 'Has The Prisoner Been Charged With Any Offence (Including The Offence Of Failure To Return)',
      label: 'Has The Prisoner Been Charged With Any Offence (Including The Offence Of Failure To Return)',
      multipleAnswers: false,
      answers: [
        {
          id: '195225',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49328',
        },
        {
          id: '195226',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49328',
        },
        {
          id: '195227',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49328',
        },
      ],
    },
    '49328': {
      id: '49328',
      active: false,
      code: 'With What Type Of Offence or Offences Has The Prisoner Been Charged (Select As Many As Appropriate)',
      label: 'With What Type Of Offence or Offences Has The Prisoner Been Charged (Select As Many As Appropriate)',
      multipleAnswers: true,
      answers: [
        {
          id: '195228',
          code: 'Violence Against The Person',
          active: false,
          label: 'Violence Against The Person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195229',
          code: 'Sexual Offences',
          active: false,
          label: 'Sexual Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195230',
          code: 'Robbery',
          active: false,
          label: 'Robbery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195231',
          code: 'Burglary',
          active: false,
          label: 'Burglary',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195232',
          code: 'Theft And Handling',
          active: false,
          label: 'Theft And Handling',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195233',
          code: 'Fraud And Forgery',
          active: false,
          label: 'Fraud And Forgery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195234',
          code: 'Drug Offences',
          active: false,
          label: 'Drug Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195235',
          code: 'Motoring Offences',
          active: false,
          label: 'Motoring Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195236',
          code: 'Failure To Return From ROTL',
          active: false,
          label: 'Failure To Return From ROTL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
        {
          id: '195237',
          code: 'Other Offence',
          active: false,
          label: 'Other Offence',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49331',
        },
      ],
    },
    '49331': {
      id: '49331',
      active: false,
      code: 'Has The Prisoner Been Found Guilty Of Offences Committed On ROTL',
      label: 'Has The Prisoner Been Found Guilty Of Offences Committed On ROTL',
      multipleAnswers: false,
      answers: [
        {
          id: '195249',
          code: 'Yes',
          active: false,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49334',
        },
        {
          id: '195250',
          code: 'No',
          active: false,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
      ],
    },
    '49334': {
      id: '49334',
      active: false,
      code: 'What Offence Or Offences Has The Prisoner Been Found Guilty Of (Select As Many As Appropriate)',
      label: 'What Offence Or Offences Has The Prisoner Been Found Guilty Of (Select As Many As Appropriate)',
      multipleAnswers: true,
      answers: [
        {
          id: '195238',
          code: 'Violence Against The Person',
          active: false,
          label: 'Violence Against The Person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195239',
          code: 'Sexual Offences',
          active: false,
          label: 'Sexual Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195240',
          code: 'Robbery',
          active: false,
          label: 'Robbery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195241',
          code: 'Burglary',
          active: false,
          label: 'Burglary',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195242',
          code: 'Theft And Handling',
          active: false,
          label: 'Theft And Handling',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195243',
          code: 'Fraud And Forgery',
          active: false,
          label: 'Fraud And Forgery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195244',
          code: 'Drug Offences',
          active: false,
          label: 'Drug Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195245',
          code: 'Motoring Offences',
          active: false,
          label: 'Motoring Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195246',
          code: 'Failure To Return From ROTL',
          active: false,
          label: 'Failure To Return From ROTL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
        {
          id: '195247',
          code: 'Other Offence',
          active: false,
          label: 'Other Offence',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '49335',
        },
      ],
    },
    '49335': {
      id: '49335',
      active: false,
      code: 'Confirm SFO Team, Offender Manager In The Community, Victim Liaison Officer And Employer (where appropriate) Informed',
      label:
        'Confirm SFO Team, Offender Manager In The Community, Victim Liaison Officer And Employer (where appropriate) Informed',
      multipleAnswers: false,
      answers: [
        {
          id: '195248',
          code: 'Yes (Date)',
          active: false,
          label: 'Yes (Date)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ABSCONDER',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default OLD_TEMPORARY_RELEASE_FAILURE1
