// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-20T16:52:35.791Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_FIREARM_ETC: IncidentTypeConfiguration = {
  incidentType: 'OLD_FIREARM_ETC',
  active: false,
  startingQuestionId: '44776',
  questions: {
    '44123': {
      id: '44123',
      active: false,
      code: 'HOW WAS THE ITEM FOUND',
      label: 'HOW WAS THE ITEM FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'TARGET SEARCH',
          active: false,
          label: 'TARGET SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44637',
        },
        {
          code: 'ROUTINE SEARCH',
          active: false,
          label: 'ROUTINE SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44980',
        },
        {
          code: 'CHANCE',
          active: false,
          label: 'CHANCE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44980',
        },
      ],
    },
    '44160': {
      id: '44160',
      active: false,
      code: 'WHAT WAS THE COUNTRY OF MANUFACTURE OF THE SPRAY',
      label: 'WHAT WAS THE COUNTRY OF MANUFACTURE OF THE SPRAY',
      multipleAnswers: false,
      answers: [
        {
          code: 'SPECIFY',
          active: false,
          label: 'SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44526',
        },
      ],
    },
    '44172': {
      id: '44172',
      active: false,
      code: 'WAS A CHEMICAL INCAPACITANT SPRAY FOUND',
      label: 'WAS A CHEMICAL INCAPACITANT SPRAY FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44548',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44526',
        },
      ],
    },
    '44189': {
      id: '44189',
      active: false,
      code: 'WAS THE FIREARM AN AUTOMATIC',
      label: 'WAS THE FIREARM AN AUTOMATIC',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44846',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44846',
        },
      ],
    },
    '44193': {
      id: '44193',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      label: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN DURING THE INCIDENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44451',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44208': {
      id: '44208',
      active: false,
      code: 'IS THERE ANY SUSPICION OF TRAFFICKING',
      label: 'IS THERE ANY SUSPICION OF TRAFFICKING',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45049',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45049',
        },
      ],
    },
    '44209': {
      id: '44209',
      active: false,
      code: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'WAS THE SYSTEM RE-ACTIVATED LOCALLY OR BY THE SERVICE SUPPLIER',
      multipleAnswers: false,
      answers: [
        {
          code: 'LOCAL',
          active: false,
          label: 'LOCAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'SERVICE SUPPLIER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44323': {
      id: '44323',
      active: false,
      code: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      label: 'DESCRIBE WHAT WAS COMPROMISED AND BY WHOM',
      multipleAnswers: false,
      answers: [
        {
          code: 'DESCRIPTION',
          active: false,
          label: 'DESCRIPTION',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44779',
        },
      ],
    },
    '44330': {
      id: '44330',
      active: false,
      code: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      label: 'HAS THE SERVICE SUPPLIER BEEN NOTIFIED OF A REPLACEMENT KEYWORD?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44755',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44755',
        },
      ],
    },
    '44390': {
      id: '44390',
      active: false,
      code: 'WHAT TYPE OF AMMUNITION WAS FOUND',
      label: 'WHAT TYPE OF AMMUNITION WAS FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'PISTOL/REVOLVER',
          active: false,
          label: 'PISTOL/REVOLVER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44698',
        },
        {
          code: 'RIFLE',
          active: false,
          label: 'RIFLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44698',
        },
        {
          code: 'SHOTGUN',
          active: false,
          label: 'SHOTGUN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44698',
        },
        {
          code: 'HILTI GUN',
          active: false,
          label: 'HILTI GUN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44698',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44698',
        },
      ],
    },
    '44398': {
      id: '44398',
      active: false,
      code: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      label: 'WHAT TIME WAS THE SYSTEM SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'ENTER TIME',
          active: false,
          label: 'ENTER TIME',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44964',
        },
      ],
    },
    '44430': {
      id: '44430',
      active: false,
      code: 'HOW MANY ROUNDS ETC WERE FOUND',
      label: 'HOW MANY ROUNDS ETC WERE FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NUMBER',
          active: false,
          label: 'NUMBER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44172',
        },
      ],
    },
    '44446': {
      id: '44446',
      active: false,
      code: 'HAS ANY PERSON BEEN ARRESTED BY THE POLICE',
      label: 'HAS ANY PERSON BEEN ARRESTED BY THE POLICE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44524',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44208',
        },
      ],
    },
    '44451': {
      id: '44451',
      active: false,
      code: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      label: 'WAS THE TELEPHONE/IT SYSTEM SHUT DOWN LOCALLY OR BY THE SERVICE SUPPLIER',
      multipleAnswers: false,
      answers: [
        {
          code: 'LOCAL',
          active: false,
          label: 'LOCAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44755',
        },
        {
          code: 'SERVICE SUPPLIER',
          active: false,
          label: 'SERVICE SUPPLIER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44988',
        },
      ],
    },
    '44455': {
      id: '44455',
      active: false,
      code: 'WHAT WAS THE SOURCE OF THE INFORMATION/INTELLIGENCE',
      label: 'WHAT WAS THE SOURCE OF THE INFORMATION/INTELLIGENCE',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISONER',
          active: false,
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44980',
        },
        {
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44980',
        },
        {
          code: 'POLICE',
          active: false,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44980',
        },
        {
          code: 'VISITOR',
          active: false,
          label: 'VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44980',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44980',
        },
      ],
    },
    '44470': {
      id: '44470',
      active: false,
      code: 'WAS THE ITEM CONCEALED/DISCARDED',
      label: 'WAS THE ITEM CONCEALED/DISCARDED',
      multipleAnswers: false,
      answers: [
        {
          code: 'CONCEALED',
          active: false,
          label: 'CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45102',
        },
        {
          code: 'DISCARDED',
          active: false,
          label: 'DISCARDED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
      ],
    },
    '44473': {
      id: '44473',
      active: false,
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44676',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44676',
        },
      ],
    },
    '44504': {
      id: '44504',
      active: false,
      code: 'WHAT WAS THE CALIBRE OF THE FIREARM',
      label: 'WHAT WAS THE CALIBRE OF THE FIREARM',
      multipleAnswers: false,
      answers: [
        {
          code: 'SPECIFY',
          active: false,
          label: 'SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44189',
        },
      ],
    },
    '44513': {
      id: '44513',
      active: false,
      code: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45000',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45000',
        },
      ],
    },
    '44524': {
      id: '44524',
      active: false,
      code: 'DESCRIBE THE PERSON ARRESTED',
      label: 'DESCRIBE THE PERSON ARRESTED',
      multipleAnswers: true,
      answers: [
        {
          code: 'PRISONER',
          active: false,
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44874',
        },
        {
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44874',
        },
        {
          code: 'SOCIAL VISITOR',
          active: false,
          label: 'SOCIAL VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44874',
        },
        {
          code: 'OFFICIAL VISITOR',
          active: false,
          label: 'OFFICIAL VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44874',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44874',
        },
      ],
    },
    '44526': {
      id: '44526',
      active: false,
      code: 'WHERE WAS THE ITEM FOUND',
      label: 'WHERE WAS THE ITEM FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          active: false,
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'CELL',
          active: false,
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'ASSOCIATION AREA',
          active: false,
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'CHAPEL',
          active: false,
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'DINING ROOM',
          active: false,
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'DORMITORY',
          active: false,
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'EDUCATION',
          active: false,
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'EXERCISE YARD',
          active: false,
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'GATE',
          active: false,
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'GYM',
          active: false,
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'HEALTH CARE CENTRE',
          active: false,
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'KITCHEN',
          active: false,
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'OFFICE',
          active: false,
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'RECEPTION',
          active: false,
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'RECESS',
          active: false,
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'SEGREGATION UNIT',
          active: false,
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'SPECIAL UNIT',
          active: false,
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'SHOWERS/CHANGING ROOM',
          active: false,
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'VISITS',
          active: false,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'WING',
          active: false,
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'WORKS DEPARTMENT',
          active: false,
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'WORKSHOP',
          active: false,
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'WITHIN PERIMETER',
          active: false,
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'ELSEWHERE',
          active: false,
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'FUNERAL',
          active: false,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: false,
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: false,
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          active: false,
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'SPORTSFIELD',
          active: false,
          label: 'SPORTSFIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'VEHICLE',
          active: false,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'WEDDING',
          active: false,
          label: 'WEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'MAGISTRATES COURT',
          active: false,
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
        {
          code: 'CROWN COURT',
          active: false,
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44470',
        },
      ],
    },
    '44548': {
      id: '44548',
      active: false,
      code: 'DESCRIBE THE TYPE OF SPRAY',
      label: 'DESCRIBE THE TYPE OF SPRAY',
      multipleAnswers: true,
      answers: [
        {
          code: 'C.N (CHLORACETOPHEONE)',
          active: false,
          label: 'C.N (CHLORACETOPHEONE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44622',
        },
        {
          code: 'C.S (ORTHO..NITRILE)',
          active: false,
          label: 'C.S (ORTHO..NITRILE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44622',
        },
        {
          code: 'O.C (MACE/PEPPER)',
          active: false,
          label: 'O.C (MACE/PEPPER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44622',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44622',
        },
        {
          code: 'NOT KNOWN',
          active: false,
          label: 'NOT KNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44622',
        },
      ],
    },
    '44622': {
      id: '44622',
      active: false,
      code: 'WHAT WAS THE BRAND NAME OF THE SPRAY',
      label: 'WHAT WAS THE BRAND NAME OF THE SPRAY',
      multipleAnswers: false,
      answers: [
        {
          code: 'SPECIFY',
          active: false,
          label: 'SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44160',
        },
      ],
    },
    '44624': {
      id: '44624',
      active: false,
      code: 'CAN ITEMS BE ATTRIBUTED TO A PARTICULAR PRISONER',
      label: 'CAN ITEMS BE ATTRIBUTED TO A PARTICULAR PRISONER',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44692',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44446',
        },
      ],
    },
    '44637': {
      id: '44637',
      active: false,
      code: 'WAS THE SEARCH AS A RESULT OF INFORMATION/INTELLIGENCE',
      label: 'WAS THE SEARCH AS A RESULT OF INFORMATION/INTELLIGENCE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44455',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44980',
        },
      ],
    },
    '44676': {
      id: '44676',
      active: false,
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45026',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45026',
        },
      ],
    },
    '44692': {
      id: '44692',
      active: false,
      code: 'HAS THE PRISONER BEEN ENTERED ON THE INMATE INVOLVEMENT',
      label: 'HAS THE PRISONER BEEN ENTERED ON THE INMATE INVOLVEMENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44446',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44446',
        },
      ],
    },
    '44698': {
      id: '44698',
      active: false,
      code: 'WHAT WAS THE CALIBRE OF THE AMMUNITION',
      label: 'WHAT WAS THE CALIBRE OF THE AMMUNITION',
      multipleAnswers: false,
      answers: [
        {
          code: 'SPECIFY',
          active: false,
          label: 'SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44430',
        },
      ],
    },
    '44703': {
      id: '44703',
      active: false,
      code: 'WAS AMMUNITION FOUND',
      label: 'WAS AMMUNITION FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44870',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44172',
        },
      ],
    },
    '44755': {
      id: '44755',
      active: false,
      code: 'INDICATE THE NATURE OF THE SHUT DOWN',
      label: 'INDICATE THE NATURE OF THE SHUT DOWN',
      multipleAnswers: true,
      answers: [
        {
          code: 'TELEPHONY',
          active: false,
          label: 'TELEPHONY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44398',
        },
        {
          code: 'IT',
          active: false,
          label: 'IT',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44398',
        },
      ],
    },
    '44776': {
      id: '44776',
      active: false,
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44513',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45000',
        },
      ],
    },
    '44779': {
      id: '44779',
      active: false,
      code: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      label: 'WHEN WAS THE SYSTEM RE-ACTIVATED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'ENTER COMMENT AND DATE',
          active: false,
          label: 'ENTER COMMENT AND DATE',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '44209',
        },
      ],
    },
    '44820': {
      id: '44820',
      active: false,
      code: 'WAS THE SYSTEM COMPROMISED?',
      label: 'WAS THE SYSTEM COMPROMISED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44323',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44779',
        },
      ],
    },
    '44827': {
      id: '44827',
      active: false,
      code: 'WHAT PARTS OF A FIREARM WERE FOUND',
      label: 'WHAT PARTS OF A FIREARM WERE FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'BARREL',
          active: false,
          label: 'BARREL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44703',
        },
        {
          code: 'BUTT',
          active: false,
          label: 'BUTT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44703',
        },
        {
          code: 'MAGAZINE',
          active: false,
          label: 'MAGAZINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44703',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44703',
        },
      ],
    },
    '44832': {
      id: '44832',
      active: false,
      code: 'WAS THE KEYWORD REQUESTED?',
      label: 'WAS THE KEYWORD REQUESTED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44330',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44755',
        },
      ],
    },
    '44846': {
      id: '44846',
      active: false,
      code: 'WHAT WAS THE NAME OF THE MANUFACTURER',
      label: 'WHAT WAS THE NAME OF THE MANUFACTURER',
      multipleAnswers: false,
      answers: [
        {
          code: 'SPECIFY',
          active: false,
          label: 'SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45001',
        },
      ],
    },
    '44870': {
      id: '44870',
      active: false,
      code: 'DESCRIBE THE AMMUNITION',
      label: 'DESCRIBE THE AMMUNITION',
      multipleAnswers: true,
      answers: [
        {
          code: 'LIVE',
          active: false,
          label: 'LIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44390',
        },
        {
          code: 'BLANK',
          active: false,
          label: 'BLANK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44390',
        },
        {
          code: 'DISABLED',
          active: false,
          label: 'DISABLED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44390',
        },
        {
          code: 'CARTRIDGE CASE',
          active: false,
          label: 'CARTRIDGE CASE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44390',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44390',
        },
      ],
    },
    '44874': {
      id: '44874',
      active: false,
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44208',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44208',
        },
      ],
    },
    '44907': {
      id: '44907',
      active: false,
      code: 'WHO AUTHORISED THE SHUT DOWN?',
      label: 'WHO AUTHORISED THE SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'GOVERNOR',
          active: false,
          label: 'GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44820',
        },
        {
          code: 'DEPUTY GOVERNOR',
          active: false,
          label: 'DEPUTY GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44820',
        },
        {
          code: 'DUTY GOVERNOR',
          active: false,
          label: 'DUTY GOVERNOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44820',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44820',
        },
      ],
    },
    '44922': {
      id: '44922',
      active: false,
      code: 'WHICH DETECTION AIDS WERE USED',
      label: 'WHICH DETECTION AIDS WERE USED',
      multipleAnswers: true,
      answers: [
        {
          code: 'METAL DETECTING PORTAL',
          active: false,
          label: 'METAL DETECTING PORTAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44624',
        },
        {
          code: 'HAND HELD METAL DETECTOR',
          active: false,
          label: 'HAND HELD METAL DETECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44624',
        },
        {
          code: 'X-RAY MACHINE',
          active: false,
          label: 'X-RAY MACHINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44624',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44624',
        },
      ],
    },
    '44928': {
      id: '44928',
      active: false,
      code: 'WERE DETECTION AIDS USED',
      label: 'WERE DETECTION AIDS USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44922',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44624',
        },
      ],
    },
    '44964': {
      id: '44964',
      active: false,
      code: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      label: 'WAS THIS A FULL OR PARTIAL SHUT DOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'FULL',
          active: false,
          label: 'FULL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44907',
        },
        {
          code: 'PARTIAL',
          active: false,
          label: 'PARTIAL',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44907',
        },
      ],
    },
    '44980': {
      id: '44980',
      active: false,
      code: 'WERE SPECIALIST DOGS USED',
      label: 'WERE SPECIALIST DOGS USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44928',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44928',
        },
      ],
    },
    '44988': {
      id: '44988',
      active: false,
      code: 'QUOTE THE VANTIVE CASE NUMBER',
      label: 'QUOTE THE VANTIVE CASE NUMBER',
      multipleAnswers: false,
      answers: [
        {
          code: 'NUMBER',
          active: false,
          label: 'NUMBER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44832',
        },
      ],
    },
    '45000': {
      id: '45000',
      active: false,
      code: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45005',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45005',
        },
      ],
    },
    '45001': {
      id: '45001',
      active: false,
      code: 'WAS THE FIREARM COMPLETE',
      label: 'WAS THE FIREARM COMPLETE',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44703',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44827',
        },
      ],
    },
    '45005': {
      id: '45005',
      active: false,
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44473',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44473',
        },
      ],
    },
    '45026': {
      id: '45026',
      active: false,
      code: 'WAS A FIREARM FOUND',
      label: 'WAS A FIREARM FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          active: false,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45029',
        },
        {
          code: 'NO',
          active: false,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44703',
        },
      ],
    },
    '45029': {
      id: '45029',
      active: false,
      code: 'WHAT TYPE OF FIREARM WAS FOUND',
      label: 'WHAT TYPE OF FIREARM WAS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'PISTOL',
          active: false,
          label: 'PISTOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45119',
        },
        {
          code: 'REVOLVER',
          active: false,
          label: 'REVOLVER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45119',
        },
        {
          code: 'RIFLE',
          active: false,
          label: 'RIFLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45119',
        },
        {
          code: 'SHOTGUN',
          active: false,
          label: 'SHOTGUN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45119',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45119',
        },
      ],
    },
    '45049': {
      id: '45049',
      active: false,
      code: 'WHO NOW HAS CUSTODY OF THE ITEMS',
      label: 'WHO NOW HAS CUSTODY OF THE ITEMS',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISON',
          active: false,
          label: 'PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44193',
        },
        {
          code: 'POLICE',
          active: false,
          label: 'POLICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44193',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44193',
        },
      ],
    },
    '45056': {
      id: '45056',
      active: false,
      code: 'DESCRIBE THE PERSON',
      label: 'DESCRIBE THE PERSON',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISONER',
          active: false,
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'STAFF',
          active: false,
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'SOCIAL VISITOR',
          active: false,
          label: 'SOCIAL VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'OFFICIAL VISITOR',
          active: false,
          label: 'OFFICIAL VISITOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'OTHER',
          active: false,
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44123',
        },
      ],
    },
    '45102': {
      id: '45102',
      active: false,
      code: 'WHERE WAS THE ITEM CONCEALED',
      label: 'WHERE WAS THE ITEM CONCEALED',
      multipleAnswers: false,
      answers: [
        {
          code: 'ON A PERSON',
          active: false,
          label: 'ON A PERSON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45056',
        },
        {
          code: 'BURIED',
          active: false,
          label: 'BURIED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'IN I/P PROPERTY',
          active: false,
          label: 'IN I/P PROPERTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'IN STORED PROPERTY',
          active: false,
          label: 'IN STORED PROPERTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'IN CELL FURNITURE',
          active: false,
          label: 'IN CELL FURNITURE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'IN BUILDING FABRIC',
          active: false,
          label: 'IN BUILDING FABRIC',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'STORES ITEMS',
          active: false,
          label: 'STORES ITEMS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'DELIVERED FOODS/PARCELS',
          active: false,
          label: 'DELIVERED FOODS/PARCELS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'VEHICLE',
          active: false,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44123',
        },
        {
          code: 'ELSEWHERE',
          active: false,
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44123',
        },
      ],
    },
    '45119': {
      id: '45119',
      active: false,
      code: 'DESCRIBE THE FIREARM',
      label: 'DESCRIBE THE FIREARM',
      multipleAnswers: false,
      answers: [
        {
          code: 'REAL (FUNCTIONAL)',
          active: false,
          label: 'REAL (FUNCTIONAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44504',
        },
        {
          code: 'REAL (NON-FUNCTIONAL)',
          active: false,
          label: 'REAL (NON-FUNCTIONAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44504',
        },
        {
          code: 'REPLICA',
          active: false,
          label: 'REPLICA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44504',
        },
        {
          code: 'HOME MADE',
          active: false,
          label: 'HOME MADE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44504',
        },
        {
          code: 'TOY',
          active: false,
          label: 'TOY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44504',
        },
      ],
    },
  },
} as const

export default OLD_FIREARM_ETC
