// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-12T16:34:00.573Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_MOBILES: IncidentTypeConfiguration = {
  incidentType: 'OLD_MOBILES',
  active: false,
  startingQuestionId: '47179',
  questions: {
    '45209': {
      id: '45209',
      label: 'Item found. Must enter value (how many found) in comments field',
      multipleAnswers: true,
      answers: [
        {
          label: 'Mobile:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'SIM:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Charger:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other please specify:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Mobile:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
        {
          label: 'SIM:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
        {
          label: 'Charger:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
        {
          label: 'Other please specify:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
      ],
    },
    '45210': {
      id: '45210',
      label: 'Date item was found',
      multipleAnswers: false,
      answers: [
        {
          label: 'Enter Date:',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Enter Date:',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45211',
        },
      ],
    },
    '45211': {
      id: '45211',
      label: 'Time item was found',
      multipleAnswers: false,
      answers: [
        {
          label: 'Enter Time:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Enter Time:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45212',
        },
      ],
    },
    '45212': {
      id: '45212',
      label: 'Is the method of entry into the establishment known?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45213',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
      ],
    },
    '45213': {
      id: '45213',
      label: 'Describe the method of entry into the establishment',
      multipleAnswers: false,
      answers: [
        {
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Prisoner/Young Offender',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Visitor: Specify:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Social',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Official',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contractor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Thrown In',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Post - Social/Rule 39',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Not attributable',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Prisoner / Young Offender',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Visitor: Social',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Visitor: Official',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Contractor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Thrown In',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Post – Social / Rule 39',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Not attributable',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45214',
        },
        {
          label: 'Other : Please Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45214',
        },
      ],
    },
    '45214': {
      id: '45214',
      label: 'Describe how item/s were found',
      multipleAnswers: true,
      answers: [
        {
          label: 'Boss Chair',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'High Sensitivity Wand',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Mobile Phone Detection Dog',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Physical search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Cell search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Unusual/Suspicious behaviour',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Mobile phone signal detector',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Intelligence led search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Information received',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Boss Chair',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'High Sensitivity Wand',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Mobile phone detection Dog',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Physical Search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Cell Search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Unusual/Suspicious Behaviour',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Mobile phone signal detector',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Intelligence led search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Information Received',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45215',
        },
        {
          label: 'Other: Please Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45215',
        },
      ],
    },
    '45215': {
      id: '45215',
      label: 'If the item was found in possession - Whose possession was it found in?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Prisoner/Young Offender',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contractor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Visitor: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Official',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Prisoner/Young Offender',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45216',
        },
        {
          label: 'Staff',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45216',
        },
        {
          label: 'Contractor',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45216',
        },
        {
          label: 'Visitor: Social',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45216',
        },
        {
          label: 'Visitor: Official',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45216',
        },
        {
          label: 'Other: Please Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45216',
        },
      ],
    },
    '45216': {
      id: '45216',
      label: 'Where was the mobile phone found?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Administration Area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Association Area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Prisoner Accommodation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Exercise Yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'External Area (within prison grounds)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Health Care Centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Post/Parcel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Segregation Unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Special Unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Showers/Changing Room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Works Department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Staff Area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Administration Area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Association Area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Prisoner Accommodation',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Chapel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Dormitory',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Exercise Yard',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'External Area (within prison grounds)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Gate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Gym',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Health Care Centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Post/Parcel',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Reception',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Recess',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Segregation Unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Special Unit',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Showers/Changing Room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Visits',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Wing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Works Department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Sports field',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Staff Area',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45217',
        },
        {
          label: 'Other: Please Specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45217',
        },
      ],
    },
    '45217': {
      id: '45217',
      label: 'Is make of phone/sims/equipment known?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Please specify',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45218',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45218',
        },
      ],
    },
    '45218': {
      id: '45218',
      label: 'Has Phone/SIM/Equipment been sent to NDTSG?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Evidence Bag Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No: Please state why',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45219',
        },
        {
          label: 'Evidence Bag Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45219',
        },
        {
          label: 'No: Please state why',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45219',
        },
      ],
    },
    '45219': {
      id: '45219',
      label: 'Name and grade of member of staff who has authorised for the mobile/SIM to be interrogated',
      multipleAnswers: true,
      answers: [
        {
          label: 'Name:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Grade:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Name:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45220',
        },
        {
          label: 'Grade:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45220',
        },
      ],
    },
    '45220': {
      id: '45220',
      label: 'Has Phone/SIM/Equipment been retained by Police?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Police Incident Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45221',
        },
        {
          label: 'Police Incident Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45221',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45221',
        },
      ],
    },
    '45221': {
      id: '45221',
      label: 'Has incident been referred to Police for consideration under OMA or Crime & Security Act?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Police Ref Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45222',
        },
        {
          label: 'Police Ref Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45222',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45222',
        },
      ],
    },
    '45222': {
      id: '45222',
      label: 'NDTSG Priority',
      multipleAnswers: false,
      answers: [
        {
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Urgent',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45223',
        },
        {
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45223',
        },
        {
          label: 'Urgent',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45223',
        },
        {
          label: 'N/A Not Applicable',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45223',
        },
      ],
    },
    '45223': {
      id: '45223',
      label:
        'If a mobile / SIM was found on a person, please state where (this will assist with identifying contaminated mobiles)',
      multipleAnswers: false,
      answers: [
        {
          label: 'Please state where on person mobile phone was found:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Please state where on person mobile phone was found:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45224',
        },
      ],
    },
    '45224': {
      id: '45224',
      label: 'Is the item heavily contaminated?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45225',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45226',
        },
      ],
    },
    '45225': {
      id: '45225',
      label: 'If the item is heavily contaminated is interrogation still required?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes: Please state why',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Please state why',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45226',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45226',
        },
      ],
    },
    '45226': {
      id: '45226',
      label: 'Has written consent been given to interrogate item (Only necessary for staff, visitors and contractors)',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No: Please state why',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45227',
        },
        {
          label: 'No: Please state why',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45227',
        },
      ],
    },
    '45227': {
      id: '45227',
      label: 'Has any prosecution taken place or are any pending?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45228',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45228',
        },
      ],
    },
    '45228': {
      id: '45228',
      label: 'Is the Incident subject to an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45229',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45229',
        },
      ],
    },
    '45229': {
      id: '45229',
      label: 'Is the incident subject to an adjudication?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45230',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45230',
        },
      ],
    },
    '45230': {
      id: '45230',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45231',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45231',
        },
      ],
    },
    '45231': {
      id: '45231',
      label: 'Have items been returned: Please specify who to in comments field',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes: Date',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Date',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '45232',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45232',
        },
      ],
    },
    '45232': {
      id: '45232',
      label: 'Establishment Category',
      multipleAnswers: false,
      answers: [
        {
          label: 'HSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Local Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Cat B Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Cat C Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Open Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Cluster',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'YOI Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Young People',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Female Estate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'HSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'Local Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'Cat B Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'Cat C Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'Open Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'Cluster',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'YOI Male',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'Young People',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
        {
          label: 'Female Estate',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45233',
        },
      ],
    },
    '45233': {
      id: '45233',
      label: 'Establishment Name',
      multipleAnswers: false,
      answers: [
        {
          label: 'Enter Establishment name in comments:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Enter Establishment name in comments:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45234',
        },
      ],
    },
    '45234': {
      id: '45234',
      label: 'Area/Region',
      multipleAnswers: false,
      answers: [
        {
          label: 'High Security',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'East Midlands',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'West Midlands',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Greater London',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'South West',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Kent & Sussex',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'North East',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'South Central',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'East of England',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'North West',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Wales',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yorkshire & Humberside',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contracted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '47179': {
      id: '47179',
      label: 'Item found. Must enter how many found in comments field',
      multipleAnswers: true,
      answers: [
        {
          label: 'Mobile:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
        {
          label: 'SIM:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
        {
          label: 'Charger:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
        {
          label: 'Other please specify:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45210',
        },
      ],
    },
  },
} as const

export default OLD_MOBILES
