// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-16T15:41:51.344Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_ASSAULT: IncidentTypeConfiguration = {
  incidentType: 'OLD_ASSAULT',
  active: false,
  startingQuestionId: '44127',
  questions: {
    '44127': {
      id: '44127',
      code: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES (ENTER DATE)',
          label: 'YES (ENTER DATE)',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44913',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44405',
        },
      ],
    },
    '44141': {
      id: '44141',
      code: 'WAS A MINOR INJURY SUSTAINED',
      label: 'WAS A MINOR INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44612',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44460',
        },
      ],
    },
    '44153': {
      id: '44153',
      code: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44186',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44186',
        },
      ],
    },
    '44186': {
      id: '44186',
      code: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44201',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44201',
        },
      ],
    },
    '44201': {
      id: '44201',
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      label: 'IS THE LOCATION OF THE INCIDENT KNOWN',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45134',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
      ],
    },
    '44254': {
      id: '44254',
      code: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      label: 'WERE ANY INJURIES RECEIVED DURING THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44793',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44460',
        },
      ],
    },
    '44344': {
      id: '44344',
      code: 'WERE ANY WEAPONS USED',
      label: 'WERE ANY WEAPONS USED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44464',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
      ],
    },
    '44367': {
      id: '44367',
      code: 'WHAT TYPE OF ASSAULT WAS IT',
      label: 'WHAT TYPE OF ASSAULT WAS IT',
      multipleAnswers: false,
      answers: [
        {
          code: 'PRISONER ON PRISONER',
          label: 'PRISONER ON PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45130',
        },
        {
          code: 'PRISONER ON OFFICER',
          label: 'PRISONER ON OFFICER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44495',
        },
        {
          code: 'PRISONER ON OTHER',
          label: 'PRISONER ON OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44495',
        },
        {
          code: 'OTHER',
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44495',
        },
      ],
    },
    '44391': {
      id: '44391',
      code: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      label: 'ARE THERE ANY STAFF NOW OFF DUTY AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44652',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44652',
        },
      ],
    },
    '44405': {
      id: '44405',
      code: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45088',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45088',
        },
      ],
    },
    '44460': {
      id: '44460',
      code: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      label: 'DID INJURIES RESULT IN DETENTION IN OUTSIDE HOSPITAL AS AN IN-PATIENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44943',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44391',
        },
      ],
    },
    '44464': {
      id: '44464',
      code: 'DESCRIBE WEAPONS USED',
      label: 'DESCRIBE WEAPONS USED',
      multipleAnswers: true,
      answers: [
        {
          code: 'FIREARM',
          label: 'FIREARM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'CHEMICAL INCAPACITANT',
          label: 'CHEMICAL INCAPACITANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'KNIFE/BLADE',
          label: 'KNIFE/BLADE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'OTHER SHARP INSTRUMENT',
          label: 'OTHER SHARP INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'BLUNT INSTRUMENT',
          label: 'BLUNT INSTRUMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'LIGATURE',
          label: 'LIGATURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'DANGEROUS LIQUID',
          label: 'DANGEROUS LIQUID',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'EXCRETA/URINE',
          label: 'EXCRETA/URINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'SPITTING',
          label: 'SPITTING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'FOOD',
          label: 'FOOD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'THROWN FURNITURE',
          label: 'THROWN FURNITURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'THROWN EQUIPMENT',
          label: 'THROWN EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45074',
        },
        {
          code: 'OTHER',
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45074',
        },
      ],
    },
    '44495': {
      id: '44495',
      code: 'DID THE ASSAULT OCCUR IN PUBLIC VIEW',
      label: 'DID THE ASSAULT OCCUR IN PUBLIC VIEW',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44344',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44344',
        },
      ],
    },
    '44522': {
      id: '44522',
      code: 'WAS MEDICAL TREATMENT FOR CONCUSSION OR INTERNAL INJURIES REQUIRED',
      label: 'WAS MEDICAL TREATMENT FOR CONCUSSION OR INTERNAL INJURIES REQUIRED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44254',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44254',
        },
      ],
    },
    '44586': {
      id: '44586',
      code: 'WAS THIS A SEXUAL ASSAULT',
      label: 'WAS THIS A SEXUAL ASSAULT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44522',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44522',
        },
      ],
    },
    '44612': {
      id: '44612',
      code: 'WHICH MINOR INJURIES WERE SUSTAINED',
      label: 'WHICH MINOR INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'GRAZES, SCRATCHES OR ABRASIONS',
          label: 'GRAZES, SCRATCHES OR ABRASIONS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44460',
        },
        {
          code: 'MINOR BRUISES',
          label: 'MINOR BRUISES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44460',
        },
        {
          code: 'SWELLINGS',
          label: 'SWELLINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44460',
        },
        {
          code: 'SUPERFICIAL CUTS',
          label: 'SUPERFICIAL CUTS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44460',
        },
        {
          code: 'OTHER',
          label: 'OTHER',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44460',
        },
      ],
    },
    '44652': {
      id: '44652',
      code: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      label: 'ARE ANY STAFF ON SICK LEAVE AS A RESULT OF THIS INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44367',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44367',
        },
      ],
    },
    '44773': {
      id: '44773',
      code: 'WAS A SERIOUS INJURY SUSTAINED',
      label: 'WAS A SERIOUS INJURY SUSTAINED',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45042',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
      ],
    },
    '44793': {
      id: '44793',
      code: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      label: 'ENTER DESCRIPTION OF PERSON(S) INJURED',
      multipleAnswers: true,
      answers: [
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44773',
        },
        {
          code: 'PRISONERS',
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44773',
        },
        {
          code: 'CIVILIAN GRADES',
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44773',
        },
        {
          code: 'POLICE',
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44773',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44773',
        },
      ],
    },
    '44880': {
      id: '44880',
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44153',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44153',
        },
      ],
    },
    '44913': {
      id: '44913',
      code: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45092',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44405',
        },
      ],
    },
    '44943': {
      id: '44943',
      code: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      label: 'WHO WAS DETAINED IN OUTSIDE HOSPITAL',
      multipleAnswers: true,
      answers: [
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44391',
        },
        {
          code: 'PRISONERS',
          label: 'PRISONERS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44391',
        },
        {
          code: 'CIVILIAN GRADES',
          label: 'CIVILIAN GRADES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44391',
        },
        {
          code: 'POLICE',
          label: 'POLICE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44391',
        },
        {
          code: 'EXTERNAL CIVILIANS',
          label: 'EXTERNAL CIVILIANS',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44391',
        },
      ],
    },
    '45042': {
      id: '45042',
      code: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      label: 'WHICH SERIOUS INJURIES WERE SUSTAINED',
      multipleAnswers: true,
      answers: [
        {
          code: 'FRACTURE',
          label: 'FRACTURE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'SCALD OR BURN',
          label: 'SCALD OR BURN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'STABBING',
          label: 'STABBING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'CRUSHING',
          label: 'CRUSHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'EXTENSIVE/MULTIPLE BRUISING',
          label: 'EXTENSIVE/MULTIPLE BRUISING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'BLACK EYE',
          label: 'BLACK EYE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'BROKEN NOSE',
          label: 'BROKEN NOSE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'BROKEN TEETH',
          label: 'BROKEN TEETH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'CUTS REQUIRING SUTURES',
          label: 'CUTS REQUIRING SUTURES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'BITES',
          label: 'BITES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'GUN SHOT WOUND',
          label: 'GUN SHOT WOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
        {
          code: 'TEMPORARY/PERMANENT BLINDNESS',
          label: 'TEMPORARY/PERMANENT BLINDNESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44141',
        },
      ],
    },
    '45074': {
      id: '45074',
      code: 'WAS THERE AN APPARENT REASON FOR THE ASSAULT',
      label: 'WAS THERE AN APPARENT REASON FOR THE ASSAULT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '45088': {
      id: '45088',
      code: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44880',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44880',
        },
      ],
    },
    '45092': {
      id: '45092',
      code: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      label: 'HAS ANY PROSECUTION TAKEN PLACE OR IS ANY PENDING',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44405',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44405',
        },
      ],
    },
    '45130': {
      id: '45130',
      code: 'DID THE ASSAULT OCCUR DURING A FIGHT',
      label: 'DID THE ASSAULT OCCUR DURING A FIGHT',
      multipleAnswers: false,
      answers: [
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44495',
        },
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44495',
        },
      ],
    },
    '45134': {
      id: '45134',
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'ASSOCIATION AREA',
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'CELL',
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'CHAPEL',
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'DINING ROOM',
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'DORMITORY',
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'EDUCATION',
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'EXERCISE YARD',
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'GATE',
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'GYM',
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'HEALTH CARE CENTRE',
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'KITCHEN',
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'OFFICE',
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'RECEPTION',
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'RECESS',
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'SEGREGATION UNIT',
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'SPECIAL UNIT',
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'SHOWERS/CHANGING ROOM',
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'VISITS',
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'WING',
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'WORKS DEPARTMENT',
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'WORKSHOP',
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'WITHIN PERIMETER',
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'ELSEWHERE',
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'FUNERAL',
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'SPORTS FIELD',
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'VEHICLE',
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'WEDDINGS',
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'MAGISTRATES COURT',
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
        {
          code: 'CROWN COURT',
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44586',
        },
      ],
    },
  },
} as const

export default OLD_ASSAULT
