// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-16T15:42:07.119Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_FINDS3: IncidentTypeConfiguration = {
  incidentType: 'OLD_FINDS3',
  active: false,
  startingQuestionId: '65179',
  questions: {
    '65179': {
      id: '65179',
      code: 'DESCRIBE HOW THE ITEM WAS FOUND (SELECT ALL THAT APPLY)',
      label: 'DESCRIBE HOW THE ITEM WAS FOUND (SELECT ALL THAT APPLY)',
      multipleAnswers: true,
      answers: [
        {
          code: 'AMNESTY',
          label: 'AMNESTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'ARCHWAY METAL DETECTOR (AMD)',
          label: 'ARCHWAY METAL DETECTOR (AMD)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'BOSS CHAIR',
          label: 'BOSS CHAIR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'CELL SEARCH',
          label: 'CELL SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'CRIME SCENE',
          label: 'CRIME SCENE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'DOG SEARCH',
          label: 'DOG SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'DRONE RECOVERY',
          label: 'DRONE RECOVERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'DRUG TRACE DETECTION MACHINE',
          label: 'DRUG TRACE DETECTION MACHINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'GATE SEARCH - ENHANCED GATE SECURITY (EGS)',
          label: 'GATE SEARCH - ENHANCED GATE SECURITY (EGS)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'GATE SEARCH - FRONT END SEARCH (FES), HIGH SECURITY ONLY (HSE)',
          label: 'GATE SEARCH - FRONT END SEARCH (FES), HIGH SECURITY ONLY (HSE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'GATE SEARCH - OTHER',
          label: 'GATE SEARCH - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'HAND HELD METAL DETECTION (HHMD) WAND',
          label: 'HAND HELD METAL DETECTION (HHMD) WAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'INFORMATION RECEIVED',
          label: 'INFORMATION RECEIVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'INTELLIGENCE LED SEARCH',
          label: 'INTELLIGENCE LED SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'ITEM HANDED OVER',
          label: 'ITEM HANDED OVER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'ITEM OBSERVED & RECOVERED',
          label: 'ITEM OBSERVED & RECOVERED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'MOBILE PHONE SIGNAL DETECTOR',
          label: 'MOBILE PHONE SIGNAL DETECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'PHONE DETECTION POLE',
          label: 'PHONE DETECTION POLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'PRE-OCCUPATION SEARCH',
          label: 'PRE-OCCUPATION SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'UNUSUAL BEHAVIOUR',
          label: 'UNUSUAL BEHAVIOUR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'X-RAY BAGGAGE SCANNER',
          label: 'X-RAY BAGGAGE SCANNER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'X-RAY BODY SCANNER',
          label: 'X-RAY BODY SCANNER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'OTHER SEARCH (PRISONER)',
          label: 'OTHER SEARCH (PRISONER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'OTHER SEARCH (PREMISES)',
          label: 'OTHER SEARCH (PREMISES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'OTHER SEARCH (STAFF)',
          label: 'OTHER SEARCH (STAFF)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'OTHER SEARCH (VISITOR)',
          label: 'OTHER SEARCH (VISITOR)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65180',
        },
      ],
    },
    '65180': {
      id: '65180',
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      label: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65181',
        },
      ],
    },
    '65181': {
      id: '65181',
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      label: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'ADMINISTRATION',
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'ASSOCIATION AREA (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'ASSOCIATION AREA (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'CELL  (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'CELL  (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'CHAPEL',
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'COURT',
          label: 'COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'DINING ROOM (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'DINING ROOM (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'DORMITORY (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'DORMITORY (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'EDUCATION',
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'EXERCISE YARD (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'EXERCISE YARD (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'GATE',
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'GYM',
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'HEALTH CARE CENTRE',
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'HOSPITAL OUTSIDE (VISITING)',
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'INDUCTION/FIRST NIGHT CENTRE',
          label: 'INDUCTION/FIRST NIGHT CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'KITCHEN',
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'MAIL ROOM',
          label: 'MAIL ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'OFFICE',
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'OUTSIDE WORKING PARTY',
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'RECEPTION',
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'RECESS/ ROOF VOID',
          label: 'RECESS/ ROOF VOID',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'SEGREGATION UNIT (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'SEGREGATION UNIT (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'SHOWERS/CHANGING ROOM (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'SHOWERS/CHANGING ROOM (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'VEHICLE USED FOR COURT/TRANSFER',
          label: 'VEHICLE USED FOR COURT/TRANSFER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'VISITS',
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'VULNERABLE PRISONERS UNIT (VPU) (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'VULNERABLE PRISONERS UNIT (VPU) (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'WING (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'WING (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'WORKSHOP (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'WORKSHOP (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
        {
          code: 'OTHER (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          label: 'OTHER (PLEASE STATE LOCATION DETAILS IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65182',
        },
      ],
    },
    '65182': {
      id: '65182',
      code: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      label: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      multipleAnswers: false,
      answers: [
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'DRONE/UAV',
          label: 'DRONE/UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'POST - RULE 39 (CHECK RULE 39 MAIL, BARCODED)',
          label: 'POST - RULE 39 (CHECK RULE 39 MAIL, BARCODED)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65183',
        },
        {
          code: 'POST - RULE 39 (NOT CHECK RULE 39 MAIL, NO BARCODE)',
          label: 'POST - RULE 39 (NOT CHECK RULE 39 MAIL, NO BARCODE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'POST - OTHER',
          label: 'POST - OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'THROWN IN',
          label: 'THROWN IN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'VISITOR - DOMESTIC',
          label: 'VISITOR - DOMESTIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'VISITOR - SOCIAL',
          label: 'VISITOR - SOCIAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'VISITOR - OTHER (PLEASE ENTER COMMENT TO EXPLAIN)',
          label: 'VISITOR - OTHER (PLEASE ENTER COMMENT TO EXPLAIN)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65184',
        },
      ],
    },
    '65183': {
      id: '65183',
      code: 'DID RULE 39 MAIL BARCODE PASS SCANNER CHECK?',
      label: 'DID RULE 39 MAIL BARCODE PASS SCANNER CHECK?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65184',
        },
      ],
    },
    '65184': {
      id: '65184',
      code: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      label: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NOT APPLICABLE',
          label: 'NOT APPLICABLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65186',
        },
        {
          code: 'CONTRACTOR',
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65185',
        },
        {
          code: 'PRISONER',
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65185',
        },
        {
          code: 'STAFF',
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65185',
        },
        {
          code: 'VISITOR - DOMESTIC',
          label: 'VISITOR - DOMESTIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65185',
        },
        {
          code: 'VISITOR - SOCIAL',
          label: 'VISITOR - SOCIAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65185',
        },
        {
          code: 'VISITOR - OTHER (PLEASE ENTER COMMENT TO EXPLAIN)',
          label: 'VISITOR - OTHER (PLEASE ENTER COMMENT TO EXPLAIN)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65185',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65185',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65185',
        },
      ],
    },
    '65185': {
      id: '65185',
      code: 'IS IT SUSPECTED THAT THE ITEM WAS BROUGHT IN BY ACCIDENT?',
      label: 'IS IT SUSPECTED THAT THE ITEM WAS BROUGHT IN BY ACCIDENT?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65186',
        },
        {
          code: 'YES (e.g. ITEM RETURN TO STAFF AT END OF SHIFT/VISIT)',
          label: 'YES (e.g. ITEM RETURN TO STAFF AT END OF SHIFT/VISIT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65186',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65186',
        },
      ],
    },
    '65186': {
      id: '65186',
      code: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      label: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      multipleAnswers: true,
      answers: [
        {
          code: 'NOT CONCEALED',
          label: 'NOT CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'BED/BEDDING',
          label: 'BED/BEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'BOOK/PAPERS',
          label: 'BOOK/PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'CELL/BUILDING FABRIC',
          label: 'CELL/BUILDING FABRIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'FOOD/CONTAINER',
          label: 'FOOD/CONTAINER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'IN BAG (i.e. BACKPACK/BRIEFCASE/HANDBAG)',
          label: 'IN BAG (i.e. BACKPACK/BRIEFCASE/HANDBAG)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'IN CLOTHING',
          label: 'IN CLOTHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'IN HAND',
          label: 'IN HAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'IN MOUTH',
          label: 'IN MOUTH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'INTERNALLY CONCEALED',
          label: 'INTERNALLY CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'LETTER/PARCEL',
          label: 'LETTER/PARCEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'LIGHT FITTINGS',
          label: 'LIGHT FITTINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'PIPEWORK',
          label: 'PIPEWORK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'RULE 39/LEGAL PAPERS',
          label: 'RULE 39/LEGAL PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'TV/RADIO/DVD/CONSOLES ETC',
          label: 'TV/RADIO/DVD/CONSOLES ETC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65187',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65187',
        },
      ],
    },
    '65187': {
      id: '65187',
      code: 'PLEASE SELECT CATEGORY OF FIND',
      label: 'PLEASE SELECT CATEGORY OF FIND',
      multipleAnswers: false,
      answers: [
        {
          code: 'MULTIPLE TYPES (SEE FULL BELOW LIST BEFORE SELECTING)',
          label: 'MULTIPLE TYPES (SEE FULL BELOW LIST BEFORE SELECTING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65207',
        },
        {
          code: 'ALCOHOL / HOOCH / DISTILLING EQUIPMENT',
          label: 'ALCOHOL / HOOCH / DISTILLING EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65188',
        },
        {
          code: 'DRUG / DRUG EQUIPMENT',
          label: 'DRUG / DRUG EQUIPMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: 'MOBILE PHONE / MOBILE RELATED ITEM',
          label: 'MOBILE PHONE / MOBILE RELATED ITEM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65194',
        },
        {
          code: 'DIGITAL FIND (EXLUDING MOBILE PHONES)',
          label: 'DIGITAL FIND (EXLUDING MOBILE PHONES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65200',
        },
        {
          code: 'TOBACCO / TOBACCO RELATED ITEMS',
          label: 'TOBACCO / TOBACCO RELATED ITEMS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65201',
        },
        {
          code: 'WEAPON',
          label: 'WEAPON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65203',
        },
        {
          code: 'OTHER REPORTALE ITEMS (BY NATIONAL OR LOCAL POLICY)',
          label: 'OTHER REPORTALE ITEMS (BY NATIONAL OR LOCAL POLICY)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65204',
        },
      ],
    },
    '65188': {
      id: '65188',
      code: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND',
      label: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: 'LESS THAN 1 LITRE (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'LESS THAN 1 LITRE (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: '1 LITRE TO LESS THAN 2 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '1 LITRE TO LESS THAN 2 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: '2 LITRES TO LESS THAN 3 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '2 LITRES TO LESS THAN 3 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: '3 LITRES TO LESS THAN 4 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '3 LITRES TO LESS THAN 4 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: '4 LITRES TO LESS THAN 5 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '4 LITRES TO LESS THAN 5 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: '5 LITRES TO LESS THAN 10 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '5 LITRES TO LESS THAN 10 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: '10 LITRES TO LESS THAN 20 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '10 LITRES TO LESS THAN 20 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
        {
          code: '20 LITRES OR MORE (PLEASE STATE NUMBER IN COMMENTS)',
          label: '20 LITRES OR MORE (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65190',
        },
      ],
    },
    '65189': {
      id: '65189',
      code: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      label: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES (Please specify)',
          label: 'YES (Please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65190': {
      id: '65190',
      code: 'DESCRIBE THE DRUG FOUND',
      label: 'DESCRIBE THE DRUG FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'NONE FOUND',
          label: 'NONE FOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'AMPHETAMINES',
          label: 'AMPHETAMINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'BARBITURATES',
          label: 'BARBITURATES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'BENZODIAZEPINES',
          label: 'BENZODIAZEPINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'BUPRENORPHINE/SUBUTEX',
          label: 'BUPRENORPHINE/SUBUTEX',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'CANNABIS',
          label: 'CANNABIS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'CANNABIS PLANT',
          label: 'CANNABIS PLANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'COCAINE',
          label: 'COCAINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'CRACK',
          label: 'CRACK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'GABAPENTIN',
          label: 'GABAPENTIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'HEROIN',
          label: 'HEROIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'KETAMINE',
          label: 'KETAMINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'LSD',
          label: 'LSD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'METHADONE',
          label: 'METHADONE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'NPS (NEW PSYCHOACTIVE SUBSTANCES)',
          label: 'NPS (NEW PSYCHOACTIVE SUBSTANCES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'PREGABALIN',
          label: 'PREGABALIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'STEROIDS',
          label: 'STEROIDS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'TRAMADOL',
          label: 'TRAMADOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'TRANQUILISERS',
          label: 'TRANQUILISERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65191',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65191',
        },
      ],
    },
    '65191': {
      id: '65191',
      code: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND',
      label: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: 'LESS THAN OR EQUAL TO 1G',
          label: 'LESS THAN OR EQUAL TO 1G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '2G TO 5G',
          label: '2G TO 5G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '6G TO 10G',
          label: '6G TO 10G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '11G TO 20G',
          label: '11G TO 20G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '21G TO 30G',
          label: '21G TO 30G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '31G TO 40G',
          label: '31G TO 40G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '41G TO 50G',
          label: '41G TO 50G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '50G TO 100G',
          label: '50G TO 100G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '101G TO 200G',
          label: '101G TO 200G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '201G TO 300G',
          label: '201G TO 300G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '301G TO 400G',
          label: '301G TO 400G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '401G TO 500G',
          label: '401G TO 500G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: '501G TO 1,000G',
          label: '501G TO 1,000G',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
        {
          code: 'MORE THAN 1KG',
          label: 'MORE THAN 1KG',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65192',
        },
      ],
    },
    '65192': {
      id: '65192',
      code: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      label: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65193',
        },
        {
          code: 'YES - FORENSIC LABORATORY',
          label: 'YES - FORENSIC LABORATORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65193',
        },
        {
          code: 'YES - LOCAL WITH BDH KIT OR SIMILAR',
          label: 'YES - LOCAL WITH BDH KIT OR SIMILAR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65193',
        },
      ],
    },
    '65193': {
      id: '65193',
      code: 'DESCRIBE DRUG EQUIPMENT FOUND',
      label: 'DESCRIBE DRUG EQUIPMENT FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'NONE FOUND',
          label: 'NONE FOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'AUTHENTIC NEEDLE',
          label: 'AUTHENTIC NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'AUTHENTIC SYRINGE',
          label: 'AUTHENTIC SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'IMPROVISED NEEDLE',
          label: 'IMPROVISED NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'IMPROVISED SYRINGE',
          label: 'IMPROVISED SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'PIPE(S)',
          label: 'PIPE(S)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'ROACH',
          label: 'ROACH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65194': {
      id: '65194',
      code: 'ENTER NUMBER OF MOBILES FOUND',
      label: 'ENTER NUMBER OF MOBILES FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO MOBILE PHONE FOUND',
          label: 'NO MOBILE PHONE FOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          label: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65195',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65195',
        },
      ],
    },
    '65195': {
      id: '65195',
      code: 'ENTER NUMBER OF SIM CARDS FOUND',
      label: 'ENTER NUMBER OF SIM CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          label: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65196',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65196',
        },
      ],
    },
    '65196': {
      id: '65196',
      code: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      label: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO MEMORY CARD FOUND',
          label: 'NO MEMORY CARD FOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          label: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65197',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65197',
        },
      ],
    },
    '65197': {
      id: '65197',
      code: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO DMIU (DIGITAL MEDIA INVESTIGATION UNIT)',
      label: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO DMIU (DIGITAL MEDIA INVESTIGATION UNIT)',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO (ENTER REASON IN COMMENT)',
          label: 'NO (ENTER REASON IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65198',
        },
        {
          code: 'YES (ENTER DATE AND COMMENT WITH BAG NUMBER)',
          label: 'YES (ENTER DATE AND COMMENT WITH BAG NUMBER)',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '65198',
        },
      ],
    },
    '65198': {
      id: '65198',
      code: 'WAS A PHONE CHARGER FOUND?',
      label: 'WAS A PHONE CHARGER FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65199',
        },
        {
          code: 'YES - HOMEMADE/ADAPTED',
          label: 'YES - HOMEMADE/ADAPTED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65199',
        },
        {
          code: 'YES - FACTORY MADE/MANUFACTURED',
          label: 'YES - FACTORY MADE/MANUFACTURED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65199',
        },
      ],
    },
    '65199': {
      id: '65199',
      code: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      label: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES (PLEASE SPECIFY IN COMMENTS)',
          label: 'YES (PLEASE SPECIFY IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65200': {
      id: '65200',
      code: 'OTHER DIGITAL FIND (PLEASE STATE MAKE/MODEL WHERE KNOWN)',
      label: 'OTHER DIGITAL FIND (PLEASE STATE MAKE/MODEL WHERE KNOWN)',
      multipleAnswers: false,
      answers: [
        {
          code: 'DESKTOP',
          label: 'DESKTOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'DVD PLAYER',
          label: 'DVD PLAYER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'EXTERNAL STORAGE, E.G. EXTERNAL HARD DRIVE',
          label: 'EXTERNAL STORAGE, E.G. EXTERNAL HARD DRIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'GAMES CONSOLE',
          label: 'GAMES CONSOLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'LAPTOP',
          label: 'LAPTOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'MEDIA STREAMING DEVICE, E.G. KINDLE FIRE STICK',
          label: 'MEDIA STREAMING DEVICE, E.G. KINDLE FIRE STICK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'MOBILE HOT SPOT (MIFI DIVICE)',
          label: 'MOBILE HOT SPOT (MIFI DIVICE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'SMART WATCH',
          label: 'SMART WATCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'STEREO / RADIO',
          label: 'STEREO / RADIO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'TABLET, E.G. IPAD',
          label: 'TABLET, E.G. IPAD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'USB MEMORY STICK',
          label: 'USB MEMORY STICK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'WIRELESS HEADSET, E.G. APPLE AIRPODS',
          label: 'WIRELESS HEADSET, E.G. APPLE AIRPODS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'OTHER (PLEASE STATE IN COMMENTS)',
          label: 'OTHER (PLEASE STATE IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65201': {
      id: '65201',
      code: 'DESCRIBE THE TOBACCO FOUND',
      label: 'DESCRIBE THE TOBACCO FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'CIGARETTES/CIGARS',
          label: 'CIGARETTES/CIGARS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65202',
        },
        {
          code: 'LOOSE TOBACCO',
          label: 'LOOSE TOBACCO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65202',
        },
        {
          code: 'OTHER - INCLUDING PACKAGING AND ROACHES (PLEASE STATE IN COMMENTS)',
          label: 'OTHER - INCLUDING PACKAGING AND ROACHES (PLEASE STATE IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65202',
        },
      ],
    },
    '65202': {
      id: '65202',
      code: 'APPROX WEIGHT OF TOBACCO',
      label: 'APPROX WEIGHT OF TOBACCO',
      multipleAnswers: false,
      answers: [
        {
          code: 'N/A',
          label: 'N/A',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'LESS THAN OR EQUAL TO 1G (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'LESS THAN OR EQUAL TO 1G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: '2G TO 5G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '2G TO 5G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: '6G TO 10G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '6G TO 10G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: '11G TO 20G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '11G TO 20G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'GREATER THAN 20G (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'GREATER THAN 20G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65203': {
      id: '65203',
      code: 'WAS A WEAPON FOUND?',
      label: 'WAS A WEAPON FOUND?',
      multipleAnswers: true,
      answers: [
        {
          code: 'YES - BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC)',
          label: 'YES - BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES- FIREARM (FAKE GUNS, AMMUNITION, CHEMICAL INCAPACITANT ETC)',
          label: 'YES- FIREARM (FAKE GUNS, AMMUNITION, CHEMICAL INCAPACITANT ETC)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES - KNIFE/BLADED ARTICLE',
          label: 'YES - KNIFE/BLADED ARTICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES - OTHER (PLEASE SPECIFY)',
          label: 'YES - OTHER (PLEASE SPECIFY)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65204': {
      id: '65204',
      code: 'WERE ANY OTHER REPORTABLE ITEMS FOUND (BY NATIONAL OR LOCAL POLICY)?',
      label: 'WERE ANY OTHER REPORTABLE ITEMS FOUND (BY NATIONAL OR LOCAL POLICY)?',
      multipleAnswers: true,
      answers: [
        {
          code: 'YES (NOOSE / LIGATURE)',
          label: 'YES (NOOSE / LIGATURE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES (PLEASE SPECIFY IN COMMENTS)',
          label: 'YES (PLEASE SPECIFY IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65205': {
      id: '65205',
      code: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND',
      label: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NIL',
          label: 'NIL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: 'LESS THAN 1 LITRE (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'LESS THAN 1 LITRE (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: '1 LITRE TO LESS THAN 2 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '1 LITRE TO LESS THAN 2 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: '2 LITRES TO LESS THAN 3 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '2 LITRES TO LESS THAN 3 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: '3 LITRES TO LESS THAN 4 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '3 LITRES TO LESS THAN 4 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: '4 LITRES TO LESS THAN 5 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '4 LITRES TO LESS THAN 5 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: '5 LITRES TO LESS THAN 10 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '5 LITRES TO LESS THAN 10 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: '10 LITRES TO LESS THAN 20 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          label: '10 LITRES TO LESS THAN 20 LITRES (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
        {
          code: '20 LITRES OR MORE (PLEASE STATE NUMBER IN COMMENTS)',
          label: '20 LITRES OR MORE (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65206',
        },
      ],
    },
    '65206': {
      id: '65206',
      code: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      label: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES (Please specify)',
          label: 'YES (Please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65207': {
      id: '65207',
      code: 'WERE ANY DRUGS FOUND?',
      label: 'WERE ANY DRUGS FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65211',
        },
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65208',
        },
      ],
    },
    '65208': {
      id: '65208',
      code: 'DESCRIBE THE DRUG FOUND',
      label: 'DESCRIBE THE DRUG FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'AMPHETAMINES',
          label: 'AMPHETAMINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'BARBITURATES',
          label: 'BARBITURATES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'BENZODIAZEPINES',
          label: 'BENZODIAZEPINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'BUPRENORPHINE/SUBUTEX',
          label: 'BUPRENORPHINE/SUBUTEX',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'CANNABIS',
          label: 'CANNABIS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'CANNABIS PLANT',
          label: 'CANNABIS PLANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'COCAINE',
          label: 'COCAINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'CRACK',
          label: 'CRACK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'GABAPENTIN',
          label: 'GABAPENTIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'HEROIN',
          label: 'HEROIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'KETAMINE',
          label: 'KETAMINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'LSD',
          label: 'LSD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'METHADONE',
          label: 'METHADONE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'NPS (NEW PSYCHOACTIVE SUBSTANCES)',
          label: 'NPS (NEW PSYCHOACTIVE SUBSTANCES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'PREGABALIN',
          label: 'PREGABALIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'STEROIDS',
          label: 'STEROIDS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'TRAMADOL',
          label: 'TRAMADOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'TRANQUILISERS',
          label: 'TRANQUILISERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65209',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65209',
        },
      ],
    },
    '65209': {
      id: '65209',
      code: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND',
      label: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: 'LESS THAN OR EQUAL TO 1G (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'LESS THAN OR EQUAL TO 1G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '2G TO 5G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '2G TO 5G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '6G TO 10G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '6G TO 10G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '11G TO 20G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '11G TO 20G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '21G TO 30G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '21G TO 30G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '31G TO 40G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '31G TO 40G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '41G TO 50G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '41G TO 50G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '50G TO 100G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '50G TO 100G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '101G TO 200G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '101G TO 200G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '201G TO 300G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '201G TO 300G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '301G TO 400G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '301G TO 400G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '401G TO 500G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '401G TO 500G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: '501G TO 1,000G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '501G TO 1,000G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
        {
          code: 'MORE THAN 1KG (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'MORE THAN 1KG (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65210',
        },
      ],
    },
    '65210': {
      id: '65210',
      code: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      label: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65211',
        },
        {
          code: 'YES - FORENSIC LABORATORY',
          label: 'YES - FORENSIC LABORATORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65211',
        },
        {
          code: 'YES - LOCAL WITH BDH KIT OR SIMILAR',
          label: 'YES - LOCAL WITH BDH KIT OR SIMILAR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65211',
        },
      ],
    },
    '65211': {
      id: '65211',
      code: 'WAS DRUG EQUIPMENT FOUND',
      label: 'WAS DRUG EQUIPMENT FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65213',
        },
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65212',
        },
      ],
    },
    '65212': {
      id: '65212',
      code: 'DESCRIBE DRUG EQUIPMENT FOUND',
      label: 'DESCRIBE DRUG EQUIPMENT FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'AUTHENTIC NEEDLE',
          label: 'AUTHENTIC NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65213',
        },
        {
          code: 'AUTHENTIC SYRINGE',
          label: 'AUTHENTIC SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65213',
        },
        {
          code: 'IMPROVISED NEEDLE',
          label: 'IMPROVISED NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65213',
        },
        {
          code: 'IMPROVISED SYRINGE',
          label: 'IMPROVISED SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65213',
        },
        {
          code: 'PIPE(S)',
          label: 'PIPE(S)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65213',
        },
        {
          code: 'ROACH',
          label: 'ROACH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65213',
        },
        {
          code: 'OTHER (PLEASE SPECIFY)',
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65213',
        },
      ],
    },
    '65213': {
      id: '65213',
      code: 'WERE MOBILE PHONE / MOBILE PHONE RELATED ITEMS FOUND',
      label: 'WERE MOBILE PHONE / MOBILE PHONE RELATED ITEMS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65220',
        },
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65214',
        },
      ],
    },
    '65214': {
      id: '65214',
      code: 'ENTER NUMBER OF MOBILES FOUND',
      label: 'ENTER NUMBER OF MOBILES FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO MOBILE PHONE FOUND',
          label: 'NO MOBILE PHONE FOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          label: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65215',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65215',
        },
      ],
    },
    '65215': {
      id: '65215',
      code: 'ENTER NUMBER OF SIM CARDS FOUND',
      label: 'ENTER NUMBER OF SIM CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO SIM CARDS FOUND',
          label: 'NO SIM CARDS FOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          label: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65216',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65216',
        },
      ],
    },
    '65216': {
      id: '65216',
      code: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      label: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO MEMORY CARD FOUND',
          label: 'NO MEMORY CARD FOUND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '1',
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '2',
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '3',
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '4',
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '5',
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '6',
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '7',
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '8',
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '9',
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '10',
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '11',
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '12',
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '13',
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '14',
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '15',
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '16',
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '17',
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '18',
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '19',
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: '20',
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          label: 'MORE THAN 20 (STATE NUMBER IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65217',
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65217',
        },
      ],
    },
    '65217': {
      id: '65217',
      code: 'WAS A PHONE CHARGER FOUND?',
      label: 'WAS A PHONE CHARGER FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65218',
        },
        {
          code: 'YES - HOMEMADE/ADAPTED',
          label: 'YES - HOMEMADE/ADAPTED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65218',
        },
        {
          code: 'YES - FACTORY MADE/MANUFACTURED',
          label: 'YES - FACTORY MADE/MANUFACTURED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65218',
        },
      ],
    },
    '65218': {
      id: '65218',
      code: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      label: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65219',
        },
        {
          code: 'YES: PLEASE SPECIFY',
          label: 'YES: PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65219',
        },
      ],
    },
    '65219': {
      id: '65219',
      code: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO DMIU (DIGITAL MEDIA INVESTIGATION UNIT)',
      label: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO DMIU (DIGITAL MEDIA INVESTIGATION UNIT)',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO (ENTER REASON IN COMMENT)',
          label: 'NO (ENTER REASON IN COMMENT)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65220',
        },
        {
          code: 'YES (ENTER DATE AND COMMENT WITH BAG NUMBER)',
          label: 'YES (ENTER DATE AND COMMENT WITH BAG NUMBER)',
          commentRequired: true,
          dateRequired: true,
          nextQuestionId: '65220',
        },
      ],
    },
    '65220': {
      id: '65220',
      code: 'OTHER DIGITAL FIND (PLEASE STATE MAKE/MODEL WHERE KNOWN)',
      label: 'OTHER DIGITAL FIND (PLEASE STATE MAKE/MODEL WHERE KNOWN)',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO OTHER DIGITAL FINDS',
          label: 'NO OTHER DIGITAL FINDS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'DESKTOP',
          label: 'DESKTOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'DVD PLAYER',
          label: 'DVD PLAYER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'EXTERNAL STORAGE, E.G. EXTERNAL HARD DRIVE',
          label: 'EXTERNAL STORAGE, E.G. EXTERNAL HARD DRIVE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'GAMES CONSOLE',
          label: 'GAMES CONSOLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'LAPTOP',
          label: 'LAPTOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'MEDIA STREAMING DEVICE, E.G. KINDLE FIRE STICK',
          label: 'MEDIA STREAMING DEVICE, E.G. KINDLE FIRE STICK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'MOBILE HOT SPOT (MIFI DIVICE)',
          label: 'MOBILE HOT SPOT (MIFI DIVICE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'SMART WATCH',
          label: 'SMART WATCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'STEREO / RADIO',
          label: 'STEREO / RADIO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'TABLET, E.G. IPAD',
          label: 'TABLET, E.G. IPAD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'USB MEMORY STICK',
          label: 'USB MEMORY STICK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'WIRELESS HEADSET, E.G. APPLE AIRPODS',
          label: 'WIRELESS HEADSET, E.G. APPLE AIRPODS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65221',
        },
        {
          code: 'OTHER (PLEASE STATE)',
          label: 'OTHER (PLEASE STATE)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65221',
        },
      ],
    },
    '65221': {
      id: '65221',
      code: 'WAS TOBACCO / TOBACCO RELATED ITEMS FOUND',
      label: 'WAS TOBACCO / TOBACCO RELATED ITEMS FOUND',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65224',
        },
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65222',
        },
      ],
    },
    '65222': {
      id: '65222',
      code: 'DESCRIBE THE TOBACCO FOUND',
      label: 'DESCRIBE THE TOBACCO FOUND',
      multipleAnswers: true,
      answers: [
        {
          code: 'CIGARETTES/CIGARS',
          label: 'CIGARETTES/CIGARS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65223',
        },
        {
          code: 'LOOSE TOBACCO',
          label: 'LOOSE TOBACCO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65223',
        },
        {
          code: 'OTHER (including packaging and roaches)',
          label: 'OTHER (including packaging and roaches)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65223',
        },
      ],
    },
    '65223': {
      id: '65223',
      code: 'APPROX WEIGHT OF TOBACCO',
      label: 'APPROX WEIGHT OF TOBACCO',
      multipleAnswers: false,
      answers: [
        {
          code: 'LESS THAN OR EQUAL TO 1G (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'LESS THAN OR EQUAL TO 1G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65224',
        },
        {
          code: '2G TO 5G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '2G TO 5G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65224',
        },
        {
          code: '6G TO 10G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '6G TO 10G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65224',
        },
        {
          code: '11G TO 20G (PLEASE STATE NUMBER IN COMMENTS)',
          label: '11G TO 20G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65224',
        },
        {
          code: 'GREATER THAN 20G (PLEASE STATE NUMBER IN COMMENTS)',
          label: 'GREATER THAN 20G (PLEASE STATE NUMBER IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65224',
        },
      ],
    },
    '65224': {
      id: '65224',
      code: 'WAS A WEAPON FOUND?',
      label: 'WAS A WEAPON FOUND?',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65225',
        },
        {
          code: 'YES - BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC)',
          label: 'YES - BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65225',
        },
        {
          code: 'YES- FIREARM (FAKE GUNS, AMMUNITION, CHEMICAL INCAPACITANT ETC)',
          label: 'YES- FIREARM (FAKE GUNS, AMMUNITION, CHEMICAL INCAPACITANT ETC)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65225',
        },
        {
          code: 'YES - KNIFE/BLADED ARTICLE',
          label: 'YES - KNIFE/BLADED ARTICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65225',
        },
        {
          code: 'YES - OTHER (PLEASE SPECIFY)',
          label: 'YES - OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65225',
        },
      ],
    },
    '65225': {
      id: '65225',
      code: 'WERE ANY OTHER REPORTABLE ITEMS FOUND (BY NATIONAL OR LOCAL POLICY)',
      label: 'WERE ANY OTHER REPORTABLE ITEMS FOUND (BY NATIONAL OR LOCAL POLICY)',
      multipleAnswers: true,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES (NOOSE / LIGATURE)',
          label: 'YES (NOOSE / LIGATURE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65226',
        },
        {
          code: 'YES (PLEASE SPECIFY IN COMMENTS)',
          label: 'YES (PLEASE SPECIFY IN COMMENTS)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '65226',
        },
      ],
    },
    '65226': {
      id: '65226',
      code: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      label: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      multipleAnswers: false,
      answers: [
        {
          code: 'NO',
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'YES',
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '65227',
        },
      ],
    },
    '65227': {
      id: '65227',
      code: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      label: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      multipleAnswers: true,
      answers: [
        {
          code: 'COMMUNITY VISIT',
          label: 'COMMUNITY VISIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'COMPASSIONATE',
          label: 'COMPASSIONATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'FACILITY',
          label: 'FACILITY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'RESETTLEMENT',
          label: 'RESETTLEMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          code: 'UNKNOWN',
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default OLD_FINDS3
