// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-12-02T17:35:29.948Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const OLD_FINDS4: IncidentTypeConfiguration = {
  incidentType: 'OLD_FINDS4',
  active: false,
  startingQuestionId: '57284',
  questions: {
    '57284': {
      id: '57284',
      active: false,
      code: 'WHAT WAS THE MAIN MANAGEMENT OUTCOME OF THIS INCIDENT?',
      label: 'What was the main management outcome of this incident?',
      multipleAnswers: true,
      answers: [
        {
          id: '209109',
          code: 'NO FURTHER ACTION',
          active: true,
          label: 'NO FURTHER ACTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          id: '209110',
          code: 'IEP REGRESSION',
          active: true,
          label: 'IEP REGRESSION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          id: '209111',
          code: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          active: true,
          label: 'PLACED ON REPORT/ADJUDICATION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          id: '209112',
          code: 'POLICE REFERRAL',
          active: true,
          label: 'POLICE REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          id: '209113',
          code: 'CPS REFRRAL',
          active: false,
          label: 'CPS REFRRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
        {
          id: '209114',
          code: 'PROSECUTION REFERRAL',
          active: true,
          label: 'PROSECUTION REFERRAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57285',
        },
      ],
    },
    '57285': {
      id: '57285',
      active: true,
      code: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES?',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          id: '209115',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57286',
        },
        {
          id: '209116',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57286',
        },
      ],
    },
    '57286': {
      id: '57286',
      active: true,
      code: 'IS THE LOCATION OF THE INCIDENT KNOWN?',
      label: 'Is the location of the incident known?',
      multipleAnswers: false,
      answers: [
        {
          id: '209117',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57287',
        },
        {
          id: '209118',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
      ],
    },
    '57287': {
      id: '57287',
      active: true,
      code: 'WHAT WAS THE LOCATION OF THE INCIDENT?',
      label: 'What was the location of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '209119',
          code: 'ADMINISTRATION',
          active: true,
          label: 'ADMINISTRATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209120',
          code: 'ASSOCIATION AREA',
          active: true,
          label: 'ASSOCIATION AREA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209121',
          code: 'CELL',
          active: true,
          label: 'CELL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209122',
          code: 'CHAPEL',
          active: true,
          label: 'CHAPEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209123',
          code: 'CROWN COURT',
          active: true,
          label: 'CROWN COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209124',
          code: 'DINING ROOM',
          active: true,
          label: 'DINING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209125',
          code: 'DORMITORY',
          active: true,
          label: 'DORMITORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209126',
          code: 'EDUCATION',
          active: true,
          label: 'EDUCATION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209127',
          code: 'ELSEWHERE',
          active: true,
          label: 'ELSEWHERE',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209128',
          code: 'EXERCISE YARD',
          active: true,
          label: 'EXERCISE YARD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209129',
          code: 'FUNERAL',
          active: true,
          label: 'FUNERAL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209130',
          code: 'GATE',
          active: true,
          label: 'GATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209131',
          code: 'GYM',
          active: true,
          label: 'GYM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209132',
          code: 'HEALTH CARE CENTRE',
          active: true,
          label: 'HEALTH CARE CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209133',
          code: 'HOSPITAL OUTSIDE (PATIENT)',
          active: true,
          label: 'HOSPITAL OUTSIDE (PATIENT)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209134',
          code: 'HOSPITAL OUTSIDE (VISITING)',
          active: true,
          label: 'HOSPITAL OUTSIDE (VISITING)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209135',
          code: 'KITCHEN',
          active: true,
          label: 'KITCHEN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209136',
          code: 'MAGISTRATES COURT',
          active: true,
          label: 'MAGISTRATES COURT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209137',
          code: 'OFFICE',
          active: true,
          label: 'OFFICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209138',
          code: 'OUTSIDE WORKING PARTY',
          active: true,
          label: 'OUTSIDE WORKING PARTY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209139',
          code: 'RECEPTION',
          active: true,
          label: 'RECEPTION',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209140',
          code: 'RECESS',
          active: true,
          label: 'RECESS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209141',
          code: 'SEGREGATION UNIT',
          active: true,
          label: 'SEGREGATION UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209142',
          code: 'SHOWERS/CHANGING ROOM',
          active: true,
          label: 'SHOWERS/CHANGING ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209143',
          code: 'SPECIAL UNIT',
          active: true,
          label: 'SPECIAL UNIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209144',
          code: 'SPORTS FIELD',
          active: true,
          label: 'SPORTS FIELD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209145',
          code: 'VEHICLE',
          active: true,
          label: 'VEHICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209146',
          code: 'VISITS',
          active: true,
          label: 'VISITS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209147',
          code: 'WEDDINGS',
          active: true,
          label: 'WEDDINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209148',
          code: 'WING',
          active: true,
          label: 'WING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209149',
          code: 'WITHIN PERIMETER',
          active: true,
          label: 'WITHIN PERIMETER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209150',
          code: 'WORKS DEPARTMENT',
          active: true,
          label: 'WORKS DEPARTMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209151',
          code: 'WORKSHOP',
          active: true,
          label: 'WORKSHOP',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209152',
          code: 'INDUCTION/1ST NIGHT CENTRE',
          active: true,
          label: 'INDUCTION/1ST NIGHT CENTRE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209153',
          code: 'MAIL ROOM',
          active: true,
          label: 'MAIL ROOM',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209154',
          code: 'EXTERNAL ROOF',
          active: true,
          label: 'EXTERNAL ROOF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
        {
          id: '209155',
          code: 'VULNERABLE PRISONERS UNIT (VPU)',
          active: true,
          label: 'VULNERABLE PRISONERS UNIT (VPU)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57288',
        },
      ],
    },
    '57288': {
      id: '57288',
      active: true,
      code: 'WAS A DRUG FOUND?',
      label: 'Was a drug found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209156',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57289',
        },
        {
          id: '209157',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57294',
        },
      ],
    },
    '57289': {
      id: '57289',
      active: true,
      code: 'DESCRIBE THE DRUG FOUND',
      label: 'Describe the drug found',
      multipleAnswers: true,
      answers: [
        {
          id: '209158',
          code: 'AMPHETAMINES',
          active: true,
          label: 'AMPHETAMINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209159',
          code: 'BARBITURATES',
          active: true,
          label: 'BARBITURATES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209160',
          code: 'BENZODIAZEPINES',
          active: true,
          label: 'BENZODIAZEPINES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209161',
          code: 'BUPRENORPHINE/SUBUTEX',
          active: true,
          label: 'BUPRENORPHINE/SUBUTEX',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209162',
          code: 'CANNABIS',
          active: true,
          label: 'CANNABIS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209163',
          code: 'CANNABIS PLANT',
          active: true,
          label: 'CANNABIS PLANT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209164',
          code: 'COCAINE',
          active: true,
          label: 'COCAINE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209165',
          code: 'CRACK',
          active: true,
          label: 'CRACK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209166',
          code: 'HEROIN',
          active: true,
          label: 'HEROIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209167',
          code: 'LSD',
          active: true,
          label: 'LSD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209168',
          code: 'METHADONE',
          active: true,
          label: 'METHADONE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209169',
          code: 'PREGABALIN',
          active: true,
          label: 'PREGABALIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209170',
          code: 'TRANQUILISERS',
          active: true,
          label: 'TRANQUILISERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209171',
          code: 'TRAMADOL',
          active: true,
          label: 'TRAMADOL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209172',
          code: 'GABAPENTIN',
          active: true,
          label: 'GABAPENTIN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209173',
          code: 'NPS: SPICE',
          active: true,
          label: 'NPS: SPICE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209174',
          code: 'NPS: BLACK MAMBA',
          active: true,
          label: 'NPS: BLACK MAMBA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209175',
          code: 'NPS: OTHER',
          active: true,
          label: 'NPS: OTHER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209176',
          code: 'STEROIDS',
          active: true,
          label: 'STEROIDS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209177',
          code: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57290',
        },
        {
          id: '209178',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57290',
        },
      ],
    },
    '57290': {
      id: '57290',
      active: true,
      code: 'WHAT WAS THE ESTIMATED WEIGHT OF ALL DRUGS/SUBSTANCES FOUND?',
      label: 'What was the estimated weight of all drugs/substances found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209179',
          code: '<1g',
          active: true,
          label: '<1g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209180',
          code: '2g to 5g',
          active: true,
          label: '2g to 5g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209181',
          code: '6g to 10g',
          active: true,
          label: '6g to 10g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209182',
          code: '11g to 20g',
          active: true,
          label: '11g to 20g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209183',
          code: '21g to 30g',
          active: true,
          label: '21g to 30g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209184',
          code: '31g to 40g',
          active: true,
          label: '31g to 40g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209185',
          code: '41g to 50g',
          active: true,
          label: '41g to 50g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209186',
          code: '51g to 100g',
          active: true,
          label: '51g to 100g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209187',
          code: '101g to 200g',
          active: true,
          label: '101g to 200g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209188',
          code: '201g to 300g',
          active: true,
          label: '201g to 300g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209189',
          code: '301g to 400g',
          active: true,
          label: '301g to 400g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209190',
          code: '401g to 500g',
          active: true,
          label: '401g to 500g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209191',
          code: '501g to 1,000g',
          active: true,
          label: '501g to 1,000g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209192',
          code: 'More than 1kg',
          active: true,
          label: 'More than 1kg',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
        {
          id: '209193',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57291',
        },
      ],
    },
    '57291': {
      id: '57291',
      active: true,
      code: 'WAS THE SUBSTANCE FOUND ANALYSED?',
      label: 'Was the substance found analysed?',
      multipleAnswers: false,
      answers: [
        {
          id: '209194',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57292',
        },
        {
          id: '209195',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57293',
        },
      ],
    },
    '57292': {
      id: '57292',
      active: true,
      code: 'HOW WAS THE SUBSTANCE ANALYSED?',
      label: 'How was the substance analysed?',
      multipleAnswers: false,
      answers: [
        {
          id: '209196',
          code: 'FORENSIC LABORATORY',
          active: true,
          label: 'FORENSIC LABORATORY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57293',
        },
        {
          id: '209197',
          code: 'LOCAL WITH BDH KIT OR SIMILAR',
          active: true,
          label: 'LOCAL WITH BDH KIT OR SIMILAR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57293',
        },
      ],
    },
    '57293': {
      id: '57293',
      active: true,
      code: 'TO WHICH POLICE STATION WERE SEIZED DRUGS SENT FOR DESTRUCTION?',
      label: 'To which police station were seized drugs sent for destruction?',
      multipleAnswers: false,
      answers: [
        {
          id: '209198',
          code: 'NAME',
          active: true,
          label: 'NAME',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57294',
        },
      ],
    },
    '57294': {
      id: '57294',
      active: true,
      code: 'WAS DRUG EQUIPMENT FOUND?',
      label: 'Was drug equipment found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209199',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57295',
        },
        {
          id: '209200',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
      ],
    },
    '57295': {
      id: '57295',
      active: true,
      code: 'DESCRIBE DRUG EQUIPMENT FOUND',
      label: 'Describe drug equipment found',
      multipleAnswers: true,
      answers: [
        {
          id: '209201',
          code: 'AUTHENTIC NEEDLE',
          active: true,
          label: 'AUTHENTIC NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          id: '209202',
          code: 'AUTHENTIC SYRINGE',
          active: true,
          label: 'AUTHENTIC SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          id: '209203',
          code: 'IMPROVISED NEEDLE',
          active: true,
          label: 'IMPROVISED NEEDLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          id: '209204',
          code: 'IMPROVISED SYRINGE',
          active: true,
          label: 'IMPROVISED SYRINGE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          id: '209205',
          code: 'PIPE(S)',
          active: true,
          label: 'PIPE(S)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          id: '209206',
          code: 'ROACH',
          active: true,
          label: 'ROACH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57296',
        },
        {
          id: '209207',
          code: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57296',
        },
      ],
    },
    '57296': {
      id: '57296',
      active: true,
      code: 'WAS A MOBILE PHONE RELATED ITEM FOUND?',
      label: 'Was a mobile phone related item found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209208',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57297',
        },
        {
          id: '209209',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57307',
        },
      ],
    },
    '57297': {
      id: '57297',
      active: true,
      code: 'WAS A MOBILE PHONE FOUND?',
      label: 'Was a mobile phone found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209210',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57298',
        },
        {
          id: '209211',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
      ],
    },
    '57298': {
      id: '57298',
      active: true,
      code: 'ENTER NUMBER OF MOBILES FOUND',
      label: 'Enter number of mobiles found',
      multipleAnswers: false,
      answers: [
        {
          id: '209212',
          code: '1',
          active: true,
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209213',
          code: '2',
          active: true,
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209214',
          code: '3',
          active: true,
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209215',
          code: '4',
          active: true,
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209216',
          code: '5',
          active: true,
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209217',
          code: '6',
          active: true,
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209218',
          code: '7',
          active: true,
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209219',
          code: '8',
          active: true,
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209220',
          code: '9',
          active: true,
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209221',
          code: '10',
          active: true,
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209222',
          code: '11',
          active: true,
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209223',
          code: '12',
          active: true,
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209224',
          code: '13',
          active: true,
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209225',
          code: '14',
          active: true,
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209226',
          code: '15',
          active: true,
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209227',
          code: '16',
          active: true,
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209228',
          code: '17',
          active: true,
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209229',
          code: '18',
          active: true,
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209230',
          code: '19',
          active: true,
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209231',
          code: '20',
          active: true,
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209232',
          code: 'MORE THAN 20',
          active: true,
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
        {
          id: '209233',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57299',
        },
      ],
    },
    '57299': {
      id: '57299',
      active: true,
      code: 'WAS A SIM CARD FOUND?',
      label: 'Was a SIM card found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209234',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57300',
        },
        {
          id: '209235',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
      ],
    },
    '57300': {
      id: '57300',
      active: true,
      code: 'ENTER NUMBER OF SIM CARDS FOUND',
      label: 'Enter number of SIM cards found',
      multipleAnswers: false,
      answers: [
        {
          id: '209236',
          code: '1',
          active: true,
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209237',
          code: '2',
          active: true,
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209238',
          code: '3',
          active: true,
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209239',
          code: '4',
          active: true,
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209240',
          code: '5',
          active: true,
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209241',
          code: '6',
          active: true,
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209242',
          code: '7',
          active: true,
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209243',
          code: '8',
          active: true,
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209244',
          code: '9',
          active: true,
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209245',
          code: '10',
          active: true,
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209246',
          code: '11',
          active: true,
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209247',
          code: '12',
          active: true,
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209248',
          code: '13',
          active: true,
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209249',
          code: '14',
          active: true,
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209250',
          code: '15',
          active: true,
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209251',
          code: '16',
          active: true,
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209252',
          code: '17',
          active: true,
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209253',
          code: '18',
          active: true,
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209254',
          code: '19',
          active: true,
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209255',
          code: '20',
          active: true,
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209256',
          code: 'MORE THAN 20',
          active: true,
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
        {
          id: '209257',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57301',
        },
      ],
    },
    '57301': {
      id: '57301',
      active: true,
      code: ' WAS A MEMORY CARD FOUND?',
      label: 'Was a memory card found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209258',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57302',
        },
        {
          id: '209259',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
      ],
    },
    '57302': {
      id: '57302',
      active: true,
      code: 'ENTER NUMBER OF MEMORY CARDS FOUND',
      label: 'Enter number of memory cards found',
      multipleAnswers: false,
      answers: [
        {
          id: '209260',
          code: '1',
          active: true,
          label: '1',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209261',
          code: '2',
          active: true,
          label: '2',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209262',
          code: '3',
          active: true,
          label: '3',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209263',
          code: '4',
          active: true,
          label: '4',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209264',
          code: '5',
          active: true,
          label: '5',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209265',
          code: '6',
          active: true,
          label: '6',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209266',
          code: '7',
          active: true,
          label: '7',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209267',
          code: '8',
          active: true,
          label: '8',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209268',
          code: '9',
          active: true,
          label: '9',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209269',
          code: '10',
          active: true,
          label: '10',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209270',
          code: '11',
          active: true,
          label: '11',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209271',
          code: '12',
          active: true,
          label: '12',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209272',
          code: '13',
          active: true,
          label: '13',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209273',
          code: '14',
          active: true,
          label: '14',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209274',
          code: '15',
          active: true,
          label: '15',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209275',
          code: '16',
          active: true,
          label: '16',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209276',
          code: '17',
          active: true,
          label: '17',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209277',
          code: '18',
          active: true,
          label: '18',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209278',
          code: '19',
          active: true,
          label: '19',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209279',
          code: '20',
          active: true,
          label: '20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209280',
          code: 'MORE THAN 20',
          active: true,
          label: 'MORE THAN 20',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
        {
          id: '209281',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57303',
        },
      ],
    },
    '57303': {
      id: '57303',
      active: true,
      code: 'WAS A CHARGER FOUND?',
      label: 'Was a charger found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209282',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57304',
        },
        {
          id: '209283',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57304',
        },
      ],
    },
    '57304': {
      id: '57304',
      active: true,
      code: 'WAS ANY OTHER MOBILE PHONE/COMMUNICATION RELATED ITEM FOUND?',
      label: 'Was any other mobile phone/communication related item found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209284',
          code: 'YES (PLEASE SPECIFY)',
          active: true,
          label: 'YES (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57305',
        },
        {
          id: '209285',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57305',
        },
      ],
    },
    '57305': {
      id: '57305',
      active: true,
      code: 'HAS PHONE/SIM/MEMORY CARD BEEN SENT TO NDTSG?',
      label: 'Has phone/sim/memory card been sent to NDTSG?',
      multipleAnswers: true,
      answers: [
        {
          id: '209286',
          code: 'YES (PLEASE ENTER DATE)',
          active: true,
          label: 'YES (PLEASE ENTER DATE)',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '57306',
        },
        {
          id: '209287',
          code: 'EVIDENCE BAG (PLEASE ENTER BAG NUMBER)',
          active: true,
          label: 'EVIDENCE BAG (PLEASE ENTER BAG NUMBER)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57306',
        },
        {
          id: '209288',
          code: 'NO (PLEASE STATE WHY)',
          active: true,
          label: 'NO (PLEASE STATE WHY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57306',
        },
      ],
    },
    '57306': {
      id: '57306',
      active: true,
      code: 'HAS PHONE/SIM/EQUIPMENT BEEN RETAINED BY POLICE?',
      label: 'Has phone/sim/equipment been retained by police?',
      multipleAnswers: false,
      answers: [
        {
          id: '209289',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57307',
        },
        {
          id: '209290',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57307',
        },
      ],
    },
    '57307': {
      id: '57307',
      active: true,
      code: 'WAS A WEAPON FOUND?',
      label: 'Was a weapon found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209291',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57308',
        },
        {
          id: '209292',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
      ],
    },
    '57308': {
      id: '57308',
      active: true,
      code: 'DESCRIBE THE WEAPON',
      label: 'Describe the weapon',
      multipleAnswers: true,
      answers: [
        {
          id: '209293',
          code: 'BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC.)',
          active: true,
          label: 'BLUNT INSTRUMENT (COSH, ITEM IN SOCK ETC.)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
        {
          id: '209294',
          code: 'KNIFE/BLADED ARTICLE',
          active: true,
          label: 'KNIFE/BLADED ARTICLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
        {
          id: '209295',
          code: 'FIREARM (FAKE GUNS, AMMUNITION, CHEMIICAL INCAPACITANT ETC.)',
          active: true,
          label: 'FIREARM (FAKE GUNS, AMMUNITION, CHEMIICAL INCAPACITANT ETC.)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57309',
        },
        {
          id: '209296',
          code: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57309',
        },
      ],
    },
    '57309': {
      id: '57309',
      active: true,
      code: 'WAS ANY ALCOHOL/HOOCH FOUND?',
      label: 'Was any alcohol/hooch found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209297',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57310',
        },
        {
          id: '209298',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
      ],
    },
    '57310': {
      id: '57310',
      active: true,
      code: 'WHAT QUANTITY OF ALCOHOL/HOOCH WAS FOUND?',
      label: 'What quantity of alcohol/hooch was found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209299',
          code: '< 1 litre',
          active: true,
          label: '< 1 litre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209300',
          code: '1 to 2 litres',
          active: true,
          label: '1 to 2 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209301',
          code: '2 to 3 litres',
          active: true,
          label: '2 to 3 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209302',
          code: '3 to 4 litres',
          active: true,
          label: '3 to 4 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209303',
          code: ' 4 to 5 litres',
          active: true,
          label: ' 4 to 5 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209304',
          code: '6 to 10 litres',
          active: true,
          label: '6 to 10 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209305',
          code: '11 to 20 litres',
          active: true,
          label: '11 to 20 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209306',
          code: 'More than 20 litres',
          active: true,
          label: 'More than 20 litres',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
        {
          id: '209307',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57311',
        },
      ],
    },
    '57311': {
      id: '57311',
      active: true,
      code: 'WAS ANY DISTILLING EQUIPMENT FOUND?',
      label: 'Was any distilling equipment found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209308',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57312',
        },
        {
          id: '209309',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57312',
        },
      ],
    },
    '57312': {
      id: '57312',
      active: true,
      code: 'WAS ANY TOBACCO FOUND?',
      label: 'Was any tobacco found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209310',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57313',
        },
        {
          id: '209311',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
      ],
    },
    '57313': {
      id: '57313',
      active: true,
      code: 'DESCRIBE THE TOBACCO FOUND',
      label: 'Describe the tobacco found',
      multipleAnswers: true,
      answers: [
        {
          id: '209312',
          code: 'LOOSE TOBACCO',
          active: true,
          label: 'LOOSE TOBACCO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57314',
        },
        {
          id: '209313',
          code: 'CIGARETTES/CIGARS',
          active: true,
          label: 'CIGARETTES/CIGARS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57314',
        },
        {
          id: '209314',
          code: 'OTHER (INC PACKAGING AND ROACHES)',
          active: true,
          label: 'OTHER (INC PACKAGING AND ROACHES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57314',
        },
      ],
    },
    '57314': {
      id: '57314',
      active: true,
      code: 'APPROX WEIGHT OF TOBACCO?',
      label: 'Approx weight of tobacco?',
      multipleAnswers: false,
      answers: [
        {
          id: '209315',
          code: '<1g',
          active: true,
          label: '<1g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
        {
          id: '209316',
          code: '2g to 5g',
          active: true,
          label: '2g to 5g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
        {
          id: '209317',
          code: '6g to 10g',
          active: true,
          label: '6g to 10g',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
        {
          id: '209318',
          code: '10g+',
          active: true,
          label: '10g+',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57315',
        },
      ],
    },
    '57315': {
      id: '57315',
      active: true,
      code: 'WERE ANY OTHER REPORTABLE ITEMS FOUND?',
      label: 'Were any other reportable items found?',
      multipleAnswers: false,
      answers: [
        {
          id: '209319',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57316',
        },
        {
          id: '209320',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57317',
        },
      ],
    },
    '57316': {
      id: '57316',
      active: true,
      code: 'DESCRIBE THE ITEM',
      label: 'Describe the item',
      multipleAnswers: false,
      answers: [
        {
          id: '209321',
          code: 'PLEASE SPECIFY',
          active: true,
          label: 'PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57317',
        },
      ],
    },
    '57317': {
      id: '57317',
      active: true,
      code: 'DESCRIBE HOW THE ITEM WAS FOUND?',
      label: 'Describe how the item was found?',
      multipleAnswers: true,
      answers: [
        {
          id: '209322',
          code: 'BOSS CHAIR',
          active: true,
          label: 'BOSS CHAIR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209323',
          code: 'CELL SEARCH',
          active: true,
          label: 'CELL SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209324',
          code: 'CRIME SCENE',
          active: true,
          label: 'CRIME SCENE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209325',
          code: 'DOG SEARCH',
          active: true,
          label: 'DOG SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209326',
          code: 'DRONE RECOVERY',
          active: true,
          label: 'DRONE RECOVERY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209327',
          code: 'HIGH SENSITIVITY WAND',
          active: true,
          label: 'HIGH SENSITIVITY WAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209328',
          code: 'INFORMATION RECEIVED',
          active: true,
          label: 'INFORMATION RECEIVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209329',
          code: 'INTELLIGENCE LED SEARCH',
          active: true,
          label: 'INTELLIGENCE LED SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209330',
          code: 'ITEM OBSERVED',
          active: true,
          label: 'ITEM OBSERVED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209331',
          code: 'MOBILE PHONE SIGNAL DETECTOR',
          active: true,
          label: 'MOBILE PHONE SIGNAL DETECTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209332',
          code: 'MOBILE PHONE ROD',
          active: true,
          label: 'MOBILE PHONE ROD',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209333',
          code: 'OTHER SEARCH (INMATE)',
          active: true,
          label: 'OTHER SEARCH (INMATE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209334',
          code: 'OTHER SEARCH (PREMISES)',
          active: true,
          label: 'OTHER SEARCH (PREMISES)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209335',
          code: 'OTHER SEARCH (VISITOR)',
          active: true,
          label: 'OTHER SEARCH (VISITOR)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209336',
          code: 'PRE-OCCUPATION SEARCH',
          active: true,
          label: 'PRE-OCCUPATION SEARCH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209337',
          code: 'UNUSUAL BEHAVIOUR',
          active: true,
          label: 'UNUSUAL BEHAVIOUR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57318',
        },
        {
          id: '209338',
          code: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57318',
        },
      ],
    },
    '57318': {
      id: '57318',
      active: true,
      code: 'DESCRIBE THE METHOD OF ENTRY INTO THE ESTABLISHMENT',
      label: 'Describe the method of entry into the establishment',
      multipleAnswers: true,
      answers: [
        {
          id: '209339',
          code: 'PRISONER',
          active: true,
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209340',
          code: 'STAFF',
          active: true,
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209341',
          code: 'VISITOR (FRIEND)',
          active: true,
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209342',
          code: 'VISITOR (OFFICIAL)',
          active: true,
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209343',
          code: 'VISITOR (RELATIVE)',
          active: true,
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209344',
          code: 'CONTRACTOR',
          active: true,
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209345',
          code: 'POST (RULE 39)',
          active: true,
          label: 'POST (RULE 39)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209346',
          code: 'POST (OTHER)',
          active: true,
          label: 'POST (OTHER)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209347',
          code: 'THROWN IN',
          active: true,
          label: 'THROWN IN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209348',
          code: 'DRONE/UAV',
          active: true,
          label: 'DRONE/UAV',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209349',
          code: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57319',
        },
        {
          id: '209350',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57319',
        },
      ],
    },
    '57319': {
      id: '57319',
      active: true,
      code: 'IF FOUND IN POSSESSION, WHOSE WAS IT FOUND IN?',
      label: 'If found in possession, whose was it found in?',
      multipleAnswers: false,
      answers: [
        {
          id: '209351',
          code: 'PRISONER',
          active: true,
          label: 'PRISONER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          id: '209352',
          code: 'STAFF',
          active: true,
          label: 'STAFF',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          id: '209353',
          code: 'VISITOR (FRIEND)',
          active: true,
          label: 'VISITOR (FRIEND)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          id: '209354',
          code: 'VISITOR (OFFICIAL)',
          active: true,
          label: 'VISITOR (OFFICIAL)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          id: '209355',
          code: 'VISITOR (RELATIVE)',
          active: true,
          label: 'VISITOR (RELATIVE)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          id: '209356',
          code: 'CONTRACTOR',
          active: true,
          label: 'CONTRACTOR',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          id: '209357',
          code: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57320',
        },
        {
          id: '209358',
          code: 'NOT APPLICABLE',
          active: true,
          label: 'NOT APPLICABLE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57320',
        },
      ],
    },
    '57320': {
      id: '57320',
      active: true,
      code: 'WHAT WAS THE METHOD OF CONCEALMENT?',
      label: 'What was the method of concealment?',
      multipleAnswers: false,
      answers: [
        {
          id: '209359',
          code: 'NOT CONCEALED',
          active: true,
          label: 'NOT CONCEALED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209360',
          code: 'BED/BEDDING',
          active: true,
          label: 'BED/BEDDING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209361',
          code: 'BOOK/PAPERS',
          active: true,
          label: 'BOOK/PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209362',
          code: 'CELL/BUILDING FABRIC',
          active: true,
          label: 'CELL/BUILDING FABRIC',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209363',
          code: 'FOOD/CONTAINER',
          active: true,
          label: 'FOOD/CONTAINER',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209364',
          code: 'IN CLOTHING',
          active: true,
          label: 'IN CLOTHING',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209365',
          code: 'IN HAND',
          active: true,
          label: 'IN HAND',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209366',
          code: 'IN MOUTH',
          active: true,
          label: 'IN MOUTH',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209367',
          code: 'INTERNALLY/PLUGGED',
          active: true,
          label: 'INTERNALLY/PLUGGED',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209368',
          code: 'LETTER/PARCEL',
          active: true,
          label: 'LETTER/PARCEL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209369',
          code: 'LIGHT FITTINGS',
          active: true,
          label: 'LIGHT FITTINGS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209370',
          code: 'PIPEWORK',
          active: true,
          label: 'PIPEWORK',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209371',
          code: 'RULE 39/LEGAL PAPERS',
          active: true,
          label: 'RULE 39/LEGAL PAPERS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209372',
          code: 'TV/RADIO/DVD/CONSOLES ETC.',
          active: true,
          label: 'TV/RADIO/DVD/CONSOLES ETC.',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57321',
        },
        {
          id: '209373',
          code: 'OTHER (PLEASE SPECIFY)',
          active: true,
          label: 'OTHER (PLEASE SPECIFY)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57321',
        },
      ],
    },
    '57321': {
      id: '57321',
      active: true,
      code: 'IS THE ITEM HEAVILY CONTAMINATED? (E.G. BLOOD, FAECES)',
      label: 'Is the item heavily contaminated? (e.g. blood, faeces)?',
      multipleAnswers: false,
      answers: [
        {
          id: '209374',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57322',
        },
        {
          id: '209375',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57322',
        },
      ],
    },
    '57322': {
      id: '57322',
      active: true,
      code: 'WAS A VISITOR SUSPECTED OF INVOLVEMENT AND ARRESTED BY THE POLICE?',
      label: 'Was a visitor suspected of involvement and arrested by the police?',
      multipleAnswers: false,
      answers: [
        {
          id: '209376',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57323',
        },
        {
          id: '209377',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57325',
        },
      ],
    },
    '57323': {
      id: '57323',
      active: true,
      code: 'DESCRIBE CIRCUMSTANCES OF VISITORS ARREST',
      label: 'Describe circumstances of visitors arrest',
      multipleAnswers: false,
      answers: [
        {
          id: '209378',
          code: 'AFTER ENTERING PRISON',
          active: true,
          label: 'AFTER ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57324',
        },
        {
          id: '209379',
          code: 'BEFORE ENTERING PRISON',
          active: true,
          label: 'BEFORE ENTERING PRISON',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57324',
        },
      ],
    },
    '57324': {
      id: '57324',
      active: true,
      code: 'TO WHICH POLICE STATION WAS THE VISITOR TAKEN TO?',
      label: 'To which police station was the visitor taken to?',
      multipleAnswers: false,
      answers: [
        {
          id: '209380',
          code: 'PLEASE SPECIFY',
          active: true,
          label: 'PLEASE SPECIFY',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '57325',
        },
      ],
    },
    '57325': {
      id: '57325',
      active: true,
      code: 'WERE THE ITEMS OBTAINED ON TEMPORARY RELEASE?',
      label: 'Were the items obtained on temporary release?',
      multipleAnswers: false,
      answers: [
        {
          id: '209381',
          code: 'YES',
          active: true,
          label: 'YES',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57326',
        },
        {
          id: '209382',
          code: 'NO',
          active: true,
          label: 'NO',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          id: '209383',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
      ],
    },
    '57326': {
      id: '57326',
      active: true,
      code: 'DESCRIBE THE TYPE OF TEMPORARY RELEASE',
      label: 'Describe the type of temporary release',
      multipleAnswers: false,
      answers: [
        {
          id: '209384',
          code: 'COMMUNITY VISIT',
          active: true,
          label: 'COMMUNITY VISIT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          id: '209385',
          code: 'COMPASSIONATE',
          active: true,
          label: 'COMPASSIONATE',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          id: '209386',
          code: 'FACILITY',
          active: true,
          label: 'FACILITY',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          id: '209387',
          code: 'RESETTLEMENT',
          active: true,
          label: 'RESETTLEMENT',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
        {
          id: '209388',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '57327',
        },
      ],
    },
    '57327': {
      id: '57327',
      active: true,
      code: 'WHAT WAS THE TOTAL ESTIMATED VALUE OF THE FIND? (DRUGS, MOBILE PHONES ETC.)',
      label: 'What was the total estimated value of the find? (drugs, mobile phones etc.)?',
      multipleAnswers: false,
      answers: [
        {
          id: '209389',
          code: '£0',
          active: true,
          label: '£0',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209390',
          code: '£1 to £100',
          active: true,
          label: '£1 to £100',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209391',
          code: '£101 to £200',
          active: true,
          label: '£101 to £200',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209392',
          code: '£201 to £300',
          active: true,
          label: '£201 to £300',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209393',
          code: '£301 to £400',
          active: true,
          label: '£301 to £400',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209394',
          code: '£401 to £500',
          active: true,
          label: '£401 to £500',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209395',
          code: '£501 to £1,000',
          active: true,
          label: '£501 to £1,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209396',
          code: '£1,001 to £5,000',
          active: true,
          label: '£1,001 to £5,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209397',
          code: '£5,001 to £10,000',
          active: true,
          label: '£5,001 to £10,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209398',
          code: '£10,001 to £20,000',
          active: true,
          label: '£10,001 to £20,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209399',
          code: '£20,001 to £30,000',
          active: true,
          label: '£20,001 to £30,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209400',
          code: '£30,001 to £40,000',
          active: true,
          label: '£30,001 to £40,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209401',
          code: '£40,001 to £50,000',
          active: true,
          label: '£40,001 to £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209402',
          code: 'More than £50,000',
          active: true,
          label: 'More than £50,000',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '209403',
          code: 'UNKNOWN',
          active: true,
          label: 'UNKNOWN',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IN_POSSESSION',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'INTENDED_RECIPIENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PRESENT_AT_SCENE',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
} as const

export default OLD_FINDS4
