// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:52.694Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const RADIO_COMPROMISE_1: IncidentTypeConfiguration = {
  incidentType: 'RADIO_COMPROMISE_1',
  active: true,
  startingQuestionCode: '44802',
  questions: {
    '44125': {
      code: '44125',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'Is the incident the subject of an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '178897',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44811',
        },
        {
          code: '178896',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44811',
        },
      ],
    },
    '44132': {
      code: '44132',
      active: true,
      question: 'HAS THE RADIO BEEN RECOVERED',
      label: 'Has the radio been recovered?',
      multipleAnswers: false,
      answers: [
        {
          code: '178928',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '45123',
        },
        {
          code: '178929',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
      ],
    },
    '44173': {
      code: '44173',
      active: true,
      question: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '179072',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44916',
        },
        {
          code: '179071',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44916',
        },
      ],
    },
    '44184': {
      code: '44184',
      active: true,
      question: 'IS THE INTERFERENCE/JAM THOUGHT TO BE',
      label: 'Is the interference/jam thought to be?',
      multipleAnswers: false,
      answers: [
        {
          code: '179097',
          response: 'MALICIOUS',
          active: true,
          label: 'Malicious',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '179098',
          response: 'UNINTENTIONAL',
          active: true,
          label: 'Unintentional',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
      ],
    },
    '44252': {
      code: '44252',
      active: true,
      question: 'HAS THE RADIO BEEN ISOLATED FROM THE NET',
      label: 'Has the radio been isolated from the net?',
      multipleAnswers: false,
      answers: [
        {
          code: '179328',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44282',
        },
        {
          code: '179327',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44282',
        },
      ],
    },
    '44282': {
      code: '44282',
      active: true,
      question: 'HAS THE LOCAL FREQUENCY BEEN CHANGED',
      label: 'Has the local frequency been changed?',
      multipleAnswers: false,
      answers: [
        {
          code: '179403',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44618',
        },
        {
          code: '179402',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44618',
        },
      ],
    },
    '44453': {
      code: '44453',
      active: true,
      question: 'WHAT IS THE TYPE OF COMPROMISE',
      label: 'What is the type of compromise?',
      multipleAnswers: false,
      answers: [
        {
          code: '179991',
          response: 'INTERFERENCE',
          active: true,
          label: 'Interference',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44648',
        },
        {
          code: '179992',
          response: 'NET JAM',
          active: true,
          label: 'Net jam',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44648',
        },
        {
          code: '179993',
          response: 'MISSING RADIO',
          active: true,
          label: 'Missing radio',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44841',
        },
      ],
    },
    '44618': {
      code: '44618',
      active: true,
      question: 'WHAT ACTION WAS TAKEN TO RECOVER THE RADIO',
      label: 'What action was taken to recover the radio?',
      multipleAnswers: false,
      answers: [
        {
          code: '180653',
          response: 'FULL SEARCH',
          active: true,
          label: 'Full search',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44132',
        },
        {
          code: '180654',
          response: 'PARTIAL SEARCH',
          active: true,
          label: 'Partial search',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44132',
        },
      ],
    },
    '44648': {
      code: '44648',
      active: true,
      question: 'DESCRIBE THE SOURCE OF THE INTERFERENCE/JAM',
      label: 'Describe the source of the interference/jam',
      multipleAnswers: false,
      answers: [
        {
          code: '180744',
          response: 'INTERNAL',
          active: true,
          label: 'Internal',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44184',
        },
        {
          code: '180743',
          response: 'EXTERNAL',
          active: true,
          label: 'External',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44184',
        },
        {
          code: '180745',
          response: 'NOT KNOWN',
          active: true,
          label: 'Not known',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44184',
        },
      ],
    },
    '44712': {
      code: '44712',
      active: true,
      question: 'IS THE RADIO STILL OPERATIONAL',
      label: 'Is the radio still operational?',
      multipleAnswers: false,
      answers: [
        {
          code: '180985',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44252',
        },
        {
          code: '180984',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44252',
        },
      ],
    },
    '44799': {
      code: '44799',
      active: true,
      question: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: '181256',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44173',
        },
        {
          code: '181255',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44173',
        },
      ],
    },
    '44801': {
      code: '44801',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'Is the incident the subject of a police investigation?',
      multipleAnswers: false,
      answers: [
        {
          code: '181261',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44125',
        },
        {
          code: '181260',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44125',
        },
      ],
    },
    '44802': {
      code: '44802',
      active: true,
      question: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          code: '181262',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: true,
          nextQuestionCode: '44801',
        },
        {
          code: '181263',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44125',
        },
      ],
    },
    '44811': {
      code: '44811',
      active: true,
      question: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "Is the incident subject to a governor's adjudication?",
      multipleAnswers: false,
      answers: [
        {
          code: '181284',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44799',
        },
        {
          code: '181283',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44799',
        },
      ],
    },
    '44841': {
      code: '44841',
      active: true,
      question: 'IS THE MISSING RADIO THOUGHT TO BE',
      label: 'Is the missing radio thought to be?',
      multipleAnswers: false,
      answers: [
        {
          code: '181355',
          response: 'LOST',
          active: true,
          label: 'Lost',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44856',
        },
        {
          code: '181356',
          response: 'MISLAID',
          active: true,
          label: 'Mislaid',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44856',
        },
        {
          code: '181357',
          response: 'STOLEN',
          active: true,
          label: 'Stolen',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44856',
        },
      ],
    },
    '44856': {
      code: '44856',
      active: true,
      question: 'IS THE RADIO THOUGHT TO BE IN POSSESSION OF PRISONERS',
      label: 'Is the radio thought to be in possession of prisoners?',
      multipleAnswers: false,
      answers: [
        {
          code: '181415',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44712',
        },
        {
          code: '181414',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44712',
        },
      ],
    },
    '44916': {
      code: '44916',
      active: true,
      question: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: '181638',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: true,
          nextQuestionCode: '44453',
        },
        {
          code: '181637',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: '44453',
        },
      ],
    },
    '45123': {
      code: '45123',
      active: true,
      question: 'WHERE WAS THE RADIO FOUND',
      label: 'Where was the radio found?',
      multipleAnswers: false,
      answers: [
        {
          code: '182450',
          response: 'PRISONER POSSESSION',
          active: true,
          label: 'Prisoner possession',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '182446',
          response: 'CONCEALED',
          active: true,
          label: 'Concealed',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '182447',
          response: 'DISCARDED',
          active: true,
          label: 'Discarded',
          commentRequested: false,
          commentMandatory: false,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '182448',
          response: 'MISLAID/LOST',
          active: true,
          label: 'Mislaid/lost',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: null,
        },
        {
          code: '182449',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequested: true,
          commentMandatory: true,
          dateRequired: false,
          nextQuestionCode: null,
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default RADIO_COMPROMISE_1
