// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-12T16:33:59.889Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const RELEASED_IN_ERROR: IncidentTypeConfiguration = {
  incidentType: 'RELEASED_IN_ERROR',
  active: true,
  startingQuestionId: '45179',
  questions: {
    '45179': {
      id: '45179',
      label: 'How was this person released?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Bail',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Final discharge/end of sentence',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Police production',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Court production/PEMS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Escort - HMPS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Bail',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45180',
        },
        {
          label: 'Final discharge/end of sentence',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45180',
        },
        {
          label: 'Police production',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45180',
        },
        {
          label: 'Court production/PEMS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45180',
        },
        {
          label: 'Escort – HMPS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45180',
        },
        {
          label: 'Other : Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45180',
        },
        {
          label: 'Court production/PEMS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45180',
        },
      ],
    },
    '45180': {
      id: '45180',
      label: 'Where did the release occur from?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Establishment: Enter name',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Court: Enter name',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Establishment : Enter name',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45181',
        },
        {
          label: 'Court : Enter name',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45181',
        },
        {
          label: 'Other : Please enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45181',
        },
      ],
    },
    '45181': {
      id: '45181',
      label: 'What was the nature of the Incident?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Wrong person released',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Sentence miscalculated',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'ADA not included in calculations',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Immigration warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Remand warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Imprisonment warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Civil/non payment of fines warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Bail conditions not fully met',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Release criteria not met',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Recall procedures not applied',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Wrong person released',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Sentence Miscalculated',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'ADA not included on calculations',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Immigration warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Remand warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Imprisonment warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Civil/non payment of fines warrant not applied/misfiled/missing',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Bail conditions not fully met',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Release criteria not met',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Recall procedures not applied',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45182',
        },
        {
          label: 'Other : Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45182',
        },
      ],
    },
    '45182': {
      id: '45182',
      label: 'What action is being taken to return the person to custody by the Establishment?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Recall procedures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Home Probation Officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Prisoner contacted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Court contacted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Police contacted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'None - explain why none of the above procedures have been actioned',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Recall procedures',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45183',
        },
        {
          label: 'Home Probation Officer',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45183',
        },
        {
          label: 'Prisoner contacted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45183',
        },
        {
          label: 'Court contacted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45183',
        },
        {
          label: 'Police contacted',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45183',
        },
        {
          label: 'Other : Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45183',
        },
        {
          label: 'None - explain why none of the above procedures have been actioned',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45183',
        },
      ],
    },
    '45183': {
      id: '45183',
      label: 'How was the error identified?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Contact from PEMS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contact from Courts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contact from UKBA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contact from Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Post release check by Establishment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contact from other agency: Please enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Sentence calculations',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Contact from PEMS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Contact from courts',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Contact from UKBA',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Contact from police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Post release check by Establishment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Contact from other agency : Please enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Sentence calculations (new receptions)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Other: Please explain',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45184',
        },
        {
          label: 'Contact from PEMS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45184',
        },
      ],
    },
    '45184': {
      id: '45184',
      label: 'What date was the error identified?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Date:',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Date:',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45185',
        },
      ],
    },
    '45185': {
      id: '45185',
      label: 'What was the category of the person?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Enter details:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Enter details:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45186',
        },
      ],
    },
    '45186': {
      id: '45186',
      label: 'What was the prisoner status?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Sentenced prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Remand prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Immigration detainee',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Recall prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Civil prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Sentenced prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45189',
        },
        {
          label: 'Remand prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45189',
        },
        {
          label: 'Immigration detainee',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45189',
        },
        {
          label: 'Recall prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45189',
        },
        {
          label: 'Civil prisoner',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45189',
        },
      ],
    },
    '45187': {
      id: '45187',
      label: 'Has the person been reported UAL to the Police?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Police Incident Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '45188': {
      id: '45188',
      label: 'Has the release in error been reported to NOU?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Incident Ref No:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45190',
        },
        {
          label: 'Incident Ref No:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45190',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45190',
        },
      ],
    },
    '45189': {
      id: '45189',
      label: 'Has the person been reported UAL to the Police?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Police Incident Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Date',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45188',
        },
        {
          label: 'Police Incident Number:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45188',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45188',
        },
      ],
    },
    '45190': {
      id: '45190',
      label: 'Has the person been returned to custody?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other: Please enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45191',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45191',
        },
        {
          label: 'Other: Please enter details',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45191',
        },
        {
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '45191': {
      id: '45191',
      label: 'Date returned to custody',
      multipleAnswers: false,
      answers: [
        {
          label: 'Date:',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          label: 'Date:',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '45192',
        },
      ],
    },
    '45192': {
      id: '45192',
      label: 'Was person charged with committing a further offence while at large?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Yes: Please enter details of offence',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Yes: Please enter details of offence',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45193',
        },
        {
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45193',
        },
      ],
    },
    '45193': {
      id: '45193',
      label: 'To which establishment was person returned?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Enter details:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Enter details:',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '45194',
        },
      ],
    },
    '45194': {
      id: '45194',
      label: 'How long was person UAL?',
      multipleAnswers: false,
      answers: [
        {
          label: 'Enter value',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '45195': {
      id: '45195',
      label: 'How long was person UAL?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Hours',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Days',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Weeks',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Months',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '45235': {
      id: '45235',
      label: 'How long was person UAL?',
      multipleAnswers: true,
      answers: [
        {
          label: 'Hours',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Days',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Weeks',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Months',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default RELEASED_IN_ERROR
