// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2024-09-20T16:52:34.262Z

import { type IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

const TEMPORARY_RELEASE_FAILURE: IncidentTypeConfiguration = {
  incidentType: 'TEMPORARY_RELEASE_FAILURE',
  active: true,
  startingQuestionId: '59179',
  questions: {
    '59179': {
      id: '59179',
      active: true,
      code: 'What was the main management outcome of the incident?',
      label: 'What was the main management outcome of the incident?',
      multipleAnswers: true,
      answers: [
        {
          code: 'No further action',
          active: true,
          label: 'No further action',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59180',
        },
        {
          code: 'IEP Regression',
          active: true,
          label: 'IEP Regression',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59180',
        },
        {
          code: 'Placed on report/adjudication referral',
          active: true,
          label: 'Placed on report/adjudication referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59180',
        },
        {
          code: 'Police referral',
          active: true,
          label: 'Police referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59180',
        },
        {
          code: 'CPS referral',
          active: true,
          label: 'CPS referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59180',
        },
        {
          code: 'Prosecution referral',
          active: true,
          label: 'Prosecution referral',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59180',
        },
      ],
    },
    '59180': {
      id: '59180',
      active: true,
      code: 'Is any member of staff facing disciplinary charges?',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59181',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59181',
        },
      ],
    },
    '59181': {
      id: '59181',
      active: true,
      code: 'Was ROTL Standard or Restricted?',
      label: 'Was ROTL Standard or Restricted?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Standard ROTL',
          active: true,
          label: 'Standard ROTL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59182',
        },
        {
          code: 'Restricted ROTL',
          active: true,
          label: 'Restricted ROTL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59182',
        },
      ],
    },
    '59182': {
      id: '59182',
      active: true,
      code: 'What Type Of Temporary Licence Was Breached?',
      label: 'What Type Of Temporary Licence Was Breached?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Resettlement Day',
          active: true,
          label: 'Resettlement Day',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59183',
        },
        {
          code: 'Resettlement Overnight',
          active: true,
          label: 'Resettlement Overnight',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59183',
        },
        {
          code: 'Childcare Resettlement',
          active: true,
          label: 'Childcare Resettlement',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59183',
        },
        {
          code: 'Special Purpose (medical)',
          active: true,
          label: 'Special Purpose (medical)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59183',
        },
        {
          code: 'Special Purpose (other)',
          active: true,
          label: 'Special Purpose (other)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59183',
        },
      ],
    },
    '59183': {
      id: '59183',
      active: true,
      code: 'What Was The Specific Purpose Of Temporary Release?',
      label: 'What Was The Specific Purpose Of Temporary Release?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Training or Education',
          active: true,
          label: 'Training or Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Unpaid Work Placements',
          active: true,
          label: 'Unpaid Work Placements',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Paid Work Placements',
          active: true,
          label: 'Paid Work Placements',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Maintain Family Ties',
          active: true,
          label: 'Maintain Family Ties',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Outside Prison Activity',
          active: true,
          label: 'Outside Prison Activity',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Accommodation Related',
          active: true,
          label: 'Accommodation Related',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Other Day Release linked to Sentence/Resettlement Plan',
          active: true,
          label: 'Other Day Release linked to Sentence/Resettlement Plan',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Resettlement Overnight Release',
          active: true,
          label: 'Resettlement Overnight Release',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Childcare Resettlement Leave',
          active: true,
          label: 'Childcare Resettlement Leave',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Funeral/Visiting Dying Relative',
          active: true,
          label: 'Funeral/Visiting Dying Relative',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Medical Treatment',
          active: true,
          label: 'Medical Treatment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Other Compassionate Reason',
          active: true,
          label: 'Other Compassionate Reason',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
        {
          code: 'Court/Legal/Police',
          active: true,
          label: 'Court/Legal/Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59184',
        },
      ],
    },
    '59184': {
      id: '59184',
      active: true,
      code: 'Were UAL contingency plans (including notification to the police) activated?',
      label: 'Were UAL contingency plans (including notification to the police) activated?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59185',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
      ],
    },
    '59185': {
      id: '59185',
      active: true,
      code: 'Why were UAL contingency plans activated?',
      label: 'Why were UAL contingency plans activated?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Apparent failure to return',
          active: true,
          label: 'Apparent failure to return',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59186',
        },
        {
          code: "Revocation of the prisoner's licence",
          active: true,
          label: "Revocation of the prisoner's licence",
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59186',
        },
      ],
    },
    '59186': {
      id: '59186',
      active: true,
      code: 'Has the prisoner surrendered/been recaptured?',
      label: 'Has the prisoner surrendered/been recaptured?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes (Enter Date)',
          active: true,
          label: 'Yes (Enter Date)',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '59187',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
      ],
    },
    '59187': {
      id: '59187',
      active: true,
      code: 'How did prisoner surrender/get recaptured?',
      label: 'How did prisoner surrender/get recaptured?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Surrendered before midnight on return date',
          active: true,
          label: 'Surrendered before midnight on return date',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
        {
          code: 'Surrender To HMPS (after midnight on return date)',
          active: true,
          label: 'Surrender To HMPS (after midnight on return date)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
        {
          code: 'Surrender To Police (after midnight on return date)',
          active: true,
          label: 'Surrender To Police (after midnight on return date)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
        {
          code: 'Arrest By HMPS',
          active: true,
          label: 'Arrest By HMPS',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
        {
          code: 'Arrest By Police',
          active: true,
          label: 'Arrest By Police',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
        {
          code: 'Admitted to hospital for treatment',
          active: true,
          label: 'Admitted to hospital for treatment',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
        {
          code: 'Deceased',
          active: true,
          label: 'Deceased',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59188',
        },
        {
          code: 'Other (Provide Details)',
          active: true,
          label: 'Other (Provide Details)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59188',
        },
      ],
    },
    '59188': {
      id: '59188',
      active: true,
      code: 'Was the prisoner late returning back to prison?',
      label: 'Was the prisoner late returning back to prison?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59189',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59189',
        },
      ],
    },
    '59189': {
      id: '59189',
      active: true,
      code: 'Was prisoner arrested for an offence allegedly committed whilst temp released? (do not include FAILURE TO RETURN)',
      label:
        'Was prisoner arrested for an offence allegedly committed whilst temp released? (do not include FAILURE TO RETURN)',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59190',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
      ],
    },
    '59190': {
      id: '59190',
      active: true,
      code: 'For What Type Of Offence Or Offences Has The Prisoner Been Arrested?',
      label: 'For What Type Of Offence Or Offences Has The Prisoner Been Arrested?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Violence Against The Person',
          active: true,
          label: 'Violence Against The Person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Sexual Offences',
          active: true,
          label: 'Sexual Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Robbery',
          active: true,
          label: 'Robbery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Burglary',
          active: true,
          label: 'Burglary',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Theft And Handling',
          active: true,
          label: 'Theft And Handling',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Fraud And Forgery',
          active: true,
          label: 'Fraud And Forgery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Drug Offences',
          active: true,
          label: 'Drug Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Motoring Offences',
          active: true,
          label: 'Motoring Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Other Offence (Please specify)',
          active: true,
          label: 'Other Offence (Please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59191',
        },
        {
          code: 'Unknown',
          active: true,
          label: 'Unknown',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59191',
        },
      ],
    },
    '59191': {
      id: '59191',
      active: true,
      code: 'Has The Prisoner Been Charged With Any Offence (INCLUDE the offence of failure to return)?',
      label: 'Has The Prisoner Been Charged With Any Offence (INCLUDE the offence of failure to return)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59192',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
      ],
    },
    '59192': {
      id: '59192',
      active: true,
      code: 'With What Type Of Offence or Offences Has The Prisoner Been Charged?',
      label: 'With What Type Of Offence or Offences Has The Prisoner Been Charged?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Violence Against The Person',
          active: true,
          label: 'Violence Against The Person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Sexual Offences',
          active: true,
          label: 'Sexual Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Robbery',
          active: true,
          label: 'Robbery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Burglary',
          active: true,
          label: 'Burglary',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Theft And Handling',
          active: true,
          label: 'Theft And Handling',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Fraud And Forgery',
          active: true,
          label: 'Fraud And Forgery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Drug Offences',
          active: true,
          label: 'Drug Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Motoring Offences',
          active: true,
          label: 'Motoring Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59193',
        },
        {
          code: 'Other Offence (Please specify)',
          active: true,
          label: 'Other Offence (Please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59193',
        },
      ],
    },
    '59193': {
      id: '59193',
      active: true,
      code: 'Has The Prisoner Been Found Guilty Of Offences Committed On ROTL?',
      label: 'Has The Prisoner Been Found Guilty Of Offences Committed On ROTL?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59194',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
      ],
    },
    '59194': {
      id: '59194',
      active: true,
      code: 'What Offence Or Offences Has The Prisoner Been Found Guilty Of?',
      label: 'What Offence Or Offences Has The Prisoner Been Found Guilty Of?',
      multipleAnswers: true,
      answers: [
        {
          code: 'Violence Against The Person',
          active: true,
          label: 'Violence Against The Person',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Sexual Offences',
          active: true,
          label: 'Sexual Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Robbery',
          active: true,
          label: 'Robbery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Burglary',
          active: true,
          label: 'Burglary',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Theft And Handling',
          active: true,
          label: 'Theft And Handling',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Fraud And Forgery',
          active: true,
          label: 'Fraud And Forgery',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Drug Offences',
          active: true,
          label: 'Drug Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Motoring Offences',
          active: true,
          label: 'Motoring Offences',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Failure To Return From ROTL',
          active: true,
          label: 'Failure To Return From ROTL',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59195',
        },
        {
          code: 'Other Offence (Please specify)',
          active: true,
          label: 'Other Offence (Please specify)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59195',
        },
      ],
    },
    '59195': {
      id: '59195',
      active: true,
      code: 'Was Any Part Of The Failure Failing To Comply With Any Other Licence Conditions (Standard or Bespoke)?',
      label: 'Was Any Part Of The Failure Failing To Comply With Any Other Licence Conditions (Standard or Bespoke)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59196',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
      ],
    },
    '59196': {
      id: '59196',
      active: true,
      code: 'Please Specify Which Conditions apply',
      label: 'Please Specify Which Conditions apply',
      multipleAnswers: true,
      answers: [
        {
          code: 'Location',
          active: true,
          label: 'Location',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
        {
          code: 'Alcohol/drugs (under influence)',
          active: true,
          label: 'Alcohol/drugs (under influence)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
        {
          code: 'Gambling',
          active: true,
          label: 'Gambling',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
        {
          code: 'Finds (fill in separate report)',
          active: true,
          label: 'Finds (fill in separate report)',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
        {
          code: 'Social Media',
          active: true,
          label: 'Social Media',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
        {
          code: 'Bad Behaviour',
          active: true,
          label: 'Bad Behaviour',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
        {
          code: 'Media Contact',
          active: true,
          label: 'Media Contact',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59197',
        },
        {
          code: 'Other (Provide Details)',
          active: true,
          label: 'Other (Provide Details)',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59197',
        },
      ],
    },
    '59197': {
      id: '59197',
      active: true,
      code: 'Was failure due to matters beyond the prisoner’s control?',
      label: 'Was failure due to matters beyond the prisoner’s control?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59198',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '59198',
        },
      ],
    },
    '59198': {
      id: '59198',
      active: true,
      code: 'Has the NOMS SFO Team been informed (SFO CASES only)',
      label: 'Has the NOMS SFO Team been informed (SFO CASES only)',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '59199',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59199',
        },
      ],
    },
    '59199': {
      id: '59199',
      active: true,
      code: 'Has the Offender Manager been informed?',
      label: 'Has the Offender Manager been informed?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '59200',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59200',
        },
      ],
    },
    '59200': {
      id: '59200',
      active: true,
      code: 'Has the Victim Liaison Officer been informed (where appropriate)?',
      label: 'Has the Victim Liaison Officer been informed (where appropriate)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '59201',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59201',
        },
      ],
    },
    '59201': {
      id: '59201',
      active: true,
      code: 'Has the ROTL Placement Provider been informed (where appropriate)?',
      label: 'Has the ROTL Placement Provider been informed (where appropriate)?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '59202',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59202',
        },
      ],
    },
    '59202': {
      id: '59202',
      active: true,
      code: 'Has The Deputy Director Of Custody Been Informed?',
      label: 'Has The Deputy Director Of Custody Been Informed?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '59203',
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '59203',
        },
      ],
    },
    '59203': {
      id: '59203',
      active: true,
      code: 'Have PPCS Been Informed?',
      label: 'Have PPCS Been Informed?',
      multipleAnswers: false,
      answers: [
        {
          code: 'Yes',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: null,
        },
        {
          code: 'No',
          active: true,
          label: 'No',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
  },
} as const

export default TEMPORARY_RELEASE_FAILURE
