// Generated with ./scripts/updateNomisIncidentTypeConfigurations.ts at 2025-04-01T22:59:30.552Z

import type { IncidentTypeConfiguration } from '../../data/incidentTypeConfiguration/types'

export const TOOL_LOSS_1: IncidentTypeConfiguration = {
  incidentType: 'TOOL_LOSS_1',
  active: true,
  startingQuestionId: '45142',
  questions: {
    '44195': {
      id: '44195',
      active: true,
      question: 'WHAT ACTION WAS TAKEN TO FIND THESE ITEMS',
      label: 'What action was taken to find these items?',
      multipleAnswers: false,
      answers: [
        {
          id: '179154',
          response: 'FULL CLOSE DOWN SEARCH',
          active: true,
          label: 'Full close down search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44565',
        },
        {
          id: '179156',
          response: 'PARTIAL SEARCH',
          active: true,
          label: 'Partial search',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44565',
        },
        {
          id: '179155',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44565',
        },
      ],
    },
    '44372': {
      id: '44372',
      active: true,
      question: 'IS THE MISSING ITEM THOUGHT TO BE',
      label: 'Is the missing item thought to be?',
      multipleAnswers: false,
      answers: [
        {
          id: '179749',
          response: 'LOST',
          active: true,
          label: 'Lost',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44445',
        },
        {
          id: '179750',
          response: 'MISLAID',
          active: true,
          label: 'Mislaid',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44445',
        },
        {
          id: '179751',
          response: 'STOLEN',
          active: true,
          label: 'Stolen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44445',
        },
      ],
    },
    '44412': {
      id: '44412',
      active: true,
      question: 'HAS THE PRISON SERVICE PRESS OFFICE BEEN INFORMED',
      label: 'Has the prison service press office been informed?',
      multipleAnswers: false,
      answers: [
        {
          id: '179883',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44593',
        },
        {
          id: '179882',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44593',
        },
      ],
    },
    '44445': {
      id: '44445',
      active: true,
      question: "IS THE MISSING ITEM THOUGHT TO BE IN A PRISONER'S POSSESSION",
      label: "Is the missing item thought to be in a prisoner's possession?",
      multipleAnswers: false,
      answers: [
        {
          id: '179974',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44195',
        },
        {
          id: '179973',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44195',
        },
      ],
    },
    '44477': {
      id: '44477',
      active: true,
      question: 'HOW ARE TOOLS/IMPLEMENTS STORED',
      label: 'How are tools/implements stored?',
      multipleAnswers: false,
      answers: [
        {
          id: '180133',
          response: 'SHADOW BOARD',
          active: true,
          label: 'Shadow board',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44509',
        },
        {
          id: '180131',
          response: 'SECURE CABINET',
          active: true,
          label: 'Secure cabinet',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44509',
        },
        {
          id: '180132',
          response: 'SECURE ROOM',
          active: true,
          label: 'Secure room',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44509',
        },
        {
          id: '180130',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44509',
        },
      ],
    },
    '44489': {
      id: '44489',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF AN INTERNAL INVESTIGATION',
      label: 'Is the incident the subject of an internal investigation?',
      multipleAnswers: false,
      answers: [
        {
          id: '180170',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44993',
        },
        {
          id: '180169',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44993',
        },
      ],
    },
    '44509': {
      id: '44509',
      active: true,
      question: 'IS THE F78A CHECKING SYSTEM IN OPERATION',
      label: 'Is the F78A checking system in operation?',
      multipleAnswers: false,
      answers: [
        {
          id: '180253',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
        {
          id: '180252',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: null,
        },
      ],
    },
    '44565': {
      id: '44565',
      active: true,
      question: 'HAS THE ITEM BEEN FOUND',
      label: 'Has the item been found?',
      multipleAnswers: false,
      answers: [
        {
          id: '180473',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '45169',
        },
        {
          id: '180474',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44477',
        },
      ],
    },
    '44593': {
      id: '44593',
      active: true,
      question: 'WHAT TOOL OR IMPLEMENT IS MISSING',
      label: 'What tool or implement is missing?',
      multipleAnswers: true,
      answers: [
        {
          id: '180563',
          response: 'KNIFE',
          active: true,
          label: 'Knife',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180562',
          response: 'HACKSAW',
          active: true,
          label: 'Hacksaw',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180565',
          response: 'OTHER SAW',
          active: true,
          label: 'Other saw',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180570',
          response: 'SPADE',
          active: true,
          label: 'Spade',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180560',
          response: 'AXE',
          active: true,
          label: 'Axe',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180566',
          response: 'PICKAXE',
          active: true,
          label: 'Pickaxe',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180567',
          response: 'PLIERS',
          active: true,
          label: 'Pliers',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180569',
          response: 'SCREWDRIVER',
          active: true,
          label: 'Screwdriver',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180571',
          response: 'WIRE CUTTERS',
          active: true,
          label: 'Wire cutters',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180561',
          response: 'BOLT CROPPERS',
          active: true,
          label: 'Bolt croppers',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180568',
          response: 'SCISSORS',
          active: true,
          label: 'Scissors',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44950',
        },
        {
          id: '180564',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44950',
        },
      ],
    },
    '44603': {
      id: '44603',
      active: true,
      question: 'IS ANY MEMBER OF STAFF FACING DISCIPLINARY CHARGES',
      label: 'Is any member of staff facing disciplinary charges?',
      multipleAnswers: false,
      answers: [
        {
          id: '180609',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44672',
        },
        {
          id: '180608',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44672',
        },
      ],
    },
    '44672': {
      id: '44672',
      active: true,
      question: 'IS THERE ANY MEDIA INTEREST IN THIS INCIDENT',
      label: 'Is there any media interest in this incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '180830',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44412',
        },
        {
          id: '180829',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44412',
        },
      ],
    },
    '44808': {
      id: '44808',
      active: true,
      question: 'IS THE INCIDENT THE SUBJECT OF A POLICE INVESTIGATION',
      label: 'Is the incident the subject of a police investigation?',
      multipleAnswers: false,
      answers: [
        {
          id: '181276',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44489',
        },
        {
          id: '181275',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44489',
        },
      ],
    },
    '44950': {
      id: '44950',
      active: true,
      question: 'WHERE WAS THE TOOLS LOST FROM',
      label: 'Where was the tools lost from?',
      multipleAnswers: true,
      answers: [
        {
          id: '181796',
          response: 'WORKS DEPARTMENT',
          active: true,
          label: 'Works department',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181788',
          response: 'CONTRACTORS',
          active: true,
          label: 'Contractors',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181789',
          response: 'EDUCATION',
          active: true,
          label: 'Education',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181792',
          response: 'HEALTH CARE CENTRE',
          active: true,
          label: 'Health care centre',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181790',
          response: 'FARMS AND GARDENS',
          active: true,
          label: 'Farms and gardens',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181791',
          response: 'GYMNASIUM/SPORTSFIELD',
          active: true,
          label: 'Gymnasium/sportsfield',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181797',
          response: 'WORKSHOP',
          active: true,
          label: 'Workshop',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181793',
          response: 'KITCHEN',
          active: true,
          label: 'Kitchen',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181787',
          response: 'CELL HOBBIES',
          active: true,
          label: 'Cell hobbies',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181795',
          response: 'WING OFFICE',
          active: true,
          label: 'Wing office',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44372',
        },
        {
          id: '181794',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44372',
        },
      ],
    },
    '44993': {
      id: '44993',
      active: true,
      question: "IS THE INCIDENT SUBJECT TO A GOVERNOR'S ADJUDICATION",
      label: "Is the incident subject to a governor's adjudication?",
      multipleAnswers: false,
      answers: [
        {
          id: '181941',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44603',
        },
        {
          id: '181940',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44603',
        },
      ],
    },
    '45142': {
      id: '45142',
      active: true,
      question: 'WERE THE POLICE INFORMED OF THE INCIDENT',
      label: 'Were the police informed of the incident?',
      multipleAnswers: false,
      answers: [
        {
          id: '182533',
          response: 'YES',
          active: true,
          label: 'Yes',
          commentRequired: false,
          dateRequired: true,
          nextQuestionId: '44808',
        },
        {
          id: '182534',
          response: 'NO',
          active: true,
          label: 'No',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44489',
        },
      ],
    },
    '45169': {
      id: '45169',
      active: true,
      question: 'WHERE WAS THE ITEM FOUND',
      label: 'Where was the item found?',
      multipleAnswers: false,
      answers: [
        {
          id: '182624',
          response: 'PRISONERS POSSESSION',
          active: true,
          label: 'Prisoners possession',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44477',
        },
        {
          id: '182621',
          response: 'CONCEALED',
          active: true,
          label: 'Concealed',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44477',
        },
        {
          id: '182622',
          response: 'DISCARDED',
          active: true,
          label: 'Discarded',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44477',
        },
        {
          id: '182625',
          response: 'WHERE MISLAID/LOST',
          active: true,
          label: 'Where mislaid/lost',
          commentRequired: false,
          dateRequired: false,
          nextQuestionId: '44477',
        },
        {
          id: '182623',
          response: 'OTHER',
          active: true,
          label: 'Other',
          commentRequired: true,
          dateRequired: false,
          nextQuestionId: '44477',
        },
      ],
    },
  },
  prisonerRoles: [
    {
      prisonerRole: 'ACTIVE_INVOLVEMENT',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'ASSISTED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'IMPEDED_STAFF',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'PERPETRATOR',
      onlyOneAllowed: false,
      active: true,
    },
    {
      prisonerRole: 'SUSPECTED_INVOLVED',
      onlyOneAllowed: false,
      active: true,
    },
  ],
}

export default TOOL_LOSS_1
