generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: incident-reporting-preprod.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: preprod
    SERVICE_ACTIVE_PRISONS: "***"

    INGRESS_URL: "https://incident-reporting-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk"

    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HMPPS_INCIDENT_REPORTING_API_URL: "https://incident-reporting-api-preprod.hmpps.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-preprod.prison.service.justice.gov.uk"
    OFFENDER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-incident-reporting-preprod
  businessHoursOnly: true
